Repository friendica/friendica, pull requests merged in 2018-10, with the labels that each got.

#5762 Add api_friendships_destroy() like mod/unfollow.php
  include/api.php
Labels: API, Enhancement

#5773 Rewrite JS hooks
  doc/Addons.md
  include/conversation.php
  include/text.php
  index.php
  mod/cal.php
  mod/contacts.php
  mod/editpost.php
  mod/events.php
  mod/message.php
  mod/profile_photo.php
  mod/profiles.php
  mod/settings.php
  mod/videos.php
  mod/wallmessage.php
  src/App.php
  view/js/addon-hooks.js
  view/js/main.js
  view/templates/contact_end.tpl
  view/templates/contacts-end.tpl
  view/templates/cropend.tpl
  view/templates/end.tpl
  view/templates/event_end.tpl
  view/templates/footer.tpl
  view/templates/head.tpl
  view/templates/jot-end.tpl
  view/templates/message-end.tpl
  view/templates/msg-end.tpl
  view/templates/profed_end.tpl
  view/templates/videos_end.tpl
  view/templates/wallmsg-end.tpl
  view/theme/frio/php/default.php
  view/theme/frio/templates/footer.tpl
  view/theme/frio/templates/head.tpl
Labels: Addons, Enhancement

#5803 Issue 5798: We had displayed the author as owner
  include/api.php
Labels: Bug, UX

#5804 Issue 5797: Retweets are now displayed again via API
  include/api.php
Labels: API, Bug

#5807 The API test should now complete again
  tests/ApiTest.php
Labels: API, Enhancement

#5806 Repeated posts from OStatus, ActitivyPub and Twitter are now shown as is
  include/api.php
Labels: API, Enhancement

#5812 Issue 5811: "objects" instead of "object"
  mod/display.php
  src/Model/Item.php
  src/Module/Objects.php
  src/Protocol/ActivityPub.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
Labels: Bug, PHP7.2

#5792 Add Cache console
  src/Core/Cache.php
  src/Core/Cache/ArrayCache.php
  src/Core/Cache/DatabaseCacheDriver.php
  src/Core/Cache/ICacheDriver.php
  src/Core/Cache/MemcacheCacheDriver.php
  src/Core/Cache/MemcachedCacheDriver.php
  src/Core/Cache/RedisCacheDriver.php
  src/Core/Console.php
  src/Core/Console/Cache.php
  src/Core/Console/Config.php
Labels: Enhancement

#5816 [Frio] Fix Layout when login failed
  src/Module/Login.php
Labels: Bug, UX

#5819 Install: After detecting DB already in use, go back to db_stettings with error
  mod/install.php
Labels: Enhancement, Installation

#5824 Following a soapbox now works / rapid follow/unfollow should work now
  src/Model/Contact.php
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement, Federation

#5825 Adding "FRIENDICA_URL_PATH" to the automatic installation
  doc/Install.md
  src/Core/Console/AutomaticInstallation.php
  tests/src/Core/Console/AutomaticInstallationConsoleTest.php
Labels: Enhancement, Installation

#5826 We now can show "Friendica (AP)" as network name
  include/conversation.php
  src/Content/ContactSelector.php
  src/Object/Post.php
Labels: Enhancement, Federation

#5827 Send a follow request upon contact switch to AP
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, UX

#5831 moving boot::check_addons to Friendica\Core\Addon::check
  boot.php
  index.php
  src/Core/Addon.php
Labels: Enhancement

#5828 Creating Friendica\App\Mode for encapsulating the App Mode
  bin/auth_ejabberd.php
  index.php
  src/App.php
  src/App/Mode.php
  src/Core/Config.php
  src/Core/Console/ArchiveContact.php
  src/Core/Console/Cache.php
  src/Core/Console/Config.php
  src/Core/PConfig.php
Labels: Enhancement

#5833 Replace remaining $a->isInstallMode() instances
  bin/daemon.php
  index.php
  src/Core/Console/GlobalCommunityBlock.php
  src/Core/Console/GlobalCommunitySilence.php
  src/Core/Console/Maintenance.php
  src/Core/Console/NewPassword.php
  src/Core/Console/PostUpdate.php
Labels: Bug

#5829 Cache the AP delivery process
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/APDelivery.php
  src/Worker/Notifier.php
Labels: Enhancement, Performance

#5839 The owner of a "like" should be the author
  src/Model/Item.php
  src/Protocol/Diaspora.php
Labels: Bug

#5841 Fix (short) profile editing showing 'e' for martial and sexual preferences
  mod/profiles.php
  view/theme/frio/templates/profile_edit.tpl
Labels: Bug, UI/Theme, UX

#5842 Improved AP distribution / Only process trusted content
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/Notifier.php
Labels: Bug

#5844 Changing Friendica\App\Mode from static methods to public methods
  bin/auth_ejabberd.php
  bin/daemon.php
  composer.json
  composer.lock
  index.php
  src/App.php
  src/App/Mode.php
  src/Core/Config.php
  src/Core/Console/ArchiveContact.php
  src/Core/Console/Cache.php
  src/Core/Console/Config.php
  src/Core/Console/GlobalCommunityBlock.php
  src/Core/Console/GlobalCommunitySilence.php
  src/Core/Console/Maintenance.php
  src/Core/Console/NewPassword.php
  src/Core/Console/PostUpdate.php
  src/Core/PConfig.php
  tests/ApiTest.php
  tests/DatabaseTest.php
  tests/Util/VFSTrait.php
  tests/bootstrap.php
  tests/src/App/ModeTest.php
  tests/src/Core/Console/ConsoleTest.php
Labels: Enhancement

#5845 Preparation for suggestions under AP
  mod/fsuggest.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/APDelivery.php
Labels: Enhancement, Federation

#5853 Return to previous page after login
  mod/contacts.php
  mod/events.php
  mod/message.php
  mod/notifications.php
  mod/profiles.php
  mod/settings.php
  src/Module/Login.php
Labels: Enhancement, UX

#5854 We now parse a compacted JSON
  database.sql
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Util/JsonLD.php
Labels: Enhancement, Federation

#5848 friendica-5847 Console Cache List command doesn't work
  src/Core/Cache.php
  src/Core/Cache/AbstractCacheDriver.php
  src/Core/Cache/ArrayCache.php
  src/Core/Cache/DatabaseCacheDriver.php
  src/Core/Cache/ICacheDriver.php
  src/Core/Cache/MemcacheCacheDriver.php
  src/Core/Cache/MemcachedCacheDriver.php
  src/Core/Cache/RedisCacheDriver.php
  src/Core/Console/Cache.php
  tests/src/Core/Cache/ArrayCacheDriverTest.php
  tests/src/Core/Cache/CacheTest.php
  tests/src/Core/Cache/DatabaseCacheDriverTest.php
  tests/src/Core/Cache/MemcacheCacheDriverTest.php
  tests/src/Core/Cache/MemcachedCacheDriverTest.php
  tests/src/Core/Cache/RedisCacheDriverTest.php
Labels: Bug

#5855 AP: Avoid an empty avatar field
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#5860 [frio] Word Wrap for long words in comments
  view/theme/frio/css/style.css
  view/theme/vier/style.css
Labels: Enhancement, UI/Theme, UX

#5865 Fix Login return with pop-up menu form
  src/Module/Login.php
Labels: Enhancement, UX

#5866 AP: Avoid a misleading log entry / unneeded field removed
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#5867 AP: Switchting existing contacts to AP when receiving activities
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation

#5876 Uncaught Error for getCurlCode()
  src/Util/HTTPSignature.php
Labels: Bug

#5878 Curl response refactoring
  include/items.php
  mod/admin.php
  mod/dfrn_confirm.php
  mod/dfrn_poll.php
  mod/feedtest.php
  mod/match.php
  mod/ostatus_subscribe.php
  mod/parse_url.php
  mod/pubsubhubbub.php
  src/Core/ACL.php
  src/Core/Install.php
  src/Model/APContact.php
  src/Model/GContact.php
  src/Model/Profile.php
  src/Module/Magic.php
  src/Module/Proxy.php
  src/Network/Curl.php
  src/Network/CurlResult.php
  src/Network/Probe.php
  src/Object/Image.php
  src/Protocol/ActivityPub.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Protocol/PortableContact.php
  src/Protocol/Salmon.php
  src/Util/ExAuth.php
  src/Util/HTTPSignature.php
  src/Util/Network.php
  src/Util/ParseUrl.php
  src/Worker/DiscoverPoCo.php
  src/Worker/OnePoll.php
  src/Worker/PubSubPublish.php
Labels: Enhancement

#5887 Store conversation data directly from the AP receiver
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement, Federation

#5889 We now store the diaspora comment data as well
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement, Federation

#5897 The virtual fields for the diaspora signatures have to be removed at any time
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement

#5901 Catching error when compacting doesn't work
  src/Util/JsonLD.php
Labels: Enhancement

#5905 Move global functions
  boot.php
  mod/admin.php
  mod/help.php
  mod/item.php
  mod/viewsrc.php
  src/App.php
  src/Core/System.php
  src/Core/Worker.php
Labels: Enhancement

#5904 AP: Announce will now work
  index.php
  mod/crepair.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#5906 OStatus contacts are now automatically converted to AP
  boot.php
  config/dbstructure.json
  database.sql
  src/Model/Contact.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Worker/OnePoll.php
Labels: Enhancement, Federation

#5912 Fix [code] tag whitespace nonsense
  mod/babel.php
  src/Content/Text/BBCode.php
Labels: Bug, UX

#5921 ActivityPub: Rudimentary support for videos
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement, Federation

#5891 Move module contacts
  include/api.php
  mod/allfriends.php
  mod/common.php
  mod/contacts.php
  mod/crepair.php
  mod/dfrn_confirm.php
  mod/dfrn_request.php
  mod/dirfind.php
  mod/group.php
  mod/newmember.php
  mod/update_contacts.php
  src/Content/Nav.php
  src/Model/Contact.php
  src/Module/Contact.php
  util/messages.po
  view/templates/contacts-template.tpl
  view/templates/crepair.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/frio/templates/contacts-template.tpl
  view/theme/frio/templates/crepair.tpl
  view/theme/frio/theme.php
Labels: Enhancement

#5922 Admin: Change User deleted since to delete in
  mod/admin.php
  src/Util/Temporal.php
Labels: Bug, UX

#5923 Improve Contact module
  mod/update_contacts.php
  src/Model/Group.php
  src/Module/Contact.php
Labels: Bug, Enhancement

#5930 added links to alternative ways to install Friendica to the docs
  INSTALL.txt
  doc/Install.md
  doc/de/Install.md
Labels: Docs, Installation

#5933 Signed Diaspora posts should now be stored more reliable
  boot.php
  config/dbstructure.json
  database.sql
  src/Model/Item.php
  src/Protocol/Diaspora.php
Labels: Enhancement, Federation

#5935 Fix namespace usage in mod/group
  mod/group.php
Labels: Bug

#5936 Fix PHP notices S02E01
  include/enotify.php
  src/Database/DBStructure.php
  src/Network/Probe.php
Labels: Enhancement

#5939 Onepoll hadn't polled anymore / small relocation in zrlinit for better logging
  src/Model/Profile.php
  src/Worker/OnePoll.php
Labels: Bug, Enhancement

#5944 Fix template urls from contacts/ to contact/
  view/templates/contact_edit.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/vier/templates/contact_edit.tpl
Labels: Bug

#5945 Remaining contacts to contact
  include/conversation.php
Labels: Bug

#5947 Use "uri-id" for item relations
  boot.php
  config/dbstructure.json
  src/Model/Item.php
  update.php
Labels: Enhancement

#5920 Avoid storing plaintext password in register table
  boot.php
  include/enotify.php
  mod/admin.php
  mod/invite.php
  mod/ping.php
  mod/register.php
  mod/regmod.php
  src/Database/DBA.php
  src/Model/Register.php
  src/Model/User.php
Labels: Bug, Enhancement, Security, UX

#5942 Add BBCode::convertShare callback parameter
  mod/item.php
  src/Content/Text/BBCode.php
  src/Core/Protocol.php
Labels: Enhancement, New Feature

#5950 For test purposes we can now deactivate polling
  config/config.ini.php
  src/Worker/OnePoll.php
Labels: Enhancement, Performance

#5951 Avoid endless loop when trying to fetch contact id
  src/Model/Contact.php
Labels: Enhancement, Performance

#5954 AP: Fix "null" receiver
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#5957 Restore preshare prepending in BBCode::convertShare
  src/Content/Text/BBCode.php
Labels: Bug

#5958 Fix app/client links
  doc/FAQ.md
Labels: Docs

#5963 Diaspora: Widen the magic link regular expression
  src/Content/Text/BBCode.php
  src/Model/Conversation.php
  src/Module/Itemsource.php
  src/Protocol/Diaspora.php
  view/templates/debug/itemsource.tpl
Labels: Enhancement, Federation

#5962 Remove superfluous L10n::t() parameter in Model\user
  src/Model/User.php
Labels: Bug

#5964 Use item class instead of direct call
  mod/community.php
Labels: Enhancement

#5965 Use nickname based mentions for AP
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#5946 Move and Split include/security
  include/api.php
  include/security.php
  mod/admin.php
  mod/attach.php
  mod/cal.php
  mod/community.php
  mod/delegate.php
  mod/display.php
  mod/filer.php
  mod/group.php
  mod/invite.php
  mod/item.php
  mod/like.php
  mod/manage.php
  mod/notes.php
  mod/openid.php
  mod/photo.php
  mod/photos.php
  mod/poke.php
  mod/profile.php
  mod/profile_photo.php
  mod/profiles.php
  mod/register.php
  mod/search.php
  mod/settings.php
  mod/subthread.php
  mod/tagger.php
  mod/videos.php
  src/BaseModule.php
  src/Content/Widget/TagCloud.php
  src/Core/Authentication.php
  src/Model/Group.php
  src/Model/Item.php
  src/Model/Photo.php
  src/Module/Login.php
  src/Module/Logout.php
  src/Module/Proxy.php
  src/Object/Thread.php
  src/Util/Proxy.php
  src/Util/Security.php
Labels: Enhancement

#5967 Fix function naming
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement

#5969 [frio] Enable click through image caption in file browser
  view/theme/frio/css/style.css
Labels: Bug, UI/Theme, UX

#5971 Use system.temppath for PasswordExposedChecker cache
  config/settings.ini.php
  src/Model/User.php
Labels: Bug

#5972 Remove last references to include/security.php
  mod/pubsub.php
  src/Protocol/DFRN.php
Labels: Bug

#5973 Update Addon documentation about location of logged_in hook
  doc/Addons.md
  doc/de/Addons.md
Labels: Docs

#5974 AP: Transmitting and receiving with non AP contacts
  boot.php
  config/dbstructure.json
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#5977 Move Global Functions - Part 3
  boot.php
  index.php
  mod/ping.php
  mod/search.php
  src/App.php
  src/Content/OEmbed.php
  src/Model/GContact.php
  src/Model/Photo.php
  src/Model/Profile.php
  src/Network/Probe.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Util/JsonLD.php
  src/Worker/DiscoverPoCo.php
  src/Worker/Queue.php
Labels: Enhancement

#5980 The limit for dbclean is now configurable
  config/config.ini.php
  src/Worker/DBClean.php
Labels: Enhancement

#5982 Bugfix: We hadn't deliverd AP posts to all intended receivers
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#5976 Add missing L10n::popLang calls
  include/enotify.php
  src/Database/DBStructure.php
Labels: Bug

#5979 Encapsulate legacy module functions in a BaseModule-inherited class
  index.php
  src/LegacyModule.php
Labels: Enhancement

#5959 Fix broken credits box
  view/theme/frio/templates/credits.tpl
Labels: Bug, UI/Theme

#5984 Fix webmentions and microformats ("redir" only for logged in users)
  include/conversation.php
  src/Object/Post.php
Labels: Bug, Federation

#5985 AP: We now send the previous followers collection as well
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#5978 Make username length configurable
  config/config.ini.php
  src/Model/User.php
Labels: Enhancement

#5989 Improved parsing of AP profiles
  src/Model/APContact.php
  src/Util/JsonLD.php
Labels: Enhancement, Federation

#5991 API: The source field does now reliably return the correct network name
  include/api.php
Labels: Enhancement, Federation

#5993 Fix testing
  tests/ApiTest.php
  tests/DatabaseTest.php
  tests/src/Core/Console/AutomaticInstallationConsoleTest.php
  tests/src/Core/InstallTest.php
Labels: Enhancement

#5987 Road to Router Part 2: Empty index.php
  bin/worker.php
  index.php
  src/App.php
  src/Core/System.php
Labels: Enhancement

#5988 Road to Router Part 3: Move $strings out of App
  bin/worker.php
  mod/register.php
  src/App.php
  src/Core/Console/Maintenance.php
  src/Core/L10n.php
  src/Util/Temporal.php
Labels: Enhancement

#5981 Move dbstructure to PHP array
  boot.php
  config/dbstructure.json
  config/dbstructure.php
  mod/admin.php
  mod/events.php
  mod/friendica.php
  mod/profiles.php
  mod/settings.php
  src/App.php
  src/Core/Addon.php
  src/Core/Authentication.php
  src/Core/Hook.php
  src/Core/UserImport.php
  src/Core/Worker.php
  src/Database/DBA.php
  src/Database/DBStructure.php
  src/Model/Contact.php
  src/Model/Event.php
  src/Model/GContact.php
  src/Model/Profile.php
  src/Model/PushSubscriber.php
  src/Module/Contact.php
  src/Object/Post.php
  src/Protocol/PortableContact.php
  src/Util/Temporal.php
  src/Worker/Cron.php
  src/Worker/CronJobs.php
  src/Worker/Expire.php
  src/Worker/ForkHook.php
  src/Worker/Notifier.php
  src/Worker/OnePoll.php
  tests/Util/VFSTrait.php
  update.php
Labels: Enhancement

#5995 Updated Friendiqa's links
  doc/Developers-Intro.md
Labels: Docs

#5997 Fix a notice when sending relocation messages
  src/Worker/Delivery.php
Labels: Enhancement, Federation

#5998 Unsuccessful ActivitiyPub transmission are now deferred
  src/Core/Worker.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Util/HTTPSignature.php
  src/Worker/APDelivery.php
Labels: Enhancement, Federation

#6009 raising profile photo size to comply with frio sidebar profile photo scaling
  doc/api.md
  images/person-300.jpg
  include/api.php
  mod/dfrn_confirm.php
  mod/photo.php
  mod/profile_photo.php
  src/Core/NotificationsManager.php
  src/Model/Contact.php
  src/Model/GContact.php
  src/Model/Photo.php
  src/Model/User.php
  src/Module/Proxy.php
  src/Network/Probe.php
  src/Protocol/DFRN.php
  src/Protocol/OStatus.php
  src/Util/Network.php
Labels: Enhancement, UX

#6011 Fix move from Core\Addon to Core\Hook
  src/App.php
Labels: Bug

#6014 Show deferred worker tasks in the admin interface and workerqueue logs
  mod/admin.php
  src/Core/Worker.php
  view/templates/admin/summary.tpl
  view/theme/frio/templates/admin/summary.tpl
Labels: Enhancement, UI/Theme

#6013 [frio] Add media / link prompt in comments
  include/conversation.php
  mod/parse_url.php
  src/Object/Post.php
  view/js/main.js
  view/theme/frio/js/textedit.js
  view/theme/frio/templates/comment_item.tpl
  view/theme/frio/templates/jot-header.tpl
  view/theme/frio/templates/jot.tpl
Labels: Enhancement, UI/Theme, UX

#6020 Bugfixing redirects
  mod/randprof.php
  mod/redir.php
  src/App.php
  src/Module/Magic.php
Labels: Enhancement

#6023 Preparations to work with BCC
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Util/HTTPSignature.php
Labels: Enhancement, Federation

#6024 Fix unsetting non-existent index in Addon::$addons on uninstall
  src/Core/Addon.php
Labels: Bug

#5949 Develop: Edit group-name can't be edited in frio-theme
  view/theme/frio/templates/group_edit.tpl
Labels: Bug, UI/Theme

#6017 Road to Router Part 5: Move pager out of App
  boot.php
  include/conversation.php
  include/text.php
  mod/admin.php
  mod/allfriends.php
  mod/common.php
  mod/community.php
  mod/directory.php
  mod/dirfind.php
  mod/display.php
  mod/item.php
  mod/match.php
  mod/message.php
  mod/network.php
  mod/notes.php
  mod/notifications.php
  mod/photos.php
  mod/profile.php
  mod/search.php
  mod/videos.php
  mod/viewcontacts.php
  src/App.php
  src/Content/Pager.php
  src/Core/ACL.php
  src/Core/Hook.php
  src/Model/Contact.php
  src/Module/Contact.php
  view/js/main.js
  view/templates/head.tpl
  view/templates/infinite_scroll_head.tpl
  view/theme/frio/templates/js_strings.tpl
Labels: Enhancement

#6025 Fix small typo (land -> lang)
  doc/Install.md
  doc/de/Install.md
Labels: Docs, Enhancement

#6003 Fix adding / removing photo tags
  mod/photos.php
  mod/tagrm.php
  src/Model/Item.php
  src/Model/Term.php
  view/theme/frio/templates/photo_view.tpl
Labels: Enhancement, UX

#6028 Issue 5913: Fix fatal error in "RemoveUser"
  src/Model/Item.php
Labels: Bug

#6026 AP: We now transmit and process events
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#6029 CS translation update THX Aditoo
  view/lang/cs/messages.po
  view/lang/cs/strings.php
Labels: Translation

#6031 Declare missing `$lang` for default template in App->runFrontend
  src/App.php
Labels: Bug

#6033 AP: Event participation and editing of posts are now supported
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement

#6035 Fixes duplicated transmissions and not working undo of like/dislike
  mod/item.php
  mod/photos.php
  mod/poke.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#6037 Diaspora signatures are now stored and transmitted correctly
  mod/item.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
Labels: Bug, Enhancement, Federation

#6044 Diaspora signature transport via AP/DFRN should be repaired now
  mod/item.php
  src/Model/Item.php
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#6045 [frio] Show error message on image upload
  view/theme/frio/js/filebrowser.js
  view/theme/frio/templates/filebrowser.tpl
Labels: Bug, Enhancement, UX

#6041 Install to Module
  mod/install.php
  src/App.php
  src/Core/Console/AutomaticInstallation.php
  src/Core/Installer.php
  src/Module/Install.php
  tests/src/Core/Console/AutomaticInstallationConsoleTest.php
  tests/src/Core/InstallerTest.php
  util/testargs.php
  view/templates/install.tpl
  view/templates/install_db.tpl
  view/templates/install_finished.tpl
  view/templates/install_settings.tpl
Labels: Enhancement, Installation

#6050 regen master messages.po
  util/messages.po
Labels: Translation

#6052 Frio - on mobiles the links in the thread will always have the link color (disabling thread hover effect)
  view/theme/frio/css/style.css
  view/theme/frio/php/default.php
Labels: Enhancement, Mobile, UI/Theme, UX

#6048 Split include/text.php to Model/FileTag class
  include/text.php
  mod/editpost.php
  mod/filer.php
  mod/filerm.php
  mod/item.php
  src/Content/Widget.php
  src/Model/FileTag.php
  src/Model/Item.php
  src/Protocol/DFRN.php
Labels: Enhancement

#6056 Return correctly after post deletion (Non-Ajax)
  include/items.php
  mod/item.php
  src/Object/Post.php
  view/theme/frio/templates/wall_thread.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: Enhancement, UI/Theme

#6057 Update Install.php typos
  src/Module/Install.php
Labels: Docs
