Repository friendica/friendica, pull requests merged in 2018-05, with the labels that each got.

#4962 vier: Fix layout issue introduced with PR #4873.
  view/theme/vier/style.css
Labels: Bug, UI/Theme

#4972 Replace old database queries with the new ones
  include/api.php
  mod/admin.php
  mod/dfrn_confirm.php
  mod/dfrn_poll.php
  mod/dfrn_request.php
  mod/message.php
  mod/pubsubhubbub.php
  mod/settings.php
  src/Model/GContact.php
  src/Model/Term.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
Labels: Enhancement

#4973 Bugfix: Twitter "Reshares" are now appearing again on Diaspora
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#4974 Ugly bugfix: Public contacts had been blocked automatically when created
  src/Network/Probe.php
Labels: Bug

#4977 Avoid SQL error with wrong formatted datetime value
  src/Database/PostUpdate.php
  src/Worker/OnePoll.php
Labels: Bug

#4978 Diaspora: Fix person/contact retraction
  include/api.php
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#4989 Fix video display problems with videos with parameters
  src/Content/Text/BBCode.php
Labels: Bug

#4996 Docs: add a note on adding `use` on theme.php
  doc/themes.md
Labels: Docs/Translation

#5001 translation updates DE, FI, PL
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/fi-fi/messages.po
  view/lang/fi-fi/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Docs/Translation

#5003 Update script to set author-id and owner-id
  boot.php
  src/Database/DBStructure.php
  src/Model/Contact.php
  src/Model/Item.php
  update.php
Labels: Bug

#5007 documentation update for !mentions of forum accounts
  doc/Tags-and-Mentions.md
Labels: Docs/Translation

#5009 regenerated master messages.po file
  util/messages.po
Labels: Docs/Translation

#5012 added dedicated documentation about tools for admins
  doc/Home.md
  doc/de/Home.md
  doc/tools.md
Labels: Docs/Translation

#5015 Issue 4772: Display posts with uid=0 as well
  include/api.php
Labels: API, Enhancement

#5016 Corrects falsely blocked contacts because of some bug in the develop branch
  boot.php
  update.php
Labels: Bug

#5018 Issue 4997: Avoid database duplicates
  src/Protocol/Diaspora.php
  src/Protocol/PortableContact.php
Labels: Bug

#5023 Fix SQL error
  src/Model/GContact.php
Labels: Bug

#5024 Fix: Public items werent visible under certain circumstances
  include/conversation.php
Labels: Bug

#5030 Fix SQL error during postupdate
  src/Database/PostUpdate.php
  src/Model/Item.php
  src/Protocol/PortableContact.php
Labels: Bug

#5031 Avoid SQL error with empty "bd" field
  src/Protocol/Diaspora.php
Labels: Bug

#5032 DE, FI and PL translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/fi-fi/messages.po
  view/lang/fi-fi/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Docs/Translation

#5035 Automatic table optimisation is deactivated by default now
  mod/admin.php
  util/messages.po
Labels: Enhancement

#5036 Fix wrong use of class constants
  src/Protocol/DFRN.php
Labels: Bug

#5040 FI and PL translation updates
  view/lang/fi-fi/messages.po
  view/lang/fi-fi/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Docs/Translation

#5041 [TASK] Automatic installation: Install theme
  doc/themes.md
  src/Core/Console/AutomaticInstallation.php
Labels: Bug, Installation

#5037 Rewrites/curly braces is result usage 001
  mod/admin.php
  mod/poco.php
  mod/share.php
  src/Protocol/DFRN.php
Labels: Enhancement

#5044 We mustn't reshare a feed item (only DFRN and Diaspora)
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#5045 regenerated master messages.po file
  util/messages.po
Labels: Docs/Translation

#5053 Fix for "Illegal string offset 'success'"
  src/Model/Contact.php
Labels: Bug

#5042 Rewrites/curly braces is result usage 002
  .gitattributes
  .gitignore
  .htaccess-dist
  bin/daemon.php
  boot.php
  doc/server-config/readme.txt
  doc/server-config/sample-Lighttpd.config
  doc/server-config/sample-nginx-reverse-proxy.config
  doc/server-config/sample-nginx.config
  include/api.php
  include/conversation.php
  include/items.php
  include/security.php
  include/text.php
  mod/admin.php
  mod/events.php
  mod/photos.php
  mod/subthread.php
  mod/tagger.php
  src/Core/Cache.php
  src/Core/Cache/RedisCacheDriver.php
  src/Core/PConfig.php
  src/Core/Worker.php
  src/Model/Event.php
  src/Model/Item.php
  src/Protocol/DFRN.php
  src/Protocol/OStatus.php
  src/Protocol/PortableContact.php
Labels: Enhancement

#5057 [BUGFIX] .htaccess: Add file
  .gitignore
  .htaccess
Labels: Bug

#5058 [DOCS] Environment variables: Add explanation
  doc/de/Settings.md
  doc/htconfig.md
Labels: Docs/Translation

#5060 item deletion now works again
  include/conversation.php
  src/Model/Item.php
  src/Object/Post.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Worker/Cron.php
Labels: Bug, Enhancement, UX

#5061 Update sample-nginx.config
  mods/sample-nginx.config
Labels: Installation, PHP7

#5068 OpenId possibly fixed
  mod/openid.php
  mod/settings.php
  src/Model/User.php
  src/Module/Login.php
Labels: Bug

#5069 Changed tooltip from #4965
  mod/group.php
  util/messages.po
Labels: Docs/Translation, UX

#5073 regen master messages.po
  util/messages.po
Labels: Bug, Docs/Translation

#5077 Fix to OStatus delivery to be not so blocking to other tasks
  boot.php
  database.sql
  src/Database/DBStructure.php
  src/Model/PushSubscriber.php
  src/Worker/Notifier.php
  src/Worker/PubSubPublish.php
  src/Worker/Queue.php
Labels: Enhancement, Federation

#5076 dont parse the addons directory for translateable strings
  bin/run_xgettext.sh
Labels: Docs/Translation

#5078 Fix: Subscriptions from GNU Social partially don't work
  boot.php
  mod/pubsubhubbub.php
  src/Database/DBStructure.php
Labels: Bug, Federation

#5080 Changed database structure
  database.sql
Labels: Docs/Translation

#5079 Fix: Sometimes the contact endpoints seem to be wrong
  src/Model/Contact.php
Labels: Bug, Federation

#5082 Avoid warning when no valid data could be read
  src/Protocol/PortableContact.php
Labels: Bug

#5085 Fix constant display updates
  mod/display.php
Labels: Enhancement, UX

#5090 Issue-3412 related: Don't send connection posts anymore
  mod/dfrn_confirm.php
  mod/dfrn_request.php
  mod/notifications.php
  mod/profiles.php
  mod/settings.php
  src/Protocol/Diaspora.php
  view/templates/intros.tpl
  view/templates/settings/settings.tpl
  view/theme/frio/templates/intros.tpl
  view/theme/frio/templates/settings/settings.tpl
  view/theme/frost-mobile/templates/settings/settings.tpl
  view/theme/smoothly/style.css
Labels: Enhancement, UX

#5094 regen master messages.po
  util/messages.po
Labels: Docs/Translation

#5097 regen credits
  bin/dev/make_credits.py
  util/credits.txt
Labels: Docs/Translation

#5098 translation update DE, FR, FI, PL
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/fi-fi/messages.po
  view/lang/fi-fi/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Docs/Translation

#5102 forgot to rename vars in TOS template
  view/templates/tos.tpl
Labels: Bug

#5105 Don't proxy pictures when they are sent to other networks
  src/Content/Text/BBCode.php
Labels: Bug

#5106 EN US and GB translation updates THX AndyH3
  view/lang/en-gb/messages.po
  view/lang/en-gb/strings.php
  view/lang/en-us/messages.po
  view/lang/en-us/strings.php
Labels: Docs/Translation

#5108 update DE translations THX hauke
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Docs/Translation

#5117 Issue 5010: Don't show removed users
  src/Model/Profile.php
Labels: Bug

#5119 Remove obsolete DNS test from include/dba
  include/dba.php
Labels: Bug

#5124 IS and PL translation updates
  view/lang/is/messages.po
  view/lang/is/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Docs/Translation

#5123 Bugfix: compute the current theme each time we want to know which theme is beeing used
  src/App.php
Labels: Bug

#5122 applying changes to mods/sample-nginx.config from #5019
  mods/sample-nginx.config
Labels: Enhancement, Installation

#5128 exchange help text
  mod/settings.php
Labels: Bug, Docs/Translation

#5129 added a warning to an admin setting
  mod/admin.php
Labels: Docs/Translation

#5132 update to the zh-cn translation THX 朱陈锬
  view/lang/zh-cn/messages.po
  view/lang/zh-cn/strings.php
Labels: Docs/Translation

#5131 Make `htconfig.php` fit for MariaDB
  htconfig.php
  view/templates/htconfig.tpl
Labels: Enhancement, Installation

#5139 Frio: fix tos page background for frio and move tos link to a another place in the nave menu
  view/theme/frio/css/style.css
  view/theme/frio/templates/nav.tpl
Labels: Bug, UI/Theme

#5140 Fix autoname output length
  include/text.php
Labels: Bug

#5145 4419 Update the comments in src/Database/DBStructure.php from doc
  boot.php
  database.sql
  src/Database/DBStructure.php
Labels: Docs/Translation

#5143 hide profile help text clarification
  mod/settings.php
Labels: Docs/Translation

#5152 the detected language was not stored during user creation
  src/Model/User.php
Labels: Bug

#5150 5147 Typo 'bandwith' should be 'bandwidth'
  mod/admin.php
  mod/settings.php
  mod/update_community.php
  mod/update_display.php
  mod/update_network.php
  mod/update_notes.php
  mod/update_profile.php
Labels: Bug, Docs/Translation

#5153 update to the NL translation THX Pascal Deklerck
  view/lang/nl/messages.po
  view/lang/nl/strings.php
Labels: Docs/Translation
