Repository friendica/friendica, pull requests merged in 2018-11, with the labels that each got.

#6058 [frio] Fix unarchive contact batch action
  src/Module/Contact.php
Labels: Bug, UI/Theme

#6060 CS, DE, PL translation updates
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#6061 AutoInstall Test fix
  tests/Util/AppMockTrait.php
  tests/Util/RendererMockTrait.php
  tests/datasets/ini/assert.ini.php
  tests/src/Core/Console/AutomaticInstallationConsoleTest.php
Labels: Enhancement, Tests

#6062 Test enhancements
  src/BaseObject.php
  tests/DatabaseTest.php
  tests/MockedTest.php
  tests/Util/AppMockTrait.php
  tests/Util/DBAMockTrait.php
  tests/Util/L10nMockTrait.php
  tests/Util/RendererMockTrait.php
  tests/include/ApiTest.php
  tests/include/TextTest.php
  tests/src/App/ModeTest.php
  tests/src/BaseObjectTest.php
  tests/src/Core/Console/AutomaticInstallationConsoleTest.php
  tests/src/Core/InstallerTest.php
Labels: Enhancement, Tests

#6065 Fix for delivering forum posts again
  mod/item.php
  src/Model/Term.php
Labels: Bug

#6067 Preparations for a relocation message / fix for notice
  src/Model/APContact.php
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Util/JsonLD.php
Labels: Enhancement, Federation

#6071 Support for fetching non-public content / preparations for forum posts
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Util/HTTPSignature.php
  src/Util/Network.php
Labels: Enhancement, Federation

#6072 Fixes #6071: We should use the correct variable ...
  src/Core/Worker.php
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, Federation

#6076 Lock TTL fix
  tests/src/Core/Cache/ArrayCacheDriverTest.php
  tests/src/Core/Cache/DatabaseCacheDriverTest.php
  tests/src/Core/Cache/MemcacheCacheDriverTest.php
  tests/src/Core/Cache/MemcachedCacheDriverTest.php
  tests/src/Core/Cache/RedisCacheDriverTest.php
  tests/src/Core/Lock/ArrayCacheLockDriverTest.php
  tests/src/Core/Lock/DatabaseLockDriverTest.php
  tests/src/Core/Lock/MemcacheCacheLockDriverTest.php
  tests/src/Core/Lock/MemcachedCacheLockDriverTest.php
  tests/src/Core/Lock/RedisCacheLockDriverTest.php
  tests/src/Core/Lock/SemaphoreLockDriverTest.php
Labels: Enhancement, Tests

#6080 Issue 6074: Language and "explicit" are now exported
  mod/friendica.php
Labels: Enhancement, Federation

#6079 Directory issue 15: Support the "account-type"
  mod/noscrape.php
Labels: Enhancement, Federation

#6085 Split text.php functions to HTML class
  include/api.php
  include/text.php
  mod/network.php
  mod/profperm.php
  mod/search.php
  src/Content/ForumManager.php
  src/Content/Text/HTML.php
  src/Model/Profile.php
  src/Protocol/DFRN.php
Labels: Enhancement

#6086 Fix Friendica node info json
  mod/friendica.php
  src/Protocol/PortableContact.php
Labels: Bug

#6090 Split functions to L10n
  include/items.php
  include/text.php
  mod/poke.php
  src/Core/L10n.php
  src/Model/Event.php
  src/Model/Profile.php
  src/Util/Temporal.php
Labels: Enhancement

#6092 Fix return url when dropping post loaded by update_* in non-frio
  include/items.php
  mod/update_contact.php
  view/js/main.js
Labels: Enhancement

#6093 Split text.php to Item class
  include/conversation.php
  include/enotify.php
  include/text.php
  mod/item.php
  src/Content/Text/BBCode.php
  src/Model/Item.php
  src/Object/Post.php
  src/Protocol/Email.php
Labels: Enhancement

#6096 We now directly support the custom emojis from Mastodon
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Util/JsonLD.php
Labels: Enhancement, Federation

#6098 New indexes to speed up the worker
  config/dbstructure.php
Labels: Enhancement, Performance

#6099 Using CSS for custom emojis
  src/Protocol/ActivityPub/Processor.php
  view/global.css
Labels: Enhancement, Federation, UX

#6097 Refactoring identities to Model\User::identities
  src/Core/Authentication.php
  src/Model/User.php
  tests/Util/DBAMockTrait.php
  tests/src/Model/UserTest.php
Labels: Enhancement

#6106 Fix webfinger and OStatus support
  mod/follow.php
  src/Core/Logger.php
  src/Model/Contact.php
  src/Network/Probe.php
  src/Protocol/Feed.php
Labels: Bug, Federation

#6108 Add some hook to check if hook should be forked
  doc/Addons.md
  src/Core/Hook.php
Labels: Enhancement, Performance

#6110 Issue 6100: The AS object should be fetchable for every original post
  src/Module/Objects.php
Labels: Enhancement, Federation

#6112 Removing some notices again
  src/Protocol/PortableContact.php
  src/Worker/Delivery.php
Labels: Enhancement

#6113 API: The wrong user had been shown for repeated posts
  include/api.php
Labels: API, Bug

#6116 Avoid a blocked workerqueue due to removed users
  src/Worker/RemoveUser.php
Labels: Enhancement, Performance

#6114 Fix wrong server detecting / improved Pleroma version numbers
  mod/admin.php
  src/Network/CurlResult.php
Labels: Enhancement, Federation

#6118 Execute database update before post update is called
  src/Core/Console/PostUpdate.php
Labels: Enhancement, UX

#6120 Issue 6032: Avoid fatal error
  mod/profile.php
Labels: Bug

#6121 Don't suggest hidden contacts / Added AP to the suggestions
  mod/dirfind.php
  mod/noscrape.php
  src/Model/GContact.php
Labels: Enhancement, UX

#6123 Fix Notice in LegacyModule
  src/LegacyModule.php
Labels: Bug

#6129 Convert remaining instances of "contacts" in mod/(un)follow
  mod/follow.php
  mod/unfollow.php
Labels: Enhancement

#6127 Avoid "Cannot modify header information - headers already sent"
  mod/profile.php
Labels: Enhancement, Federation

#6132 Just some notice again
  src/Module/Contact.php
Labels: Enhancement

#6134 We now use our regular feed that allows anonymous polling
  src/Protocol/OStatus.php
Labels: Enhancement, Federation

#6137 WebSub fixes
  mod/pubsubhubbub.php
Labels: Enhancement, Federation

#6138 Make feeds look more like feeds
  src/Module/Feed.php
  src/Protocol/OStatus.php
Labels: Enhancement, Federation

#6139 Some more feed simplification
  src/Protocol/OStatus.php
Labels: Enhancement, Federation

#6143 cp htaccess in Vagrant VM on setup
  bin/dev/vagrant_provision.sh
Labels: Berlin2018, Bug, Installation

#6146 Title difference for two different ATOM feeds
  mod/profile.php
Labels: Enhancement, Federation

#6145 Fix ATOM feed entry titles encoding
  src/Protocol/OStatus.php
Labels: Enhancement, Federation

#6153 Fix return url when delete comment from display
  include/items.php
Labels: Enhancement, UX

#6147 Fix lack of HTML encoding for stylesheet link
  view/templates/head.tpl
  view/theme/frio/templates/head.tpl
Labels: Enhancement

#6155 Use appropriate redirect in dfrn_poll
  mod/dfrn_poll.php
Labels: Berlin2018, Bug

#6156 recreated SQL file for Vagrant VM from current DB structure
  friendica_test_data.sql
Labels: Berlin2018, Installation

#6152 Fix deleting last element and displaying empty saved folder
  mod/filerm.php
  mod/network.php
  src/Model/FileTag.php
  src/Model/Item.php
Labels: Berlin2018, Enhancement, UX

#6158 Add link to user groups from /contact
  doc/Accesskeys.md
  src/Module/Contact.php
Labels: Berlin2018, Bug, UI/Theme

#6159 [frio] Fix setting permisson as post for uploaded photo in album via modal create post
  mod/item.php
Labels: Berlin2018, Bug, UX

#6144 Correct self attribute in ATOM feeds
  src/Protocol/OStatus.php
Labels: Enhancement, Federation

#6162 Delete comment from its guid and return to parent guid
  include/items.php
Labels: Bug, UX

#6164 Networks are now protocols
  src/Content/ContactSelector.php
  src/Content/Feature.php
  src/Content/Widget.php
Labels: Enhancement, UX

#6163 [Doc] Rearranged and wrote some parts new and more coherent.
  doc/de/Account-Basics.md
Labels: Berlin2018, Docs, Translation

#6169 Update nginx sample config
  mods/sample-nginx.config
Labels: Docs, Installation

#6171 Change Worker to use only MemFree in isMinMemoryReached
  src/App.php
Labels: Enhancement, Performance

#6177 Sanitize the OEmbed data before processing it
  src/Content/OEmbed.php
  src/Object/OEmbed.php
Labels: Enhancement, Security

#6178 "viewcontacts" hadn't displayed the AP contacts
  mod/viewcontacts.php
Labels: Enhancement, UX

#6179 Fix SQL grammar error: ORDER BY clause is not in SELECT
  mod/profile.php
Labels: Bug

#6176 AP: Security check against forged "create" activities
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement, Federation, Security

#6182 Add new REGISTRATION_INVITATION value to mod/friendica output
  mod/friendica.php
  mod/redir.php
Labels: Enhancement, Federation

#6185 Checking for blocked user does now check for blocked domain as well
  src/Model/Contact.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/Delivery.php
Labels: Enhancement

#6186 Fix OStatus Subscribe fatal error
  mod/ostatus_subscribe.php
Labels: Bug

#6188 Protect OAuthException declaration to avoid conflict with php-pecl-oauth
  library/OAuth1.php
Labels: Bug

#6189 Fix ignore link showing for anonymous users
  src/Object/Post.php
Labels: Bug, UX

#6192 Fix display of Connect/Disconnect links on contact page
  src/Module/Contact.php
Labels: Bug, UX

#6191 URL encode /network file query parameter
  include/conversation.php
  mod/filerm.php
  mod/network.php
  mod/search.php
  src/Content/Text/HTML.php
Labels: Bug

#6194 regen master messages.po
  util/messages.po
Labels: Enhancement, Translation

#6184 Normalize BBCode hashtags links
  include/items.php
  mod/photos.php
  mod/tagger.php
  src/Content/Text/BBCode.php
  src/Model/Item.php
  src/Model/Term.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
Labels: Enhancement

#6193 Fixing redirection problems with parameters
  src/Network/CurlResult.php
Labels: Enhancement

#6183 Hide follower-only birthday reminders
  composer.json
  composer.lock
  mod/hovercard.php
  mod/profiles.php
  src/Model/Contact.php
  src/Model/Event.php
  src/Model/GContact.php
  src/Model/Profile.php
  src/Protocol/DFRN.php
Labels: Enhancement, UX

#6181 [Frio] Add collapsable panel groups for admin/site with anchors at headlines
  mod/admin.php
  view/templates/admin/site.tpl
  view/theme/frio/css/mod_admin.css
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement, UI/Theme, UX

#6198 User removal improvements
  mod/admin.php
  mod/removeme.php
  src/Model/User.php
Labels: Bug, Enhancement

#6203 Show contact posts from hidden users
  include/conversation.php
Labels: Enhancement, UX

#6207 Add missing closing tags
  view/templates/admin/summary.tpl
  view/theme/frio/templates/admin/summary.tpl
Labels: Bug, UI/Theme

#6199 Move config to PHP array
  .gitignore
  .travis.yml
  INSTALL.txt
  bin/daemon.php
  bin/dev/vagrant_provision.sh
  boot.php
  config/addon-sample.config.php
  config/addon-sample.ini.php
  config/config.ini.php
  config/dbstructure.config.php
  config/defaults.config.php
  config/local-sample.config.php
  config/local-sample.ini.php
  config/settings.config.php
  config/settings.ini.php
  doc/Config.md
  doc/FAQ.md
  doc/Home.md
  doc/Install.md
  doc/Installing-Connectors.md
  doc/Settings.md
  doc/Update.md
  doc/Vagrant.md
  doc/de/FAQ.md
  doc/de/Home.md
  doc/de/Install.md
  doc/de/Installing-Connectors.md
  doc/de/Settings.md
  mod/admin.php
  src/App.php
  src/App/Mode.php
  src/Core/Config/JITConfigAdapter.php
  src/Core/Console/AutomaticInstallation.php
  src/Core/Console/Config.php
  src/Core/Installer.php
  src/Database/DBStructure.php
  tests/Util/VFSTrait.php
  tests/src/App/ModeTest.php
  tests/src/Core/Console/AutomaticInstallationConsoleTest.php
  tests/src/Core/Console/ConfigConsoleTest.php
  tests/src/Core/InstallerTest.php
  update.php
  util/local.config.vagrant.php
  util/local.ini.vagrant.php
  view/templates/local.config.tpl
  view/templates/local.ini.tpl
Labels: Enhancement, Installation

#6210 Fix insert multiple hashtags to term
  src/Model/Term.php
Labels: Bug

#6214 Issue 6212: No need of a redirect for fetching content
  mod/display.php
Labels: Enhancement, Federation
