Repository friendica/friendica, pull requests merged in 2018-08, with the labels that each got.

#5540 Fix missing fields in event reminder
  src/Model/Profile.php
Labels: Bug

#5542 CS, PL translation updates
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#5546 Avoid notices and warnings
  src/Protocol/PortableContact.php
  src/Util/Network.php
Labels: Enhancement

#5551 Fix: Notes can be posted again. Never use "defaults" with "false"
  mod/item.php
  src/Database/DBA.php
  view/theme/frio/templates/jot.tpl
  view/theme/quattro/templates/jot.tpl
Labels: Bug

#5552 Skip DB tests if MYSQL_* environment variables are missing
  tests/DatabaseTest.php
Labels: Bug

#5555 [frio] Removing vertical spaces under the notification button
  view/theme/frio/scheme/plusminus.css
Labels: Enhancement, UI/Theme

#5556 OStatus: Add CW to shared posts
  src/Protocol/OStatus.php
Labels: Bug, Federation

#5554 [frio/vier] Fix JS errors in compose private message page
  view/templates/msg-header.tpl
  view/theme/frio/templates/msg-header.tpl
Labels: Bug, UI/Theme

#5553 [frio] Increase content space on <600px width devices
  view/theme/frio/css/style.css
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: Enhancement, UI/Theme

#5557 Fixes issue 5321: Likes can be undone and comments can be deleted again
  src/Model/Item.php
Labels: Bug

#5558 We shouldn't cascade this deletion as well
  src/Model/Item.php
Labels: Bug

#5559 Fix: dbstructure.json had had dos endings
  config/dbstructure.json
Labels: Enhancement

#5573 Post update script for setting the uri-id
  mod/friendica.php
  src/Database/PostUpdate.php
  src/Model/Item.php
Labels: Enhancement

#5577 regen master messages.po after version string format got updated
  util/messages.po
Labels: Translation

#5567 Converting timezone in admin queues
  mod/admin.php
Labels: Enhancement

#5563 Fix various notices
  mod/cal.php
  mod/photos.php
  src/App.php
  src/Core/Session.php
  src/Model/Profile.php
  src/Util/Proxy.php
Labels: Bug

#5583 Fix for duplicated addon entries in the hook table
  src/Core/Addon.php
Labels: Bug

#5587 Notice in tt fixed that happens with chinese translations
  src/Core/L10n.php
Labels: Enhancement, Translation

#5588 Issue 5158: Ignore all threads, even public ones
  boot.php
  config/dbstructure.json
  database.sql
  include/enotify.php
  mod/ignored.php
  src/Model/Item.php
  src/Object/Post.php
Labels: Bug

#5589 And again removed notices
  mod/update_network.php
Labels: Enhancement

#5591 Fix: Prevent threads from being collapsed in network view
  mod/update_network.php
Labels: Bug, Enhancement

#5592 Avoid probing for contacts if we don't want to update
  src/Model/Contact.php
Labels: Enhancement

#5590 update PL translations THX waldis
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#5593 Issue 4507: Superblock does now work on comments as well
  include/conversation.php
Labels: Addons, Bug

#5595 Hide deprecated networks
  src/Content/Widget.php
Labels: Enhancement

#5537 Stopped using deprecated constants NETWORK_*
  boot.php
  include/api.php
  include/conversation.php
  include/items.php
  include/text.php
  mod/acl.php
  mod/contacts.php
  mod/crepair.php
  mod/delegate.php
  mod/dfrn_confirm.php
  mod/dfrn_request.php
  mod/dirfind.php
  mod/display.php
  mod/fetch.php
  mod/follow.php
  mod/item.php
  mod/network.php
  mod/noscrape.php
  mod/notifications.php
  mod/ostatus_subscribe.php
  mod/poco.php
  mod/profperm.php
  mod/pubsub.php
  mod/redir.php
  mod/repair_ostatus.php
  mod/salmon.php
  mod/unfollow.php
  mod/viewcontacts.php
  src/Content/ContactSelector.php
  src/Content/Widget.php
  src/Core/ACL.php
  src/Core/NotificationsManager.php
  src/Core/UserImport.php
  src/Database/PostUpdate.php
  src/Model/Contact.php
  src/Model/Conversation.php
  src/Model/GContact.php
  src/Model/Item.php
  src/Model/ItemContent.php
  src/Model/Profile.php
  src/Model/User.php
  src/Network/Probe.php
  src/Object/Post.php
  src/Object/Thread.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Email.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  src/Protocol/PortableContact.php
  src/Worker/Cron.php
  src/Worker/CronJobs.php
  src/Worker/Delivery.php
  src/Worker/DiscoverPoCo.php
  src/Worker/GProbe.php
  src/Worker/Notifier.php
  src/Worker/OnePoll.php
  src/Worker/Queue.php
  src/Worker/UpdateGContact.php
Labels: Enhancement

#5601 And again, and again, and again, ... some more notices removed
  mod/bookmarklet.php
  mod/item.php
  src/Content/Nav.php
  src/Content/Widget/CalendarExport.php
  view/theme/frio/templates/profile_edit.tpl
Labels: Bug

#5603 Fix: We now are notified again when a new post had been created
  include/enotify.php
Labels: Bug

#5607 Remove contacts in the background
  src/Model/Contact.php
  src/Worker/RemoveContact.php
Labels: Enhancement

#5609 Fix: Wrong array index / added logging for DFRN connects
  mod/cal.php
  mod/dfrn_confirm.php
Labels: Bug

#5611 Call asynchronous JS after complete page load
  view/js/acl.js
  view/js/main.js
Labels: Enhancement, UX

#5613 frio - add missing page template to various photo pages (fix missing background)
  view/theme/frio/templates/photo_view.tpl
  view/theme/frio/templates/photos_upload.tpl
Labels: Enhancement, UI/Theme

#5614 Fixes the missing refresh after ignoring or unignoring a thread
  mod/ignored.php
Labels: Bug

#5617 Fix bug with ACL and contact network page
  mod/events.php
  mod/network.php
  mod/photos.php
  src/Core/ACL.php
Labels: Bug

#5628 CS translation update THX Aditoo
  view/lang/cs/messages.po
  view/lang/cs/strings.php
Labels: Translation

#5631 placeholder for a funny commit description for removing some more notices
  mod/match.php
  mod/profperm.php
  mod/videos.php
  src/Model/Event.php
Labels: Bug

#5632 Some easy to replace "q" calls have been replaced by "DBA" calls
  boot.php
  include/api.php
  include/enotify.php
  include/items.php
  include/security.php
  include/text.php
  mod/network.php
  mod/subthread.php
  src/Model/Contact.php
  src/Model/Event.php
  src/Model/GContact.php
  src/Model/Item.php
  src/Model/Mail.php
  src/Model/Profile.php
  src/Model/User.php
  src/Module/Login.php
  src/Network/Probe.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Worker/CronJobs.php
Labels: Enhancement

#5636 We now use a central function to fetch the importer
  include/items.php
  mod/dfrn_notify.php
  src/Protocol/DFRN.php
  src/Worker/Delivery.php
Labels: Enhancement

#5634 [frio] Add icons on photo view page.
  view/theme/frio/css/style.css
  view/theme/frio/templates/like_noshare.tpl
  view/theme/frio/templates/photo_view.tpl
Labels: Enhancement, UI/Theme, UX

#5637 Frio: new photos upload template
  mod/photos.php
  view/js/ajaxupload.js
  view/theme/frio/css/style.css
  view/theme/frio/js/modal.js
  view/theme/frio/templates/photos_default_uploader_box.tpl
  view/theme/frio/templates/photos_default_uploader_submit.tpl
  view/theme/frio/templates/photos_upload.tpl
Labels: Enhancement, UI/Theme

#5640 typo in config/settings.ini.php
  config/settings.ini.php
Labels: Bug

#5641 Fix for double $$
  mod/dfrn_notify.php
Labels: Bug

#5565 Automatic Installation fix
  mod/install.php
  src/App.php
  src/Core/Console/AutomaticInstallation.php
  src/Core/Install.php
Labels: Enhancement

#5642 The content generation for the display page is now using a centralized function
  include/conversation.php
  mod/display.php
Labels: Enhancement

#5648 fix redirection - don't dfrn auth when contact is still pending
  mod/redir.php
Labels: UX

#5650 Fix the settings in frio
  view/theme/frio/config.php
Labels: Bug

#5652 Removing a small notice in the network.php
  src/Util/Network.php
Labels: Enhancement

#5654 Fix: Mail notifications arrive again
  include/enotify.php
Labels: Bug

#5655 "dba" is now "DBA". This hadn't been respected at some places
  include/dba.php
  src/Core/System.php
  src/Database/DBA.php
  src/Model/Group.php
  src/Protocol/Diaspora.php
Labels: Enhancement

#5647 API: add private value (bool) to item results
  doc/api.md
  include/api.php
Labels: API, Enhancement

#5608 Cleanups: isResult() more used, readability improved
  mod/dfrn_confirm.php
  mod/photos.php
  mod/repair_ostatus.php
  mod/salmon.php
  mod/suggest.php
  mod/videos.php
  mod/wall_attach.php
  src/Database/DBA.php
  src/Model/Contact.php
  src/Model/Conversation.php
  src/Model/GContact.php
  src/Model/User.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Worker/Delivery.php
  src/Worker/OnePoll.php
Labels: Enhancement

#5657 Issue 4960: Ignoring and blocking of contacts should work again
  boot.php
  config/dbstructure.json
  database.sql
  include/conversation.php
  mod/allfriends.php
  mod/common.php
  mod/contacts.php
  mod/crepair.php
  mod/dirfind.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Object/Thread.php
  view/js/main.js
  view/templates/contact_edit.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/frio/theme.php
  view/theme/vier/templates/contact_edit.tpl
Labels: Bug

#5664 Isse 4726: Fixes the condition for showing hidden contacts
  src/Content/ForumManager.php
Labels: Bug

#5665 NL translation update THX Jeroen
  view/lang/nl/messages.po
  view/lang/nl/strings.php
Labels: Translation

#5663 Issue 5320: Deleting of events returned a wrong message
  mod/events.php
Labels: Bug, Calendar

#5666 Issue 5260: Ensure that user data is really deleted
  src/Model/User.php
  src/Worker/CronJobs.php
  src/Worker/RemoveUser.php
Labels: Bug, UX

#5661 Issue 5660: Check if .well-known is reachable
  mod/admin.php
Labels: Enhancement

#5668 [frio] Prevent Safari iOS input zoom
  view/theme/frio/css/style.css
  view/theme/frio/templates/nav.tpl
Labels: Enhancement, Mobile, UI/Theme, UX

#5671 Avoid useless contact updates
  src/Protocol/DFRN.php
Labels: Bug

#5672 Issue 5670: Jump to the unassigned contacts
  mod/group.php
Labels: Bug, UX

#5667 Update doc/Install.md to Describe host-meta
  doc/Install.md
Labels: Docs

#5674 Automatic Install Tests & Doku
  composer.json
  composer.lock
  doc/Install.md
  doc/de/Install.md
  mod/install.php
  src/App.php
  src/Core/Console/AutomaticInstallation.php
  src/Core/Install.php
  tests/src/Core/Console/AutomaticInstallationConsoleTest.php
  tests/src/Core/Console/ConfigConsoleTest.php
  tests/src/Core/Console/ConsoleTest.php
Labels: Enhancement, Installation

#5680 User import is now only possible on open sites or via an administrator
  mod/uimport.php
Labels: Bug

#5675 Added widget class to invitationsbox
  src/Content/Widget.php
Labels: UI/Theme

#5683 Added documentation about the limits of the user import
  doc/Move-Account.md
  doc/de/Move-Account.md
Labels: Docs

#5684 Ensure that the post update doesn't end prematurely
  src/Database/PostUpdate.php
Labels: Enhancement

#5688 CS translation update THX Aditoo
  view/lang/cs/messages.po
  view/lang/cs/strings.php
Labels: Translation

#5689 Poke is fixed
  include/conversation.php
  mod/poke.php
Labels: Bug

#5692 The post update version can now be set
  src/Core/Console/PostUpdate.php
Labels: Enhancement

#5693 Removed notice - pokes do now work mostly
  include/conversation.php
  src/Protocol/DFRN.php
Labels: Bug

#5697 Oh no, even more notices ...
  mod/videos.php
  src/Model/User.php
Labels: Enhancement

#5698 Issue 5696: Removed old forum link
  doc/Developers-Intro.md
Labels: Bug, Docs

#5699 Issue 5691: Post dates of feeds sometimes had been wrong
  src/Protocol/Feed.php
Labels: Bug

#5700 Issue 5653: The mastodonemoji addon hadn't got all needed data.
  src/Model/Item.php
Labels: Bug

#5703 Fix: Missing gserver entries - show correct server platform
  src/Model/Contact.php
Labels: Bug, UX

#5704 Fix unfollow sharing-only contacts (except connector protocols)
  mod/contacts.php
  mod/unfollow.php
  src/Core/Protocol.php
Labels: Bug
