Repository friendica/friendica, pull requests merged in 2018-12, with the labels that each got.

#6220 Fixing permanent deletion counter
  mod/admin.php
  src/Worker/CronJobs.php
Labels: Enhancement, UX

#6221 Updated .well-known location within Nginx Sample Config:
  mods/sample-nginx.config
Labels: Enhancement, Installation

#6216 Remove "all" value for nets parameter
  mod/network.php
  src/Content/Nav.php
  src/Module/Contact.php
  view/templates/contact_edit.tpl
  view/templates/nets.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/frio/templates/nets.tpl
  view/theme/quattro/templates/nets.tpl
  view/theme/vier/templates/contact_edit.tpl
Labels: Bug, Enhancement, UX

#6225 Using the standard function to return http errors
  mod/fetch.php
  mod/pubsub.php
  src/Core/System.php
Labels: Enhancement

#6224 Avoid duplicated contacts, improve contact deletion, avoid memory issues
  config/dbstructure.config.php
  src/Core/Update.php
  src/Database/DBA.php
  src/Model/Contact.php
Labels: Enhancement

#6226 Ignoring OEmbed array values
  src/Object/OEmbed.php
Labels: Enhancement

#6227 Fix: The event name mustn't be escaped, since it can contain converte…
  view/theme/frio/templates/event_stream_item.tpl
Labels: Bug

#6223 Fix for "Unknown column 'guid' in 'field list'"
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug

#6222 Avoid problems with too long URI (should only happen with some RSS feeds)
  src/Model/ItemURI.php
Labels: Enhancement, Federation

#6229 Issue 5911: Fix for fetching the correct user
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#6230 Fix for exceptions on external redirects
  src/Core/System.php
Labels: Enhancement

#6233 Added a hint to help/Settings "Logs/logrotate" section in install.md
  doc/Install.md
Labels: Docs

#6234 Issue 6168: "redir" now mostly use OWA
  mod/dfrn_poll.php
  mod/redir.php
  src/Model/Contact.php
  src/Network/CurlResult.php
  src/Network/Probe.php
  src/Util/LDSignature.php
Labels: Enhancement

#6235 Avoids the notice "array_merge(): Argument #1 is not an array"
  src/Network/CurlResult.php
Labels: Bug

#6237 Issue 6236: Handle account removal messages with very low priority
  src/Worker/Notifier.php
Labels: Enhancement, Performance

#6244 Fix for remote authentication when visiting contact's pages
  include/conversation.php
  mod/delegate.php
  mod/display.php
  mod/profile.php
  src/Model/Contact.php
  src/Model/Item.php
Labels: Bug, Federation

#6252 Possibly fix a memory issue with large posts
  mod/display.php
  src/Util/JsonLD.php
Labels: Enhancement, Federation, Performance

#6253 The "about" field shouldn't be escaped
  view/theme/frio/templates/contact_edit.tpl
Labels: Bug, UI/Theme

#6260 Issue 6257: Make notes visible again
  include/conversation.php
  mod/notes.php
Labels: Bug

#6256 Add check for relationship with remote user for connect display
  src/Model/Profile.php
Labels: Bug, UX

#6261 Fix for magic auth
  src/Model/Profile.php
Labels: Bug, Federation

#6180 [WIP] Pluggable storage backend
  .gitignore
  composer.json
  config/dbstructure.config.php
  database.sql
  doc/AddonStorageBackend.md
  doc/Home.md
  doc/Settings.md
  doc/tools.md
  include/api.php
  mod/admin.php
  mod/item.php
  mod/photo.php
  mod/photos.php
  mod/profile_photo.php
  src/Core/Console.php
  src/Core/Console/Storage.php
  src/Core/StorageManager.php
  src/Core/System.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Mail.php
  src/Model/Photo.php
  src/Model/Storage/Database.php
  src/Model/Storage/Filesystem.php
  src/Model/Storage/IStorage.php
  src/Model/Storage/StorageException.php
  src/Model/Storage/SystemResource.php
  src/Model/User.php
  src/Module/Photo.php
  src/Module/Proxy.php
  src/Worker/CronJobs.php
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: New Feature, Performance

#6270 Fix various notices
  src/Content/Text/BBCode.php
  src/Model/GContact.php
  src/Protocol/Email.php
  src/Protocol/OStatus.php
  src/Protocol/PortableContact.php
  src/Util/Network.php
  src/Worker/GProbe.php
Labels: Bug

#6273 API - /media/upload - add return value #6272
  doc/api.md
  include/api.php
  tests/include/ApiTest.php
Labels: API, Enhancement

#6275 API - /search #6274
  include/api.php
  tests/include/ApiTest.php
Labels: API, Enhancement

#6278 Fix: Contacts can now be edited again
  view/theme/frio/templates/contact_edit.tpl
Labels: Bug, UX

#6279 Fix StorageManager::move()
  src/Core/StorageManager.php
Labels: Bug

#5751 Gender, Maritial status and sexual preference fix
  config/dbstructure.config.php
  src/Content/ContactSelector.php
  src/Model/Profile.php
  update.php
Labels: Enhancement, Translation, UX

#6287 Updated update.php towards code standard
  update.php
Labels: Enhancement

#6290 Fixes issue 6289
  view/templates/jot.tpl
  view/theme/frio/templates/jot.tpl
  view/theme/quattro/templates/jot.tpl
  view/theme/smoothly/templates/jot.tpl
Labels: Bug, Security, UI/Theme, UX

#6295 Issue 6294: Fix templates
  view/theme/frio/templates/register.tpl
Labels: Bug, Security, UX

#6280 Fix message list query
  mod/message.php
  view/templates/mail_head.tpl
  view/theme/frio/templates/mail_head.tpl
Labels: Bug, UX

#6298 Issue 6297 - and again template stuff
  view/templates/photos_upload.tpl
  view/theme/frio/templates/photos_upload.tpl
Labels: Bug, Security, UX

#6299 Issue 6296 - and again templates
  view/templates/admin/addon_details.tpl
Labels: Bug, Security, UX

#6301 API: Fix author of repeated items from Diaspora
  include/api.php
Labels: Bug, Federation

#6302 Isse 6300: And again templates ...
  view/templates/intros.tpl
  view/theme/frio/templates/intros.tpl
Labels: Bug, Security, UX

#6310 Handles issue 6122 - the self contact will be updated when invalid
  src/Model/Contact.php
  src/Model/User.php
Labels: Enhancement

#6311 Issue 6308 - and again ...
  view/theme/frio/templates/group_edit.tpl
Labels: Bug, Security, UX

#6293 Add number of comments to API calls + add support for exclude_replies in API search
  doc/api.md
  include/api.php
  tests/include/ApiTest.php
Labels: API, Enhancement

#6312 Checks if JSON is enabled
  src/Core/Installer.php
  tests/src/Core/InstallerTest.php
Labels: Enhancement, Installation

#6314 Fix template escaping in photo gallery view
  view/templates/email_notify_html.tpl
  view/templates/photo_view.tpl
  view/theme/frio/templates/photo_view.tpl
  view/theme/quattro/templates/photo_view.tpl
  view/theme/vier/templates/photo_view.tpl
Labels: Bug, Security, UX

#6318 The "Follow" activity shouldn't be send to Diaspora
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#6321 Escape event output
  mod/events.php
  src/Model/Event.php
  src/Protocol/ActivityPub/Processor.php
  view/theme/frio/templates/event_stream_item.tpl
Labels: Bug, Security, UX

#6324 Remove redundant html encoding
  mod/admin.php
  mod/allfriends.php
  mod/babel.php
  mod/common.php
  mod/credits.php
  mod/crepair.php
  mod/editpost.php
  mod/follow.php
  mod/message.php
  mod/network.php
  mod/profile.php
  mod/unfollow.php
  mod/viewcontacts.php
  mod/wallmessage.php
  src/Content/Text/HTML.php
  src/Module/Itemsource.php
  view/templates/babel.tpl
  view/templates/wallmessage.tpl
  view/theme/frio/templates/contact_template.tpl
  view/theme/frio/templates/field_textarea.tpl
Labels: Bug, Security, UX

#6320 I'm wishing you and your family a very happy christmas
  boot.php
  index.php
Labels: Won't Fix

#6331 Unescape vcard network link
  include/api.php
  mod/hovercard.php
  src/Model/Profile.php
  src/Module/Contact.php
  src/Util/Strings.php
  view/templates/hovercard.tpl
  view/templates/profile_vcard.tpl
  view/templates/vcard-widget.tpl
  view/theme/duepuntozero/templates/profile_vcard.tpl
  view/theme/frio/templates/vcard-widget.tpl
  view/theme/quattro/templates/profile_vcard.tpl
  view/theme/vier/templates/profile_vcard.tpl
Labels: Bug, UX

#6341 Replace latin-1 by latin1 in charset detection
  src/Util/ParseUrl.php
Labels: Bug

#6209 Remove util/ folder
  .tx/config
  CREDITS.txt
  Doxyfile
  INSTALL.md
  INSTALL.txt
  README.translate.md
  bin/dev/friendica-to-smarty-tpl.py
  bin/dev/make_credits.py
  bin/dev/updatetpl.py
  bin/dev/vagrant_provision.sh
  bin/run_xgettext.sh
  bin/testargs.php
  config/addon-sample.config.php
  doc/Config.md
  doc/Developers-Intro.md
  doc/Settings.md
  doc/de/Settings.md
  doc/html/index.php
  doc/translations.md
  mod/credits.php
  mods/README.md
  mods/bookmarklet-share2friendica/README.md
  mods/bookmarklet-share2friendica/bookmarklet-share2friendica.js
  mods/fpostit/README
  mods/fpostit/fpostit.js
  mods/fpostit/fpostit.php
  mods/fpostit/friendika-32.png
  mods/local.config.vagrant.php
  mods/redme.txt
  phpunit.xml
  src/Core/Console/DocBloxErrorChecker.php
  src/Core/Console/PhpToPo.php
  src/Core/Console/PoToPhp.php
  src/Core/Console/Typo.php
  src/Core/Installer.php
  util/.htaccess
  util/Doxygen.footer
  util/README
  util/strings.php
  view/lang/C/messages.po
Labels: Docs, Enhancement, Translation

#6342 Warning and notice fixed
  src/Content/Text/HTML.php
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#6339 forcing language by parameter
  doc/FAQ.md
  src/Core/L10n.php
Labels: Enhancement

#6340 Fix site theme settings modal form
  mod/admin.php
  src/App.php
  view/templates/admin/addon_details.tpl
  view/templates/admin/site.tpl
  view/theme/frio/README.md
  view/theme/frio/css/style.css
  view/theme/frio/templates/admin/site.tpl
Labels: Bug, UX

#6353 Unescape plaintext email body
  view/templates/email_notify_text.tpl
Labels: Bug, UX

#6352 Normalize config file line endings to LF
  config/addon-sample.config.php
  config/defaults.config.php
  config/local-sample.config.php
  config/settings.config.php
Labels: Bug

#6351 Unescape admin warning text
  view/templates/admin/summary.tpl
  view/theme/frio/templates/admin/summary.tpl
Labels: Bug, UX

#6348 Updated lang parameter docs towards Tobias comment
  doc/FAQ.md
Labels: Docs
