Repository friendica/friendica, pull requests merged in 2018-06, with the labels that each got.

#5154 Fix version number in database.sql
  database.sql
Labels: Docs/Translation

#5156 Small corrections to the database descriptions
  src/Database/DBStructure.php
Labels: Bug, Docs/Translation

#5160 regen master messages.po
  util/messages.po
Labels: Docs/Translation

#5161 "redir" is now centralized
  include/conversation.php
  include/text.php
  mod/allfriends.php
  mod/contacts.php
  mod/dfrn_request.php
  mod/directory.php
  mod/dirfind.php
  mod/hovercard.php
  mod/match.php
  mod/message.php
  mod/photos.php
  mod/randprof.php
  mod/redir.php
  mod/suggest.php
  mod/unfollow.php
  mod/viewcontacts.php
  src/Content/ForumManager.php
  src/Core/NotificationsManager.php
  src/Model/Contact.php
  src/Model/Event.php
  src/Model/Profile.php
  src/Model/Term.php
  src/Object/Post.php
  view/theme/vier/theme.php
Labels: Enhancement

#5162 update DE translations
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Docs/Translation

#5157 Workers can now be started exclusively from the daemon and other workers
  bin/daemon.php
  boot.php
  database.sql
  include/dba.php
  src/Core/Worker.php
  src/Database/DBStructure.php
Labels: Enhancement

#5169 update to the NL translation THX Pascal
  view/lang/nl/messages.po
  view/lang/nl/strings.php
Labels: Docs/Translation

#5170 We don't poll, we work ... Bugfix for renamed config value.
  mod/admin.php
  mod/worker.php
Labels: Bug

#5182 Translation updates DE, FI, IT, NL. PL
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/fi-fi/messages.po
  view/lang/fi-fi/strings.php
  view/lang/it/messages.po
  view/lang/it/strings.php
  view/lang/nl/messages.po
  view/lang/nl/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Docs/Translation

#5203 More abstraction for the item access
  mod/acl.php
  mod/poke.php
  mod/share.php
  mod/subthread.php
  mod/tagger.php
Labels: Enhancement

#5179 5118 Create Javascript hook mechanism
  doc/Addons.md
  view/js/addon-hooks.js
  view/js/main.js
  view/templates/head.tpl
Labels: New Feature

#5210 Frio: fix contact filtering on contacts page
  mod/contacts.php
  view/theme/frio/js/theme.js
Labels: Bug

#5213 Create config keys if they not exists on set (bis)
  src/App.php
Labels: Enhancement

#5216 solves 2337 Smiley Pack 1.04: some smiley keywords aren't replaced correctly
  src/Content/Smilies.php
Labels: Bug

#5218 Fix feed blank reshare body
  mod/share.php
Labels: Bug

#5223 Multiple daemon improvements (foreground, faster spawning)
  bin/daemon.php
  src/Core/Worker.php
Labels: Enhancement

#5227 Fix PHP 7.2 Warning in Model\Contact
  src/Model/Contact.php
Labels: Bug, PHP7.2

#5226 More item calls have been replaced with the new functions
  include/conversation.php
  include/enotify.php
  mod/network.php
  mod/ping.php
  src/Core/NotificationsManager.php
  src/Model/Item.php
Labels: Enhancement

#5229 fix scroll position in stream while ajax update
  composer.json
  composer.lock
  mod/update_community.php
  mod/update_display.php
  mod/update_network.php
  mod/update_notes.php
  mod/update_profile.php
  view/js/main.js
  view/templates/head.tpl
  view/theme/frio/templates/head.tpl
  view/theme/quattro/templates/search_item.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/vier/templates/search_item.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: Enhancement, UX

#5230 New function for generating item URI
  include/api.php
  include/text.php
  mod/item.php
  mod/photos.php
  mod/poke.php
  mod/subthread.php
  mod/tagger.php
  src/Model/Event.php
  src/Model/Item.php
  src/Protocol/Diaspora.php
Labels: Enhancement

#5232 Separate functions for fetching items for the system and for users
  include/api.php
  include/conversation.php
  include/enotify.php
  mod/acl.php
  mod/display.php
  mod/network.php
  mod/notes.php
  mod/ping.php
  mod/poke.php
  mod/profile.php
  mod/search.php
  mod/share.php
  mod/subthread.php
  mod/tagger.php
  src/Core/NotificationsManager.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Worker/Delivery.php
  src/Worker/Notifier.php
Labels: Enhancement

#5235 missing markdown formatting added
  doc/htconfig.md
Labels: Docs

#5236 CS and NL translation update
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/nl/messages.po
  view/lang/nl/strings.php
Labels: Translation

#5237 update to the zh-cn translation THX 朱陈锬
  view/lang/zh-cn/messages.po
  view/lang/zh-cn/strings.php
Labels: Translation

#5240 worker.php - fix missing use statement
  mod/worker.php
Labels: Bug

#5242 Bugfix: hide savedsearch button and subthread button for non local_users
  include/text.php
  view/theme/frio/theme.php
Labels: Bug, UI/Theme

#5238 Even more replaced item calls ...
  include/api.php
  include/conversation.php
  include/items.php
  include/text.php
  mod/display.php
  mod/editpost.php
  mod/fetch.php
  mod/photos.php
  mod/tagrm.php
  mod/viewsrc.php
  src/Model/Item.php
  src/Model/Term.php
  src/Model/User.php
  src/Object/Post.php
  src/Protocol/OStatus.php
Labels: Enhancement

#5248 Fix logic errors in tooMuchWorkers()
  src/Core/Worker.php
Labels: Bug

#5250 regen master messages.po
  util/messages.po
Labels: Translation

#5251 Unify Worker Load Formulas
  doc/htconfig.md
  src/Core/Worker.php
Labels: Enhancement

#5255 update DE translations
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#5256 Filter Removed Users From Directory
  mod/directory.php
Labels: Bug, UX

#5253 Port hubzillas OpenWebAuth - remote authentification
  boot.php
  database.sql
  doc/Addons.md
  index.php
  mod/xrd.php
  src/Core/System.php
  src/Database/DBStructure.php
  src/Model/OpenWebAuthToken.php
  src/Model/Profile.php
  src/Module/Magic.php
  src/Module/Owa.php
  src/Util/Crypto.php
  src/Util/HTTPHeaders.php
  src/Util/HTTPSignature.php
  view/templates/xrd_person.tpl
Labels: New Feature

#5259 port hubzillas OpenWebAuth - don't initiate magic auth if the contact is allready authentificated
  src/Model/Profile.php
Labels: Bug

#5263 Make Conversation Cleanup Configurable
  doc/htconfig.md
  src/Worker/DBClean.php
Labels: Enhancement

#5261 And again the item abstraction - and a fix for issue 5252
  include/api.php
  include/conversation.php
  include/text.php
  mod/search.php
  mod/starred.php
  mod/tagger.php
  src/Model/Item.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Worker/Delivery.php
  src/Worker/Notifier.php
  src/Worker/OnePoll.php
  src/Worker/TagUpdate.php
Labels: Bug, Enhancement

#5267 Allow for Integer Literals in PDO Database Driver
  include/dba.php
Labels: Enhancement

#5271 Correct dba::close() To Match dba::p()
  include/dba.php
Labels: Bug

#5269 This fixes the problem with mixed variables in queries
  include/dba.php
Labels: Bug

#5273 update PL translations THX waldis
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#5272 Ensure IN() Conditions Never Mix Data Types
  include/dba.php
Labels: Enhancement

#5277 We now are using the native pdo mode
  include/dba.php
Labels: Bug

#4836 chmod 777 is a bad practice
  doc/Install.md
Labels: Docs

#5282 INSTALL.txt and doc/de/Install.md updates
  INSTALL.txt
  doc/de/Install.md
Labels: Docs, Installation

#5283 Installation better start with master and eventially switch to develop
  INSTALL.txt
  doc/Install.md
  doc/de/Install.md
Labels: Docs, Installation

#5284 The fetch function now centrally controls the content
  include/api.php
  include/conversation.php
  mod/acl.php
  mod/display.php
  mod/network.php
  mod/notes.php
  mod/ping.php
  mod/profile.php
  mod/search.php
  mod/starred.php
  src/Core/NotificationsManager.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Object/Post.php
Labels: Enhancement

#5287 CS translation update THX Aditoo
  view/lang/cs/messages.po
  view/lang/cs/strings.php
Labels: Translation

#5289 Item content is now stored outside the item table
  boot.php
  database.sql
  mod/community.php
  mod/item.php
  src/Database/DBStructure.php
  src/Model/Item.php
  src/Worker/Expire.php
Labels: Enhancement

#5167 a domain name is unlikely to be both a CNAME and A record
  src/Util/Network.php
Labels: Bug

#5303 regen credits
  util/credits.txt
Labels: Docs

#5302 The detected language now moved to "item-content" as well
  boot.php
  database.sql
  src/Database/DBStructure.php
  src/Model/Item.php
Labels: Enhancement

#5304 frio: new scheme Plusminus aims to minimize empty design spaces
  view/theme/frio/scheme/plusminus.css
  view/theme/frio/scheme/plusminus.jpg
  view/theme/frio/scheme/plusminus.php
Labels: New Feature, UI/Theme

#5307 added documentation of the groupedit_image_limit variable
  doc/htconfig.md
Labels: Docs

#5306 Label for the Events happening in the next 7 days was wrong
  src/Model/Profile.php
  util/messages.po
Labels: Enhancement

#5305 Tags aren't stored in the item table anymore
  database.sql
  include/enotify.php
  src/Database/DBStructure.php
  src/Model/Item.php
  src/Model/Term.php
Labels: Enhancement

#5308 Added support for internal Diaspora links to accounts
  src/Content/Text/BBCode.php
Labels: Enhancement, Federation
