Repository friendica/friendica, pull requests merged in 2018-04, with the labels that each got.

#4724 update for PL translation THX waldis
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Docs

#4731 pass uid to notification system so securemail addon can pick it up
  mod/lostpass.php
Labels: Addons, Enhancement

#4727 added TOS module
  mod/admin.php
  mod/friendica.php
  mod/register.php
  src/BaseModule.php
  src/Model/User.php
  src/Module/Tos.php
  util/messages.po
  view/templates/admin/tos.tpl
  view/templates/register.tpl
  view/templates/tos.tpl
Labels: Docs, New Feature

#4742 Avoid "Failed to parse time string (-001-11-30T00:00:00+00:00 + 32 days)"
  src/Util/DateTimeFormat.php
Labels: Bug

#4744 Queue: Better handling of return values of transmissions
  src/Worker/Delivery.php
  src/Worker/Queue.php
Labels: Enhancement

#4745 Fix: The register mail contained variables in a wrong order
  src/Model/User.php
Labels: Bug, UX

#4750 Revert "Added support of alt texts in images"
  src/Content/Text/BBCode.php
Labels: Bug

#4747 Bugfix: The rendering with images with width and height was broken
  src/Content/Text/BBCode.php
Labels: Bug

#4754 Improved accessibility for "Frio"
  include/conversation.php
  view/theme/frio/templates/comment_item.tpl
  view/theme/frio/templates/jot.tpl
  view/theme/frio/templates/nav.tpl
Labels: UI/Theme, UX

#4722 Add content_filter hook
  doc/Addons.md
  doc/de/Addons.md
  include/conversation.php
  include/text.php
  mod/settings.php
  src/Object/Post.php
  util/messages.po
  view/templates/settings/connectors.tpl
  view/theme/frio/templates/settings/connectors.tpl
Labels: Addons, New Feature

#4761 regenerated master messages.po file
  util/messages.po
Labels: Docs/Translation

#4762 Some more accessibility for "Frio"
  view/templates/hovercard.tpl
  view/theme/frio/templates/intros.tpl
Labels: Enhancement, UI/Theme, UX

#4766 [frio] Add color to group membership action buttons
  view/theme/frio/css/style.css
Labels: Enhancement, UI/Theme, UX

#4764 Use Sender: header for invite emails
  include/enotify.php
  mod/invite.php
  src/App.php
Labels: Bug

#4767 Update of the DE translations
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Docs/Translation

#4770 Fix: Empty answers in DFRN-Delivery can be okay
  src/Protocol/DFRN.php
Labels: Bug, Federation

#4771 Add profile_image_url_profile_size and profile_image_url_large to API
  include/api.php
Labels: API, Enhancement

#4777 Implement parts of the list API
  doc/api.md
  include/api.php
  src/Model/Group.php
Labels: API, New Feature

#4773 Move dev executables to bin/dev/
  Vagrantfile
  bin/dev/friendica-to-smarty-tpl.py
  bin/dev/make_credits.py
  bin/dev/minifyjs.sh
  bin/dev/updatetpl.py
  bin/dev/vagrant_provision.sh
  bin/dev/vagrant_vhost.sh
Labels: Enhancement

#4783 Don't queue relay posts
  boot.php
  src/Protocol/Diaspora.php
  src/Worker/Queue.php
Labels: Enhancement, Federation

#4785 The magic link is added at more places
  mod/dirfind.php
  src/Model/Profile.php
Labels: Enhancement, Federation

#4792 Improvement for the systemd timer unit
  mods/sample-systemd.timer
Labels: Enhancement, Installation

#4793 Throw a ForbiddenException if api_get_user() returns false
  include/api.php
Labels: Enhancement

#4794 Return types
  include/api.php
Labels: API, Enhancement

#4768 Hide posts from recently ignored/unfollowed contact
  mod/network.php
Labels: Enhancement, UX

#4795 Various small fixes
  include/api.php
Labels: API, Enhancement

#4797 Old database functions had been replaced in the workers
  src/Worker/Delivery.php
  src/Worker/DiscoverPoCo.php
  src/Worker/Notifier.php
  src/Worker/PubSubPublish.php
  src/Worker/Queue.php
  src/Worker/TagUpdate.php
Labels: Enhancement

#4796 Enable Travis
  .travis.yml
  phpunit.xml
  tests/BaseObjectTest.php
  tests/TextTest.php
  tests/autoname_test.php
  tests/contains_attribute_test.php
  tests/expand_acl_test.php
  tests/get_tags_test.php
  tests/template_test.php
  tests/xss_filter_test.php
Labels: Enhancement

#4799 Reintroduce own posts in network list
  mod/network.php
Labels: Bug

#4798 Prevent empty $uid from messing up the PreloadConfigAdapter
  src/Core/Config/PreloadPConfigAdapter.php
Labels: Bug

#4802 api_get_user() should not return false right away if the number in the URL is not a valid user
  include/api.php
Labels: API, Bug

#4811 translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/fi-fi/messages.po
  view/lang/fi-fi/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Docs/Translation

#4813 added example home css and html file
  mods/home.css
  mods/home.html
  mods/readme.txt
Labels: Docs/Translation

#4812 noreply should not be translate-able in email addresses
  src/App.php
  src/Worker/Delivery.php
Labels: Enhancement

#4817 Avoid sending relay posts to servers that already received content
  src/Protocol/Diaspora.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#4822 Issue-4816: Avoid SQL errors / Unarchive living relais servers
  src/Model/Contact.php
  src/Protocol/PortableContact.php
Labels: Enhancement, Federation

#4825 [BUGFIX] Domain Check: Remove DNS_PTR from check
  include/dba.php
  src/Util/Network.php
Labels: Enhancement

#4824 [BUGFIX] DB: Don't check DNS on IPs
  include/dba.php
Labels: Enhancement, Installation

#4837 Don't show multiple calls from the "dba" class
  src/Core/System.php
Labels: Enhancement

#4840 Update Making-Friends.md
  doc/Making-Friends.md
Labels: Docs/Translation

#4842 notify admin when user deletes account
  include/enotify.php
  mod/removeme.php
Labels: Enhancement

#4845 Forum posts now show the author when posted to Diaspora
  src/Protocol/Diaspora.php
Labels: Enhancement, Federation

#4848 display the thing
  view/templates/tos.tpl
Labels: Docs/Translation, Enhancement

#4850 new info mail address
  mod/friendica.php
Labels: Docs/Translation

#4782 Fix update password rehash
  src/Model/User.php
Labels: Bug

#4856 better support for the Diaspora app "Dandelion"
  index.php
Labels: Enhancement, Federation

#4864 Fix MemcachedCacheDrive::delete() method
  src/Core/Cache/MemcachedCacheDriver.php
  src/Core/Session/CacheSessionHandler.php
Labels: Bug

#4849 [FEATURE] Install Script: Add first version
  src/Core/Console.php
  src/Core/Console/AutomaticInstallation.php
Labels: Installation, New Feature

#4861 Frio: add template for admin/users
  view/theme/frio/css/mod_admin.css
  view/theme/frio/js/mod_admin.js
  view/theme/frio/templates/admin/users.tpl
Labels: Enhancement, UI/Theme

#4870 Add space before Impressum.
  mod/friendica.php
Labels: Enhancement, UI/Theme

#4863 Add hidden input in newpassword console
  composer.json
  composer.lock
  src/Core/Console/NewPassword.php
  src/Model/User.php
Labels: Enhancement

#4874 IT, FI and ZH_CN translation updates
  view/lang/fi-fi/messages.po
  view/lang/fi-fi/strings.php
  view/lang/it/messages.po
  view/lang/it/strings.php
  view/lang/zh-cn/messages.po
  view/lang/zh-cn/strings.php
Labels: Docs/Translation

#4875 regenerated master messages.po file
  util/messages.po
Labels: Docs/Translation

#4855 [TASK] Config: Add MySQL environment variables
  htconfig.php
  view/templates/htconfig.tpl
Labels: Enhancement, Installation

#4880 translation updates to DE, FI and PL
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/fi-fi/messages.po
  view/lang/fi-fi/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Docs/Translation

#4884 frio - fix image upload for prv messages
  view/theme/frio/css/style.css
  view/theme/frio/js/filebrowser.js
  view/theme/frio/js/modal.js
  view/theme/frio/js/theme.js
  view/theme/frio/templates/comment_item.tpl
  view/theme/frio/templates/event_form.tpl
  view/theme/frio/templates/prv_message.tpl
Labels: Bug, UX

#4883 Moved .htconfig.php file & extracted Install business logic
  INSTALL.txt
  bin/auth_ejabberd.php
  bin/daemon.php
  bin/dev/vagrant_provision.sh
  bin/worker.php
  config/htconfig.php
  doc/Install.md
  doc/Update.md
  doc/Vagrant.md
  doc/de/FAQ.md
  doc/de/Install.md
  include/dba.php
  index.php
  mod/install.php
  src/Core/Console/Config.php
  src/Core/Console/DatabaseStructure.php
  src/Core/Console/GlobalCommunityBlock.php
  src/Core/Console/GlobalCommunitySilence.php
  src/Core/Console/Maintenance.php
  src/Core/Console/NewPassword.php
  src/Core/Install.php
  util/Doxyfile
Labels: Enhancement, Installation

#4885 frio - fix default template if friendica is installed into a subdirectory
  view/theme/frio/php/default.php
Labels: Bug, UI/Theme

#4892 Prevent infinite loop when a dbstructure_definition hook is orphan
  include/dba.php
  src/Core/Addon.php
Labels: Bug

#4901 check more PHP version
  .travis.yml
Labels: Enhancement

#4900 Preparation for transmitting public posts via DFRN
  mod/dfrn_notify.php
  src/Protocol/DFRN.php
Labels: Enhancement, Federation

#4904 [DOCS] Automatic install: Add documentation
  doc/Install.md
  doc/de/Install.md
Labels: Docs/Translation

#4905 Add one-line content filter when there's only one reason
  include/text.php
Labels: Enhancement, UX

#4906 Move content filter HTML in a template
  include/text.php
  view/templates/wall/content_filter.tpl
Labels: Enhancement

#4907 Frio - rework admin users and admin contactblock template to be more consistant with other setting pages
  view/theme/frio/css/mod_admin.css
  view/theme/frio/css/style.css
  view/theme/frio/js/mod_admin.js
  view/theme/frio/templates/admin/contactblock.tpl
  view/theme/frio/templates/admin/users.tpl
Labels: Enhancement, UI/Theme, UX

#4881 Guess language from plaintext
  mod/babel.php
  src/Content/Text/BBCode.php
  src/Model/Item.php
  src/Model/ItemContent.php
Labels: Enhancement

#4909 Fix PHP 7.2 warnings
  include/dba.php
  mod/friendica.php
  src/Model/Profile.php
  src/Object/Post.php
  src/Util/Temporal.php
Labels: Bug, PHP7

#4910 translation updates DE and FI
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/fi-fi/messages.po
  view/lang/fi-fi/strings.php
Labels: Docs/Translation

#4913 phpunit compat 5.6 vs 7.x
  tests/BaseObjectTest.php
  tests/TextTest.php
Labels: Bug

#4924 Item distribution is now done via the public post
  boot.php
  mod/admin.php
  mod/community.php
  mod/dfrn_notify.php
  src/Content/Nav.php
  src/Model/Item.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
Labels: Enhancement, Federation

#4925 frio - provide a template for invite page
  mod/invite.php
  view/templates/invite.tpl
  view/theme/frio/css/style.css
  view/theme/frio/js/modal.js
  view/theme/frio/templates/invite.tpl
  view/theme/frio/templates/peoplefind.tpl
  view/theme/vier/style.css
Labels: Enhancement, UI/Theme

#4915 [DOCS] Docs: Minor improvements
  doc/Account-Basics.md
  doc/Addons.md
  doc/Chats.md
  doc/Improve-Performance.md
  doc/Installing-Connectors.md
  doc/Making-Friends.md
  doc/de/Addons.md
  doc/de/Chats.md
  doc/de/Improve-Performance.md
Labels: Docs/Translation

#4931 Don't distribute for ignored contacts
  src/Model/Item.php
Labels: Bug, Federation

#4933 Bugfix: The Distribition of public items failed with comments
  src/Model/Item.php
Labels: Bug, Federation

#4934 Item distribution: Better don't store these values
  src/Model/Item.php
Labels: Enhancement

#4935 Reworked delivery worker
  src/Model/Item.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Worker/Delivery.php
  src/Worker/PubSubPublish.php
Labels: Enhancement

#4936 Diaspora reshares should now always reshare the correct content
  src/Protocol/Diaspora.php
Labels: Enhancement, Federation

#4890 Reorganize Login to Fix #4878
  view/templates/field_checkbox.tpl
  view/templates/field_combobox.tpl
  view/templates/field_custom.tpl
  view/templates/field_input.tpl
  view/templates/field_intcheckbox.tpl
  view/templates/field_openid.tpl
  view/templates/field_password.tpl
  view/templates/field_radio.tpl
  view/templates/field_richtext.tpl
  view/templates/field_select.tpl
  view/templates/field_select_raw.tpl
  view/templates/field_textarea.tpl
  view/templates/field_themeselect.tpl
  view/templates/field_yesno.tpl
  view/templates/login.tpl
  view/theme/frio/css/style.css
  view/theme/frio/templates/field_checkbox.tpl
  view/theme/frio/templates/field_colorinput.tpl
  view/theme/frio/templates/field_custom.tpl
  view/theme/frio/templates/field_fileinput.tpl
  view/theme/frio/templates/field_input.tpl
  view/theme/frio/templates/field_intcheckbox.tpl
  view/theme/frio/templates/field_openid.tpl
  view/theme/frio/templates/field_password.tpl
  view/theme/frio/templates/field_radio.tpl
  view/theme/frio/templates/field_select.tpl
  view/theme/frio/templates/field_select_raw.tpl
  view/theme/frio/templates/field_textarea.tpl
  view/theme/frio/templates/field_themeselect.tpl
  view/theme/frio/templates/field_yesno.tpl
  view/theme/frio/templates/login.tpl
  view/theme/vier/mobile.css
  view/theme/vier/style.css
Labels: Enhancement, UI/Theme

#4937 Install selected theme during settings persistence.
  mod/admin.php
  mod/settings.php
Labels: Bug

#4940 frio: Fix login page layout without OpenId.
  view/theme/frio/css/style.css
  view/theme/frio/templates/login.tpl
Labels: Bug, UI/Theme

#4939 Better curl error during install.
  .gitignore
  mod/install.php
  src/Util/Network.php
  view/install/style.css
  view/templates/install_checks.tpl
Labels: Enhancement, Installation

#4941 Update directory URL protocol
  boot.php
  util/htconfig.vagrant.php
  view/templates/htconfig.tpl
Labels: Bug, Docs/Translation

#4942 Import posts from ignored contacts
  include/conversation.php
  src/Model/Item.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Worker/OnePoll.php
Labels: Enhancement

#4948 Corrected query to don't show hash tag posts from blocked or ignored contacts
  mod/network.php
Labels: Bug

#4952 Fix own post check for content filter
  include/text.php
Labels: Bug

#4953 regenerated master messages.po file
  util/messages.po
Labels: Docs/Translation

#4951 Move current_theme() to App
  boot.php
  include/text.php
  index.php
  src/App.php
  src/Core/Addon.php
  src/Core/Theme.php
  src/Model/Profile.php
  src/Render/FriendicaSmarty.php
  src/Render/FriendicaSmartyEngine.php
  view/theme/frio/php/frio_boot.php
  view/theme/frio/php/scheme.php
Labels: Bug, UX

#4920 Add Application Mode (Install, Maintenance, Normal)
  include/dba.php
  include/text.php
  index.php
  mod/install.php
  src/App.php
  src/Core/Console/AutomaticInstallation.php
  src/Core/Install.php
Labels: Enhancement, Installation

#4955 update FI translations THX Kris
  view/lang/fi-fi/messages.po
  view/lang/fi-fi/strings.php
Labels: Docs/Translation

#4959 Added dark scheme to frio
  view/theme/frio/scheme/koyu-dark.css
  view/theme/frio/scheme/koyu-dark.php
Labels: New Feature, UI/Theme

#4961 Direct Relay is now working with DFRN as well
  mod/_well_known.php
  mod/dfrn_notify.php
  src/Network/Probe.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/PortableContact.php
  src/Worker/Delivery.php
Labels: Enhancement, Federation
