Repository friendica/friendica, pull requests merged in 2019-11, with the labels that each got.

#7793 Fix/FollowUp ACLFormatter
  mod/lockview.php
  src/Model/Item.php
  src/Module/Item/Compose.php
  src/Util/ACLFormatter.php
  src/Worker/Notifier.php
  tests/src/Util/ACLFormaterTest.php
Labels: Bug

#7785 Fix wrong check for logfile in admin summary
  src/Module/Admin/Summary.php
Labels: Bug

#7794 Added usort() to the saved folders widget
  src/Content/Widget.php
Labels: Enhancement

#7726 move uexport module to src
  mod/settings.php
  mod/uexport.php
  src/Module/BaseSettingsModule.php
  src/Module/Settings/UserExport.php
  src/Module/Tos.php
  static/routes.config.php
Labels: Enhancement

#7797 Posted order is now arrival order
  mod/network.php
Labels: Enhancement, UX

#7800 AP: Respect "manually approve" during contact request
  src/Model/Contact.php
Labels: Enhancement, Federation

#7749 [frio] Rework hovercard actions
  mod/hovercard.php
  src/Model/Contact.php
  src/Module/Contact/Hovercard.php
  static/routes.config.php
  view/templates/hovercard.tpl
  view/theme/frio/css/style.css
  view/theme/frio/frameworks/jsmart/jsmart.custom.js
  view/theme/frio/frameworks/jsmart/jsmart.js
  view/theme/frio/frameworks/jsmart/jsmart.min.js
  view/theme/frio/js/hovercard.js
  view/theme/frio/templates/event_stream_item.tpl
  view/theme/frio/templates/head.tpl
  view/theme/frio/templates/nav.tpl
  view/theme/frio/templates/notify.tpl
  view/theme/frio/templates/photo_item.tpl
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: Bug, Enhancement, UI/Theme, UX

#7798 Rework photo functions
  include/api.php
  mod/fbrowser.php
  mod/photos.php
  mod/wall_upload.php
  src/App/Arguments.php
  src/Content/Text/BBCode.php
  src/Core/Installer.php
  src/Model/Contact.php
  src/Model/Photo.php
  src/Model/User.php
  src/Object/Image.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/OStatus.php
  src/Util/Images.php
  src/Util/ParseUrl.php
  tests/src/Core/InstallerTest.php
Labels: Enhancement

#7810 Diaspora: Use the standard function for adding a relationship
  src/Protocol/Diaspora.php
Labels: Berlin 2019, Enhancement, Federation

#7809 Plusminus Scheme for Frio improved contacts and visibility
  view/theme/frio/scheme/plusminus.css
  view/theme/frio/templates/widget/follow.tpl
Labels: Enhancement, UI, UI/Theme

#7811 categories of postings linked
  src/Content/Item.php
  view/templates/wall_thread.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/smoothly/templates/wall_thread.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: Berlin 2019, Enhancement

#7813 move link generation into the loop
  src/Content/Item.php
Labels: Berlin 2019, Bug

#7806 added export and import of followed contacts to and from CSV files
  doc/Export-Import-Contacts.md
  doc/Home.md
  doc/de/Export-Import-Contacts.md
  doc/de/Home.md
  mod/settings.php
  src/Module/Settings/UserExport.php
  static/settings.config.php
  view/templates/settings/settings.tpl
  view/theme/frio/templates/settings/settings.tpl
Labels: Berlin 2019

#7814 Add missing quotation
  mod/settings.php
Labels: Berlin 2019, Bug

#7815 add missing template for userexport
  view/templates/settings/userexport.tpl
  view/theme/frio/templates/settings/userexport.tpl
Labels: Berlin 2019, Bug, UI/Theme

#7816 regen messages.po after Hackathon 2019
  view/lang/C/messages.po
Labels: Berlin 2019, Translation

#7812 a hidden field for the registration form
  src/Module/Register.php
  view/templates/register.tpl
  view/theme/frio/templates/register.tpl
Labels: Berlin 2019, Enhancement

#7818 Pass the parameters from the router to the modules
  src/App/Module.php
  src/App/Router.php
  tests/src/App/ModeTest.php
Labels: Enhancement

#7820 Fix a notice
  src/Protocol/Diaspora.php
Labels: Bug

#7822 Pass Router parameters to module content method
  src/App/Module.php
  src/App/Page.php
  src/App/Router.php
  static/dependencies.config.php
  tests/src/App/ModuleTest.php
  tests/src/App/RouterTest.php
Labels: Enhancement

#7823 We can now pin posts
  database.sql
  include/conversation.php
  src/Model/Item.php
  src/Module/Profile.php
  src/Object/Post.php
  static/dbstructure.config.php
  static/routes.config.php
  view/js/main.js
  view/templates/wall_thread.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/smoothly/templates/wall_thread.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: Berlin 2019, New Feature

#7826 Pinning: Missing file added
  src/Module/Pinned.php
Labels: New Feature

#7827 User account page flags is stored as 255
  mod/settings.php
Labels: Bug

#7828 Remove unnecessary code in "include/enotify"
  database.sql
  include/enotify.php
  static/dbstructure.config.php
Labels: Enhancement

#7829 Fix image links with descriptions in API and AP transmission
  include/api.php
  src/Model/Photo.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#7831 ActivityPub: Use the contentMap to transmit additional content encodings
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#7832 Fix: Mentions in the HTML part of the "contentMap" now are links
  src/Content/Text/BBCode.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#7833 AP: Read different content types for the source and the content
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement, Federation

#7839 Don't guess the site info / restrict the description length
  src/Util/ParseUrl.php
Labels: Enhancement, Federation

#7841 AP: Remove the link description from the "rich html" and adds it to the attachment
  src/Content/Text/BBCode.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#7842 Fix fatal errors, caused by an empty "verb"
  include/conversation.php
Labels: Bug

#7843 Improve the look of fetched feeds and the BBCode processing of attachments
  src/Content/Text/BBCode.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Feed.php
Labels: Enhancement, Federation

#7844 Fix warnings
  src/Model/GServer.php
  src/Protocol/Feed.php
Labels: Bug

#7845 Show title for posts with attached pages
  src/Protocol/Diaspora.php
Labels: Enhancement, Federation

#7846 Fix further notes and warnings
  src/Model/GServer.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#7847 Make the automatic title appending optional
  mod/settings.php
  src/Protocol/Diaspora.php
  view/templates/settings/connectors.tpl
  view/theme/frio/templates/settings/connectors.tpl
Labels: Enhancement, Federation

#7848 Added hooks for the email fetch process
  doc/Addons.md
  doc/de/Addons.md
  src/Protocol/Email.php
Labels: Addons, Enhancement

#7851 Storing the mail header in the item
  src/Model/Item.php
  src/Worker/OnePoll.php
Labels: Enhancement, Federation

#7853 Fix some notices/warnings again
  include/api.php
  src/Protocol/Diaspora.php
Labels: Bug

#7854 Fix mail delivery via AP when the contact is hidden
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#7856 Update to version 1.9.1
  bin/composer.phar
Labels: Enhancement, Installation

#7858 Don't use the creation date when transmitting to Diaspora
  src/Module/Diaspora/Fetch.php
  src/Protocol/Diaspora.php
Labels: Enhancement, Federation

#7861 E-Mail import: The item is now provided to the hook
  src/Protocol/Email.php
  src/Worker/OnePoll.php
Labels: Enhancement, Federation

#7862 Only read undeleted mails / improved structure
  src/Protocol/Email.php
Labels: Enhancement

#7865 Add "discourse" as protocol
  src/Content/ContactSelector.php
  src/Content/Widget.php
  src/Core/Protocol.php
Labels: Addons, New Feature

#7867 Notice/warning in event fixed
  src/Model/Event.php
Labels: Bug

#7871 Fix a notice in gcontact.php
  src/Model/GContact.php
Labels: Bug

#7872 Don't allow unencrypted IMAP, allow deleting mails
  mod/settings.php
  static/defaults.config.php
Labels: Enhancement, Federation

#7875 Attached photos from pixelfed are now added to the body again
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation

#7874 Only transfer posts via mail
  src/Worker/Delivery.php
Labels: Enhancement, Federation

#7873 nodeinfo version 2 / basic nodeinfo data is always enabled
  src/Module/NodeInfo.php
  src/Module/WellKnown/NodeInfo.php
  static/routes.config.php
Labels: Enhancement, Federation

#7876 Generalize the Compose ACL to the whole site
  bin/dev/minifyjs.sh
  mod/community.php
  mod/display.php
  mod/events.php
  mod/network.php
  mod/photos.php
  mod/settings.php
  src/App/Page.php
  src/Core/ACL.php
  src/Core/Theme.php
  src/Module/Bookmarklet.php
  src/Module/Contact.php
  src/Module/Item/Compose.php
  src/Module/Profile.php
  view/js/acl.js
  view/js/friendica-tagsinput/LICENSE
  view/js/friendica-tagsinput/friendica-tagsinput-typeahead.css
  view/js/friendica-tagsinput/friendica-tagsinput.css
  view/js/friendica-tagsinput/friendica-tagsinput.js
  view/js/linkPreview.js
  view/js/main.js
  view/templates/acl_selector.tpl
  view/templates/head.tpl
  view/templates/item/compose-footer.tpl
  view/templates/item/compose.tpl
  view/theme/frio/frameworks/friendica-tagsinput/friendica-tagsinput.css
  view/theme/frio/js/compose.js
  view/theme/frio/js/event_edit.js
  view/theme/frio/js/modal.js
  view/theme/frio/php/standard.php
  view/theme/frio/templates/acl_selector.tpl
  view/theme/frio/templates/event_form.tpl
  view/theme/frio/templates/head.tpl
  view/theme/smoothly/templates/jot.tpl
Labels: Enhancement

#7877 Show the received date along with the creation date of posts
  src/Object/Post.php
  static/defaults.config.php
Labels: Enhancement

#7879 Fix ACL-related warnings
  src/App/Page.php
  src/Core/ACL.php
Labels: Bug

#7883 Various ACL/jot fixes
  src/Core/ACL.php
  view/templates/acl_selector.tpl
  view/theme/duepuntozero/deriv/darkzero.css
  view/theme/duepuntozero/style.css
  view/theme/frio/css/style.css
  view/theme/frio/js/modal.js
  view/theme/frio/templates/filebrowser.tpl
  view/theme/frio/templates/jot.tpl
  view/theme/quattro/dark/style.css
  view/theme/quattro/green/style.css
  view/theme/quattro/lilac/style.css
  view/theme/quattro/quattro.less
  view/theme/smoothly/style.css
  view/theme/vier/dark.css
  view/theme/vier/mobile.css
  view/theme/vier/style.css
Labels: Bug, UI/Theme, UX
