Repository friendica/friendica, pull requests merged in 2019-08, with the labels that each got.

#7381 [frio] New Compose page
  composer.json
  composer.lock
  include/text.php
  mod/lockview.php
  mod/network.php
  src/App/Router.php
  src/Core/Protocol.php
  src/Model/Group.php
  src/Model/Item.php
  src/Module/Item/Compose.php
  src/Worker/Notifier.php
  tests/include/TextTest.php
  view/js/main.js
  view/templates/comment_item.tpl
  view/templates/item/compose-footer.tpl
  view/templates/item/compose.tpl
  view/templates/moderated_comment.tpl
  view/theme/duepuntozero/templates/comment_item.tpl
  view/theme/duepuntozero/templates/moderated_comment.tpl
  view/theme/frio/config.php
  view/theme/frio/css/style.css
  view/theme/frio/frameworks/friendica-tagsinput/LICENSE
  view/theme/frio/frameworks/friendica-tagsinput/friendica-tagsinput-typeahead.css
  view/theme/frio/frameworks/friendica-tagsinput/friendica-tagsinput.css
  view/theme/frio/frameworks/friendica-tagsinput/friendica-tagsinput.js
  view/theme/frio/js/theme.js
  view/theme/frio/templates/comment_item.tpl
  view/theme/frio/templates/jot.tpl
  view/theme/frio/templates/theme_settings.tpl
  view/theme/frio/theme.php
  view/theme/quattro/templates/comment_item.tpl
  view/theme/vier/templates/comment_item.tpl
Labels: New Feature, UI/Theme, UX

#7460 Improved PR 7452: We now respect the "self" contact
  src/Model/Item.php
Labels: Enhancement

#7459 Fix a notice when setting a picture description via API
  include/api.php
Labels: Bug

#7462 The "contact-uid" is now a reliable proof for contacts that we follow
  include/conversation.php
Labels: Enhancement, Performance

#7461 Moved several database stuff out of the transaction to avoid error 1205
  src/Model/Item.php
Labels: Enhancement, Performance

#7466 API: We now transmit the text description there as well
  include/api.php
  mod/photos.php
  src/Content/Text/BBCode.php
  src/Model/Photo.php
  src/Module/Photo.php
Labels: Bug, Federation

#7463 Respecting the "alt" description of images during import from HTML
  src/Content/Text/HTML.php
Labels: Enhancement

#7476 [frio] remove basepath form field from admin panel site page
  view/theme/frio/templates/admin/site.tpl
Labels: Bug, UI/Theme

#7478 Typo in setting description
  mod/settings.php
Labels: Bug, Docs

#7477 DE, PL translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#7479 Support for image descriptions and multiple image posts to external services
  src/Content/Text/BBCode.php
  src/Model/Photo.php
Labels: Enhancement

#7480 Revert using LIBXML_NOBLANKS
  src/Content/Text/HTML.php
Labels: Bug

#7465 Refactor Cache/Lock to DICE
  bin/auth_ejabberd.php
  bin/console.php
  bin/daemon.php
  bin/worker.php
  index.php
  src/Console/Cache.php
  src/Core/Cache.php
  src/Core/Cache/APCuCache.php
  src/Core/Cache/ArrayCache.php
  src/Core/Cache/Cache.php
  src/Core/Cache/DatabaseCache.php
  src/Core/Cache/ICache.php
  src/Core/Cache/IMemoryCache.php
  src/Core/Cache/MemcacheCache.php
  src/Core/Cache/MemcachedCache.php
  src/Core/Cache/ProfilerCache.php
  src/Core/Cache/RedisCache.php
  src/Core/Cache/TraitCompareDelete.php
  src/Core/Cache/TraitCompareSet.php
  src/Core/Lock.php
  src/Core/Lock/CacheLock.php
  src/Core/Lock/DatabaseLock.php
  src/Core/Lock/ILock.php
  src/Core/Lock/Lock.php
  src/Core/Lock/SemaphoreLock.php
  src/Core/System.php
  src/Factory/CacheDriverFactory.php
  src/Factory/CacheFactory.php
  src/Factory/LockFactory.php
  static/dependencies.config.php
  tests/DatabaseTest.php
  tests/DatabaseTestTrait.php
  tests/Util/DbaCacheMockTrait.php
  tests/Util/DbaLockMockTrait.php
  tests/Util/VFSTrait.php
  tests/functional/DependencyCheckTest.php
  tests/include/ApiTest.php
  tests/src/Content/Text/BBCodeTest.php
  tests/src/Core/Cache/APCuCacheTest.php
  tests/src/Core/Cache/ArrayCacheTest.php
  tests/src/Core/Cache/CacheTest.php
  tests/src/Core/Cache/DatabaseCacheDriverTest.php
  tests/src/Core/Cache/DatabaseCacheTest.php
  tests/src/Core/Cache/MemcacheCacheTest.php
  tests/src/Core/Cache/MemcachedCacheTest.php
  tests/src/Core/Cache/MemoryCacheTest.php
  tests/src/Core/Cache/RedisCacheTest.php
  tests/src/Core/Lock/APCuCacheLockTest.php
  tests/src/Core/Lock/ArrayCacheLockTest.php
  tests/src/Core/Lock/DatabaseLockDriverTest.php
  tests/src/Core/Lock/DatabaseLockTest.php
  tests/src/Core/Lock/LockTest.php
  tests/src/Core/Lock/MemcacheCacheLockTest.php
  tests/src/Core/Lock/MemcachedCacheLockDriverTest.php
  tests/src/Core/Lock/MemcachedCacheLockTest.php
  tests/src/Core/Lock/RedisCacheLockTest.php
  tests/src/Core/Lock/SemaphoreLockDriverTest.php
  tests/src/Core/Lock/SemaphoreLockTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
Labels: Enhancement, Performance

#7481 Add trending tags widget to community page
  mod/community.php
  src/Content/Feature.php
  src/Content/Widget/TrendingTags.php
  src/Model/Term.php
  src/Module/Item/Compose.php
  view/lang/C/messages.po
  view/templates/widget/trending_tags.tpl
Labels: New Feature

#7483 Fix bug removing spaces between hashtag links in HTML::toPlaintext
  src/Content/Text/HTML.php
  tests/datasets/content/text/html/bug-7474.html
  tests/datasets/content/text/html/bug-7474.txt
Labels: Bug

#7484 regen messages.po
  view/lang/C/messages.po
Labels: Translation

#7489 Ensure trimmed HTML nodes are text nodes in HTML::toBBCode
  src/Content/Text/HTML.php
  src/Module/Debug/Babel.php
  tests/datasets/content/text/html/bug-7488.html
  tests/datasets/content/text/html/bug-7488.txt
Labels: Bug

#7487 Fix trending tags variable name mistakes in Model\Term
  src/Model/Term.php
  view/templates/widget/trending_tags.tpl
Labels: Bug

#7490 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#7492 DE,FR,NL translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/nl/messages.po
  view/lang/nl/strings.php
Labels: Translation

#7493 Don't fork worker on frontend by default
  mod/item.php
  src/Core/Worker.php
Labels: Performance

#7500 Introduce Arguments / Module class
  index.php
  src/App.php
  src/App/Arguments.php
  src/App/Mode.php
  src/App/Module.php
  src/Core/Installer.php
  src/Model/Profile.php
  src/Module/Install.php
  static/dependencies.config.php
  tests/src/App/ArgumentsTest.php
  tests/src/App/ModeTest.php
  tests/src/App/ModuleTest.php
Labels: Enhancement

#7503 Use contact.network field instead of contact.protocol in Group::expand
  src/Model/Group.php
Labels: Bug, Federation

#7499 Worker: The retrial value can now skip retrial levels
  src/Core/Worker.php
  static/defaults.config.php
Labels: Enhancement, Performance

#7504 Revert "Introduce Arguments / Module class"
  index.php
  src/App.php
  src/App/Arguments.php
  src/App/Mode.php
  src/App/Module.php
  src/Core/Installer.php
  src/Model/Profile.php
  src/Module/Install.php
  static/dependencies.config.php
  tests/src/App/ArgumentsTest.php
  tests/src/App/ModeTest.php
  tests/src/App/ModuleTest.php
Labels: Bug

#7505 Queue numbers corrected, only display 999 queue items
  src/Module/Admin/Queue.php
  src/Module/Admin/Summary.php
Labels: Bug

#7509 Improved calculation of deferred tasks
  src/Core/Worker.php
Labels: Enhancement

#7510 Fix Redis test
  src/Core/Cache/RedisCache.php
Labels: Bug

#7511 Fixed typo
  doc/Install.md
Labels: Bug, Docs

#7512 Use the contact id whenever we are following the contact
  src/Model/Item.php
Labels: Bug, Federation

#7508 Add Arguments & Module class (again)
  index.php
  src/App.php
  src/App/Arguments.php
  src/App/Mode.php
  src/App/Module.php
  src/Core/Installer.php
  src/Model/Profile.php
  src/Module/Install.php
  static/dependencies.config.php
  tests/src/App/ArgumentsTest.php
  tests/src/App/ModeTest.php
  tests/src/App/ModuleTest.php
Labels: Enhancement

#7516 Move isBackend logic to App\Mode
  src/App.php
  src/App/Mode.php
  static/dependencies.config.php
  tests/src/App/ModeTest.php
Labels: Enhancement

#7515 New Console Command: Lock
  src/Console/Lock.php
  src/Core/Cache/ArrayCache.php
  src/Core/Cache/Cache.php
  src/Core/Cache/MemcachedCache.php
  src/Core/Console.php
  src/Core/Lock/CacheLock.php
  src/Core/Lock/DatabaseLock.php
  src/Core/Lock/ILock.php
  src/Core/Lock/Lock.php
  src/Core/Lock/SemaphoreLock.php
  tests/src/Console/LockConsoleTest.php
  tests/src/Core/Cache/CacheTest.php
  tests/src/Core/Lock/LockTest.php
  tests/src/Core/Lock/SemaphoreLockTest.php
Labels: Bug, New Feature

#7517 Prepare App for further usage
  src/App.php
  src/App/BaseURL.php
  src/Console/AutomaticInstallation.php
  src/Core/Authentication.php
  src/Core/Session.php
  src/Core/System.php
  src/Factory/CacheFactory.php
  src/Model/Contact.php
  src/Module/Admin/Site.php
  src/Module/Install.php
  src/Protocol/DFRN.php
  static/dependencies.config.php
  tests/src/Console/AutomaticInstallationConsoleTest.php
  tests/src/Content/Text/BBCodeTest.php
  tests/src/Util/BaseURLTest.php
Labels: Bug, Enhancement

#7518 Fix Lock-Unlink
  src/Core/Lock/SemaphoreLock.php
Labels: Bug

#7514 Allow protocol-less links
  src/Content/Text/BBCode.php
  static/defaults.config.php
Labels: Enhancement, Security

#7519 Add Page class (Frontend code)
  src/App.php
  src/App/Page.php
  static/dependencies.config.php
Labels: Enhancement

#7520 Suppress relationship string in template vars for public contact
  src/Module/Contact.php
Labels: Bug, UX

#7523 Prevents linkPreview to match on URLs lead by an equal sign
  view/js/linkPreview.js
Labels: Bug, UX

#7521 Add Process class / move run-settings to App\Mode
  src/App.php
  src/App/Mode.php
  src/App/Page.php
  src/Core/Process.php
  src/Core/Worker.php
  static/dependencies.config.php
  tests/src/App/ModeTest.php
Labels: Enhancement

#7525 replacing slideshare icon with paper plane
  view/theme/frio/templates/jot.tpl
Labels: Enhancement, UI/Theme

#7529 replace paper plane for finished transfers
  view/theme/frio/templates/sub/delivery_count.tpl
Labels: Enhancement, UI/Theme, UX

#7530 Fix Admin Theme reload
  src/Module/Admin/Themes/Index.php
Labels: Bug

#7528 Fix Locks
  src/Core/Lock/DatabaseLock.php
  src/Core/Lock/SemaphoreLock.php
  src/Factory/LockFactory.php
  tests/src/Core/Lock/LockTest.php
  tests/src/Core/Lock/SemaphoreLockTest.php
Labels: Bug

#7532 Fix GContact warning
  src/Model/GContact.php
Labels: Bug

#7533 Fixing wrong defaults() usage
  src/Module/Admin/Item/Source.php
Labels: Bug

#7524 Prune unavailable contacts from AP envelope
  src/Model/Item.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#7534 Add entry title HTML entities conversion in Protocol\Feed
  src/Protocol/Feed.php
Labels: Bug

#7535 Add missing use statement in Search\Directory
  src/Module/Search/Directory.php
Labels: Bug

#7537 fix vier mobile display
  view/theme/vier/mobile.css
Labels: Bug, UI/Theme

#7538 move notification to top nav on mobile view
  view/theme/frio/templates/nav.tpl
Labels: Enhancement, Mobile, UI/Theme, UX

#7539 switched exclamation mark to bell
  view/theme/frio/templates/nav.tpl
Labels: Enhancement, UI/Theme, UX

#7540 Update SSL.md
  doc/SSL.md
Labels: Bug, Docs

#7541 Update Install.md
  doc/Install.md
Labels: Bug, Docs

#7543 Delivery count now counts the failed delivery attempts as well
  database.sql
  src/Core/Worker.php
  src/Model/Item.php
  src/Model/ItemDeliveryData.php
  src/Object/Post.php
  src/Worker/APDelivery.php
  src/Worker/Delivery.php
  static/dbstructure.config.php
Labels: Enhancement, UX

#7544 Profile vcard translation
  src/Model/Profile.php
Labels: Translation

#7547 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#7546 Fix table structure definition
  database.sql
  static/dbstructure.config.php
Labels: Bug, Installation

#7549 adapt usage of admin user icon to match every other occurrence
  view/theme/frio/templates/admin/users.tpl
Labels: Enhancement, UX

#7550 Replace mb_convert_encoding with html_entity_decode for feed item title conversion
  src/Protocol/Feed.php
Labels: Bug

#7551 Replaced FontAwesome by ForkAwesome
  composer.json
  composer.lock
  view/theme/frio/css/font-awesome.custom.css
  view/theme/frio/css/style.css
  view/theme/frio/frameworks/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css
  view/theme/frio/frameworks/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.less
  view/theme/frio/frameworks/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.scss
  view/theme/frio/frameworks/font-awesome/HELP-US-OUT.txt
  view/theme/frio/frameworks/font-awesome/css/font-awesome.css
  view/theme/frio/frameworks/font-awesome/css/font-awesome.min.css
  view/theme/frio/frameworks/font-awesome/fonts/FontAwesome.otf
  view/theme/frio/frameworks/font-awesome/fonts/fontawesome-webfont.eot
  view/theme/frio/frameworks/font-awesome/fonts/fontawesome-webfont.svg
  view/theme/frio/frameworks/font-awesome/fonts/fontawesome-webfont.ttf
  view/theme/frio/frameworks/font-awesome/fonts/fontawesome-webfont.woff
  view/theme/frio/frameworks/font-awesome/fonts/fontawesome-webfont.woff2
  view/theme/frio/frameworks/font-awesome/less/animated.less
  view/theme/frio/frameworks/font-awesome/less/bordered-pulled.less
  view/theme/frio/frameworks/font-awesome/less/core.less
  view/theme/frio/frameworks/font-awesome/less/fixed-width.less
  view/theme/frio/frameworks/font-awesome/less/font-awesome.less
  view/theme/frio/frameworks/font-awesome/less/icons.less
  view/theme/frio/frameworks/font-awesome/less/larger.less
  view/theme/frio/frameworks/font-awesome/less/list.less
  view/theme/frio/frameworks/font-awesome/less/mixins.less
  view/theme/frio/frameworks/font-awesome/less/path.less
  view/theme/frio/frameworks/font-awesome/less/rotated-flipped.less
  view/theme/frio/frameworks/font-awesome/less/stacked.less
  view/theme/frio/frameworks/font-awesome/less/variables.less
  view/theme/frio/frameworks/font-awesome/scss/_animated.scss
  view/theme/frio/frameworks/font-awesome/scss/_bordered-pulled.scss
  view/theme/frio/frameworks/font-awesome/scss/_core.scss
  view/theme/frio/frameworks/font-awesome/scss/_fixed-width.scss
  view/theme/frio/frameworks/font-awesome/scss/_icons.scss
  view/theme/frio/frameworks/font-awesome/scss/_larger.scss
  view/theme/frio/frameworks/font-awesome/scss/_list.scss
  view/theme/frio/frameworks/font-awesome/scss/_mixins.scss
  view/theme/frio/frameworks/font-awesome/scss/_path.scss
  view/theme/frio/frameworks/font-awesome/scss/_rotated-flipped.scss
  view/theme/frio/frameworks/font-awesome/scss/_stacked.scss
  view/theme/frio/frameworks/font-awesome/scss/_variables.scss
  view/theme/frio/frameworks/font-awesome/scss/font-awesome.scss
  view/theme/frio/templates/head.tpl
Labels: Enhancement, UI/Theme

#7554 Output better comparable log entries for the worker
  src/Core/Worker.php
Labels: Enhancement

#7553 Prevent a fatal error for an empty parameter in "unparseURL"
  src/Content/Text/HTML.php
Labels: Bug

#7561 Remove contacts auto completion
  view/js/autocomplete.js
  view/theme/frio/js/mod_contacts.js
  view/theme/frio/js/modal.js
  view/theme/frio/js/theme.js
Labels: Bug, UI/Theme, UX

#7565 Prevents Enter from submitting forms in ACL fields
  view/js/acl.js
  view/templates/acl_selector.tpl
  view/templates/item/compose-footer.tpl
  view/theme/frio/frameworks/friendica-tagsinput/friendica-tagsinput.js
  view/theme/frio/templates/acl_selector.tpl
Labels: Enhancement, UX

#7569 adding desaturation and transition for forumlist widget
  view/theme/frio/css/style.css
Labels: Enhancement, UI/Theme, UX

#7573 Updated CHANGELOG with missing closed issues from 2019.06
  CHANGELOG
  src/Protocol/DFRN.php
Labels: Docs

#7583 CS and JA translation updates
  CHANGELOG
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/ja/messages.po
  view/lang/ja/strings.php
Labels: Translation

#7570 Some code hardenings for semaphore locking
  src/Core/Lock/SemaphoreLock.php
Labels: Bug

#7587 Remove unevenly supported lookbehind from link preview regular expression
  view/js/linkPreview.js
Labels: Bug, UX

#7582 Avoid and remove duplicated contact entries
  src/Database/PostUpdate.php
  src/Model/Contact.php
  src/Protocol/Diaspora.php
Labels: Bug

#7588 Follow up to #7582: Only update the contact when needed
  src/Model/Contact.php
Labels: Enhancement
