Repository friendica/friendica, pull requests merged in 2019-04, with the labels that each got.

#6956 Sanitize theme/addon path items
  mod/settings.php
  mod/view.php
  src/App.php
  src/Core/Addon.php
  src/Core/Hook.php
  src/Core/L10n.php
  src/Core/Theme.php
  src/Util/Strings.php
  view/theme/frio/README.md
  view/theme/frio/php/scheme.php
  view/theme/frio/style.php
  view/theme/quattro/style.php
  view/theme/vier/style.php
Labels: Bug, Security

#6960 Add "announce" activity for incoming Diaspora reshares
  src/Protocol/Diaspora.php
Labels: Enhancement, Federation

#6963 CS, DE, PL translation updates
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#6964 Changed keyup to oninput
  view/theme/frio/templates/theme_settings.tpl
Labels: Bug, Mobile, UX

#6966 AP: Incoming announces are now stored as activities
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement, Federation

#6968 Set the newest resharer as owner of a thread
  include/conversation.php
Labels: Enhancement, UX

#6955 vier mobile enhancements
  view/theme/vier/mobile.css
  view/theme/vier/templates/nav.tpl
Labels: Enhancement, UI/Theme

#6957 Send AP Tombstone activity on deleted profiles
  CHANGELOG
  src/Module/Profile.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#6972 Use deferred workers instead of the queue mechanism
  src/Protocol/Diaspora.php
  src/Worker/Delivery.php
Labels: Enhancement

#6973 beautification of pleroma stats
  mod/admin.php
Labels: Enhancement

#6974 Avoid repeated transmitting of profile updates
  src/Protocol/Diaspora.php
Labels: Enhancement

#6977 Fix: Only use reshare information for the top level post
  include/conversation.php
Labels: Bug

#6969 Add rule-based router
  CHANGELOG
  composer.json
  composer.lock
  doc/Addons.md
  src/App.php
  src/App/Router.php
  src/Factory/DependencyFactory.php
  src/Module/Itemsource.php
  tests/include/ApiTest.php
  tests/src/App/RouterTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
Labels: New Feature

#6978 Remove the queue from the core
  config/dbstructure.config.php
  database.sql
  doc/Addons.md
  doc/de/Addons.md
  mod/admin.php
  src/Core/Console/ArchiveContact.php
  src/Model/Queue.php
  src/Protocol/Diaspora.php
  src/Worker/Cron.php
  src/Worker/Queue.php
  update.php
  view/templates/admin/summary.tpl
  view/theme/frio/templates/admin/summary.tpl
Labels: Enhancement

#6985 vier mobile: private mail width
  view/theme/vier/mobile.css
Labels: Bug, UX

#6987 Add subject to DB Update email
  src/Core/Update.php
Labels: Enhancement

#6990 Fix warning
  src/App.php
Labels: Bug

#6784 Delete deprecated method Image::storePhoto()
  src/Object/Image.php
Labels: Enhancement

#6988 Fetch profile data from different contact tables
  config/dbstructure.config.php
  database.sql
  src/Model/Contact.php
  src/Protocol/ActivityPub.php
  src/Worker/UpdateContact.php
Labels: Enhancement, Performance

#6992 Fix warnings
  src/Model/Contact.php
Labels: Bug

#6993 Added missing "cron_interval" default value
  config/defaults.config.php
  src/Worker/Cron.php
Labels: Bug

#6989 Automatic BaseURL determination fix
  boot.php
  config/defaults.config.php
  mod/admin.php
  src/App.php
  src/Core/Authentication.php
  src/Core/Config/Configuration.php
  src/Core/Session.php
  src/Core/System.php
  src/Core/Update.php
  src/Factory/DependencyFactory.php
  src/Model/Contact.php
  src/Network/Probe.php
  src/Protocol/DFRN.php
  src/Util/BasePath.php
  src/Util/BaseURL.php
  src/Util/Config/ConfigFileSaver.php
  src/Util/Network.php
  tests/datasets/api.yml
  tests/include/ApiTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
  tests/src/Util/BaseURLTest.php
  tests/src/Util/Config/ConfigFileSaverTest.php
Labels: Bug, Enhancement

#6995 Fix check backend
  src/App.php
  src/Core/Session/CacheSessionHandler.php
  src/Core/Session/DatabaseSessionHandler.php
Labels: Bug, Performance

#6991 Allow set empty string storage class for legacy
  mod/admin.php
  src/Core/StorageManager.php
Labels: Enhancement, UX

#6996 fixing error "json not defined" in frio
  view/js/linkPreview.js
Labels: Bug, UI/Theme

#7003 Only call page_end hooks for standalone pages (no Ajax)
  src/App.php
Labels: Enhancement, UX

#7005 DBA & Logger fix
  src/Core/Installer.php
  src/Database/DBA.php
  src/Factory/DBFactory.php
  src/Factory/DependencyFactory.php
  tests/DatabaseTest.php
Labels: Bug

#7007 Remove obsolete hack in file browser template
  view/templates/filebrowser.tpl
  view/theme/frio/templates/filebrowser.tpl
Labels: Enhancement

#7010 Basepath Hardening
  src/Util/BasePath.php
  tests/src/Util/BasePathTest.php
Labels: Enhancement

#7009 Prevent full page to load on save to folder modal
  src/BaseModule.php
  src/Module/Filer.php
Labels: Bug, UX

#7011 SetLogger fix
  src/Factory/DependencyFactory.php
Labels: Bug

#7017 Don't show a reshare in the top of a message if we know the author
  include/conversation.php
Labels: Enhancement, Federation

#7019 New redis configuration
  config/defaults.config.php
  src/Core/Cache/RedisCacheDriver.php
  src/Factory/CacheDriverFactory.php
  tests/src/Core/Cache/RedisCacheDriverTest.php
  tests/src/Core/Lock/RedisCacheLockDriverTest.php
Labels: New Feature

#7018 New Command "BlockedServers"
  composer.json
  composer.lock
  src/Core/Console.php
  src/Core/Console/ServerBlock.php
  tests/src/Core/Console/ServerBlockConsoleTest.php
Labels: New Feature

#7024 Update Friendica requirements in doc/
  doc/Install.md
  doc/Settings.md
  doc/de/Install.md
  doc/de/Settings.md
Labels: Docs

#7022 Support for APCu caching
  .travis.yml
  .travis/apcu.ini
  .travis/memcached.ini
  .travis/redis.ini
  src/Core/Cache/APCuCache.php
  src/Core/Cache/AbstractCacheDriver.php
  src/Factory/CacheDriverFactory.php
  tests/src/Core/Cache/APCuCacheDriverTest.php
  tests/src/Core/Lock/APCuCacheLockDriverTest.php
Labels: New Feature

#7025 Moving mod/babel to src/Module/babel
  mod/babel.php
  src/Module/Babel.php
Labels: Enhancement

#7026 Improved reshare check
  include/conversation.php
Labels: Enhancement, Federation, UX

#7028 Move mod/localtime to src/Module/Localtime
  mod/localtime.php
  src/Module/Localtime.php
Labels: Enhancement

#7027 Moving mod/statistics_json to src/Module/Statistics_json
  mod/statistics_json.php
  src/Module/Statistics_json.php
Labels: Enhancement

#7030 Move mod/nodeinfo to src/Module/Nodeinfo
  mod/_well_known.php
  mod/nodeinfo.php
  src/Model/Nodeinfo.php
  src/Model/User.php
  src/Module/Nodeinfo.php
  src/Worker/CronJobs.php
Labels: Enhancement

#7034 API: Fix the displaying of reshared posts
  include/api.php
  src/Model/Item.php
Labels: API, Bug

#7029 Move mod/manifest to src/Module/Manifest
  mod/manifest.php
  src/Module/Manifest.php
Labels: Enhancement

#7035 updated CHANGELOG
  CHANGELOG
Labels: Docs

#7040 Probing of Pleroma contacts does work again
  src/Model/APContact.php
Labels: Bug, Federation

#7039 API: Reshares and Quotes should now work in any combination
  include/api.php
Labels: Enhancement, Federation

#7041 Remove failing require to non-existent file in Worker\CronJobs
  src/Worker/CronJobs.php
Labels: Bug

#7042 Follow up to #7036: Automatically update AP contacts
  src/Model/APContact.php
Labels: Enhancement

#7043 Workaround for systems who don't use a correct context in ActivityPub
  src/Util/JsonLD.php
Labels: Enhancement, Federation

#7045 AP: Parsing of messages from Pleroma should work now again
  src/Model/APContact.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Util/JsonLD.php
Labels: Bug, Enhancement

#7046 Fix "Illegal string offset 'title'/'description'" notice in Module\Photo
  src/Module/Photo.php
Labels: Bug

#7052 Move item feed display after permission checking in mod/display
  mod/display.php
Labels: Bug, Security

#7053 Move item feed display after permission checking in mod/display
  mod/display.php
Labels: Bug, Security

#7054 Fix parenthesis encoding in admin.php
  mod/admin.php
Labels: Bug, UI/Theme, UX

#7055 regen messages.po
  view/lang/C/messages.po
Labels: Translation

#7056 CS, DE translation update
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#7058 AP endpoints are added to the list of backend processes
  src/App.php
Labels: Enhancement, Performance

#7060 Preparation for switching the connect mechanism from DFRN to AP
  mod/dfrn_confirm.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation
