Repository friendica/friendica, pull requests merged in 2019-07, with the labels that each got.

#7334 New constant for federated protocols
  include/conversation.php
  mod/crepair.php
  mod/item.php
  src/Content/ContactSelector.php
  src/Content/Widget/ContactBlock.php
  src/Core/Protocol.php
  src/Core/Search.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Profile.php
  src/Module/Contact.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/UpdateGContact.php
Labels: Enhancement, Federation

#7336 Use Contact::getIdForURL instead of Probe::uri and manual contact table lookup
  src/Console/GlobalCommunitySilence.php
Labels: Bug

#7342 Ensure $link_item variable type when calling get_responses() in mod/photos
  mod/photos.php
Labels: Bug

#7343 Various small fixes
  view/theme/frio/img/none.png
  view/theme/frio/style.php
  view/theme/frio/templates/admin/blocklist/contact.tpl
Labels: Bug

#7339 Restructured Contact/GContact handling
  config/dbstructure.config.php
  database.sql
  mod/redir.php
  src/Model/APContact.php
  src/Model/Contact.php
  src/Model/GContact.php
  src/Network/Probe.php
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Worker/OnePoll.php
  src/Worker/UpdateGContact.php
Labels: Enhancement, Performance

#7348 Use "received" instead of "created" for sorting items
  config/dbstructure.config.php
  include/api.php
  include/conversation.php
  mod/network.php
  mod/ping.php
  mod/search.php
  src/Core/NotificationsManager.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Module/Profile.php
  src/Protocol/DFRN.php
  src/Protocol/OStatus.php
Labels: Enhancement, UX

#7352 Add ActivityPub related fields to the "uri" function
  src/Network/Probe.php
  src/Protocol/ActivityPub.php
Labels: Enhancement, Federation

#7347 Changed unavailable to in a relation
  config/dbstructure.config.php
  database.sql
  src/Content/ContactSelector.php
  update.php
Labels: Enhancement, UX

#7353 Revert "Changed unavailable to in a relation"
  config/dbstructure.config.php
  database.sql
  src/Content/ContactSelector.php
  update.php
Labels: Bug

#7349 Rewrite conditions for photo linked item to prevent crash on old photos
  mod/photos.php
Labels: Bug

#7354 Only fetch toplevel posts when searching for hashtags on network page
  mod/network.php
Labels: Enhancement, UX

#7355 Changed unavailable to in a relation (Resubmit)
  config/dbstructure.config.php
  database.sql
  src/Content/ContactSelector.php
  update.php
Labels: Enhancement, UX

#7360 Fix fatal error with incomplete contact data upon delivery
  src/Protocol/DFRN.php
Labels: Bug, Federation

#7361 [FRIO] fixing chromium mobile navbar color when not logged in
  view/theme/frio/php/default.php
Labels: Enhancement, UI/Theme

#7368 Use standard function to update the contact to avoid SQL errors
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug

#7358 Bugfixing DB/Installer (Simplify Config Part 1)
  src/Core/Config/Cache/ConfigCache.php
  src/Core/Installer.php
  tests/src/Console/AutomaticInstallationConsoleTest.php
  tests/src/Core/Config/Cache/ConfigCacheTest.php
Labels: Bug, Installation

#7371 Splitting ConfigCache & PConfigCache (Simplify Config Part 2)
  src/App.php
  src/Console/AutomaticInstallation.php
  src/Core/Config/Cache/ConfigCache.php
  src/Core/Config/Cache/IConfigCache.php
  src/Core/Config/Cache/IPConfigCache.php
  src/Core/Config/Cache/PConfigCache.php
  src/Core/Config/Configuration.php
  src/Core/Config/PConfiguration.php
  src/Core/Installer.php
  src/Database/Database.php
  src/Factory/ConfigFactory.php
  src/Factory/DBFactory.php
  src/Factory/DependencyFactory.php
  src/Factory/ProfilerFactory.php
  src/Module/Install.php
  src/Util/Config/ConfigFileLoader.php
  tests/Util/AppMockTrait.php
  tests/include/ApiTest.php
  tests/src/Core/Cache/MemoryCacheTest.php
  tests/src/Core/Config/Cache/ConfigCacheTest.php
  tests/src/Core/Config/Cache/PConfigCacheTest.php
  tests/src/Core/Config/ConfigurationTest.php
  tests/src/Core/Config/PConfigurationTest.php
  tests/src/Core/InstallerTest.php
  tests/src/Core/Lock/LockTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
Labels: Enhancement

#7373 Don't filter partner in relation status
  view/templates/profile_advanced.tpl
  view/theme/frio/templates/profile_advanced.tpl
Labels: UX

#7378 [frio] Use server theme settings for user's empty settings
  view/theme/frio/style.php
Labels: Enhancement, UI/Theme

#7372 Refactor Configuration (Simplify Config Part 3)
  include/api.php
  src/Core/Config/Adapter/IConfigAdapter.php
  src/Core/Config/Adapter/JITConfigAdapter.php
  src/Core/Config/Adapter/PreloadConfigAdapter.php
  src/Core/Config/Cache/ConfigCache.php
  src/Core/Config/Cache/PConfigCache.php
  src/Core/Config/Configuration.php
  src/Core/Config/JitConfiguration.php
  src/Core/Config/PConfiguration.php
  src/Core/Config/PreloadConfiguration.php
  src/Database/Database.php
  src/Factory/ConfigFactory.php
  src/Factory/DependencyFactory.php
  src/Model/Config/Config.php
  src/Model/Config/DbaConfig.php
  tests/DatabaseTest.php
  tests/Util/AppMockTrait.php
  tests/include/ApiTest.php
  tests/src/Core/Config/Cache/ConfigCacheTest.php
  tests/src/Core/Config/Cache/PConfigCacheTest.php
  tests/src/Core/Config/ConfigurationTest.php
  tests/src/Core/Config/JitConfigurationTest.php
  tests/src/Core/Config/PreloadConfigurationTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
Labels: Bug, Enhancement

#7382 Issue 7367: Enhanced check when DFRN delivery can be skipped
  src/Worker/Notifier.php
Labels: Bug, Federation

#7384 Fixing initial load config (Simplify Config Part 3a)
  src/Core/Config/JitConfiguration.php
  tests/Util/AppMockTrait.php
  tests/src/Core/Config/JitConfigurationTest.php
Labels: Bug

#7387 Refactor PConfiguration (Simplify Config Part 4)
  src/Core/Config/Adapter/AbstractDbaConfigAdapter.php
  src/Core/Config/Adapter/IPConfigAdapter.php
  src/Core/Config/Adapter/JITPConfigAdapter.php
  src/Core/Config/Adapter/PreloadPConfigAdapter.php
  src/Core/Config/Cache/PConfigCache.php
  src/Core/Config/JitPConfiguration.php
  src/Core/Config/PConfiguration.php
  src/Core/Config/PreloadConfiguration.php
  src/Core/Config/PreloadPConfiguration.php
  src/Factory/ConfigFactory.php
  src/Factory/DependencyFactory.php
  src/Model/Config/PConfig.php
  tests/include/ApiTest.php
  tests/src/Core/Config/Cache/PConfigCacheTest.php
  tests/src/Core/Config/JitPConfigurationTest.php
  tests/src/Core/Config/PConfigurationTest.php
  tests/src/Core/Config/PreloadPConfigurationTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
Labels: Bug, Enhancement

#7388 Issue 7315: Changed handling of "Group" posts
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, Federation

#7386 Hide registration button on login page when registration are closed
  src/Module/Login.php
Labels: Bug, UX

#7390 Issue 7315: Set the forum's contact id for forum posts
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation

#7389 Ensure NULL isn't passed to Feature::isEnabled
  mod/cal.php
  mod/photos.php
  src/Content/Feature.php
  src/Content/Widget.php
  src/Content/Widget/CalendarExport.php
  src/Core/Config/JitPConfiguration.php
  src/Core/Config/PConfiguration.php
  src/Core/Config/PreloadPConfiguration.php
  src/Core/PConfig.php
  src/Model/Profile.php
  tests/src/Core/Config/JitPConfigurationTest.php
  tests/src/Core/Config/PConfigurationTest.php
  tests/src/Core/Config/PreloadPConfigurationTest.php
Labels: Bug

#7313 Dynamic config loading
  config/local-sample.config.php
  doc/Config.md
  src/App.php
  src/Console/AutomaticInstallation.php
  src/Core/Config/Configuration.php
  src/Database/DBStructure.php
  src/Factory/ConfigFactory.php
  src/Factory/DependencyFactory.php
  src/Module/Admin/Summary.php
  src/Util/Config/ConfigFileManager.php
  src/Util/ConfigFileLoader.php
  static/dbstructure.config.php
  static/defaults.config.php
  static/settings.config.php
  tests/DatabaseTest.php
  tests/Util/VFSTrait.php
  tests/datasets/config/A.config.php
  tests/datasets/config/A.ini.php
  tests/datasets/config/B.config.php
  tests/datasets/config/B.ini.php
  tests/include/ApiTest.php
  tests/src/Console/AutomaticInstallationConsoleTest.php
  tests/src/Util/Config/ConfigFileLoaderTest.php
  update.php
  view/templates/local.config.tpl
Labels: Enhancement

#7391 Avoid a warning in Notifier worker
  src/Worker/Notifier.php
Labels: Bug

#7379 Refactor L10n for testing
  src/App.php
  src/Core/L10n.php
  src/Core/L10n/L10n.php
  src/Factory/DependencyFactory.php
  src/Module/Register.php
  tests/Util/L10nMockTrait.php
  tests/include/ApiTest.php
  tests/src/Console/AutomaticInstallationConsoleTest.php
  tests/src/Content/SmiliesTest.php
  tests/src/Content/Text/BBCodeTest.php
  tests/src/Core/InstallerTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
Labels: Enhancement

#7395 Fix InstallerTest
  tests/src/Core/InstallerTest.php
Labels: Bug

#7394 [frio] Remove outer post padding
  view/theme/frio/css/style.css
  view/theme/frio/js/theme.js
  view/theme/frio/templates/wall_thread.tpl
Labels: UI/Theme

#7398 Preparation for being able to fetch AP posts by proving the URL
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement, Federation

#7402 Ensures node theme settings are used to render theme embed
  src/Module/Admin/Themes/Embed.php
Labels: Bug, UI/Theme, UX

#7400 [frio] Theme settings fallback on node settings
  mod/settings.php
  view/theme/frio/config.php
Labels: Bug, UI/Theme

#7407 Fix undefined property notice in L10n\L10n
  src/Core/L10n/L10n.php
Labels: Bug

#7409 Fix reference non-existing "mobile-theme" field in user record
  mod/settings.php
Labels: Bug

#7410 Remove confusing extraneous `success_update` >= `failure_update` conditions
  mod/acl.php
  src/Content/ForumManager.php
Labels: Enhancement, UX

#7411 Preparation for quoted reshares on AP
  include/api.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#7413 Issue 6675: Improved check for follower, removed global setting
  src/Module/Admin/Site.php
  src/Protocol/OStatus.php
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement, Federation, UX

#7415 Fix tag rendering which was displayed as escaped HTML
  view/theme/frio/templates/photo_view.tpl
Labels: Bug, UI/Theme

#7412 Introduce DICE
  bin/auth_ejabberd.php
  bin/console.php
  bin/daemon.php
  bin/worker.php
  composer.json
  composer.lock
  index.php
  src/App.php
  src/App/Mode.php
  src/App/Router.php
  src/Console/AutomaticInstallation.php
  src/Core/Installer.php
  src/Core/L10n/L10n.php
  src/Database/Database.php
  src/Factory/ConfigFactory.php
  src/Factory/DBFactory.php
  src/Factory/DependencyFactory.php
  src/Factory/LoggerFactory.php
  src/Factory/ProfilerFactory.php
  src/Module/Install.php
  src/Util/BasePath.php
  src/Util/ConfigFileLoader.php
  src/Util/Profiler.php
  static/dependencies.config.php
  tests/DatabaseTest.php
  tests/functional/DependencyCheckTest.php
  tests/include/ApiTest.php
  tests/src/App/ModeTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
  tests/src/Util/BasePathTest.php
  tests/src/Util/Config/ConfigFileLoaderTest.php
  tests/src/Util/ProfilerTest.php
Labels: Enhancement

#7414 Fetch Diaspora posts by url
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/Diaspora.php
Labels: Enhancement, Federation

#7419 Add app-specific passwords feature
  doc/Two-Factor-Authentication.md
  include/api.php
  src/App/Router.php
  src/Model/TwoFactor/AppSpecificPassword.php
  src/Model/TwoFactor/RecoveryCode.php
  src/Model/User.php
  src/Module/Settings/TwoFactor/AppSpecific.php
  src/Module/Settings/TwoFactor/Index.php
  src/Module/Settings/TwoFactor/Recovery.php
  src/Module/TwoFactor/Recovery.php
  static/dbstructure.config.php
  view/templates/settings/twofactor/app_specific.tpl
  view/templates/settings/twofactor/index.tpl
Labels: API, New Feature, Security

#7420 Fix contact issues with fake reshares from Twitter
  src/Content/Text/BBCode.php
  src/Model/Contact.php
  src/Network/Probe.php
Labels: Bug, Federation

#7421 Enable two-factor app-specific passwords for ejabberd
  src/Util/ExAuth.php
Labels: Enhancement, Security

#7427 Set shared instances in DICE
  static/dependencies.config.php
  tests/functional/DependencyCheckTest.php
  tests/src/Core/SystemTest.php
Labels: Bug

#7429 Support for empty nick names
  src/Model/APContact.php
Labels: Enhancement, Federation

#7430 "all contacts" shouldn't show archived contacts
  src/Module/Contact.php
Labels: Enhancement, UX

#7425 2FA: Remove mod/ping from exception list
  src/App.php
  src/Core/Authentication.php
  src/Module/TwoFactor/Verify.php
  view/templates/twofactor/verify.tpl
Labels: Enhancement, Privacy

#7432 Use multibyte string functions
  include/api.php
Labels: API, Bug

#7431 Add shell wildcard patterns feature to server blocklist
  src/Console/ServerBlock.php
  src/Module/Admin/Blocklist/Server.php
  src/Util/Network.php
  tests/src/Console/ServerBlockConsoleTest.php
  view/lang/C/messages.po
  view/templates/admin/blocklist/server.tpl
Labels: Enhancement, UX

#7435 Added "selectToArray" functions in DBA and Item
  src/Database/DBA.php
  src/Database/Database.php
  src/Model/Attach.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Photo.php
  src/Module/Admin/Blocklist/Contact.php
  src/Protocol/DFRN.php
Labels: Enhancement

#7436 Fix displaying of reshared items
  include/conversation.php
Labels: Bug, UX

#7434 New functions to check if a contact supports that protocol
  src/Protocol/ActivityPub.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
Labels: Enhancement, Federation

#7417 Remove DependencyFactory
  bin/auth_ejabberd.php
  bin/console.php
  bin/daemon.php
  bin/worker.php
  include/api.php
  index.php
  mod/settings.php
  src/App.php
  src/BaseObject.php
  src/Core/Config.php
  src/Core/Installer.php
  src/Core/L10n.php
  src/Core/L10n/L10n.php
  src/Core/Logger.php
  src/Core/PConfig.php
  src/Core/Worker.php
  src/Database/DBA.php
  src/Database/Database.php
  src/Factory/ConfigFactory.php
  src/Factory/DependencyFactory.php
  src/Factory/LoggerFactory.php
  src/Model/Profile.php
  src/Util/Logger/WorkerLogger.php
  tests/DatabaseTest.php
  tests/Util/AppMockTrait.php
  tests/Util/Database/ExtendedPDO.php
  tests/Util/Database/StaticDatabase.php
  tests/include/ApiTest.php
  tests/src/BaseObjectTest.php
  tests/src/Content/Text/BBCodeTest.php
  tests/src/Core/Cache/MemoryCacheTest.php
  tests/src/Core/InstallerTest.php
  tests/src/Core/Lock/LockTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
  tests/src/Network/CurlResultTest.php
Labels: Enhancement

#7437 Replace last instance of Contact::select
  include/api.php
  src/Database/Database.php
  src/Model/Attach.php
  src/Model/Item.php
Labels: API, Bug

#7441 Remove Phpunit/Dbunit
  composer.json
  composer.lock
  tests/DatabaseTest.php
  tests/Util/Database/StaticDatabase.php
  tests/datasets/api.fixture.php
  tests/datasets/api.yml
  tests/include/ApiTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
Labels: Enhancement, Performance

#7443 Delivery comments to Diaspora only if it is useful
  src/Worker/Delivery.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#7445 Unescape stream event title
  view/templates/event_stream_item.tpl
Labels: Bug, UI/Theme

#7446 ActivityPub: Support for incoming picture descriptions
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement, Federation

#7447 ActivityPub: We now support transmitting alternative image descriptions
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#7174 DBA: Correctly escape identifier names
  src/Database/DBA.php
  src/Database/DBStructure.php
  src/Database/Database.php
Labels: Bug, Security

#7448 Replace remaining Photo::select by new Photo::selectToArray
  mod/photos.php
  mod/profile_photo.php
Labels: Bug

#7449 Use another "img" format to simplify adding of alternative texts
  view/js/filebrowser.js
  view/theme/frio/js/filebrowser.js
Labels: Enhancement, UX

#7451 Fix: The field "contact-id" now contains the correct contact id again
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, UX

#7450 We can now set image descriptions via API
  doc/api.md
  include/api.php
  mod/dfrn_notify.php
  mod/pubsub.php
  mod/receive.php
  mod/salmon.php
  src/Module/Inbox.php
  src/Util/Network.php
Labels: API, New Feature

#7453 Improved logging when item had been deliberately deleted after creation
  src/Model/Item.php
Labels: Enhancement

#7444 Use DICE for Console
  bin/console.php
  src/Console/ArchiveContact.php
  src/Console/AutomaticInstallation.php
  src/Console/Cache.php
  src/Console/Config.php
  src/Console/DatabaseStructure.php
  src/Console/GlobalCommunityBlock.php
  src/Console/GlobalCommunitySilence.php
  src/Console/Maintenance.php
  src/Console/NewPassword.php
  src/Console/PostUpdate.php
  src/Console/ServerBlock.php
  src/Console/Typo.php
  src/Core/Console.php
  src/Core/Installer.php
  static/dependencies.config.php
  tests/src/Console/AutomaticInstallationConsoleTest.php
  tests/src/Console/ConfigConsoleTest.php
  tests/src/Console/ConsoleTest.php
  tests/src/Console/ServerBlockConsoleTest.php
Labels: Enhancement
