Repository friendica/friendica, pull requests merged in 2019-06, with the labels that each got.

#7213 The delivery counter now counts only successful deliveries
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Worker/Delivery.php
Labels: Bug, Federation, UX

#7215 The only reason we don't defer is when it was a post to a relay
  src/Worker/Delivery.php
Labels: Bug, Federation

#7219 Remove .well-known hardening
  src/App.php
Labels: Bug

#7218 Remove queue from Admin/Summary
  src/Module/Admin/Summary.php
Labels: Bug

#7221 Issue #6799 - remove linefeeds inside of a table structure
  src/Content/Text/BBCode.php
Labels: Bug, UX

#7225 Fix frio hovercard modal buttons
  view/js/main.js
  view/templates/hovercard.tpl
  view/theme/frio/js/modal.js
Labels: Bug, UI/Theme, UX

#7227 Updated composer lock file
  composer.lock
Labels: Enhancement

#7228 Ensure that pokes are always send only via DFRN
  mod/item.php
  src/Model/Item.php
  src/Protocol/Diaspora.php
  src/Worker/APDelivery.php
  src/Worker/Delivery.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#7233 Fixing Installer - ReplaceMacro
  src/Core/Installer.php
  tests/Util/RendererMockTrait.php
  tests/src/Console/AutomaticInstallationConsoleTest.php
Labels: Bug, Installation

#7237 expand permission check to remote array
  src/Util/Security.php
Labels: Bug, Security, UX

#7243 Check Contact ID (fix PHP notice)
  src/Model/Contact.php
  src/Protocol/DFRN.php
Labels: Bug

#7242 Add typed parameter for methods in `Friendica\Util\Network`
  mod/dfrn_confirm.php
  mod/parse_url.php
  src/Content/OEmbed.php
  src/Core/Search.php
  src/Core/Worker.php
  src/Model/APContact.php
  src/Module/Magic.php
  src/Network/Probe.php
  src/Object/Image.php
  src/Protocol/ActivityPub.php
  src/Protocol/OStatus.php
  src/Protocol/PortableContact.php
  src/Util/HTTPSignature.php
  src/Util/Network.php
  src/Worker/OnePoll.php
Labels: Bug

#7244 Introduce HiddenString for Config-Values
  composer.json
  composer.lock
  src/Core/Config/Cache/ConfigCache.php
  src/Core/Config/Configuration.php
  src/Factory/DBFactory.php
  tests/src/Core/Config/Cache/ConfigCacheTest.php
Labels: Enhancement, Security

#7245 Fix delivery counter for poking / unify delivery commands
  mod/events.php
  mod/fsuggest.php
  mod/item.php
  mod/settings.php
  mod/tagger.php
  src/Core/UserImport.php
  src/Core/Worker.php
  src/Model/Item.php
  src/Model/Mail.php
  src/Model/User.php
  src/Module/Admin/Site.php
  src/Protocol/Diaspora.php
  src/Worker/APDelivery.php
  src/Worker/Delivery.php
  src/Worker/Notifier.php
  update.php
Labels: Bug, Enhancement, Federation

#7246 Fix the detection of image posts
  src/Content/Text/BBCode.php
Labels: Bug, Federation

#7247 Fixes PR 7242: Now the "post" function works again
  src/Util/Network.php
Labels: Bug

#7248 Fixing Network::post() caused by wrong argument
  mod/dfrn_confirm.php
  src/Util/Network.php
Labels: Bug

#7251 Avoid fatal error when AP contact has no photo
  src/Model/APContact.php
  src/Model/Photo.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#7254 Fix pixture posts to connectors / fix delivery counter for connector posts
  src/Content/Text/BBCode.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#7256 Fix remote logout
  src/Content/Nav.php
  src/Module/Logout.php
  view/theme/duepuntozero/deriv/darkzero.css
  view/theme/duepuntozero/deriv/easterbunny.css
  view/theme/duepuntozero/deriv/greenzero.css
  view/theme/duepuntozero/deriv/purplezero.css
  view/theme/duepuntozero/style.css
  view/theme/frio/theme.php
  view/theme/vier/style.css
  view/theme/vier/templates/nav.tpl
Labels: Bug, Federation

#7250 Normalize message button in profile sidebar
  mod/display.php
  src/Model/Contact.php
  src/Model/Profile.php
  src/Module/Contact.php
  view/templates/contact_edit.tpl
  view/templates/profile_vcard.tpl
  view/templates/widget/vcard.tpl
  view/theme/duepuntozero/templates/profile_vcard.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/frio/templates/profile_vcard.tpl
  view/theme/frio/templates/widget/vcard.tpl
  view/theme/quattro/templates/profile_vcard.tpl
  view/theme/vier/templates/contact_edit.tpl
  view/theme/vier/templates/profile_vcard.tpl
Labels: Bug, Enhancement

#7258 Fix notice in Model\Profile
  src/Model/Profile.php
Labels: Bug

#7259 Normalize the datetime format of received activity before DB insertion
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation

#7261 Issue 7142: Prevent respawn of "remote self" items
  src/Model/Item.php
Labels: Bug, Federation

#7260 Sanitize the date for mails
  src/Model/Mail.php
Labels: Enhancement

#7262 Restore show_connect flag in Model\Profile::sidebar
  src/Model/Profile.php
Labels: Bug

#7263 Add additional check for $links in Probe
  src/Network/Probe.php
Labels: Bug

#7265 Issue 7264: Count local delivery as well
  src/Worker/Delivery.php
Labels: Bug, UX

#7267 Avoid a notice in AP Receiver
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, Federation

#7270 Define expected /fetch module routes
  src/App/Router.php
Labels: Bug, Federation

#7266 Add type-hint in ActivityPub\Receiver::fetchObject to catch wrong type coercion
  src/Database/DBA.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/PortableContact.php
Labels: Bug

#7272 Fix directory entry display (including wrong links)
  src/Module/Directory.php
Labels: Bug, UX

#7268 Issue 5983: Central check for blocked and ignored contacts added
  src/Model/Item.php
Labels: Bug, Federation, UX

#7273 Fix various notices 2019.06
  src/Model/Contact.php
  src/Module/Admin/Federation.php
  src/Protocol/Diaspora.php
Labels: Bug

#7274 Perform link replacement at the end of BBCode::convert
  src/Console/Typo.php
  src/Content/Text/BBCode.php
  tests/src/Content/Text/BBCodeTest.php
Labels: Bug, UX

#7276 Fix reshare new lines display
  src/Content/Text/BBCode.php
Labels: Bug, UX

#7277 Issue #5983: Ignore reshares from blocked and ignored contacts
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, UX

#7280 Fix the base url detection of AP profiles
  src/Model/APContact.php
Labels: Bug, Federation

#7282 Issue 6477: Automatically repair self contact avatar
  src/Model/Contact.php
  src/Model/User.php
  src/Module/Xrd.php
  src/Protocol/ActivityPub/Transmitter.php
  view/templates/tag_slap.tpl
  view/templates/xrd_person.tpl
Labels: Enhancement

#7284 Don't send activities to "null" endpoints
  src/Model/APContact.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#7287 Issue 6477: Use the correct content-type to resize the images
  src/Model/Contact.php
  src/Model/Photo.php
Labels: Bug, UX

#7288 Fix searching for contacts
  src/Module/BaseSearchModule.php
Labels: Bug, UX

#7289 updated the credits for 2019.06
  CREDITS.txt
Labels: Docs

#7292 Fix a notice when the author is missing
  src/Module/Diaspora/Fetch.php
Labels: Bug

#7294 Fix receiving of DFRN posts with public envelope
  mod/dfrn_notify.php
Labels: Bug

#7286 Escape all the HTML pre-formatted blocks in Smilies::replaceFromArray
  src/Content/Smilies.php
Labels: Bug, UX

#7291 Update default log location
  .gitignore
  config/settings.config.php
Labels: Bug, UX

#7306 Fix the processing of event activities
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, Calendar, Federation

#7304 Escape HTML pre-formatted blocks before converting smilies
  src/Content/Smilies.php
Labels: Bug

#7307 Fix for distribution of event deletions
  src/Model/Event.php
  src/Model/Item.php
Labels: Bug, Calendar, Federation

#7305 Make authentication work for local private images
  src/Model/Photo.php
  src/Protocol/DFRN.php
Labels: Bug, Federation

#7312 Creating Database class out of DBA (nearly 1:1 - copy)
  bin/daemon.php
  include/dba.php
  src/App.php
  src/Database/DBA.php
  src/Database/Database.php
  src/Factory/DBFactory.php
  src/Factory/DependencyFactory.php
  src/Factory/LoggerFactory.php
  tests/include/ApiTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
Labels: Enhancement

#7296 Limit smilies replacement to BBCode::convert
  include/text.php
  mod/message.php
  src/Content/Smilies.php
  src/Content/Text/BBCode.php
  tests/src/Content/Text/BBCodeTest.php
Labels: Enhancement

#7323 Removing functionality from OnePoll.php
  src/Model/Contact.php
  src/Worker/Cron.php
  src/Worker/OnePoll.php
  src/Worker/UpdateContact.php
Labels: Enhancement, Federation

#7324 Collect data about used protocols for delivery
  config/dbstructure.config.php
  database.sql
  src/Model/ItemDeliveryData.php
  src/Protocol/DFRN.php
  src/Worker/APDelivery.php
  src/Worker/Delivery.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#7328 Item delivery data must only be stored when there is data
  config/dbstructure.config.php
  src/Model/Item.php
  update.php
Labels: Enhancement, Federation

#7329 Issue 4815: Silently ignoring trailing @ at follow requests
  mod/follow.php
Labels: Enhancement, UX

#7332 Fix missing App object in Worker\OnePoll
  src/Worker/OnePoll.php
Labels: Bug
