Repository friendica/friendica, pull requests merged in 2019-02, with the labels that each got.

#6572 Hopefully fixes a communicaton problem with Hubzilla
  src/Network/Probe.php
Labels: Bug, Federation

#6573 translation updates
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
  view/lang/zh-cn/messages.po
  view/lang/zh-cn/strings.php
Labels: Translation

#6576 Refactoring DBA-mocking tests
  src/Core/Lock/DatabaseLockDriver.php
  tests/Util/DBAMockTrait.php
  tests/Util/DateTimeFormatMockTrait.php
  tests/Util/DbaCacheMockTrait.php
  tests/Util/DbaLockMockTrait.php
  tests/src/BaseObjectTest.php
  tests/src/Core/Cache/CacheTest.php
  tests/src/Core/Cache/DatabaseCacheDriverTest.php
  tests/src/Core/Cache/MemcacheCacheDriverTest.php
  tests/src/Core/Cache/MemcachedCacheDriverTest.php
  tests/src/Core/Cache/MemoryCacheTest.php
  tests/src/Core/Cache/RedisCacheDriverTest.php
  tests/src/Core/Console/ConfigConsoleTest.php
  tests/src/Core/Console/ConsoleTest.php
  tests/src/Core/InstallerTest.php
  tests/src/Core/Lock/DatabaseLockDriverTest.php
  tests/src/Core/Lock/LockTest.php
  tests/src/Core/Lock/MemcacheCacheLockDriverTest.php
  tests/src/Core/Lock/MemcachedCacheLockDriverTest.php
  tests/src/Core/Lock/RedisCacheLockDriverTest.php
  tests/src/Core/Lock/SemaphoreLockDriverTest.php
  tests/src/Network/CurlResultTest.php
Labels: Enhancement, Tests

#6580 Add nofilter to field_input attribute parameter
  view/templates/field_input.tpl
  view/templates/field_select.tpl
  view/templates/field_select_raw.tpl
  view/templates/field_textarea.tpl
  view/templates/field_themeselect.tpl
  view/templates/field_yesno.tpl
  view/theme/frio/templates/field_input.tpl
  view/theme/frio/templates/field_select.tpl
  view/theme/frio/templates/field_select_raw.tpl
  view/theme/frio/templates/field_textarea.tpl
  view/theme/frio/templates/field_themeselect.tpl
Labels: Bug, UX

#6583 Lower priority for removing items
  src/Model/User.php
  src/Worker/RemoveContact.php
Labels: Enhancement, Performance

#6582 Only escape leading hash marks in Markdown::toBBCode
  src/Content/Text/Markdown.php
Labels: Bug, UX

#6584 CS translation update THX Aditoo
  view/lang/cs/messages.po
  view/lang/cs/strings.php
Labels: Translation

#6590 Diaspora: Remove asterisk-meddling regular expression
  mod/babel.php
  src/Content/Text/Markdown.php
Labels: Bug, UX

#6591 Filestorage Backend and legacy label
  doc/Settings.md
  doc/de/Settings.md
  mod/admin.php
Labels: Bug, Docs

#6581 Config Refactoring
  bin/auth_ejabberd.php
  bin/console.php
  bin/daemon.php
  bin/worker.php
  boot.php
  index.php
  mod/admin.php
  mod/friendica.php
  src/App.php
  src/BaseObject.php
  src/Core/Addon.php
  src/Core/Config.php
  src/Core/Config/ConfigCache.php
  src/Core/Config/ConfigCacheLoader.php
  src/Core/Config/IConfigAdapter.php
  src/Core/Config/IConfigCache.php
  src/Core/Config/IPConfigAdapter.php
  src/Core/Config/IPConfigCache.php
  src/Core/Config/JITConfigAdapter.php
  src/Core/Config/JITPConfigAdapter.php
  src/Core/Config/PreloadConfigAdapter.php
  src/Core/Config/PreloadPConfigAdapter.php
  src/Core/Console/AutomaticInstallation.php
  src/Core/Console/Config.php
  src/Core/Console/DatabaseStructure.php
  src/Core/Console/PostUpdate.php
  src/Core/Console/Typo.php
  src/Core/Installer.php
  src/Core/Logger.php
  src/Core/PConfig.php
  src/Core/System.php
  src/Core/Update.php
  src/Database/DBA.php
  src/Database/DBStructure.php
  src/Factory/ConfigFactory.php
  src/Factory/LoggerFactory.php
  src/Model/Attach.php
  src/Module/Install.php
  src/Util/BasePath.php
  src/Worker/DBUpdate.php
  tests/DatabaseTest.php
  tests/Util/AppMockTrait.php
  tests/include/ApiTest.php
  tests/src/BaseObjectTest.php
  tests/src/Core/Cache/CacheTest.php
  tests/src/Core/Console/AutomaticInstallationConsoleTest.php
  tests/src/Core/Console/ConsoleTest.php
  tests/src/Core/Lock/LockTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
Labels: Enhancement, Performance, Tests

#6598 Improved indexes for worker queue processing
  config/dbstructure.config.php
Labels: Enhancement, Performance

#6599 frio: remove useless </a> for categories from wall_thread template
  view/theme/frio/css/style.css
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: Bug, UI/Theme

#6593 Storage Backend: wording of admin panel help
  mod/admin.php
Labels: Docs

#6600 The automatic follow request is currently deactivated
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#6601 Hopefully final fix for false notifications
  src/Model/Item.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#6577 Attachement live preview
  mod/item.php
  mod/parse_url.php
  view/js/linkPreview.js
  view/theme/frio/css/style.css
  view/theme/frio/js/jot.js
  view/theme/frio/js/modal.js
  view/theme/frio/js/textedit.js
  view/theme/frio/templates/acl_selector.tpl
  view/theme/frio/templates/jot-header.tpl
Labels: New Feature, UI/Theme, UX

#6605 Refactor ConfigMockTrait to mocked ConfigCache
  src/Core/Config.php
  src/Core/Config/AbstractDbaConfigAdapter.php
  src/Core/Config/ConfigCache.php
  src/Core/Config/IConfigAdapter.php
  src/Core/Config/IConfigCache.php
  src/Core/Config/JITConfigAdapter.php
  src/Core/Config/PreloadConfigAdapter.php
  tests/Util/AppMockTrait.php
  tests/Util/ConfigMockTrait.php
  tests/Util/RendererMockTrait.php
  tests/src/App/ModeTest.php
  tests/src/BaseObjectTest.php
  tests/src/Core/Cache/ArrayCacheDriverTest.php
  tests/src/Core/Cache/CacheTest.php
  tests/src/Core/Cache/DatabaseCacheDriverTest.php
  tests/src/Core/Cache/MemcacheCacheDriverTest.php
  tests/src/Core/Cache/MemcachedCacheDriverTest.php
  tests/src/Core/Cache/RedisCacheDriverTest.php
  tests/src/Core/Console/AutomaticInstallationConsoleTest.php
  tests/src/Core/Console/ConfigConsoleTest.php
  tests/src/Core/Lock/ArrayCacheLockDriverTest.php
  tests/src/Core/Lock/LockTest.php
  tests/src/Core/Lock/MemcacheCacheLockDriverTest.php
  tests/src/Core/Lock/MemcachedCacheLockDriverTest.php
  tests/src/Core/Lock/RedisCacheLockDriverTest.php
  tests/src/Core/Lock/SemaphoreLockDriverTest.php
  tests/src/Database/DBStructureTest.php
Labels: Enhancement, Performance, Tests

#6613 Add "delivery done" label
  src/Object/Post.php
  src/Worker/APDelivery.php
  view/lang/C/messages.po
  view/templates/sub/delivery_count.tpl
  view/theme/frio/templates/sub/delivery_count.tpl
Labels: Bug, UX

#6612 Cache config adapter connection status to reduce number of calls to DBA::isConnected()
  src/Core/Config/AbstractDbaConfigAdapter.php
  src/Core/Config/JITConfigAdapter.php
  src/Core/Config/PreloadConfigAdapter.php
Labels: Bug, Performance

#6615 Restore legacy REGISTER_* constants for local config backward compatibility
  boot.php
Labels: Bug

#6608 Fix poco discover server users
  mod/admin.php
  src/Protocol/PortableContact.php
  src/Worker/DiscoverPoCo.php
Labels: Bug

#6614 Add explicit mentions to ActivityPub/Diaspora comments
  mod/crepair.php
  src/Content/Feature.php
  src/Model/APContact.php
  src/Module/Itemsource.php
  src/Object/Post.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
  view/templates/crepair.tpl
  view/theme/frio/templates/crepair.tpl
Labels: Enhancement, Federation, UX

#6619 Furtner improval of the worker speed
  config/defaults.config.php
  mod/worker.php
  src/Core/Worker.php
  src/Worker/Cron.php
Labels: Enhancement, Performance

#6616 fix typo
  src/Model/Storage/Filesystem.php
Labels: Bug, Translation

#6625 img tag documentation update
  doc/BBCode.md
  doc/de/BBCode.md
Labels: Docs

#6623 regen messages.po
  view/lang/C/messages.po
Labels: Translation

#6624 CS and DE translation update
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#6626 Config tests
  src/Core/Config/AbstractDbaConfigAdapter.php
  src/Core/Config/ConfigCache.php
  src/Core/Config/ConfigCacheLoader.php
  tests/Util/VFSTrait.php
  tests/datasets/config/.htconfig.test.php
  tests/datasets/config/local.config.php
  tests/datasets/config/local.ini.php
  tests/src/Core/Config/ConfigCacheLoaderTest.php
  tests/src/Core/Config/ConfigCacheTest.php
Labels: Tests

#6634 style the warning in crepair
  view/global.css
Labels: UI/Theme

#6638 ACL network - fixed preselected acl items
  mod/network.php
  src/Core/ACL.php
Labels: Bug, UX

#6639 Don't send single item deletions to protocols that support account removal
  src/Model/User.php
  src/Worker/Notifier.php
Labels: Federation, Performance

#6640 Fix worker statistics
  src/Core/Worker.php
Labels: Bug

#6643 added AP to the example home.html file
  mods/home.html
Labels: Docs

#6646 Should fix "DB Error 1205: Lock wait timeout exceeded"
  src/Model/Item.php
Labels: Bug, Performance

#6648 Issue 6603: Events are now fetchable via AP
  src/Model/Event.php
Labels: Bug

#6649 Include new lines in implicit mention regular expression
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#6651 New configuration to disable the automatic mentions removal
  config/defaults.config.php
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement

#6654 PL translation update THX waldis
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#6655 Worker: Changed behaviour of "worker_fetch_limit" config value
  src/Core/Worker.php
Labels: Performance

#6663 [frio] Fix saved search button display
  view/theme/frio/templates/searchbox.tpl
Labels: Bug, UI/Theme, UX

#6664 translation updates DE, FR and EN_US
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/en-us/messages.po
  view/lang/en-us/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
Labels: Translation

#6660 [frio] Improve thread display
  include/conversation.php
  src/App.php
  src/Object/Post.php
  view/global.css
  view/js/main.js
  view/lang/C/messages.po
  view/templates/head.tpl
  view/templates/jot-header.tpl
  view/templates/photos_head.tpl
  view/templates/settings/head.tpl
  view/templates/wall_thread.tpl
  view/theme/frio/css/style.css
  view/theme/frio/js/textedit.js
  view/theme/frio/js/theme.js
  view/theme/frio/templates/comment_item.tpl
  view/theme/frio/templates/head.tpl
  view/theme/frio/templates/jot-header.tpl
  view/theme/frio/templates/photos_head.tpl
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/voting_fakelink.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/smoothly/templates/jot-header.tpl
  view/theme/smoothly/templates/wall_thread.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: Enhancement, UI/Theme, UX

#6680 [frio] Reduce replies right padding
  view/theme/frio/css/style.css
Labels: Enhancement, UI/Theme, UX

#6683 directory - own function for processing data of directory entries
  mod/directory.php
  view/templates/directory_header.tpl
  view/theme/frio/css/style.css
  view/theme/frio/templates/directory_header.tpl
Labels: Enhancement

#6686 [frio] Change comment expand icons to carets
  view/theme/frio/templates/wall_thread.tpl
Labels: Enhancement, UI/Theme, UX

#6692 Some documentation changes
  doc/Install.md
  doc/Update.md
Labels: Docs

#6695 added forgotten line break
  doc/Install.md
Labels: Docs

#6696 DE translation update THX Ulf Rompe
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#6706 update FR translations THX hypolite
  view/lang/fr/messages.po
  view/lang/fr/strings.php
Labels: Translation

#6707 Fixing Rendertime
  src/Util/Profiler.php
  tests/src/Util/ProfilerTest.php
Labels: Bug, UX

#6708 Change iframe address
  doc/Quick-Start-groupsandpages.md
  doc/de/Quick-Start-groupsandpages.md
Labels: Docs, Enhancement

#6709 Issue 6679: Quick fix
  src/App.php
Labels: Bug

#6715 CS translation update THX Aditoo
  view/lang/cs/messages.po
  view/lang/cs/strings.php
Labels: Translation

#6681 New scheduler mechanism for the worker
  config/dbstructure.config.php
  mod/worker.php
  src/Core/Worker.php
  src/Model/Contact.php
Labels: Enhancement

#6722 Sharing color schemes
  view/theme/frio/config.php
  view/theme/frio/templates/theme_settings.tpl
Labels: Enhancement, UI/Theme

#6724 Config Set Bugfix
  bin/daemon.php
  src/App.php
  src/Core/Config/Adapter/AbstractDbaConfigAdapter.php
  src/Core/Config/Adapter/IConfigAdapter.php
  src/Core/Config/Adapter/IPConfigAdapter.php
  src/Core/Config/Adapter/JITConfigAdapter.php
  src/Core/Config/Adapter/JITPConfigAdapter.php
  src/Core/Config/Adapter/PreloadConfigAdapter.php
  src/Core/Config/Adapter/PreloadPConfigAdapter.php
  src/Core/Config/Cache/ConfigCache.php
  src/Core/Config/Cache/ConfigCacheLoader.php
  src/Core/Config/Cache/IConfigCache.php
  src/Core/Config/Cache/IPConfigCache.php
  src/Core/Config/Configuration.php
  src/Core/Config/PConfiguration.php
  src/Core/PConfig.php
  src/Database/DBA.php
  src/Factory/DBFactory.php
  src/Factory/DependencyFactory.php
  src/Model/Photo.php
  tests/DatabaseTest.php
  tests/include/ApiTest.php
  tests/src/Core/Config/Cache/ConfigCacheLoaderTest.php
  tests/src/Core/Config/Cache/ConfigCacheTest.php
  tests/src/Core/Config/ConfigurationTest.php
  tests/src/Core/Config/PConfigurationTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
Labels: Bug

#6725 Addon loading fix
  src/App.php
  src/Util/Profiler.php
  tests/src/Util/ProfilerTest.php
Labels: Bug

#6728 Fixing Update retval warning
  src/Core/Update.php
Labels: Bug

#6727 Returning 404 if nodeinfo isn't enabled
  mod/nodeinfo.php
Labels: Bug

#6723 Adding worker ID to log
  src/App.php
  src/Core/System.php
  src/Core/Worker.php
  src/Factory/LoggerFactory.php
  src/Util/Logger/WorkerLogger.php
  tests/src/Util/Logger/WorkerLoggerTest.php
Labels: Enhancement

#6730 DBA::(re-)connect fix for basePath
  src/Core/Console/AutomaticInstallation.php
  src/Core/Installer.php
  src/Database/DBA.php
  src/Module/Install.php
  tests/DatabaseTest.php
Labels: Bug

#6731 Fixes "Undefined property: Friendica\App::$queue"
  src/Core/Worker.php
  src/Object/Post.php
Labels: Bug

#6734 Fix: Following url with html entities now works again
  view/theme/frio/templates/auto_request.tpl
  view/theme/frio/templates/dfrn_request.tpl
Labels: Bug

#6735 Don't allow calling the install page after the install
  src/Module/Install.php
Labels: Enhancement, Security, UX

#6736 Updated Bootstrap to 3.4.1
  view/theme/frio/frameworks/bootstrap/css/bootstrap-theme.css
  view/theme/frio/frameworks/bootstrap/css/bootstrap-theme.css.map
  view/theme/frio/frameworks/bootstrap/css/bootstrap-theme.min.css
  view/theme/frio/frameworks/bootstrap/css/bootstrap-theme.min.css.map
  view/theme/frio/frameworks/bootstrap/css/bootstrap.css
  view/theme/frio/frameworks/bootstrap/css/bootstrap.css.map
  view/theme/frio/frameworks/bootstrap/css/bootstrap.min.css
  view/theme/frio/frameworks/bootstrap/css/bootstrap.min.css.map
  view/theme/frio/frameworks/bootstrap/js/bootstrap.js
  view/theme/frio/frameworks/bootstrap/js/bootstrap.min.js
Labels: Enhancement, Security

#6737 Fix "EMPTY" label in profile
  mod/profiles.php
  src/Content/ContactSelector.php
  src/Model/Profile.php
  view/lang/C/messages.po
Labels: Bug, UX

#6741 Ensure that the database update will be processed anyway
  src/Core/Update.php
Labels: Enhancement

#6740 Fixing force-flag for lock-release
  src/Core/Console/DatabaseStructure.php
  src/Core/Console/PostUpdate.php
  src/Core/Lock.php
  src/Core/Lock/CacheLockDriver.php
  src/Core/Lock/DatabaseLockDriver.php
  src/Core/Lock/ILockDriver.php
  src/Core/Lock/SemaphoreLockDriver.php
  src/Core/Update.php
Labels: Bug

#6744 Replace string namespace with *::class
  src/Factory/LoggerFactory.php
  src/Factory/ProfilerFactory.php
  tests/Util/DBAMockTrait.php
  tests/Util/DBStructureMockTrait.php
  tests/Util/DateTimeFormatMockTrait.php
  tests/Util/L10nMockTrait.php
  tests/Util/RendererMockTrait.php
  tests/src/Core/Console/ConfigConsoleTest.php
  tests/src/Core/InstallerTest.php
  tests/src/Util/Logger/WorkerLoggerTest.php
  tests/src/Util/ProfilerTest.php
Labels: Bug, Enhancement, Tests

#6732 Allow to remove blocked contact from groups
  mod/contactgroup.php
  mod/group.php
  src/Core/System.php
  src/Model/Contact.php
  src/Model/Group.php
  src/Module/Group.php
  view/js/main.js
  view/templates/group_side.tpl
  view/theme/frio/templates/group_side.tpl
  view/theme/quattro/templates/group_side.tpl
Labels: Bug, Enhancement

#6726 Fix last batch of implicit mentions issues
  boot.php
  config/defaults.config.php
  include/conversation.php
  include/enotify.php
  mod/item.php
  src/Database/DBA.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Term.php
  src/Module/Itemsource.php
  src/Object/Post.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Util/Strings.php
  src/Util/XML.php
  view/templates/debug/itemsource.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: Bug, Federation, UX

#6747 Fixing frio theme customization for admin
  view/theme/frio/php/scheme.php
Labels: Bug, UX

#6749 Fixing appending child at DFRN without a parent id.
  src/Protocol/DFRN.php
Labels: Bug

#6750 moving mod/apps to src/Module/Apps
  mod/apps.php
  src/Module/Apps.php
Labels: Enhancement

#6751 Add missing use statement in Model\Term
  src/Model/Term.php
Labels: Bug

#6752 Fix various notices
  src/Protocol/DFRN.php
  src/Protocol/OStatus.php
  view/theme/frio/config.php
Labels: Bug

#6754 update FR translations THX hypolite
  view/lang/fr/messages.po
  view/lang/fr/strings.php
Labels: Translation

#6753 Add missing author contact in ActivityPub\Processor
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#6755 Protect access to rel attribute in Network\Probe
  src/Network/Probe.php
Labels: Bug

#6758 Fix various notice messages
  src/Content/Text/BBCode.php
  src/Core/Worker.php
Labels: Bug

#6759 [Composer] Update npm-asset/fullcalendar to version 3.10.0
  composer.json
  composer.lock
Labels: Enhancement, Installation

#6761 fixing links in photoMenu
  include/conversation.php
  src/Model/Contact.php
Labels: Bug, UI/Theme

#6764 Better worker lifetime check
  src/Core/Worker.php
Labels: Enhancement, Performance

#6766 Fix namespaces for Tests
  tests/src/BaseObjectTest.php
  tests/src/Core/Config/Cache/ConfigCacheLoaderTest.php
  tests/src/Core/Config/Cache/ConfigCacheTest.php
  tests/src/Core/Config/ConfigurationTest.php
  tests/src/Core/Config/PConfigurationTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
  tests/src/Model/UserTest.php
  tests/src/Util/ArraysTest.php
  tests/src/Util/Logger/WorkerLoggerTest.php
  tests/src/Util/ProfilerTest.php
  tests/src/Util/StringsTest.php
  tests/src/Util/XmlTest.php
Labels: Bug, Tests

#6765 Hide silenced authors from public timeline
  include/api.php
Labels: API, Bug

#6767 Replace isset by array_key_exists on array class constant in Model\Term
  src/Model/Term.php
Labels: Bug

#6769 Syslog Logger
  config/defaults.config.php
  src/Factory/LoggerFactory.php
  src/Util/Logger/Introspection.php
  src/Util/Logger/SyslogLogger.php
Labels: Enhancement, Performance

#6768 added DiCa and Fedilab clients to the FAQ listed clients
  doc/FAQ.md
  doc/de/FAQ.md
Labels: Docs

#6770 Reuse existing Strings::getRandomHex function
  src/Util/Logger/WorkerLogger.php
  tests/src/Util/Logger/WorkerLoggerTest.php
Labels: Enhancement

#6773 Update - query missmatch
  src/Core/Update.php
Labels: Bug

#6771 SyslogLogger - Disabling Logging
  src/Factory/LoggerFactory.php
  src/Util/Logger/VoidLogger.php
Labels: Bug, Enhancement

#6774 Improve reshare format to Diaspora destinations
  mod/share.php
  src/Content/Text/BBCode.php
Labels: Bug, Federation, UX
