Repository friendica/friendica, pull requests merged in 2019-01, with the labels that each got.

#6359 Unescape $invite_desc in follow/register templates
  view/templates/auto_request.tpl
  view/templates/dfrn_request.tpl
  view/templates/register.tpl
  view/theme/frio/templates/auto_request.tpl
  view/theme/frio/templates/dfrn_request.tpl
  view/theme/frio/templates/register.tpl
Labels: Bug, UX

#6362 Unescape profiles template variables
  view/templates/contact_edit.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/frio/templates/profile_entry.tpl
  view/theme/vier/templates/contact_edit.tpl
Labels: Bug, UX

#6365 Unescape $prevlink and $nextlink template variables
  view/templates/photo_view.tpl
  view/theme/quattro/templates/photo_view.tpl
  view/theme/vier/templates/photo_view.tpl
Labels: Bug, UX

#6364 Bugfix - the remote user also has magicLinks again
  src/Model/Contact.php
Labels: Needs More Info

#6371 Use nickname instead of email for Login Name
  mod/admin.php
  mod/lostpass.php
  src/Model/User.php
Labels: Bug, UX

#6369 Use storage backend with attachments
  config/dbstructure.config.php
  database.sql
  mod/attach.php
  mod/item.php
  mod/videos.php
  mod/wall_attach.php
  src/Core/Console/Storage.php
  src/Core/StorageManager.php
  src/Model/Attach.php
  src/Model/Item.php
  src/Model/Photo.php
  src/Module/Attach.php
  src/Module/Proxy.php
  src/Util/Mimetype.php
Labels: Enhancement

#6385 clarification for the translation of addons.
  doc/translations.md
Labels: Docs

#6387 adding lang parameter to DE FAQ
  doc/de/FAQ.md
Labels: Docs

#6388 Periodically update contacts / update the contact type
  src/Model/APContact.php
Labels: Bug, Federation

#6381 Strip base url from links before determining anchor status for iOS linker
  view/templates/head.tpl
  view/theme/frio/templates/head.tpl
Labels: Bug, Mobile, UX

#6380 Change stylesheet path name for mobile browsers
  src/Core/Theme.php
Labels: Bug, Mobile, UI/Theme

#6393 [frio] Fix justifyGalley scales list
  view/theme/frio/js/theme.js
Labels: Bug, UI/Theme, UX

#6373 [vier] Fix private messages notification display
  view/theme/frio/css/style.css
  view/theme/vier/mobile.css
  view/theme/vier/style.css
  view/theme/vier/templates/nav.tpl
Labels: Bug, UI/Theme, UX

#6400 Issue 6394: The contact location has to be BBEncoded
  src/Model/Profile.php
  src/Module/Contact.php
  view/templates/contact_edit.tpl
  view/templates/profile_vcard.tpl
  view/theme/duepuntozero/templates/profile_vcard.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/frio/templates/profile_vcard.tpl
  view/theme/quattro/templates/profile_vcard.tpl
  view/theme/vier/templates/contact_edit.tpl
  view/theme/vier/templates/profile_vcard.tpl
Labels: Bug, UX

#6372 Escape get_app() calls
  boot.php
  include/api.php
  include/enotify.php
  include/items.php
  mod/dfrn_request.php
  mod/fbrowser.php
  mod/item.php
  mod/lostpass.php
  mod/message.php
  mod/nodeinfo.php
  mod/ostatus_subscribe.php
  mod/regmod.php
  mod/repair_ostatus.php
  mod/settings.php
  src/BaseModule.php
  src/Content/OEmbed.php
  src/Content/Text/HTML.php
  src/Content/Widget.php
  src/Content/Widget/CalendarExport.php
  src/Core/Console/DocBloxErrorChecker.php
  src/Core/Console/GlobalCommunityBlock.php
  src/Core/Console/GlobalCommunitySilence.php
  src/Core/Console/NewPassword.php
  src/Core/Console/PhpToPo.php
  src/Core/Console/PoToPhp.php
  src/Core/Console/Typo.php
  src/Core/Theme.php
  src/Core/Worker.php
  src/Database/DBA.php
  src/Model/Contact.php
  src/Model/GContact.php
  src/Model/Item.php
  src/Model/Mail.php
  src/Model/Photo.php
  src/Model/Profile.php
  src/Model/User.php
  src/Network/FKOAuth1.php
  src/Network/Probe.php
  src/Object/Image.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  src/Protocol/PortableContact.php
  src/Render/FriendicaSmarty.php
  src/Render/FriendicaSmartyEngine.php
  src/Util/ExAuth.php
  src/Util/Network.php
  src/Util/ParseUrl.php
  src/Util/Temporal.php
  tests/include/ApiTest.php
  view/templates/infinite_scroll_head.tpl
  view/templates/register.tpl
  view/theme/frio/php/scheme.php
  view/theme/frio/templates/register.tpl
  view/theme/smoothly/theme.php
  view/theme/vier/theme.php
Labels: Bug, UX

#6409 Fixing Monolog issues
  doc/tools.md
  src/Core/Logger.php
  src/Module/Login.php
  src/Util/LoggerFactory.php
Labels: Enhancement

#6412 Issue 6149: Making OWA (hopefully) compatible with Hubzilla
  mod/xrd.php
  src/Module/Magic.php
  src/Module/Owa.php
  view/templates/xrd_person.tpl
Labels: Bug, Federation

#6389 Add "on their post" label to notifications
  include/enotify.php
  util/messages.po
Labels: Enhancement, UX

#6415 Don't show deleted contacts, set new AP contacts as "pending" until accepted
  src/Core/ACL.php
  src/Model/Contact.php
  src/Module/Contact.php
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, UX

#6356 Add password rules
  composer.json
  mod/settings.php
  src/Core/Console/NewPassword.php
  src/Model/User.php
  view/lang/C/messages.po
Labels: Docs, Enhancement

#6422 Don't accept private answers to public parents
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, Federation

#6427 Revert "Change stylesheet path name for mobile browsers"
  src/Core/Theme.php
Labels: Bug

#6428 Add variable query parameter to stylesheet URL for iOS Safari
  src/App.php
  src/Core/Theme.php
  src/Model/Profile.php
  view/theme/duepuntozero/style.php
  view/theme/frio/php/default.php
  view/theme/frio/style.php
  view/theme/quattro/style.php
  view/theme/vier/style.php
Labels: Bug, Mobile, UX

#6430 Translation Updates
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/en-gb/messages.po
  view/lang/en-gb/strings.php
  view/lang/en-us/messages.po
  view/lang/en-us/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/nb-no/messages.po
  view/lang/nb-no/strings.php
  view/lang/nl/messages.po
  view/lang/nl/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#6432 Don't show deleted contacts, changed "pending" behaviour
  mod/acl.php
  mod/dfrn_confirm.php
  src/Content/Widget.php
  src/Model/Contact.php
  src/Protocol/ActivityPub/Transmitter.php
  view/theme/frio/theme.php
Labels: Bug, Federation

#6433 Issue 6282: Update the forum status of contacts
  src/Model/APContact.php
  src/Protocol/DFRN.php
  src/Worker/OnePoll.php
Labels: Bug, Federation

#6434 Update translation en-gb
  view/lang/en-gb/messages.po
  view/lang/en-gb/strings.php
Labels: Translation

#6408 Cleanup according to PHPStorm inspection part 4: Fix potential bugs
  include/conversation.php
  include/enotify.php
  mod/admin.php
  mod/dfrn_notify.php
  mod/dfrn_request.php
  mod/directory.php
  mod/dirfind.php
  mod/display.php
  mod/fbrowser.php
  mod/feedtest.php
  mod/fsuggest.php
  mod/help.php
  mod/hovercard.php
  mod/ignored.php
  mod/invite.php
  mod/item.php
  mod/match.php
  mod/msearch.php
  mod/network.php
  mod/notifications.php
  mod/notify.php
  mod/openid.php
  mod/photos.php
  mod/poco.php
  mod/suggest.php
  mod/update_contact.php
  mod/worker.php
  mod/xrd.php
  src/App.php
  src/Core/Console/DatabaseStructure.php
  src/Core/Console/GlobalCommunityBlock.php
  src/Core/NotificationsManager.php
  src/Core/StorageManager.php
  src/Model/Attach.php
  src/Model/Contact.php
  src/Model/Conversation.php
  src/Model/Event.php
  src/Model/Item.php
  src/Model/Photo.php
  src/Module/Proxy.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Util/Network.php
  src/Util/Strings.php
  src/Worker/OnePoll.php
  src/Worker/TagUpdate.php
Labels: Bug

#6436 Fixing some notice again
  src/Worker/OnePoll.php
Labels: Bug

#6435 Making Friendica compatible to Nextcloud Social
  src/Model/APContact.php
  src/Protocol/ActivityPub/Receiver.php
  src/Util/JsonLD.php
Labels: Enhancement, Federation

#6439 Issue 6438: Avoid fatal error
  src/Util/JsonLD.php
Labels: Bug

#6390 Show followers for pages, followed for users in ContactBlock widget
  include/enotify.php
  mod/admin.php
  mod/community.php
  mod/dfrn_confirm.php
  mod/dfrn_notify.php
  mod/dfrn_request.php
  mod/hcard.php
  mod/noscrape.php
  mod/photos.php
  mod/profile.php
  mod/profiles.php
  mod/settings.php
  mod/videos.php
  mod/wall_attach.php
  mod/wall_upload.php
  src/Content/Nav.php
  src/Content/Text/HTML.php
  src/Content/Widget/ContactBlock.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Profile.php
  src/Model/User.php
  src/Network/Probe.php
  src/Object/Image.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Util/Security.php
  src/Worker/Delivery.php
  src/Worker/Queue.php
  update.php
Labels: Enhancement, UX

#6444 Fix undefined offset notices in Protocol\Email
  src/Protocol/Email.php
Labels: Bug

#6445 Update CREDITS.txt for 2019.01
  CREDITS.txt
  bin/dev/make_credits.py
Labels: Docs

#6446 Now storing the "manually approve" data / fix update routine
  config/dbstructure.config.php
  database.sql
  src/Database/DBA.php
  src/Model/APContact.php
Labels: Enhancement, Federation

#6447 Enable communication with Peertube
  src/Protocol/ActivityPub/Transmitter.php
  src/Util/DateTimeFormat.php
  src/Util/HTTPSignature.php
Labels: Enhancement, Federation

#6450 Fix missing use statement in Content\Nav
  src/Content/Nav.php
  src/Model/User.php
Labels: Bug

#6452 Updated composer file
  composer.lock
Labels: Installation

#6454 Avoid a notice in HTTP signature check, preparation for authentication
  src/Module/Objects.php
  src/Module/Outbox.php
  src/Util/HTTPSignature.php
Labels: Enhancement, Federation

#6455 Issue 6282: Update the contact data regularly (including the network)
  src/Core/Protocol.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Protocol/PortableContact.php
  src/Worker/OnePoll.php
Labels: Enhancement, Federation

#6456 This fixes a problem when the URL is too long
  src/Util/Network.php
Labels: Bug

#6460 Simplyfies AP relaying, fixes relaying of public contacts
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/Delivery.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#6464 Check if the vendor path is missing and complain about it
  index.php
Labels: Enhancement, Installation

#6469 Avoid that forum posts are received via the Diaspora protocol first
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#6470 use magic links for common/all friends and the directory
  mod/allfriends.php
  mod/common.php
  mod/directory.php
  src/Content/Text/HTML.php
  src/Content/Widget.php
  src/Model/Contact.php
Labels: Bug, Enhancement, Federation

#6473 Move theme init after module init but before post/content
  mod/admin.php
  src/App.php
  view/theme/frio/theme.php
Labels: Bug, UI/Theme

#6475 HTML unescape existing albums
  view/templates/photos_upload.tpl
  view/theme/frio/templates/photos_upload.tpl
Labels: Bug, UI/Theme

#6476 AP: Only reshare stuff that is AP content
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#6474 CHANGELOG for 2019.01
  CHANGELOG
Labels: Docs

#6483 Fixes after 2019 03 develop rebase
  include/api.php
  include/conversation.php
  include/enotify.php
  include/items.php
  include/text.php
  mod/photos.php
  src/Object/Post.php
  src/Object/Thread.php
  src/Util/Emailer.php
Labels: Bug

#6488 restore THEMEPATH variable in mod/view
  mod/view.php
Labels: Bug

#6490 unescaping the HTML in the hint
  view/templates/admin/federation.tpl
Labels: Bug

#6487 Critical fixes after develop rebase
  mod/salmon.php
  src/Model/APContact.php
  src/Protocol/OStatus.php
  src/Worker/Notifier.php
Labels: Bug

#6497 Bug/6383 delivery no data
  src/Database/PostUpdate.php
  view/templates/sub/delivery_count.tpl
  view/theme/frio/css/style.css
  view/theme/frio/templates/sub/delivery_count.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/vier/templates/sub/delivery_count.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: Bug, UI/Theme, UX

#6336 Move mod/register to Module\Register
  boot.php
  config/local-sample.config.php
  config/settings.config.php
  include/api.php
  mod/admin.php
  mod/bookmarklet.php
  mod/friendica.php
  mod/home.php
  mod/invite.php
  mod/nodeinfo.php
  mod/openid.php
  mod/ping.php
  mod/register.php
  mod/regmod.php
  mod/statistics_json.php
  mod/uimport.php
  mods/local.config.vagrant.php
  src/Content/Nav.php
  src/Module/Login.php
  src/Module/Register.php
  src/Protocol/PortableContact.php
  tests/src/Core/Console/AutomaticInstallationConsoleTest.php
  view/templates/local.config.tpl
  view/templates/register.tpl
  view/theme/frio/templates/register.tpl
Labels: Enhancement

#6499 Update to CS and ES translation
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/es/messages.po
  view/lang/es/strings.php
Labels: Translation

#6485 More fixes after develop rebase
  .travis.yml
  config/dbstructure.config.php
  config/defaults.config.php
  database.sql
  mod/admin.php
  src/Content/ForumManager.php
  src/Content/OEmbed.php
  src/Content/Text/HTML.php
  src/Content/Widget/TagCloud.php
  src/Core/Console.php
  src/Core/Renderer.php
  src/Core/StorageManager.php
  src/Model/Attach.php
  src/Model/Event.php
  src/Model/Item.php
  src/Model/Mail.php
  src/Model/Photo.php
  src/Model/Term.php
  src/Module/Contact.php
  src/Module/Inbox.php
  src/Module/Photo.php
  src/Object/Image.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Email.php
  src/Protocol/OStatus.php
  src/Util/Crypto.php
  src/Util/Temporal.php
  src/Util/XML.php
  src/Worker/Delivery.php
Labels: Bug

#6504 Fix for several fatal errors
  src/Content/OEmbed.php
  src/Content/Widget/ContactBlock.php
  src/Module/Inbox.php
  src/Protocol/DFRN.php
  src/Protocol/OStatus.php
  src/Worker/Notifier.php
Labels: Bug

#6506 Fix fatal errors
  src/Database/DBStructure.php
  src/Module/Inbox.php
Labels: Bug

#6507 Updated composer.lock
  composer.lock
Labels: Installation

#6510 Logger: Display the correct file, function and line number
  src/Util/Logger/FriendicaProcessor.php
Labels: Bug

#6512 Added nofilter to geotag
  view/templates/jot-header.tpl
  view/theme/frio/templates/jot-header.tpl
  view/theme/smoothly/templates/jot-header.tpl
Labels: Bug, UX

#6513 DFRN comments are now stored as comments again
  src/Protocol/DFRN.php
  src/Protocol/OStatus.php
Labels: Bug

#6515 Fix: Connector posts now do work again (postopts hadn't been stored)
  src/Model/ItemDeliveryData.php
Labels: Bug

#6518 added nofilter to banner in smoothy and quaddro
  view/theme/quattro/templates/nav.tpl
  view/theme/smoothly/templates/nav.tpl
Labels: Bug

#6520 Replace help/guide with help/Quick-Start-guide in newmember
  mod/newmember.php
Labels: Docs

#6523 Preparation for forum posts over AP
  src/Module/Objects.php
Labels: Enhancement, Federation

#6526 frio - fixed bug in user menu for remote user - see issue #6495
  view/theme/frio/theme.php
Labels: Bug, Federation

#6527 frio - fixed bug in user menu for visitors
  view/theme/frio/theme.php
Labels: Bug, Federation, UX

#6530 frio - fixed bug in admin users with table sorting #6529
  view/theme/frio/templates/admin/users.tpl
Labels: Bug, UI/Theme

#6531 frio - fix PHP Notices reported in #6338
  view/theme/frio/theme.php
Labels: Bug, Federation

#6536 Another preparation for forum posts via AP
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#6539 Logger Unique ID
  src/Util/Logger/FriendicaIntrospectionProcessor.php
  src/Util/LoggerFactory.php
Labels: Enhancement

#6542 Rename conflicted variable $info in admin settings
  mod/admin.php
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Bug

#6541 Display mentioned users and in the comment box by default
  src/Model/Item.php
  src/Object/Post.php
  view/templates/comment_item.tpl
  view/theme/duepuntozero/templates/comment_item.tpl
  view/theme/frio/templates/comment_item.tpl
  view/theme/quattro/templates/comment_item.tpl
  view/theme/vier/templates/comment_item.tpl
Labels: Enhancement, Federation

#6549 Put cursor at end of default mentions in comment box
  view/templates/head.tpl
  view/theme/frio/js/textedit.js
Labels: Enhancement, UX

#6550 CS, DE and PL translation updates
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#6554 Fixed some bugs with weird tagging in [code] blocks and tagging of multiple ##
  src/Content/Text/BBCode.php
  src/Model/Item.php
Labels: Bug

#6555 fix isssue if friendica is installed into a subdirectory
  src/App.php
Labels: Bug, Installation

#6556 Bug/fix hashtag in code
  mod/babel.php
  src/Content/Text/BBCode.php
  src/Model/Item.php
Labels: Bug

#6559 warn in admin panel when legacy config is used
  mod/admin.php
Labels: Enhancement

#6563 AP: Clarify message distribution for forum posts
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#6565 AP: Follow a note to receive all upcoming activities
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#6566 AP: Debug option to deliver via AP first
  config/defaults.config.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/Notifier.php
Labels: Enhancement

#6568 Links of mentioned contacts hadn't looked great on Mastodon
  src/Content/Text/BBCode.php
Labels: Enhancement, UX

#6562 Move profile module to src/
  mod/profile.php
  mod/update_profile.php
  src/Module/Profile.php
Labels: Bug, Enhancement
