Repository friendica/friendica, pull requests merged in 2019-05, with the labels that each got.

#7063 Move mod/amcd to src/Module/AccMgmtControlDoc
  mod/amcd.php
  src/App/Router.php
  src/Module/AccountManagementControlDocument.php
Labels: Enhancement

#7064 Update module specific README
  src/Module/README.md
Labels: Docs

#7065 Add routes to all current BaseModules
  src/App/Router.php
  src/Module/Attach.php
  src/Module/Contact.php
  src/Module/Feed.php
  src/Module/Filer.php
  src/Module/Followers.php
  src/Module/Following.php
  src/Module/Group.php
  src/Module/Inbox.php
  src/Module/Install.php
  src/Module/Itemsource.php
  src/Module/Objects.php
  src/Module/Oembed.php
  src/Module/Outbox.php
  src/Module/Photo.php
  src/Module/Profile.php
  src/Module/Proxy.php
  src/Module/Register.php
  src/Module/Statistics.php
Labels: Enhancement

#7062 Move mod/_well_known to src/Module/WellKnown/*
  mod/_well_known.php
  mod/hostxrd.php
  mod/webfinger.php
  mod/xrd.php
  src/App/Router.php
  src/Model/Search.php
  src/Model/User.php
  src/Module/NodeInfo.php
  src/Module/WebFinger.php
  src/Module/WellKnown/HostMeta.php
  src/Module/WellKnown/XSocialRelay.php
  src/Module/Xrd.php
  view/templates/webfinger.tpl
Labels: Enhancement

#7067 Remove App->error
  mod/hcard.php
  mod/notice.php
  mod/photos.php
  mod/suggest.php
  mod/videos.php
  mod/viewsrc.php
  src/App.php
  src/Model/Profile.php
  view/templates/album_edit.tpl
  view/templates/photo_album.tpl
  view/templates/photo_edit.tpl
  view/templates/photo_view.tpl
  view/theme/frio/js/mod_photos.js
  view/theme/frio/templates/album_edit.tpl
  view/theme/frio/templates/confirm.tpl
  view/theme/frio/templates/photo_album.tpl
  view/theme/frio/templates/photo_view.tpl
  view/theme/quattro/templates/photo_view.tpl
  view/theme/vier/templates/photo_view.tpl
Labels: Enhancement

#7070 Remove old BaseModule routing
  src/App.php
Labels: Enhancement

#7073 Remove usage of non-existent Module\Special\HTTPException::rawContent return value
  src/App.php
Labels: Enhancement

#7074 Remove support for defunct Friendica F-Droid app
  mod/notify.php
  mod/ping.php
  mod/subthread.php
  mod/tagger.php
  src/App.php
  src/Model/Item.php
  src/Protocol/DFRN.php
Labels: Enhancement

#7075 Move Console namespace one level up
  src/Console/ArchiveContact.php
  src/Console/AutomaticInstallation.php
  src/Console/Cache.php
  src/Console/Config.php
  src/Console/CreateDoxygen.php
  src/Console/DatabaseStructure.php
  src/Console/DocBloxErrorChecker.php
  src/Console/Extract.php
  src/Console/GlobalCommunityBlock.php
  src/Console/GlobalCommunitySilence.php
  src/Console/Maintenance.php
  src/Console/NewPassword.php
  src/Console/PhpToPo.php
  src/Console/PoToPhp.php
  src/Console/PostUpdate.php
  src/Console/ServerBlock.php
  src/Console/Storage.php
  src/Console/Typo.php
  src/Core/Console.php
  tests/src/Console/AutomaticInstallationConsoleTest.php
  tests/src/Console/ConfigConsoleTest.php
  tests/src/Console/ConsoleTest.php
  tests/src/Console/ServerBlockConsoleTest.php
Labels: Enhancement

#7069 Move mod/allfriends to src/Module/AllFriends
  mod/allfriends.php
  src/App/Router.php
  src/Model/Contact.php
  src/Module/AllFriends.php
  src/Module/Feed.php
Labels: Enhancement

#7072 Move mod/directory to src/Module/Directory
  mod/directory.php
  src/App/Router.php
  src/Model/Profile.php
  src/Module/Directory.php
Labels: Enhancement

#7071 Move mod/bookmarklet to src/Module/BookMarklet
  mod/bookmarklet.php
  src/App/Router.php
  src/Module/BookMarklet.php
Labels: Enhancement

#7076 Fix Proxy module routes
  src/App/Router.php
  view/templates/exception.tpl
Labels: Bug

#7000 Remove probing in magic link construction
  src/Model/Contact.php
Labels: Enhancement, Performance

#7077 Move mod/nogroup to src/Module/Group
  mod/nogroup.php
  src/App/Router.php
  src/Module/Group.php
Labels: Enhancement

#7078 Move mod/fetch to src/Module/Diaspora/Fetch
  mod/fetch.php
  src/App/Router.php
  src/Core/System.php
  src/Module/Diaspora/Fetch.php
Labels: Enhancement, Federation

#7085 Move mod/home to src/Module/Home
  mod/home.php
  src/App/Router.php
  src/Module/Home.php
  view/templates/home.tpl
Labels: Bug, Enhancement

#7088 Move mod/invite to src/Module/Invite
  mod/invite.php
  src/App/Router.php
  src/Module/Invite.php
Labels: Enhancement

#7089 Move mod/help to src/Module/Help
  mod/help.php
  src/App/Router.php
  src/Module/Help.php
Labels: Enhancement

#7090 Move mod/like to src/Module/Like
  mod/like.php
  src/App/Router.php
  src/Module/Like.php
Labels: Enhancement

#7091 Move mod/rsd_xml to src/Module/ReallySimpleDiscovery
  mod/rsd_xml.php
  src/App/Router.php
  src/Module/ReallySimpleDiscovery.php
  view/templates/rsd.tpl
Labels: Enhancement

#7093 Bugfixing Home
  src/Module/Home.php
Labels: Bug

#7096 Fixes notices
  src/Model/Contact.php
  src/Model/Item.php
Labels: Bug, Federation

#7098 Fixes "parent-guid" notice - finally
  src/Model/Item.php
Labels: Bug

#7099 Move mod/modexp to src/Module/PublicRSAKey
  mod/modexp.php
  src/App/Router.php
  src/Module/PublicRSAKey.php
Labels: Enhancement

#7083 Move mod/friendica to src/Module/Friendica
  mod/friendica.php
  src/App/Router.php
  src/Model/User.php
  src/Module/Friendica.php
  view/templates/feedtest.tpl
  view/templates/friendica.tpl
Labels: Enhancement

#7100 Move mod/robots_txt to src/Module/RobotsTxt
  mod/robots_txt.php
  src/App/Router.php
  src/Module/RobotsTxt.php
Labels: Enhancement

#7097 Fixings for Mod-Refactorings
  src/App/Router.php
  src/Model/Contact.php
  src/Model/Profile.php
  src/Module/Bookmarklet.php
  src/Module/ReallySimpleDiscovery.php
  view/templates/rsd.tpl
Labels: Bug, Enhancement

#7101 Move mod/viewsrc to src/Module/ItemBody
  mod/viewsrc.php
  src/App/Router.php
  src/Module/ItemBody.php
Labels: Enhancement

#7102 Move mod/pretheme to src/Module/ThemeDetails
  mod/pretheme.php
  src/App/Router.php
  src/Module/ThemeDetails.php
Labels: Enhancement

#7086 Move mod/maintenance to src/Module/Maintenance
  mod/maintenance.php
  src/App.php
  src/App/Router.php
  src/Core/System.php
  src/Module/Maintenance.php
  src/Network/HTTPException/ServiceUnavailableException.php
Labels: Bug, Enhancement

#7084 Move mod/filerm to src/Module/Filer/RemoveTag
  mod/filerm.php
  src/App/Router.php
  src/Module/Filer/RemoveTag.php
  src/Module/Filer/SaveTag.php
Labels: Enhancement

#7092 Add style to exception page
  images/friendica-404_svg_flexy-o-hare.png
  images/friendica-404_svg_hare-bottom-light-inside.png
  src/Module/Special/HTTPException.php
  view/global.css
  view/templates/exception.tpl
  view/theme/frio/css/style.css
Labels: Enhancement, UI/Theme

#7103 Move mod/smilies to src/Module/Smilies
  mod/smilies.php
  src/App/Router.php
  src/Module/Smilies.php
  view/templates/smilies.tpl
Labels: Enhancement

#7107 Fix contact/group routes
  src/App/Router.php
  src/Module/Contact.php
Labels: Bug

#7108 Remove remaining disallowed vertical bar in Router
  src/App/Router.php
Labels: Bug

#7111 remove superfluous tpl action
  view/templates/admin/logs/settings.tpl
Labels: Bug

#7104 The follow confirmation process is now separated
  mod/dfrn_confirm.php
  mod/notifications.php
  src/App/Router.php
  src/Model/Contact.php
  src/Module/FollowConfirm.php
  view/templates/intros.tpl
  view/theme/frio/templates/intros.tpl
Labels: Enhancement, Federation

#7113 Update every AP contact once a week
  src/Worker/Cron.php
Labels: Enhancement, Federation

#7114 Make 7113 really work - now the query does contain AP
  src/Worker/Cron.php
Labels: Bug

#7115 Add contact/batch route
  src/App/Router.php
  src/Module/Contact.php
Labels: Bug

#7122 Improve addon documentation
  doc/Addons.md
Labels: Addons, Docs, Enhancement

#7116 Improve addon admin
  src/Core/Addon.php
  src/Module/Admin/Addons/Details.php
Labels: Enhancement, UX

#7124 Mail: Set the "reply" value when it is a reply
  src/Model/Mail.php
Labels: Enhancement, Federation

#7125 Magic links should work again
  src/Model/Contact.php
Labels: Bug

#7126 make the addon listing in the admin panel aside working again
  view/templates/admin/aside.tpl
Labels: Bug, UI/Theme

#7127 pwdreset templated fixed HTML escaping
  view/templates/pwdreset.tpl
Labels: Bug, UI/Theme

#7129 Contacts with protocol = AP are now delivered only via AP
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#7133 IT translations update THX Sylke Vicious
  view/lang/it/messages.po
  view/lang/it/strings.php
Labels: Translation

#7137 Don't attach images to the body if it was from a Friendica system
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation

#7136 Missing basepath fix
  src/App.php
  src/Module/Admin/Summary.php
Labels: Bug

#7135 Add native two-factor authentication support
  INSTALL.md
  composer.json
  composer.lock
  config/dbstructure.config.php
  doc/Install.md
  doc/Two-Factor-Authentication.md
  doc/de/Install.md
  include/api.php
  mod/manage.php
  mod/openid.php
  mod/settings.php
  src/App/Router.php
  src/Core/Authentication.php
  src/Core/Session.php
  src/Database/DBA.php
  src/Model/TwoFactorRecoveryCode.php
  src/Module/BaseSettingsModule.php
  src/Module/Help.php
  src/Module/Login.php
  src/Module/Settings/TwoFactor/Index.php
  src/Module/Settings/TwoFactor/Recovery.php
  src/Module/Settings/TwoFactor/Verify.php
  src/Module/TwoFactor/Recovery.php
  src/Module/TwoFactor/Verify.php
  view/templates/settings/twofactor/index.tpl
  view/templates/settings/twofactor/recovery.tpl
  view/templates/settings/twofactor/verify.tpl
  view/templates/twofactor/recovery.tpl
  view/templates/twofactor/verify.tpl
Labels: New Feature, Security

#7139 Sending direct messages via AP does work now - receiving is pending
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Util/JsonLD.php
  src/Worker/APDelivery.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#7143 Update paths to images in README.md
  README.md
Labels: Docs, Enhancement

#7144 Exclude /api and /proxy from 2fa check
  src/Core/Authentication.php
  view/lang/C/messages.po
Labels: Enhancement, Translation

#7146 AP: We can now receive "direct messages" (aka "mails") as well
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement, Federation

#7149 CS translation update THX Aditoo
  view/lang/cs/messages.po
  view/lang/cs/strings.php
Labels: Translation

#7148 Allow null $tags parameter in ActivityPub\Processor::constructTagString
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#7147 Fix database structure definition, primary keys must be marked as this
  config/dbstructure.config.php
Labels: Enhancement

#7151 Make AP "direct messages" more compatible to Mastodon
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#7152 Fix for receiving direct messages from Mastodon
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, Federation

#7153 Fix receiver list for mails
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/Notifier.php
Labels: Bug, Federation

#7155 Move mod/opensearch to src/Module/OpenSearch
  mod/opensearch.php
  src/App/Router.php
  src/Module/OpenSearch.php
  view/templates/opensearch.tpl
Labels: Enhancement

#7158 Replace htmlspecialchars_decode with html_entity_decode in XML::unescape
  src/Util/XML.php
Labels: Bug, Federation

#7157 Move mod/notify to src/Module/Notify
  mod/notify.php
  src/App/Router.php
  src/Module/Notifications/Notify.php
Labels: Enhancement

#7161 Move mod/toggle_mobile to src/Module/ToggleMobile
  mod/toggle_mobile.php
  src/App/Router.php
  src/Module/ToggleMobile.php
Labels: Enhancement

#7162 Move mod/view to src/Module/Theme
  mod/view.php
  src/App/Router.php
  src/Module/Theme.php
Labels: Enhancement

#7164 Move mod/randprof to src/Module/RandomProfile
  mod/randprof.php
  src/App/Router.php
  src/Database/DBA.php
  src/Model/GContact.php
  src/Module/RandomProfile.php
Labels: Enhancement

#7163 Move mod/starred to src/Module/Starred
  mod/starred.php
  src/App/Router.php
  src/Module/Starred.php
Labels: Enhancement

#7159 Move mod/notice to src/Module/Notice
  mod/notice.php
  src/App/Router.php
  src/Module/GnuSocial/Notice.php
Labels: Enhancement

#7154 Refactor widgets
  mod/cal.php
  mod/common.php
  mod/photos.php
  mod/videos.php
  src/App/Router.php
  src/Content/Widget.php
  src/Content/Widget/CalendarExport.php
  src/Content/Widget/ContactBlock.php
  src/Content/Widget/TagCloud.php
  src/Module/Contact.php
  view/templates/categories_widget.tpl
  view/templates/contacts-widget-sidebar.tpl
  view/templates/fileas_widget.tpl
  view/templates/nets.tpl
  view/templates/widget/contacts.tpl
  view/templates/widget/events.tpl
  view/templates/widget/filter.tpl
  view/templates/widget/follow.tpl
  view/templates/widget/peoplefind.tpl
  view/templates/widget/remote_friends_common.tpl
  view/templates/widget/tagcloud.tpl
  view/templates/widget/vcard.tpl
  view/theme/duepuntozero/deriv/darkzero.css
  view/theme/duepuntozero/deriv/slackr.css
  view/theme/duepuntozero/style.css
  view/theme/frio/templates/fileas_widget.tpl
  view/theme/frio/templates/nets.tpl
  view/theme/frio/templates/widget/contacts.tpl
  view/theme/frio/templates/widget/follow.tpl
  view/theme/frio/templates/widget/peoplefind.tpl
  view/theme/frio/templates/widget/vcard.tpl
  view/theme/quattro/templates/fileas_widget.tpl
  view/theme/quattro/templates/nets.tpl
  view/theme/quattro/templates/widget/filter.tpl
  view/theme/smoothly/style.css
  view/theme/smoothly/templates/widget/follow.tpl
  view/theme/vier/style.css
  view/theme/vier/templates/communityhome.tpl
Labels: Enhancement

#7168 Suggestions can be processed again
  src/Protocol/DFRN.php
Labels: Bug

#7169 Sending contact suggestions does work again
  mod/fsuggest.php
  src/Worker/Delivery.php
Labels: Bug

#7160 Move mod/probe to src/Module/Probe
  mod/probe.php
  src/App/Router.php
  src/Module/Debug/Babel.php
  src/Module/Debug/Feed.php
  src/Module/Debug/ItemBody.php
  src/Module/Debug/Localtime.php
  src/Module/Debug/Probe.php
  src/Module/Debug/WebFinger.php
  src/Module/Itemsource.php
  view/templates/probe.tpl
Labels: Enhancement

#7167 Add Unicode support to autolink regular expression
  src/Module/Debug/Babel.php
  src/Util/Strings.php
  tests/src/Content/Text/BBCodeTest.php
Labels: Bug, Federation

#7173 Move mod/newmember to src/Module/Welcome
  mod/newmember.php
  src/App/Router.php
  src/Module/Welcome.php
  view/templates/welcome.tpl
Labels: Enhancement

#7165 Move mod/dirfind to src/Module/Search/Directory
  mod/dirfind.php
  mod/search.php
  src/App/Router.php
  src/Core/Search.php
  src/Database/DBA.php
  src/Module/BaseSearchModule.php
  src/Module/Search/Directory.php
  src/Object/Search/ContactResult.php
  src/Object/Search/IResult.php
  src/Object/Search/ResultList.php
Labels: Bug, Enhancement

#7175 Fix table name sanitation / enable table schemes
  src/Database/DBA.php
Labels: Bug, Security

#7177 Fix SQL error in Module\Admin\Summary
  src/Module/Admin/Summary.php
Labels: Bug

#7179 Fix typo in Module\Contact
  src/Module/Contact.php
Labels: Bug

#7180 Ensures Search methods return an empty ResultList instead of null
  src/Core/Search.php
  src/Module/BaseSearchModule.php
Labels: Bug

#7181 Update FAQ.md
  doc/FAQ.md
Labels: Docs

#7156 Add contact relationship filter
  mod/cal.php
  mod/events.php
  mod/notes.php
  mod/photos.php
  mod/videos.php
  mod/viewcontacts.php
  src/App/Router.php
  src/Content/Widget.php
  src/Content/Widget/ContactBlock.php
  src/Model/Profile.php
  src/Module/Contact.php
  src/Module/Profile.php
  src/Module/Profile/Contacts.php
  src/Protocol/OStatus.php
  view/templates/profile/contacts.tpl
  view/theme/duepuntozero/style.css
  view/theme/frio/css/style.css
  view/theme/frio/templates/profile/contacts.tpl
  view/theme/smoothly/style.css
Labels: New Feature, UI/Theme, UX

#7170 Contact requests blocked
  include/api.php
  src/Model/Contact.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/OStatus.php
  src/Util/JsonLD.php
Labels: Bug, Federation, UX

#7184 AP: We now transmit "add tag" activity
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#7186 Restore profile archives widget
  include/items.php
  mod/network.php
  src/App/Router.php
  src/Content/Widget.php
  src/Module/Profile.php
  view/templates/widget/posted_date.tpl
Labels: Bug

#7189 Ensures Widget::postedByYear uid parameter is integer in Module\Profile
  src/Module/Profile.php
Labels: Bug

#7191 Fixing logfile permission denied exceptions
  src/Factory/LoggerFactory.php
  src/Module/Admin/Logs/Settings.php
  src/Module/Admin/Summary.php
Labels: Bug

#7192 Make edits of images possible again
  mod/photos.php
Labels: Bug

#7194 frio: Fix hovercard vanish
  composer.json
  composer.lock
  view/templates/head.tpl
  view/theme/frio/js/hovercard.js
  view/theme/frio/js/mod_events.js
  view/theme/frio/js/theme.js
  view/theme/frio/templates/head.tpl
Labels: Bug, UI/Theme, UX

#7195 Remove defaults() from $_SESSION
  boot.php
  include/conversation.php
  mod/network.php
  mod/settings.php
  src/App.php
  src/Content/Nav.php
  src/Core/Session.php
  src/Module/Login.php
  src/Module/Profile.php
  src/Object/Post.php
  view/theme/frio/theme.php
Labels: Enhancement

#7193 Fix NULL datetime for uimport/uexport
  mod/uexport.php
  src/Core/UserImport.php
Labels: Bug

#7197 [API] Convert user description to plain text
  include/api.php
Labels: Bug

#7198 Simplify BBCode::toPlaintext and HTML::toPlaintext
  src/Content/Text/BBCode.php
  src/Content/Text/HTML.php
  src/Module/Debug/Babel.php
Labels: Enhancement

#7187 Enable addon using emailer hooks to skip default call to mail()
  doc/Addons.md
  src/Util/Emailer.php
Labels: Addons, Enhancement

#7200 Process incoming tag add requests
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement, Federation

#7201 Fix Issue 7196
  src/Model/Mail.php
Labels: Bug

#7205 Fix "Undefined index: protocol"
  src/Protocol/Diaspora.php
Labels: Bug

#7199 Allow commas in saved folder names
  boot.php
  include/text.php
  mod/item.php
  mod/network.php
  src/App.php
  src/Content/ForumManager.php
  src/Content/Widget.php
  src/Model/FileTag.php
  src/Module/Filer/RemoveTag.php
  src/Module/Filer/SaveTag.php
  tests/src/Model/FileTagTest.php
  view/templates/saved_searches_aside.tpl
  view/theme/frio/templates/saved_searches_aside.tpl
  view/theme/quattro/templates/saved_searches_aside.tpl
  view/theme/vier/theme.php
Labels: Bug, UX

#7204 Check for array index existence
  src/Protocol/PortableContact.php
Labels: Bug

#7202 Prevent fatal error in ACL::getFullSelectorHTML when accessing a profile as a remote visitor
  src/Core/ACL.php
Labels: Bug

#7203 Fix condition in dfrn_request_content() when $a->profile isn't set
  mod/dfrn_request.php
Labels: Bug

#7206 Fixing PHP Notices
  mod/notifications.php
  mod/photos.php
  mod/redir.php
  src/Model/Item.php
  src/Module/Admin/Federation.php
Labels: Bug

#7207 Add hexadecimal check (fix warnings)
  mod/parse_url.php
  mod/photos.php
  src/Util/Strings.php
  tests/src/Util/StringsTest.php
Labels: Bug

#7210 Fix edited messages for Diaspora
  src/Protocol/Diaspora.php
Labels: Enhancement, Federation

#7208 Adding null checks before FileTag method (fix fatal)
  include/text.php
  mod/item.php
  src/Model/FileTag.php
  src/Module/Filer/SaveTag.php
Labels: Bug

#7211 Add themed themed error page or login page for /admin[/*]
  src/Module/BaseAdminModule.php
  view/lang/C/messages.po
Labels: Bug, UX
