Repository friendica/friendica, pull requests merged in 2019-10, with the labels that each got.

#7684 Critical Fix: Inbox needs to be accessed via POST
  static/routes.config.php
Labels: Bug

#7689 Fix notice "Undefined index: openRegistrations"
  src/Protocol/PortableContact.php
Labels: Bug

#7692 add option 'require' for textarea form elements
  doc/smarty3-templates.md
  src/Module/Register.php
  view/templates/field_textarea.tpl
Labels: Enhancement, UI

#7687 Enable the possibility to fetch a specific header variable
  src/Network/CurlResult.php
  tests/src/Network/CurlResultTest.php
Labels: Enhancement

#7693 Remove obsolete function to guess the base url of a contact
  src/Model/GContact.php
  src/Protocol/PortableContact.php
  src/Worker/DiscoverPoCo.php
Labels: Enhancement

#7703 modified Vagrant devel VM (PHP 7.3, proper composer)
  Vagrantfile
  bin/dev/vagrant_provision.sh
Labels: Enhancement

#7699 Move mod/acl to src/Module/Search/Acl
  mod/acl.php
  src/Core/ACL.php
  src/Core/Search.php
  src/Module/Search/Acl.php
  static/routes.config.php
  view/js/main.js
  view/templates/acl_selector.tpl
  view/templates/contacts-head.tpl
  view/templates/display-head.tpl
  view/templates/item/compose-footer.tpl
  view/templates/jot-header.tpl
  view/templates/message-head.tpl
  view/templates/msg-header.tpl
  view/templates/poke_head.tpl
  view/templates/wallmsg-header.tpl
  view/theme/frio/js/event_edit.js
  view/theme/frio/templates/acl_selector.tpl
  view/theme/frio/templates/jot-header.tpl
  view/theme/frio/templates/msg-header.tpl
  view/theme/frio/templates/nav_head.tpl
  view/theme/smoothly/templates/jot-header.tpl
  view/theme/vier/templates/nav_head.tpl
Labels: Enhancement

#7705 CS translation update THX Aditoo
  view/lang/cs/messages.po
  view/lang/cs/strings.php
Labels: Translation

#7704 Replace obsolete functionality in "PortableContact"
  src/Model/GContact.php
  src/Model/GServer.php
  src/Protocol/PortableContact.php
  src/Worker/CronJobs.php
  src/Worker/DiscoverPoCo.php
  src/Worker/GProbe.php
Labels: Enhancement

#7706 add server side check about note to admin
  src/Module/Register.php
Labels: Enhancement

#7708 [vier] Add necessary required_once statement in theme/vier/config.php
  view/theme/vier/config.php
Labels: Bug

#7711 Fix for multiline host-meta, reducement of requests, fix for wordpress
  src/Model/GServer.php
Labels: Enhancement

#7712 Some added logging to the proxy functionality to better analyze problems
  src/Module/Proxy.php
Labels: Enhancement

#7713 Fix communication issues with systems that speak both AP and Diaspora
  src/Worker/Delivery.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#7710 Rework theme session variables
  include/api.php
  mod/community.php
  mod/manage.php
  mod/search.php
  mod/uimport.php
  src/App.php
  src/App/Module.php
  src/App/Page.php
  src/Core/Session.php
  src/Model/Profile.php
  src/Module/Directory.php
  src/Module/Home.php
  src/Module/Login.php
  src/Module/Register.php
  src/Network/FKOAuth1.php
Labels: Enhancement

#7714 Move mod/search to src/Module/Search/Index
  mod/network.php
  mod/search.php
  src/BaseModule.php
  src/Content/Text/HTML.php
  src/Content/Widget/SavedSearches.php
  src/Module/BaseSearchModule.php
  src/Module/Search/Directory.php
  src/Module/Search/Index.php
  src/Module/Search/Saved.php
  static/routes.config.php
  view/templates/saved_searches_aside.tpl
  view/templates/searchbox.tpl
  view/templates/widget/saved_searches.tpl
  view/theme/frio/templates/nav.tpl
  view/theme/frio/templates/saved_searches_aside.tpl
  view/theme/frio/templates/searchbox.tpl
  view/theme/frio/templates/widget/saved_searches.tpl
  view/theme/quattro/templates/saved_searches_aside.tpl
  view/theme/quattro/templates/widget/saved_searches.tpl
  view/theme/vier/templates/nav.tpl
Labels: Enhancement

#7715 The getGUID function hadn't fetched the GUID from pictures with scale "0"
  src/Model/Photo.php
Labels: Bug

#7723 Complete L10n::detectLanguage call parameters in Module\Register
  mod/subthread.php
  src/Module/Register.php
Labels: Bug

#7725 Fix security vulnerabilities.
  library/OAuth1.php
  mod/lostpass.php
  src/Core/Authentication.php
  src/Model/Register.php
  src/Model/User.php
  src/Module/Login.php
  src/Network/FKOAuthDataStore.php
  src/Util/Strings.php
  tests/src/Util/StringsTest.php
Labels: Enhancement, Security

#7729 Fix typo in Core\Authentication
  src/Core/Authentication.php
Labels: Bug

#7730 Strings.php: Spaces are transformed to Tabs
  src/Util/Strings.php
  tests/src/Util/StringsTest.php
Labels: Bug

#7735 Replace deprecated defaults() calls in include/api and boot
  boot.php
  include/api.php
Labels: Enhancement

#7734 Catch missing Certainty bundle exception when checking for exposed password
  src/Core/Logger.php
  src/Model/User.php
Labels: Bug, UX

#7737 Saved Search fixes
  src/Content/Text/HTML.php
  src/Module/Search/Index.php
  src/Module/Search/Saved.php
  static/routes.config.php
  view/templates/searchbox.tpl
  view/templates/widget/saved_searches.tpl
  view/theme/frio/css/style.css
  view/theme/frio/js/theme.js
  view/theme/frio/templates/nav.tpl
  view/theme/frio/templates/searchbox.tpl
  view/theme/frio/templates/widget/saved_searches.tpl
  view/theme/quattro/templates/widget/saved_searches.tpl
Labels: Bug

#7727 Move mod/manage to src/Module/Delegation
  doc/Addons.md
  doc/de/Addons.md
  mod/manage.php
  src/App/Module.php
  src/App/Router.php
  src/Content/Nav.php
  src/Module/Delegation.php
  src/Module/HTTPException/MethodNotAllowed.php
  src/Module/HTTPException/PageNotFound.php
  static/routes.config.php
  tests/src/App/ModuleTest.php
  tests/src/App/RouterTest.php
  view/templates/delegation.tpl
  view/templates/manage.tpl
  view/templates/nav.tpl
  view/theme/duepuntozero/style.css
  view/theme/duepuntozero/templates/nav.tpl
  view/theme/frio/css/style.css
  view/theme/frio/templates/nav.tpl
  view/theme/quattro/dark/style.css
  view/theme/quattro/green/style.css
  view/theme/quattro/lilac/style.css
  view/theme/quattro/quattro.less
  view/theme/quattro/templates/nav.tpl
  view/theme/smoothly/style.css
  view/theme/smoothly/templates/nav.tpl
  view/theme/vier/plus.css
  view/theme/vier/plusminus.css
  view/theme/vier/style.css
  view/theme/vier/templates/nav.tpl
  view/theme/vier/theme.php
Labels: Enhancement

#7738 Convert links with empty descriptions
  mod/item.php
Labels: Enhancement, UX

#7728 Discriminate between links and non-links in [url] BBCode tag insertion
  view/js/linkPreview.js
  view/js/main.js
  view/theme/duepuntozero/theme.php
  view/theme/frio/js/textedit.js
  view/theme/quattro/js/quattro.js
  view/theme/smoothly/templates/bottom.tpl
  view/theme/smoothly/theme.php
  view/theme/vier/theme.php
Labels: Enhancement, UX

#7741 Changed quotation (" to ')
  src/Content/Text/BBCode.php
Labels: Enhancement

#7742 Replace deprecated defaults() calls by a combination of ?? and ?: operators in mod/
  mod/cal.php
  mod/common.php
  mod/crepair.php
  mod/dfrn_confirm.php
  mod/dfrn_notify.php
  mod/dfrn_poll.php
  mod/dfrn_request.php
  mod/display.php
  mod/events.php
  mod/fbrowser.php
  mod/follow.php
  mod/fsuggest.php
  mod/hcard.php
  mod/hovercard.php
  mod/ignored.php
  mod/item.php
  mod/match.php
  mod/message.php
  mod/msearch.php
  mod/network.php
  mod/noscrape.php
  mod/notifications.php
  mod/photos.php
  mod/poco.php
  mod/pubsub.php
  mod/redir.php
  mod/regmod.php
  mod/settings.php
  mod/tagrm.php
  mod/unfollow.php
  mod/videos.php
  mod/wallmessage.php
Labels: Enhancement

#7743 Replace deprecated defaults() calls by ?? and ?: operators in src/Module/
  src/Module/Acctlink.php
  src/Module/Admin/Addons/Details.php
  src/Module/Admin/Addons/Index.php
  src/Module/Admin/Blocklist/Contact.php
  src/Module/Admin/Logs/Settings.php
  src/Module/Admin/Site.php
  src/Module/Admin/Themes/Index.php
  src/Module/Admin/Users.php
  src/Module/AllFriends.php
  src/Module/Bookmarklet.php
  src/Module/Contact.php
  src/Module/Debug/Babel.php
  src/Module/Debug/Feed.php
  src/Module/Debug/Localtime.php
  src/Module/Debug/Probe.php
  src/Module/Debug/WebFinger.php
  src/Module/Feed.php
  src/Module/Filer/RemoveTag.php
  src/Module/Filer/SaveTag.php
  src/Module/FollowConfirm.php
  src/Module/Followers.php
  src/Module/Following.php
  src/Module/Install.php
  src/Module/Like.php
  src/Module/Login.php
  src/Module/Magic.php
  src/Module/Outbox.php
  src/Module/Profile.php
  src/Module/Profile/Contacts.php
  src/Module/Proxy.php
  src/Module/Register.php
  src/Module/Search/Acl.php
  src/Module/Settings/TwoFactor/Index.php
  src/Module/Settings/TwoFactor/Verify.php
  src/Module/Smilies.php
  src/Module/Special/HTTPException.php
  src/Module/Starred.php
  src/Module/ThemeDetails.php
  src/Module/TwoFactor/Recovery.php
  src/Module/Xrd.php
Labels: Enhancement

#7746 Clarify quotation style in doc/Developers-Intro
  doc/Developers-Intro.md
Labels: Docs, Enhancement

#7748 Prevent empty [url] label regular expression to break image insertion
  mod/item.php
Labels: Bug, UX

#7744 Replace deprecated calls to defaults() by ?? and ?: in src/
  src/App/Arguments.php
  src/App/BaseURL.php
  src/BaseObject.php
  src/Content/Pager.php
  src/Content/Text/BBCode.php
  src/Content/Text/HTML.php
  src/Content/Widget/CalendarExport.php
  src/Content/Widget/ContactBlock.php
  src/Core/ACL.php
  src/Core/Authentication.php
  src/Core/Config/Configuration.php
  src/Core/Config/PConfiguration.php
  src/Core/NotificationsManager.php
  src/Core/Renderer.php
  src/Core/Search.php
  src/Core/Session.php
  src/Core/StorageManager.php
  src/Database/DBStructure.php
  src/Model/Contact.php
  src/Model/Conversation.php
  src/Model/Event.php
  src/Model/GContact.php
  src/Model/GServer.php
  src/Model/Item.php
  src/Model/ItemContent.php
  src/Model/PermissionSet.php
  src/Model/Profile.php
  src/Model/Storage/Filesystem.php
  src/Model/Term.php
  src/Network/CurlResult.php
  src/Network/Probe.php
  src/Object/Post.php
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/DFRN.php
  src/Protocol/Email.php
  src/Protocol/OStatus.php
  src/Util/Emailer.php
  src/Util/Logger/SyslogLogger.php
  src/Util/Network.php
  src/Util/ParseUrl.php
  src/Util/Profiler.php
  src/Worker/Delivery.php
  src/Worker/GProbe.php
Labels: Enhancement

#7750 Remove remaining Logger log level in explicit Logger::debug call
  src/Worker/Delivery.php
Labels: Bug

#7745 Remove deprecated defaults() function
  boot.php
  include/api.php
  include/conversation.php
  include/enotify.php
  include/items.php
  view/theme/duepuntozero/style.php
  view/theme/frio/config.php
  view/theme/frio/php/default.php
  view/theme/frio/php/frio_boot.php
  view/theme/quattro/style.php
  view/theme/vier/style.php
  view/theme/vier/theme.php
Labels: Enhancement

#7752 Change Model type to `OrderedCollectionPage`
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#7754 Some improvements for accessibility - I hope
  view/theme/frio/php/minimal.php
  view/theme/frio/php/standard.php
  view/theme/frio/templates/field_checkbox.tpl
  view/theme/frio/templates/footer.tpl
  view/theme/frio/templates/nav.tpl
Labels: Enhancement, UX

#7753 Handling for HTTP Error code 417
  src/Util/Network.php
Labels: Enhancement

#7757 Reworked gcontact
  src/Model/GContact.php
Labels: Enhancement

#7760 Fix fatal error
  src/Model/GContact.php
Labels: Bug

#7759 Move mod/receive to src/Module/Diaspora/receive
  mod/dfrn_notify.php
  mod/receive.php
  src/Model/User.php
  src/Module/Diaspora/Receive.php
  src/Protocol/Diaspora.php
  static/routes.config.php
Labels: Enhancement

#7763 Add Fallback in case the logfile isn't accessible.
  src/Factory/LoggerFactory.php
  src/Module/Admin/Summary.php
  src/Util/FileSystem.php
  src/Util/Logger/StreamLogger.php
  tests/src/Util/Logger/StreamLoggerTest.php
Labels: Bug

#7765 Move include/text.php to class structure
  composer.json
  doc/Addons.md
  doc/de/Addons.md
  include/conversation.php
  include/text.php
  mod/editpost.php
  mod/events.php
  mod/item.php
  mod/lockview.php
  mod/network.php
  mod/photos.php
  mod/settings.php
  src/BaseObject.php
  src/Content/Item.php
  src/Content/Text/BBCode/Video.php
  src/Model/Event.php
  src/Model/Item.php
  src/Model/Profile.php
  src/Module/Item/Compose.php
  src/Module/Profile.php
  src/Object/Post.php
  src/Protocol/Activity.php
  src/Protocol/DFRN.php
  src/Util/ACLFormatter.php
  src/Util/DateTimeFormat.php
  src/Worker/Notifier.php
  tests/src/Content/ItemTest.php
  tests/src/Content/Text/BBCode/VideoTest.php
  tests/src/Core/InstallerTest.php
  tests/src/Protocol/ActivityTest.php
  tests/src/Util/ACLFormaterTest.php
  tests/src/Util/DateTimeFormatTest.php
Labels: Enhancement

#7762 move mod/ignored to src/Module/Item/Ignored
  mod/ignored.php
  src/Module/Item/Ignore.php
  static/routes.config.php
  view/js/main.js
Labels: Enhancement

#7768 [composer] Downgrade dependencies
  composer.json
  composer.lock
Labels: Bug

#7770 Move Activity definitions to constants
  boot.php
  include/api.php
  include/conversation.php
  include/enotify.php
  mod/dfrn_confirm.php
  mod/dfrn_request.php
  mod/item.php
  mod/photos.php
  mod/poke.php
  mod/salmon.php
  mod/subthread.php
  mod/tagger.php
  src/Content/Text/BBCode.php
  src/Core/NotificationsManager.php
  src/Model/Contact.php
  src/Model/Event.php
  src/Model/Item.php
  src/Model/Mail.php
  src/Model/Profile.php
  src/Module/Diaspora/Receive.php
  src/Module/Xrd.php
  src/Network/Probe.php
  src/Object/Post.php
  src/Object/Thread.php
  src/Protocol/Activity.php
  src/Protocol/Activity/ObjectType.php
  src/Protocol/ActivityNamespace.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  src/Worker/OnePoll.php
  tests/src/Protocol/ActivityTest.php
Labels: Docs, Enhancement

#7767 Expect outbox->first to be a Link structure in Model\GContact
  src/Model/GContact.php
Labels: Bug, Federation

#7774 Images: Show the description as title
  src/Content/Text/BBCode.php
Labels: Enhancement, UX

#7775 Move Core\NotificationsManager to Model\Notify
  include/api.php
  mod/notifications.php
  src/Core/NotificationsManager.php
  src/Model/Notify.php
  src/Module/Notifications/Notify.php
Labels: Enhancement

#7780 Wrong condition for home notifications
  src/Model/Notify.php
Labels: Bug

#7782 Check null for acl-fields
  database.sql
  mod/lockview.php
  src/Model/Item.php
  src/Module/Item/Compose.php
  src/Worker/Notifier.php
  static/dbstructure.config.php
  tests/src/Util/ACLFormaterTest.php
Labels: Bug

#7784 Revert "Add not null/default value for ACL in fields"
  database.sql
  static/dbstructure.config.php
Labels: Bug

#7786 [Drone.io] Add node info for better routing
  .drone.yml
Labels: Enhancement

#7783 Fix travis - Remove APCu setting for PHP 7.2/7.3
  .travis.yml
Labels: Bug

#7769 Changed OpenID registration
  mod/openid.php
  mod/settings.php
  src/Model/User.php
  src/Module/Login.php
  view/templates/field_openid.tpl
  view/templates/login.tpl
  view/theme/frio/templates/field_openid.tpl
  view/theme/frio/templates/login.tpl
  view/theme/frio/templates/settings/settings.tpl
Labels: Bug, Enhancement, Federation

#7789 Solve warning
  src/Worker/Notifier.php
Labels: Bug
