Repository friendica/friendica, pull requests merged in 2020-07, with the labels that each got.

#8835 PL and EN US / GB translation updates
  view/lang/en-gb/messages.po
  view/lang/en-gb/strings.php
  view/lang/en-us/messages.po
  view/lang/en-us/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#8837 Add expected support for sort strings in select() parameters
  src/Database/DBA.php
  src/Database/Database.php
Labels: Bug

#8842 Bug/warnings
  mod/item.php
Labels: Bug

#8841 Add support for "hs2019" algorithm value in Util\HTTPSignature
  src/Util/HTTPSignature.php
Labels: Enhancement, Federation

#8850 Issue 8844: Rework "follow" to fix probing issues
  mod/follow.php
Labels: Bug, Federation

#8849 Rename -q option to -y for user delete console command
  src/Console/User.php
  src/Model/User.php
Labels: Enhancement

#8851 Issue 8844: Fix probing of unknown AP contacts
  src/Network/Probe.php
Labels: Bug

#8852 Address various notices
  src/Content/Nav.php
  src/Module/Profile/Status.php
  src/Module/Xrd.php
Labels: Bug

#8853 Issue 8836: Point the event to the local post
  src/Model/Event.php
  view/templates/event.tpl
  view/theme/frio/templates/event.tpl
Labels: Bug, Calendar, UX

#8855 Fix the plink for reshared Diaspora posts
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#8854 Address various notices again
  include/api.php
  mod/cal.php
  mod/photos.php
  src/App/Page.php
  src/BaseModule.php
  src/Model/UserItem.php
  src/Module/HoverCard.php
  view/theme/frio/theme.php
  view/theme/vier/theme.php
Labels: Bug

#8856 Fix speed issues with the network page
  src/Content/Item.php
  src/Model/Item.php
  static/dbstructure.config.php
Labels: Enhancement, Performance

#8859 Fix unneeded database functions in the callstack
  src/Core/System.php
Labels: Enhancement

#8858 Issue 8857: Fix follow accept answers
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation

#8861 Fix message "empty network" in gcontact::getid
  src/Model/GContact.php
  src/Protocol/DFRN.php
Labels: Enhancement, Performance

#8863 Address various notices still
  mod/salmon.php
  src/Content/Nav.php
  src/Model/Contact.php
  src/Module/Diaspora/Fetch.php
  src/Module/Search/Acl.php
Labels: Bug

#8864 Don't check the date on regular feeds
  src/Protocol/OStatus.php
Labels: Bug, Federation

#8862 Issue 8860: Activities weren't fetchable all the time
  src/Module/Objects.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#8865 Feeds now validate
  src/Protocol/OStatus.php
Labels: Enhancement, Federation

#8812 credits for the 2020.06 release
  CREDITS.txt
Labels: Docs

#8867 Issue 8866: Fix fetching feed links with missing base
  src/Protocol/Feed.php
  src/Util/Network.php
Labels: Bug

#8819 2020.06 CHANGELOG
  CHANGELOG
Labels: Docs

#8870 Support Nodeinfo2
  src/Core/System.php
  src/Model/Nodeinfo.php
  src/Model/User.php
  src/Module/NodeInfo.php
  src/Module/NodeInfo110.php
  src/Module/NodeInfo120.php
  src/Module/NodeInfo210.php
  static/routes.config.php
Labels: Federation, New Feature

#8878 Suppress all emails when Update::run is ran with $sendEmail = false
  src/Core/Update.php
Labels: Bug

#8872 Update additional features
  mod/cal.php
  mod/network.php
  src/Content/Feature.php
  src/Content/Widget.php
  src/Content/Widget/CalendarExport.php
Labels: Enhancement, UX

#8880 Remove include/items.php
  composer.json
  doc/Addons.md
  doc/Message-Flow.md
  doc/de/Addons.md
  doc/de/Message-Flow.md
  include/items.php
  mod/item.php
  mod/parse_url.php
  mod/pubsub.php
  src/Module/Bookmarklet.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  src/Worker/Notifier.php
  src/Worker/OnePoll.php
Labels: Enhancement

#8883 Replaced "getDetailsByURL" with "getByURL/getByURLForUser"
  mod/common.php
  mod/display.php
  mod/editpost.php
  mod/follow.php
  mod/match.php
  mod/message.php
  mod/ping.php
  mod/suggest.php
  mod/unfollow.php
  src/Content/Item.php
  src/Content/Text/BBCode.php
  src/Content/Text/Markdown.php
  src/Core/Search.php
  src/Factory/Notification/Introduction.php
  src/Model/Contact.php
  src/Model/GContact.php
  src/Module/AllFriends.php
  src/Module/Contact.php
  src/Module/Contact/Advanced.php
  src/Module/Contact/Hovercard.php
  src/Module/Contact/Poke.php
  src/Module/Profile/Contacts.php
  src/Module/Search/Acl.php
  src/Module/Search/Index.php
  src/Object/Post.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Util/Profiler.php
Labels: Enhancement

#8879 Add support for token strings in HTTPSignature::parseSigheader
  src/Util/Crypto.php
  src/Util/HTTPSignature.php
  tests/src/Util/HTTPSignatureTest.php
Labels: Bug, Enhancement

#8887 Prevent "null" value when calling "getTagsFromUrl"
  src/Protocol/Feed.php
Labels: Bug

#8886 in "getidforurl" "no update" is now "update"
  boot.php
  include/api.php
  include/conversation.php
  mod/dfrn_request.php
  mod/display.php
  mod/match.php
  mod/ostatus_subscribe.php
  mod/suggest.php
  src/Content/Widget.php
  src/Core/Search.php
  src/Database/PostUpdate.php
  src/Model/Contact.php
  src/Model/GServer.php
  src/Model/Item.php
  src/Model/Mail.php
  src/Model/Tag.php
  src/Module/Acctlink.php
  src/Module/AllFriends.php
  src/Module/Debug/Feed.php
  src/Module/Profile/Contacts.php
  src/Module/RemoteFollow.php
  src/Module/Search/Index.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/OStatus.php
  src/Util/Profiler.php
  src/Worker/Notifier.php
  update.php
Labels: Enhancement

#8891 Replaced more calls of "Probe::uri" with "Contact::getByURL"
  src/Core/Search.php
  src/Protocol/OStatus.php
  src/Worker/SearchDirectory.php
Labels: Enhancement

#8892 Atom feed generation is moved to the feed class
  src/Module/Feed.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
Labels: Enhancement

#8894 Use PageInfo::appendDataToBody in ActivityPub\Processor::constructAttachList
  src/Content/PageInfo.php
  src/Module/Debug/Babel.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Util/ParseUrl.php
Labels: Enhancement, UX

#8893 Add shortened URL link label stripping to PageInfo::stripTrailingUrlFromBody
  src/Content/PageInfo.php
  src/Module/Debug/Babel.php
  tests/src/Content/PageInfoTest.php
  view/templates/babel.tpl
Labels: Enhancement, UX

#8895 Database performance updates
  mod/ping.php
  src/Database/Database.php
  src/Model/Item.php
  src/Worker/Cron.php
  static/dbstructure.config.php
Labels: Enhancement, Performance

#8898 Add some logging to SpoolPost.php
  src/Worker/SpoolPost.php
Labels: Enhancement

#8897 Support newline as block contact separator
  include/conversation.php
Labels: Enhancement, UX

#8899 Ensure to only store valid item fields
  src/Model/Item.php
Labels: Enhancement

#8901 New field in gserver, gcontact and contact for failed connections
  database.sql
  mod/poco.php
  src/Core/Search.php
  src/Model/Contact.php
  src/Model/GContact.php
  src/Model/GServer.php
  src/Model/Item.php
  src/Module/Admin/Federation.php
  src/Module/Api/Mastodon/Instance/Peers.php
  src/Object/Api/Mastodon/Stats.php
  src/Protocol/PortableContact.php
  src/Worker/OnePoll.php
  src/Worker/SearchDirectory.php
  static/dbstructure.config.php
  update.php
Labels: Enhancement, Performance

#8902 Fix wrong variable
  src/Worker/Notifier.php
Labels: Bug

#8905 Remove debug output
  src/Model/GServer.php
Labels: Bug

#8912 Posts with subscribed tags will now be stored for the user
  mod/network.php
  src/Model/Item.php
  src/Model/Tag.php
Labels: Enhancement, Performance

#8903 ActivityPub: Add support for multiple Link as urls of Images attachments
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, Federation

#8904 Add new admin debug module for ActivityPub
  src/Module/BaseAdmin.php
  src/Module/Debug/ActivityPubConversion.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  static/routes.config.php
  view/templates/debug/activitypubconversion.tpl
Labels: New Feature

#8913 Fix notice "Undefined index: parent-uri"
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#8915 Store personal copy of public item upon commenting
  mod/item.php
  src/Model/Item.php
Labels: Enhancement

#8917 Replace jquery-textcomplete with yuku/old-textcomplete
  composer.json
  composer.lock
  view/js/autocomplete.js
  view/js/jquery-textcomplete/CHANGELOG.md
  view/js/jquery-textcomplete/LICENSE
  view/js/jquery-textcomplete/README.md
  view/js/jquery-textcomplete/jquery.textcomplete.css
  view/js/jquery-textcomplete/jquery.textcomplete.js
  view/js/jquery-textcomplete/jquery.textcomplete.min.js
  view/js/jquery-textcomplete/jquery.textcomplete.min.map
  view/templates/head.tpl
  view/theme/frio/templates/head.tpl
Labels: Enhancement, Performance, UX

#8911 Introduce "HTTPRequest" class
  mod/dfrn_confirm.php
  mod/dfrn_poll.php
  mod/dfrn_request.php
  mod/match.php
  mod/oexchange.php
  mod/ostatus_subscribe.php
  mod/parse_url.php
  mod/pubsubhubbub.php
  mod/redir.php
  src/App.php
  src/Content/OEmbed.php
  src/Content/Text/BBCode.php
  src/Core/Installer.php
  src/Core/Protocol.php
  src/Core/Search.php
  src/Core/Worker.php
  src/DI.php
  src/Model/APContact.php
  src/Model/GContact.php
  src/Model/GServer.php
  src/Model/Item.php
  src/Model/Photo.php
  src/Model/Profile.php
  src/Model/User.php
  src/Module/Admin/Summary.php
  src/Module/Debug/Feed.php
  src/Module/Magic.php
  src/Network/HTTPRequest.php
  src/Network/IHTTPRequest.php
  src/Network/Probe.php
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  src/Protocol/PortableContact.php
  src/Protocol/Salmon.php
  src/Util/ExAuth.php
  src/Util/HTTPSignature.php
  src/Util/Images.php
  src/Util/Network.php
  src/Util/ParseUrl.php
  src/Worker/CheckVersion.php
  src/Worker/CronJobs.php
  src/Worker/Directory.php
  src/Worker/OnePoll.php
  src/Worker/PubSubPublish.php
  src/Worker/SearchDirectory.php
  static/dependencies.config.php
  tests/src/Core/InstallerTest.php
Labels: Enhancement

#8924 Fix Notice: "Undefined index: host"
  src/Network/Probe.php
Labels: Bug

#8927 Fetch followers/followings of contacts
  database.sql
  src/Model/Contact.php
  src/Model/ContactRelation.php
  src/Model/GContact.php
  src/Model/Item.php
  src/Module/Admin/Site.php
  src/Worker/UpdateGContact.php
  static/dbstructure.config.php
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement

#8933 Ensure that cached avatar fields are set
  src/Model/Contact.php
  src/Module/Contact.php
Labels: Enhancement

#8934 Fix fatal error because of unknown function "fetchUrl"
  src/Core/System.php
  src/Protocol/Salmon.php
Labels: Bug

#8930 Move mod/lockview to Module\PermissionTooltip
  doc/Addons.md
  doc/de/Addons.md
  mod/lockview.php
  src/Module/PermissionTooltip.php
  static/routes.config.php
  view/js/main.js
  view/templates/photo_view.tpl
  view/templates/search_item.tpl
  view/templates/wall_thread.tpl
  view/theme/frio/templates/photo_view.tpl
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/quattro/templates/photo_view.tpl
  view/theme/quattro/templates/search_item.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/smoothly/templates/search_item.tpl
  view/theme/smoothly/templates/wall_thread.tpl
  view/theme/vier/templates/photo_item.tpl
  view/theme/vier/templates/photo_view.tpl
  view/theme/vier/templates/search_item.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: Enhancement

#8936 Selective probing for AP
  src/Model/ContactRelation.php
Labels: Enhancement

#8931 Various performance improvements
  src/App/Router.php
  src/Content/Text/BBCode.php
  src/Content/Text/Markdown.php
  src/Core/Addon.php
  src/Core/Cache/ProfilerCache.php
  src/Core/Hook.php
  src/Core/Renderer.php
  src/Core/System.php
  src/Core/Theme.php
  src/Database/Database.php
  src/Factory/SessionFactory.php
  src/Network/HTTPRequest.php
  src/Object/Image.php
  src/Util/Images.php
  src/Util/Logger/ProfilerLogger.php
  src/Util/Profiler.php
  static/dependencies.config.php
  tests/src/App/ModuleTest.php
  tests/src/App/RouterTest.php
  tests/src/Util/Logger/ProfilerLoggerTest.php
  view/theme/frio/theme.php
Labels: Enhancement, Performance

#8937 New function "Item::storeForUserByUriId"
  mod/item.php
  src/Model/Item.php
Labels: Enhancement

#8939 Move "View As" form at the bottom of the profile page
  src/Module/Profile/Profile.php
  view/templates/profile/index.tpl
Labels: Enhancement, UI, UX

#8942 Some more avatar function replacements
  include/conversation.php
  mod/message.php
  mod/network.php
  mod/ping.php
  mod/suggest.php
  src/Content/ForumManager.php
  src/Content/Text/HTML.php
  src/Content/Widget.php
  src/Content/Widget/ContactBlock.php
  src/Factory/Notification/Notification.php
  src/Module/BaseSearch.php
  src/Module/Contact.php
  src/Module/Search/Acl.php
  src/Object/Post.php
  view/theme/vier/theme.php
Labels: Enhancement

#8945 Asynchronous contact relation check
  src/Model/Contact.php
  src/Model/ContactRelation.php
  src/Worker/ContactDiscovery.php
Labels: Enhancement, Performance

#8946 Possibly fix a fatal error
  src/Model/Contact.php
Labels: Bug

#8948 Replace "gcontact" with "contact" - improved suggestions
  mod/suggest.php
  src/Core/Search.php
  src/Model/Contact.php
  src/Model/GContact.php
  src/Module/Search/Acl.php
  static/dbstructure.config.php
  view/theme/vier/theme.php
Labels: Enhancement

#8952 Use a single function to create the template data for contacts
  mod/common.php
  mod/match.php
  mod/suggest.php
  src/Module/AllFriends.php
  src/Module/BaseSearch.php
  src/Module/Contact.php
  src/Module/Directory.php
  src/Module/Profile/Contacts.php
Labels: Enhancement

#8953 Synchronize contacts with the directory server
  src/Module/Admin/Site.php
  src/Worker/AddContact.php
  src/Worker/Cron.php
  src/Worker/PullDirectory.php
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement, Federation

#8954 Directory sync: Update contact when it already exists
  src/Worker/PullDirectory.php
Labels: Enhancement
