Repository friendica/friendica, pull requests merged in 2020-01, with the labels that each got.

#8042 Add missing constructor parameter to User\Cookie in dependencies.config
  static/dependencies.config.php
Labels: Bug

#8044 Don't add contacts when not needed
  src/Model/Contact.php
  src/Model/GContact.php
  src/Model/GServer.php
  src/Protocol/Diaspora.php
  src/Worker/SearchDirectory.php
  src/Worker/UpdateGContacts.php
Labels: Enhancement

#8046 Relocated functions from PortableContact to GServer
  src/Core/Search.php
  src/Model/GServer.php
  src/Protocol/PortableContact.php
  src/Worker/UpdateServerDirectories.php
Labels: Enhancement

#8050 Rework Feed::import parameters
  include/items.php
  src/Module/Debug/Feed.php
  src/Network/Probe.php
  src/Protocol/Feed.php
Labels: Bug

#8048 Fix BBCode::scaleExternalImage
  mod/item.php
  src/Content/Text/BBCode.php
  src/Content/Text/Markdown.php
  static/defaults.config.php
Labels: Bug

#8052 AP: Transmit the language in the contentMap
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#8056 Remove rdirname() in favor of native dirname()
  boot.php
  src/App/BaseURL.php
Labels: Enhancement

#8053 Remove get_app() in favor of DI::app()
  boot.php
  include/api.php
  include/enotify.php
  mod/fbrowser.php
  mod/item.php
  mod/message.php
  mod/photos.php
  mod/settings.php
  src/BaseModule.php
  src/Console/DocBloxErrorChecker.php
  src/Console/PhpToPo.php
  src/Content/OEmbed.php
  src/Content/Text/HTML.php
  src/Content/Widget.php
  src/Content/Widget/CalendarExport.php
  src/Core/System.php
  src/Core/Worker.php
  src/Model/Contact.php
  src/Model/Mail.php
  src/Model/Photo.php
  src/Model/Profile.php
  src/Protocol/DFRN.php
  src/Render/FriendicaSmarty.php
  src/Render/FriendicaSmartyEngine.php
  src/Util/Network.php
  tests/include/ApiTest.php
  view/theme/frio/php/scheme.php
  view/theme/vier/theme.php
Labels: Enhancement

#8055 Remove get_server() in favor of Search::getGlobalDirectory()
  boot.php
  mod/dfrn_request.php
  mod/match.php
  src/Core/Search.php
  src/Core/System.php
  src/Model/GContact.php
  src/Module/Admin/Site.php
  src/Module/BaseSearchModule.php
  src/Worker/SearchDirectory.php
  view/theme/vier/theme.php
Labels: Enhancement

#8060 Fix a missing ")"
  src/Module/Admin/Site.php
Labels: Bug

#8059 Item notification data is now stored in the "user-item" table
  database.sql
  include/api.php
  src/Database/PostUpdate.php
  src/Model/Item.php
  src/Model/UserItem.php
  static/dbstructure.config.php
Labels: Enhancement

#8066 The item notifications now are based upon the "user-item" field
  include/enotify.php
Labels: Enhancement

#8063 Use default user permissions when creating new event
  mod/events.php
  src/Core/ACL.php
  src/Model/Contact.php
  src/Model/Group.php
  src/Module/Item/Compose.php
Labels: Bug

#8070 Clear cookies before session clear
  src/DI.php
  src/Module/Security/Logout.php
Labels: Bug

#8073 Issue 8067: Posts from Mastodon had been wrongly parsed
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, Federation

#8074 Domain-driven-design implementation 4th iteration
  doc/Developer-Domain-Driven-Design.md
  doc/Developers-Intro.md
  doc/Home.md
  mod/notifications.php
  src/Api/BaseEntity.php
  src/Api/Entity/Mastodon/Account.php
  src/Api/Entity/Mastodon/Emoji.php
  src/Api/Entity/Mastodon/Field.php
  src/Api/Entity/Mastodon/FollowRequest.php
  src/Api/Entity/Mastodon/Instance.php
  src/Api/Entity/Mastodon/Relationship.php
  src/Api/Entity/Mastodon/Stats.php
  src/Api/Mastodon/Account.php
  src/Api/Mastodon/Emoji.php
  src/Api/Mastodon/Relationship.php
  src/BaseCollection.php
  src/BaseFactory.php
  src/BaseModel.php
  src/BaseRepository.php
  src/Collection/Introductions.php
  src/DI.php
  src/Database/DBA.php
  src/Database/Database.php
  src/Factory/Mastodon/Account.php
  src/Factory/Mastodon/FollowRequest.php
  src/Factory/Mastodon/Relationship.php
  src/Model/Introduction.php
  src/Module/Api/Mastodon/FollowRequests.php
  src/Module/Api/Mastodon/Instance.php
  src/Module/FollowConfirm.php
  src/Repository/Introduction.php
Labels: Enhancement

#8071 Replace Core\Lock wrapper with DI::lock() method
  src/Console/Lock.php
  src/Core/Lock.php
  src/Core/Lock/CacheLock.php
  src/Core/Lock/DatabaseLock.php
  src/Core/Lock/ILock.php
  src/Core/Lock/Lock.php
  src/Core/Lock/SemaphoreLock.php
  src/Core/Update.php
  src/Core/Worker.php
  src/Model/Item.php
  src/Protocol/OStatus.php
  tests/Util/DbaLockMockTrait.php
  tests/src/Console/LockConsoleTest.php
  tests/src/Core/Lock/LockTest.php
  tests/src/Core/Lock/SemaphoreLockTest.php
Labels: Enhancement

#8075 Fix: removed unneeded HTML escaping
  src/Content/Text/HTML.php
  src/Protocol/DFRN.php
  tests/src/Content/Text/HTMLTest.php
Labels: Bug, Federation

#8076 Remove unnecessary subnamespaces in Model\Introduction
  src/Model/Introduction.php
Labels: Bug

#8077 Improved notification messages
  include/enotify.php
Labels: Enhancement, UX

#8078 Add cookie clear failed validation in App\Authentication
  src/App/Authentication.php
Labels: Bug

#8080 The widgets in the sidebar are now deflated by standard
  view/templates/widget/filter.tpl
  view/templates/widget/saved_searches.tpl
  view/templates/widget_forumlist.tpl
  view/theme/frio/templates/widget/saved_searches.tpl
Labels: Enhancement, UI

#8082 Issue 8081: The usage has to be an object, not an array
  src/Module/NodeInfo.php
Labels: API, Bug

#8083 Notifications: Now declare direct thread answers as replies
  include/api.php
  include/enotify.php
  src/Model/UserItem.php
Labels: Enhancement, UX

#8062 Make Storage testable & add tests
  database.sql
  doc/AddonStorageBackend.md
  doc/Addons.md
  doc/de/Addons.md
  src/Console/Storage.php
  src/Core/StorageManager.php
  src/DI.php
  src/Model/Attach.php
  src/Model/Photo.php
  src/Model/Storage/AbstractStorage.php
  src/Model/Storage/Database.php
  src/Model/Storage/Filesystem.php
  src/Model/Storage/IStorage.php
  src/Model/Storage/SystemResource.php
  src/Module/Admin/Site.php
  src/Worker/CronJobs.php
  static/dbstructure.config.php
  static/dependencies.config.php
  tests/Util/SampleStorageBackend.php
  tests/Util/SampleStorageBackendInstance.php
  tests/datasets/storage/database.fixture.php
  tests/src/Core/StorageManagerTest.php
  tests/src/Model/Storage/DatabaseStorageTest.php
  tests/src/Model/Storage/FilesystemStorageTest.php
  tests/src/Model/Storage/StorageTest.php
  update.php
Labels: Enhancement

#8072 Replace Core\Cache wrapper with DI::cache() method
  mod/ping.php
  mod/poco.php
  src/Content/OEmbed.php
  src/Content/Text/BBCode.php
  src/Content/Widget/TrendingTags.php
  src/Core/Cache.php
  src/Core/Lock/DatabaseLock.php
  src/Core/Update.php
  src/Model/Photo.php
  src/Model/Profile.php
  src/Model/Term.php
  src/Module/Search/Index.php
  src/Network/Probe.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Util/Images.php
  src/Util/JsonLD.php
  src/Worker/CronJobs.php
  src/Worker/SearchDirectory.php
  tests/Util/DbaLockMockTrait.php
Labels: Enhancement

#8091 Fix missing storage class
  src/Model/Attach.php
  src/Model/Photo.php
Labels: Bug

#8093 The item count is now done in a single query
  src/Model/Nodeinfo.php
Labels: Bug

#8089 updateAvatar automatically repairs avatars when photos are deleted
  src/Model/Contact.php
  src/Model/Mail.php
  src/Model/Photo.php
Labels: Enhancement

#8094 Ensure that deleted contacts are really removed
  src/Worker/Cron.php
  src/Worker/RemoveContact.php
Labels: Bug

#8095 Ensure that local delivery is done via DFRN
  src/Worker/Delivery.php
  src/Worker/Notifier.php
Labels: Bug, Federation

#8099 The federation statistics now contain all systems
  src/Module/Admin/Federation.php
Labels: Enhancement

#8100 Combine matching systems
  src/Module/Admin/Federation.php
Labels: Enhancement, UI

#8106 Initial event share status doesn't depend on the user's default permissions anymore
  mod/events.php
Labels: Bug, UX

#8105 Fix typo in intro table field name
  src/Model/Introduction.php
Labels: Bug

#8107 User lowercase for platform data
  src/Model/GServer.php
  src/Module/Admin/Federation.php
  src/Module/Friendica.php
  src/Module/NodeInfo.php
Labels: Enhancement, Federation

#8108 Improved server platform detection
  src/Model/GServer.php
Labels: Enhancement

#8111 Tags and mentions should be escaped
  src/Model/Term.php
Labels: Enhancement, Security

#8112 Use "http_build_query" to build queries
  mod/network.php
Labels: Enhancement

#8113 Remove "f" parameter / network page parameter cleanup
  include/conversation.php
  mod/dfrn_poll.php
  mod/display.php
  mod/network.php
  mod/oexchange.php
  mod/photos.php
  src/Content/Item.php
  src/Content/Nav.php
  view/js/autocomplete.js
  view/js/main.js
  view/theme/frio/theme.php
Labels: Enhancement

#8114 Vier: The forumlist doesn't appear on the left in wide view
  view/templates/widget_forumlist.tpl
  view/theme/vier/wide.css
Labels: Bug, UI/Theme

#8115 Use only the first part of the path for the local storage
  view/js/main.js
Labels: Enhancement, UX

#8116 The archive functionality is working again
  mod/network.php
  src/Util/DateTimeFormat.php
Labels: Bug, UX

#8117 Use the "inbox" symbol as a symbol for mails
  src/Content/ContactSelector.php
Labels: Enhancement, UI

#8079 [frio] Stop scrollToItem() animate twice.
  view/theme/frio/js/theme.js
Labels: Enhancement, UI/Theme

#8118 Improved spam protection
  src/Module/Register.php
  view/templates/register.tpl
  view/theme/frio/templates/register.tpl
  view/theme/vier/style.css
Labels: Enhancement

#8119 Ensure that local contacts always are DFRN contacts
  src/Model/Contact.php
  src/Network/Probe.php
  src/Protocol/ActivityPub/Processor.php
  src/Worker/Cron.php
  src/Worker/OnePoll.php
Labels: Enhancement, Federation

#8121 Delegations now work again
  src/Module/Settings/Delegation.php
Labels: Bug

#8123 Storage class fixings
  src/Console/Storage.php
  src/Core/StorageManager.php
  src/Model/Storage/Filesystem.php
  tests/src/Core/StorageManagerTest.php
  update.php
Labels: Bug

#8124 updated JA translation THX Ozero Dien
  view/lang/ja/messages.po
  view/lang/ja/strings.php
Labels: Translation

#8126 Fix Storage list
  src/Console/Storage.php
Labels: Bug

#8122 Additional accounts can now be created easily
  src/Module/Register.php
  src/Module/Settings/Delegation.php
  view/templates/register.tpl
  view/templates/settings/delegation.tpl
  view/theme/frio/templates/register.tpl
Labels: New Feature

#8128 Refactor DI annotations to static methods
  src/DI.php
  tests/Util/AppMockTrait.php
  tests/src/Content/Text/BBCodeTest.php
  tests/src/Core/InstallerTest.php
  tests/src/Core/Lock/SemaphoreLockTest.php
  tests/src/Core/SystemTest.php
  tests/src/Network/CurlResultTest.php
Labels: Enhancement

#8129 CleanUp Cache namespace
  mod/ping.php
  src/Console/Cache.php
  src/Content/OEmbed.php
  src/Core/BaseCache.php
  src/Core/Cache/APCuCache.php
  src/Core/Cache/ArrayCache.php
  src/Core/Cache/DatabaseCache.php
  src/Core/Cache/Duration.php
  src/Core/Cache/ICache.php
  src/Core/Cache/IMemoryCache.php
  src/Core/Cache/MemcacheCache.php
  src/Core/Cache/MemcachedCache.php
  src/Core/Cache/ProfilerCache.php
  src/Core/Cache/RedisCache.php
  src/Core/Cache/TraitCompareDelete.php
  src/Core/Cache/TraitCompareSet.php
  src/Core/Cache/Type.php
  src/Core/Lock/CacheLock.php
  src/Core/Lock/DatabaseLock.php
  src/Core/Lock/ILock.php
  src/Core/Lock/Lock.php
  src/Core/Lock/SemaphoreLock.php
  src/Core/Update.php
  src/Factory/CacheFactory.php
  src/Factory/LockFactory.php
  src/Factory/SessionFactory.php
  src/Model/Photo.php
  src/Model/Profile.php
  src/Model/Term.php
  src/Module/Search/Index.php
  src/Network/Probe.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Util/JsonLD.php
  src/Worker/SearchDirectory.php
  tests/Util/DbaLockMockTrait.php
Labels: Enhancement

#8132 Fix: You can now register an account when you haven't done it before
  src/Module/Settings/Delegation.php
  view/templates/settings/delegation.tpl
Labels: Bug, UX

#8131 CleanUp Lock namespace
  src/Core/BaseLock.php
  src/Core/Lock/CacheLock.php
  src/Core/Lock/DatabaseLock.php
  src/Core/Lock/ILock.php
  src/Core/Lock/SemaphoreLock.php
  src/Core/Lock/Type.php
Labels: Enhancement

#8133 Remove @brief in DBA.php
  src/Database/DBA.php
Labels: Enhancement

#8137 AP: Create a GUID out of an URL
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement, Federation

#8139 Update deprecated code
  library/ASNValue.class.php
  src/Content/Text/HTML.php
Labels: Bug

#8140 Don't update mail contacts when polling
  src/Worker/OnePoll.php
Labels: Enhancement

#8143 Issue 8136: Optical enhancements for delegation page
  src/Module/Settings/Delegation.php
  view/templates/settings/delegation.tpl
  view/theme/frio/css/style.css
Labels: Enhancement, UI, UI/Theme

#8144 regen messages.po
  view/lang/C/messages.po
Labels: Translation

#8146 New custom profile fields feature part 1: Everything but custom profile fields
  include/conversation.php
  mod/cal.php
  mod/display.php
  mod/photos.php
  mod/profile_photo.php
  mod/profiles.php
  src/App/Authentication.php
  src/BaseCollection.php
  src/BaseModel.php
  src/BaseModule.php
  src/BaseRepository.php
  src/Collection/PermissionSets.php
  src/Content/ForumManager.php
  src/Content/Widget.php
  src/Core/ACL.php
  src/Core/Session.php
  src/DI.php
  src/Database/Database.php
  src/Database/PostUpdate.php
  src/Model/Group.php
  src/Model/Item.php
  src/Model/PermissionSet.php
  src/Model/Profile.php
  src/Module/Profile.php
  src/Module/Profile/Contacts.php
  src/Module/Register.php
  src/Module/Settings/Profile/Photo/Crop.php
  src/Module/Settings/Profile/Photo/Index.php
  src/Module/Special/HTTPException.php
  src/Object/Thread.php
  src/Repository/PermissionSet.php
  src/Util/ACLFormatter.php
  src/Util/Temporal.php
  static/routes.config.php
  update.php
  view/templates/acl_selector.tpl
  view/templates/cropbody.tpl
  view/templates/exception.tpl
  view/templates/http_status.tpl
  view/templates/profile/advanced.tpl
  view/templates/profile/publish.tpl
  view/templates/profile/vcard.tpl
  view/templates/profile_photo.tpl
  view/templates/settings/profile/photo/crop.tpl
  view/templates/settings/profile/photo/crop_head.tpl
  view/templates/settings/profile/photo/index.tpl
  view/templates/welcome.tpl
  view/theme/duepuntozero/templates/profile/vcard.tpl
  view/theme/frio/css/style.css
  view/theme/frio/templates/profile/advanced.tpl
  view/theme/frio/templates/profile/publish.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/quattro/templates/profile/vcard.tpl
  view/theme/vier/templates/profile/advanced.tpl
  view/theme/vier/templates/profile/vcard.tpl
  view/theme/vier/theme.php
Labels: Enhancement

#8147 Fix for AP posts where the URL don't match
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation

#8148 Remotely commenting on Peertube posts now does work
  mod/follow.php
Labels: Enhancement

#8149 Fix: unknown variable
  src/Model/GContact.php
Labels: Bug

#8152 Fix "accout" typo
  src/Module/Settings/UserExport.php
Labels: Bug, Translation

#8154 Make non-deterministic redirect for redir.php dynamic
  mod/redir.php
Labels: Bug

#8150 Prepare Model\Notify for include/enotify.php (Part 1)
  mod/notifications.php
  src/Collection/Introductions.php
  src/Model/Notify.php
  src/Model/PermissionSet.php
  src/Repository/PermissionSet.php
Labels: Enhancement

#8158 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#8161 Add group membership filter widget in contact list
  src/Content/Widget.php
  src/Module/Contact.php
Labels: New Feature

#8168 Fix Notification bubble
  mod/ping.php
  view/js/main.js
Labels: Bug, UX

#8171 Various profile fixes
  src/Module/Profile/Index.php
  src/Module/Profile/Status.php
  view/templates/profile/index.tpl
Labels: Bug, UI/Theme, UX

#8174 Remove target for notifications
  view/templates/notifications/attend_item.tpl
  view/templates/notifications/comments_item.tpl
  view/templates/notifications/dislikes_item.tpl
  view/templates/notifications/likes_item.tpl
  view/templates/notifications/network_item.tpl
  view/templates/notifications/notification.tpl
  view/templates/notifications/posts_item.tpl
Labels: Bug, UI

#8170 Prepare Model\Notify for include/enotify.php (Part 2)
  include/api.php
  include/enotify.php
  mod/ping.php
  src/BaseModel.php
  src/BaseRepository.php
  src/Collection/Notifies.php
  src/DI.php
  src/Factory/Notification/Introduction.php
  src/Factory/Notification/Notification.php
  src/Model/Notification.php
  src/Model/Notify.php
  src/Module/BaseNotifications.php
  src/Module/Notifications/Introductions.php
  src/Module/Notifications/Notification.php
  src/Module/Notifications/Notifications.php
  src/Object/Notification/Introduction.php
  src/Object/Notification/Notification.php
  src/Repository/Notify.php
Labels: Enhancement

#8175 Revert profile base URL behavior
  include/conversation.php
  mod/cal.php
  mod/events.php
  mod/notes.php
  mod/photos.php
  mod/videos.php
  src/Model/Profile.php
  src/Module/BaseProfile.php
  src/Module/Profile/Contacts.php
  src/Module/Profile/Index.php
  src/Module/Profile/Profile.php
  src/Module/Profile/Status.php
  static/routes.config.php
  view/theme/frio/templates/wall_thread.tpl
Labels: Bug, Enhancement, UX

#8177 Fix Introductions tab
  src/Factory/Notification/Introduction.php
Labels: Bug

#8176 Prepare Model\Notify for include/enotify.php (Part 3)
  include/enotify.php
  mod/item.php
  src/DI.php
  src/Object/EMail/IEmail.php
  src/Object/EMail/ItemCCEMail.php
  src/Object/Email.php
  src/Util/Emailer.php
Labels: Enhancement

#8179 Various notice fixes
  include/api.php
  mod/display.php
Labels: Bug

#8178 Move mod/noscrape to Module\Noscrape
  mod/noscrape.php
  src/Module/NoScrape.php
  static/routes.config.php
Labels: Enhancement

#8183 Fix NoScrape SQL
  src/Module/NoScrape.php
Labels: Bug

#8188 Replace profile tab GET parameter by route
  doc/Developers-Intro.md
  doc/FAQ.md
  doc/de/FAQ.md
  include/conversation.php
  mod/dfrn_poll.php
  src/Content/Nav.php
  src/Model/Contact.php
  src/Module/Contact.php
  view/theme/frio/theme.php
Labels: Bug

#8189 Fix wrong use of DPA::p return value in Module\NoScrape
  src/Module/NoScrape.php
Labels: Bug

#8190 Deprecated profile fields cleanup
  doc/API-Entities.md
  doc/Addons.md
  doc/database/db_profile.md
  doc/de/Addons.md
  mod/common.php
  mod/crepair.php
  mod/display.php
  mod/follow.php
  mod/unfollow.php
  src/Content/ContactSelector.php
  src/Model/Contact.php
  src/Model/GContact.php
  src/Model/Profile.php
  src/Module/AllFriends.php
  src/Module/Contact.php
  src/Module/Directory.php
  src/Module/HoverCard.php
  src/Module/NoScrape.php
  src/Network/Probe.php
  view/templates/profile/vcard.tpl
  view/templates/settings/profile/index.tpl
  view/theme/duepuntozero/style.css
  view/theme/duepuntozero/templates/profile/vcard.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/quattro/dark/style.css
  view/theme/quattro/green/style.css
  view/theme/quattro/lilac/style.css
  view/theme/quattro/quattro.less
  view/theme/quattro/templates/profile/vcard.tpl
  view/theme/smoothly/style.css
  view/theme/vier/templates/profile/vcard.tpl
Labels: Enhancement

#8191 Add custom emojis Mastodon API endpoint
  doc/API-Mastodon.md
  src/Api/Entity/Mastodon/Emoji.php
  src/BaseEntity.php
  src/Collection/Api/Mastodon/Emojis.php
  src/DI.php
  src/Factory/Api/Mastodon/Account.php
  src/Factory/Api/Mastodon/Emoji.php
  src/Factory/Api/Mastodon/FollowRequest.php
  src/Factory/Api/Mastodon/Relationship.php
  src/Module/Api/Mastodon/CustomEmojis.php
  src/Module/Api/Mastodon/FollowRequests.php
  src/Module/Api/Mastodon/Instance.php
  src/Module/Api/Mastodon/Instance/Peers.php
  src/Module/BaseApi.php
  src/Object/Api/Mastodon/Account.php
  src/Object/Api/Mastodon/Emoji.php
  src/Object/Api/Mastodon/Field.php
  src/Object/Api/Mastodon/FollowRequest.php
  src/Object/Api/Mastodon/Instance.php
  src/Object/Api/Mastodon/Relationship.php
  src/Object/Api/Mastodon/Stats.php
  static/routes.config.php
Labels: API, New Feature

#8186 Fix Notification issues
  include/api.php
  include/enotify.php
  src/BaseCollection.php
  src/BaseEntity.php
  src/BaseModel.php
  src/Collection/Api/Notifications.php
  src/DI.php
  src/Factory/Notification/Notification.php
  src/Model/Notify.php
  src/Object/Api/Friendica/Notification.php
  src/Object/Notification/Introduction.php
  src/Repository/Notify.php
  tests/datasets/api.fixture.php
  tests/include/ApiTest.php
Labels: Bug

#8195 updated JA translation THX Ozero Dien
  view/lang/ja/messages.po
  view/lang/ja/strings.php
Labels: Translation

#8194 Fix ignore notification
  include/enotify.php
  mod/ping.php
  src/Factory/Notification/Notification.php
  src/Module/BaseNotifications.php
  src/Module/Notifications/Notification.php
  static/routes.config.php
  view/templates/notifications/intros.tpl
  view/templates/notifications/suggestions.tpl
  view/theme/frio/templates/notifications/intros.tpl
Labels: Bug

#8196 Fix invalid "emailer_send_prepare" Hook
  doc/de/Addons.md
  src/Object/Email.php
  src/Util/Emailer.php
Labels: Bug

#8198 Fix Introduction Diaspore sendShare()
  src/Model/Introduction.php
Labels: Bug

#8199 Fix Contact addRelationship() notification link
  src/Model/Contact.php
Labels: Bug

#8204 Suppress Countable type warning messages in mod/dfrn_request
  mod/dfrn_request.php
Labels: Bug

#8203 [frio] Add new asynchronous submission of modal form
  include/conversation.php
  mod/editpost.php
  mod/item.php
  src/Core/Logger.php
  view/theme/frio/templates/jot-header.tpl
  view/theme/frio/templates/jot.tpl
Labels: Enhancement, UI/Theme, UX

#8207 Fix secure Mail addon
  src/Object/EMail/IEmail.php
  src/Object/Email.php
Labels: Bug

#8208 Fix Notifications cleared for threads
  include/api.php
  src/Model/Notify.php
  src/Module/Notifications/Notification.php
  src/Repository/Notify.php
  tests/include/ApiTest.php
Labels: Bug

#8163 New custom profile fields feature part 3: Updating the API
  doc/API-Friendica.md
  include/api.php
  src/Collection/Api/Mastodon/Fields.php
  src/DI.php
  src/Factory/Api/Mastodon/Account.php
  src/Factory/Api/Mastodon/Field.php
  src/Module/Admin/Addons/Details.php
  src/Module/Admin/Addons/Index.php
  src/Module/Admin/Blocklist/Contact.php
  src/Module/Admin/Blocklist/Server.php
  src/Module/Admin/DBSync.php
  src/Module/Admin/Features.php
  src/Module/Admin/Federation.php
  src/Module/Admin/Item/Delete.php
  src/Module/Admin/Item/Source.php
  src/Module/Admin/Logs/Settings.php
  src/Module/Admin/Logs/View.php
  src/Module/Admin/PhpInfo.php
  src/Module/Admin/Queue.php
  src/Module/Admin/Site.php
  src/Module/Admin/Summary.php
  src/Module/Admin/Themes/Details.php
  src/Module/Admin/Themes/Embed.php
  src/Module/Admin/Themes/Index.php
  src/Module/Admin/Tos.php
  src/Module/Admin/Users.php
  src/Module/Api/Friendica/Profile/Show.php
  src/Module/BaseAdmin.php
  src/Module/BaseApi.php
  src/Module/BaseSearch.php
  src/Module/BaseSettings.php
  src/Module/Search/Directory.php
  src/Module/Search/Index.php
  src/Module/Settings/Delegation.php
  src/Module/Settings/Profile/Index.php
  src/Module/Settings/Profile/Photo/Crop.php
  src/Module/Settings/Profile/Photo/Index.php
  src/Module/Settings/TwoFactor/AppSpecific.php
  src/Module/Settings/TwoFactor/Index.php
  src/Module/Settings/TwoFactor/Recovery.php
  src/Module/Settings/TwoFactor/Verify.php
  src/Module/Settings/UserExport.php
  src/Object/Api/Mastodon/Account.php
  src/Object/Api/Mastodon/Field.php
  src/Object/Api/Mastodon/FollowRequest.php
  static/routes.config.php
  tests/include/ApiTest.php
Labels: API, Enhancement

#8209 Move mod/worker to src\Module\Worker
  mod/worker.php
  src/Module/Worker.php
  static/routes.config.php
Labels: Enhancement

#8210 Move mod/fsuggest to src/Module/SuggestFriend
  mod/fsuggest.php
  src/Collection/FSuggests.php
  src/Core/ACL.php
  src/DI.php
  src/Model/FSuggest.php
  src/Module/FriendSuggest.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Repository/FSuggest.php
  src/Worker/Notifier.php
  static/routes.config.php
  view/templates/fsuggest.tpl
Labels: Enhancement
