Repository friendica/friendica, pull requests merged in 2020-12, with the labels that each got.

#9621 Add HTML Purify to BBCode::convert
  composer.json
  composer.lock
  src/Content/PageInfo.php
  src/Content/Text/BBCode.php
  src/Content/Text/HTML.php
  src/Model/Item.php
  src/Module/Debug/Babel.php
  tests/src/Content/Text/BBCodeTest.php
  view/templates/babel.tpl
Labels: Bug, Security

#9628 Don't create the parent during a deletion
  src/Protocol/DFRN.php
  src/Worker/Delivery.php
Labels: Bug, Federation

#9626 Prevents share block new lines from being converted to HTML <br> tags
  src/Content/Text/BBCode.php
Labels: Bug

#9631 Issue 9630: Prevent negative values for registered users
  src/Model/GServer.php
Labels: Bug, Federation

#9632 Centralized fetching of the default avatar
  src/Model/Contact.php
  src/Model/Photo.php
  src/Model/User.php
  src/Module/Photo.php
  static/defaults.config.php
Labels: Enhancement

#9637 Fixes "Unknown column '729' in 'field list'"
  src/Module/Photo.php
Labels: Bug

#9635 Batch of notice fixes
  src/Module/Admin/Item/Source.php
  src/Module/Objects.php
  src/Protocol/ActivityPub/Transmitter.php
  view/theme/vier/theme.php
Labels: Bug

#9643 Improved performance profiler
  index.php
  src/App.php
  src/App/Module.php
  src/App/Page.php
  src/Util/Profiler.php
Labels: Enhancement, Performance

#9644 Critical: Avoid dropping of incoming DFRN messages
  src/Protocol/DFRN.php
Labels: Bug, Federation

#9645 Normalize return value in Database->fetch
  src/Database/Database.php
  src/Model/Item.php
Labels: Bug

#9648 Issue 9633: Avoid contact lookup in conversation to avoid long loading times
  include/conversation.php
Labels: Bug, Performance

#9651 Archive/Unarchive at ActivityPub delivery
  src/Model/Contact.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/APDelivery.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#9652 Issue 9584: Only search posts from federated networks
  src/Model/ItemContent.php
  src/Model/Tag.php
  src/Module/Search/Index.php
Labels: Bug, UX

#9654 Support for unprepared delayed posts
  include/api.php
  src/Model/Item.php
  src/Model/Post/Delayed.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  src/Worker/DelayedPublish.php
Labels: Enhancement, UX

#9658 Issue 9657: Check the age of an item
  src/Protocol/Diaspora.php
Labels: Enhancement, UX

#9655 Fix several occasional fatal errors
  mod/dfrn_request.php
  src/Model/ItemURI.php
  src/Network/Probe.php
  src/Protocol/ActivityPub/Processor.php
  src/Worker/APDelivery.php
Labels: Bug

#9663 Add item user owner data check in Model\Item::isValid
  src/Model/Item.php
  src/Model/User.php
Labels: Bug

#9661 Clarify usage of ActivityPub\Transmitter::fetchTargetInboxes in Worker\APDelivery queuing
  src/Console/FixAPDeliveryWorkerTaskParameters.php
  src/Core/Console.php
  src/Worker/APDelivery.php
  src/Worker/Notifier.php
  src/Worker/ProfileUpdate.php
Labels: Bug

#9664 Delete removed contacts
  src/Model/APContact.php
  src/Model/Contact.php
  src/Model/User.php
  src/Module/Proxy.php
  src/Protocol/ActivityPub.php
  src/Util/HTTPSignature.php
  src/Worker/RemoveContact.php
Labels: Enhancement, Federation

#9667 Store the network profiler data
  src/Network/HTTPRequest.php
Labels: Enhancement

#9668 Fix warning "supplied key param cannot be coerced into a public key"
  src/Util/HTTPSignature.php
Labels: Bug, Federation

#9670 Fix notices
  src/Protocol/ActivityPub/Processor.php
  src/Worker/DelayedPublish.php
Labels: Bug

#9671 Avoid "Duplicate entry"
  src/Util/HTTPSignature.php
Labels: Bug

#9674 Add general information header translation to admin site template
  src/Module/Admin/Site.php
  view/lang/C/messages.po
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Bug, Translation

#9676 Restore Mastodon emoji span classes
  src/Content/Text/BBCode.php
  tests/src/Content/Text/BBCodeTest.php
Labels: Bug

#9675 Allow support for allowlisted iframe sources in Content\text\BBCode::convert
  doc/BBCode.md
  doc/de/BBCode.md
  src/Content/Text/BBCode.php
  src/Content/Text/HTML.php
Labels: Bug

#9679 Issue 9457: Fix remembering "personal" and "starred"
  src/Module/Conversation/Network.php
Labels: Bug, UX

#9680 Issue 9402: Avoid message "invalid storage backend settings" on empty value
  src/Module/Admin/Site.php
Labels: Bug, UX

#9683 Remove orphaned avatar photo entries
  src/Database/PostUpdate.php
Labels: Enhancement, Performance

#9681 Quit when message is empty
  src/Content/Text/HTML.php
Labels: Bug, php8.0

#9685 Remove unused cached avatar photo entries
  src/Worker/Cron.php
  src/Worker/RemoveUnusedAvatars.php
Labels: Enhancement, Performance

#9684 Add translation to untranslated strings in templates
  doc/smarty3-templates.md
  src/Module/Admin/Blocklist/Server.php
  src/Module/Admin/Item/Delete.php
  src/Module/Debug/Probe.php
  src/Module/Install.php
  src/Module/Profile/Profile.php
  src/Module/Register.php
  src/Module/Security/TwoFactor/Verify.php
  src/Module/Settings/TwoFactor/Index.php
  src/Module/Settings/TwoFactor/Verify.php
  view/global.css
  view/lang/C/messages.po
  view/templates/field/range_percent.tpl
  view/templates/field_input.tpl
  view/templates/field_password.tpl
  view/templates/field_richtext.tpl
  view/templates/field_textarea.tpl
  view/templates/install_base.tpl
  view/templates/install_checks.tpl
  view/templates/install_db.tpl
  view/templates/install_finished.tpl
  view/templates/profile/profile.tpl
  view/theme/frio/templates/field_colorinput.tpl
  view/theme/frio/templates/field_fileinput.tpl
  view/theme/frio/templates/field_input.tpl
  view/theme/frio/templates/field_password.tpl
  view/theme/frio/templates/field_textarea.tpl
Labels: Bug, Translation

#9690 Append author's contact id to allowed contacts to prevent empty ACL for private items
  mod/events.php
  mod/item.php
  mod/photos.php
  src/Module/Security/TwoFactor/Verify.php
  src/Module/Settings/TwoFactor/Verify.php
Labels: Bug, Privacy

#9694 Improve handling of the visibility parameter of the new ACL
  include/api.php
  mod/events.php
  mod/item.php
  mod/photos.php
Labels: Bug

#9693 Remove obsolete share header link color CSS rules
  view/global.css
Labels: Bug, Mobile, UI

#9695 Restore autolink in share block content in BBCode::convertShare
  src/Content/Text/BBCode.php
Labels: Bug, UX

#9696 Use correct request parameter type for poke privacy
  include/conversation.php
  mod/photos.php
  src/Model/Contact.php
  src/Module/Contact/Poke.php
Labels: Bug, Privacy

#9697 Server detection: Handle redirects, better Peertube detection
  src/Model/GServer.php
Labels: Enhancement, Federation

#9700 Add expected contact field in Module\Contact\Poke
  src/Module/Contact/Poke.php
Labels: Bug

#9701 [frio] Improve display of introduction action buttons on mobile
  include/conversation.php
  mod/editpost.php
  src/Module/Notifications/Introductions.php
  view/templates/jot-header.tpl
  view/theme/frio/css/style.css
  view/theme/frio/templates/notifications/intros.tpl
Labels: Bug, Theme-specific, UX

#9691 Add support for Unicode in Model\Tag::store
  src/Model/Tag.php
Labels: Bug, UX

#9706 Reducing load when displaying photos
  database.sql
  src/Database/PostUpdate.php
  src/Database/View.php
  src/Model/Photo.php
  src/Module/Conversation/Network.php
  src/Module/Photo.php
  static/dbstructure.config.php
Labels: Enhancement, Performance

#9707 [frio] Replace additional sort buttons by anchor links in users admin
  view/theme/frio/templates/admin/users/active.tpl
  view/theme/frio/templates/admin/users/blocked.tpl
  view/theme/frio/templates/admin/users/index.tpl
Labels: Bug, UX

#9709 messages.po updated
  view/lang/C/messages.po
Labels: Translation

#9710 Restore auto-complete feature in comments forms
  view/js/main.js
  view/templates/display-head.tpl
Labels: Bug, UX

#9711 Throw exception when item doesn't exist in Factory\Api\Mastodon\Status->createFromUriId
  src/Factory/Api/Mastodon/Status.php
Labels: Bug

#9713 Comment to Twitter post is posted to AP instead
  src/Worker/Notifier.php
Labels: Bug, Federation

#9717 DE and HU translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
Labels: Translation

#9725 Prevent alt text of emoji image tags to be converted to smilies in BBCode::convert
  src/Content/Text/BBCode.php
Labels: Bug

#9726 [frio] Vary Back to Top element depending on the theme accent/colors
  view/theme/frio/css/style.css
  view/theme/frio/php/default.php
  view/theme/frio/php/standard.php
  view/theme/frio/scheme/black.css
  view/theme/frio/scheme/dark.css
Labels: Bug, Theme-specific, UI

#9727 Fix a notice when the path is empty
  src/Network/Probe.php
Labels: Bug

#9732 Accept public and user contact id for permissionsets
  src/Repository/PermissionSet.php
Labels: Enhancement

#9724 Various improvements
  mod/events.php
  src/Module/Special/HTTPException.php
  src/Util/ACLFormatter.php
  view/templates/exception.tpl
Labels: Enhancement

#9731 Various theme changes
  view/theme/frio/php/default.php
  view/theme/frio/php/standard.php
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: Bug, Theme-specific, UI, UX
