Repository friendica/friendica, pull requests merged in 2020-03, with the labels that each got.

#8355 Remove last on/off data occurrences in additional features
  mod/settings.php
  src/Module/Admin/Features.php
Labels: Bug

#8356 Add check for semi-colon existence in theme file comment lines
  src/Core/Theme.php
Labels: Bug

#8353 [frio] Enable file upload in settings form
  mod/settings.php
  view/theme/frio/templates/settings/settings.tpl
Labels: Bug, Theme-specific, UX

#8352 Use sensible URLs for return after album actions instead of $_SESSION['photo_return'] in mod/photos
  mod/photos.php
  view/templates/photo_album.tpl
Labels: Bug, Theme-specific, UX

#8350 Add Login form in case of notification links
  include/api.php
  src/Module/Notifications/Notification.php
  src/Repository/Notify.php
Labels: Bug

#8354 Add debug for item deletion
  src/Model/Item.php
  src/Worker/DBClean.php
  src/Worker/Expire.php
  src/Worker/RemoveContact.php
Labels: Enhancement

#8359 Add callstack context to cascade deletion debug logging
  src/Database/Database.php
  src/Model/Item.php
  src/Module/Admin/Item/Delete.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Worker/DBClean.php
  src/Worker/Expire.php
  src/Worker/RemoveContact.php
  src/Worker/RemoveUser.php
Labels: Bug

#8367 Store "sc:identifier" as GUID as well
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement, Federation

#8366 Issue 8321: Follow items now work again
  include/api.php
  mod/subthread.php
  src/Model/Item.php
  src/Module/Like.php
  view/theme/frio/theme.php
Labels: Bug, UX

#8376 Return early if link is missing from share block in Model\Item
  src/Model/Item.php
Labels: Bug

#8368 AP: Bugfixing / GContact discovery
  database.sql
  src/Model/GContact.php
  src/Module/Admin/Site.php
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/UpdateGContact.php
  static/dbstructure.config.php
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement, Federation

#8365 Mail: Remove redundant body creation in case of only a preamble is set
  src/Util/EMailer/SystemMailBuilder.php
Labels: Bug

#8379 regen messages.po
  view/lang/C/messages.po
Labels: Translation

#8377 Show the relations of Twitter contacts
  src/Module/Contact.php
Labels: Addons, Enhancement, UX

#8380 Issue 8151: Automatic Friend is working again
  src/Model/Contact.php
Labels: Bug, UX

#8382 issue 8268: Birthday reminders are now more visible
  view/theme/frio/css/style.css
Labels: Enhancement, Theme-specific, UI

#8386 Fix & align HTML mail text
  view/templates/email/html.tpl
  view/templates/email/notify/html.tpl
  view/templates/email/system/html.tpl
Labels: Bug

#8390 Fix fatal error (TypeError)
  src/Model/Photo.php
Labels: Bug

#8391 DE, FR, JA, ZH-CN translation updated
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/ja/messages.po
  view/lang/ja/strings.php
  view/lang/zh-cn/messages.po
  view/lang/zh-cn/strings.php
Labels: Translation

#8392 Ensure non-NULL values in $data array in Contact::updateAvatar
  src/Model/Contact.php
Labels: Bug

#8399 Polling Mails is now done with a higher priority
  src/Worker/Cron.php
Labels: Enhancement, Federation

#8398 Issue 8383 (again): Finally fixes the double scheme problem
  src/Network/Probe.php
Labels: Bug

#8397 Fix uninstall of installed addons
  src/Core/Addon.php
  src/Model/Nodeinfo.php
  src/Module/Admin/Addons/Details.php
  update.php
Labels: Addons, Bug

#8403 Use correct variable name for deny input value concatenation
  view/templates/acl_selector.tpl
Labels: Bug

#8406 Normalize vcard across themes display after profile fields reorganization
  view/templates/profile/vcard.tpl
  view/theme/duepuntozero/templates/profile/vcard.tpl
  view/theme/quattro/templates/profile/vcard.tpl
  view/theme/vier/templates/profile/vcard.tpl
Labels: Bug, Theme-specific, UI

#8407 Remove extraneous HTML decode in Markdown::toBBCode
  src/Content/Text/Markdown.php
  src/Module/Debug/Babel.php
  tests/src/Content/Text/MarkdownTest.php
  view/templates/babel.tpl
Labels: Bug, Federation

#8410 Set the picture accesibility separate from the permissions
  src/Model/Photo.php
Labels: Bug

#8413 Avoid notice in gcontact.php
  src/Model/GContact.php
Labels: Bug

#8418 Issue #8417 RU translation
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#8419 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#8424 RU translations THX Alexander An
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#8427 Issue 8371: Ensure to always have permissions
  mod/item.php
Labels: Bug

#8428 Issue 8371 again: Fallback for item permissions
  mod/item.php
Labels: Bug

#8433 Issue 8432: Make notifications translatable
  include/enotify.php
Labels: Bug, Translation

#8434 regen messages.po
  view/lang/C/messages.po
Labels: Translation

#8437 PL translation update THX waldis
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#8435 Issue 8371: Alternate Solution
  mod/item.php
  src/Model/Item.php
  src/Model/Photo.php
Labels: Bug

#8439 a l10n call too much
  include/enotify.php
Labels: Bug

#8442 Issue 8371: More enhanced logging
  src/Model/Photo.php
Labels: Bug

#8444 Remove extraneous relation on item-activity.id
  static/dbstructure.config.php
Labels: Bug

#8443 Prevent endless loops and long running feed processing
  src/Model/GContact.php
  src/Protocol/ActivityPub.php
  src/Protocol/Feed.php
  src/Worker/Cron.php
  src/Worker/CronJobs.php
  static/defaults.config.php
Labels: Enhancement, Performance

#8446 Skip Contact::getDetailsByURL when url is empty in GContact::searchByName
  src/Model/GContact.php
Labels: Bug

#8448 NL translation update THX Casper
  view/lang/nl/messages.po
  view/lang/nl/strings.php
Labels: Translation

#8450 Enable visibility request parameter to override default user permissions in mod/item
  mod/item.php
Labels: Bug

#8451 Issue 7771: Funkwhale support
  src/Content/Text/BBCode.php
  src/Model/APContact.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement, Federation

#8452 Issue 8254: Length restriction for "title" and "uri"
  src/Model/Item.php
Labels: Bug

#8429 updated the credits for 2020.03
  CREDITS.txt
Labels: Docs

#8454 Issue 7892: Improve "plink" generation for Diaspora posts
  src/Model/Contact.php
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#8455 Issue 8254 More length shortenings
  include/enotify.php
  src/Model/Item.php
  src/Util/ParseUrl.php
Labels: Bug

#8456 Fix: Fetching content via the "objects" endpoint behaved wrong
  src/Module/Objects.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#8459 Prevent another endless loop while fetching AP items
  src/Protocol/ActivityPub.php
Labels: Enhancement

#8461 Issue 8341: Make events sharable
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#8463 Issue 8299: Don't manipulate DFRN content upon receiving
  src/Protocol/DFRN.php
Labels: Enhancement, Federation

#8462 Issue 8254: Some more fixes for too long data for columns
  src/Model/APContact.php
  src/Model/Term.php
Labels: Enhancement

#8468 Update documentation in bin/auth_ejabberd
  bin/auth_ejabberd.php
Labels: Docs

#8469 Add object key existence check in ActivityPub/Transmitter
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#8472 Discover contacts: Prevent putting much stress on remote systems
  src/Model/GContact.php
  src/Worker/UpdateGContact.php
Labels: Enhancement

#8426 2020.03 CHANGELOG
  CHANGELOG
Labels: Docs

#8479 Update.md: be more precise about items to copy
  doc/Update.md
Labels: Docs
