Repository friendica/friendica, pull requests merged in 2020-04, with the labels that each got.

#8471 Add new Strings::substringReplace method
  src/Util/Strings.php
  tests/src/Util/StringsTest.php
Labels: New Feature

#8481 Improved Mime Type detection
  include/api.php
  mod/photos.php
  mod/wall_upload.php
  src/Content/Text/BBCode.php
  src/Model/Photo.php
  src/Model/User.php
  src/Module/Settings/Profile/Photo/Index.php
  src/Object/Image.php
  src/Util/Images.php
Labels: Enhancement

#8480 Remove default post permission modal window
  mod/settings.php
  view/templates/settings/settings.tpl
  view/theme/frio/templates/settings/settings.tpl
Labels: Enhancement, UI, UX

#8484 Check for Antelope and convert to Barracuda
  src/Console/DatabaseStructure.php
  src/Database/DBStructure.php
  src/Model/Item.php
  src/Module/Admin/Summary.php
Labels: Enhancement, Installation

#8491 Updated FR translation THX me
  view/lang/fr/messages.po
  view/lang/fr/strings.php
Labels: Translation

#8492 [frio] Add link to Compose page in jot
  include/conversation.php
  mod/editpost.php
  view/theme/frio/css/style.css
  view/theme/frio/templates/jot.tpl
Labels: Enhancement, Theme-specific, UI

#8500 Fix Password Reset Token Security
  mod/lostpass.php
Labels: Enhancement, Security

#8496 Issue 8493: Avoid fatal error when fetching items via API
  include/conversation.php
Labels: Bug

#8503 Fix notice about an unknown variable
  include/conversation.php
Labels: Bug

#8502 Improve bin/run_xgettext and regenerate master messages.po
  bin/run_xgettext.sh
  view/lang/C/messages.po
Labels: Bug, Enhancement, Translation

#8504 Add cache, ETag and CORS headers to AP endpoints
  mod/display.php
  src/Module/Objects.php
  src/Module/Profile/Profile.php
  src/Util/Network.php
Labels: Enhancement, Federation

#8512 The "sign" table had been removed
  database.sql
  src/Model/Item.php
  src/Worker/DBClean.php
  static/dbstructure.config.php
Labels: Enhancement

#8519 Fix: some selected item fields hadn't been selected
  src/Model/Item.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#8530 Move poke module to src/
  include/conversation.php
  mod/poke.php
  src/Model/Contact.php
  src/Module/Contact/Poke.php
  static/routes.config.php
  view/global.css
  view/templates/contact/poke.tpl
  view/templates/poke_content.tpl
  view/templates/poke_head.tpl
  view/theme/frio/css/style.css
  view/theme/frio/js/theme.js
  view/theme/frio/theme.php
Labels: Bug, Enhancement, UX

#8531 [frio] Remove duplicate jot modal close button
  view/theme/frio/templates/jot.tpl
Labels: Bug, Mobile, Theme-specific, UI

#8532 Fix: Image descriptions now work again
  src/Content/Text/BBCode.php
Labels: Bug, UX

#8535 Remove album name bin2hex conversion in file browser
  mod/fbrowser.php
  mod/photos.php
  mod/wall_upload.php
  view/js/filebrowser.js
  view/templates/filebrowser.tpl
  view/theme/frio/js/filebrowser.js
  view/theme/frio/templates/filebrowser.tpl
Labels: Bug, UX

#8520 We now store tags in "tag"
  boot.php
  include/api.php
  include/items.php
  mod/item.php
  mod/network.php
  mod/photos.php
  mod/tagger.php
  mod/tagrm.php
  src/Content/Text/BBCode.php
  src/Content/Widget/TagCloud.php
  src/Model/FileTag.php
  src/Model/Item.php
  src/Model/ItemURI.php
  src/Model/Tag.php
  src/Model/Term.php
  src/Model/UserItem.php
  src/Module/Hashtag.php
  src/Module/Profile/Status.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  src/Worker/TagUpdate.php
  static/dbstructure.config.php
Labels: Enhancement, Performance

#8539 AP: Interpret "update" as "create" when item isn't found
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement, Federation

#8541 Move optional token parameter at the end of OAuthRequest::from_consumer_and_token() function definition
  library/OAuth1.php
Labels: Addons, Bug

#8543 [frio] Align brand name color on nav icon
  view/theme/frio/css/style.css
Labels: Enhancement, Theme-specific, UI

#8544 Fix Travis
  .travis.yml
Labels: Bug

#8537 We now can define views
  database.sql
  mod/display.php
  mod/poco.php
  mod/wall_upload.php
  src/Console/User.php
  src/Core/Worker.php
  src/Database/DBStructure.php
  src/Database/View.php
  src/Model/Item.php
  src/Model/Profile.php
  src/Model/Register.php
  src/Model/Tag.php
  src/Model/User.php
  src/Module/Admin/Users.php
  src/Module/NoScrape.php
  src/Module/Profile/Profile.php
  src/Module/Profile/Status.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Salmon.php
  src/Worker/Directory.php
  static/dbstructure.config.php
  static/dbview.config.php
  tests/datasets/api.fixture.php
  view/theme/vier/theme.php
Labels: Enhancement

#8545 Template Engine with Subdirectory
  src/Core/Renderer.php
  src/DI.php
  src/Render/FriendicaSmartyEngine.php
  src/Render/ITemplateEngine.php
Labels: Bug

#8548 [frio] Restore focus styles
  view/theme/frio/css/style.css
  view/theme/frio/templates/jot.tpl
  view/theme/frio/templates/searchbox.tpl
Labels: Enhancement, Theme-specific, UI, UX

#8549 Suppress XML logging of errors
  src/Model/GServer.php
  src/Model/Item.php
  src/Network/Probe.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Util/XML.php
Labels: Enhancement

#8554 Fix issue 8551: Last item is now displayed again
  src/Module/Admin/Users.php
Labels: Bug, UI

#8555 Issue 8546: Added option to not use prepared statements
  src/Database/Database.php
Labels: Enhancement, Performance

#8556 Added forgotten DBA::close
  mod/msearch.php
  src/Core/Worker.php
  src/Model/Contact.php
  src/Model/GContact.php
  src/Model/Process.php
  src/Model/Search.php
  src/Model/User.php
  src/Model/UserItem.php
  src/Module/Admin/DBSync.php
  src/Module/Admin/Site.php
  src/Module/Settings/Delegation.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
  src/Worker/CronJobs.php
  src/Worker/UpdateGContacts.php
  src/Worker/UpdateGServers.php
Labels: Enhancement, Performance

#8559 Fix for "Undefined index: profile_url"
  src/Core/Search.php
  src/Module/Directory.php
Labels: Bug

#8561 Iissue 8560: Wrong value for parent in mail notification
  mod/message.php
  src/Model/Mail.php
Labels: Bug
