Repository friendica/friendica, pull requests merged in 2020-06, with the labels that each got.

#8713 Issue 8675: reduce requests of foreign pages
  src/Model/APContact.php
  src/Model/Contact.php
  src/Model/Profile.php
  src/Module/RemoteFollow.php
  src/Network/CurlResult.php
  src/Network/Probe.php
  static/dbstructure.config.php
Labels: Enhancement, Federation, Performance

#8716 Let "subscribe" be filled at every time to avoid a notice
  src/Network/Probe.php
Labels: Bug

#8718 Use expected return variable type in Network\Probe::detect
  src/Network/Probe.php
Labels: Bug

#8719 Improve language of console globalcommunitysilence help line
  src/Console/GlobalCommunitySilence.php
  src/Core/Console.php
Labels: Docs, Enhancement

#8721 Fix fatal errors because of mixed data types
  src/Network/Probe.php
Labels: Bug

#8720 Issue 8714: Make redirects more secure
  mod/redir.php
Labels: Enhancement, Security

#8723 Move share content conversion before link handling in Text\BBCode::convert
  src/Content/Text/BBCode.php
  tests/src/Content/Text/BBCodeTest.php
Labels: Bug

#8725 Remove Twitter exception for shared blocks
  src/Content/Text/BBCode.php
  tests/src/Content/Text/BBCodeTest.php
Labels: Bug

#8728 Use webfinger in apcontact fetch
  database.sql
  src/Model/APContact.php
  src/Network/Probe.php
  src/Protocol/ActivityPub.php
  static/dbstructure.config.php
Labels: Enhancement, Federation, Performance

#8730 Ensure $categories is set in mod/item
  mod/item.php
Labels: Bug

#8731 [frio] Add color to active buttons in mobile view
  view/theme/frio/css/style.css
Labels: Theme-specific, UI

#8734 Exit with an error if profile info isn't available in Module\NoScrape
  src/Module/NoScrape.php
Labels: Bug

#8737 Issue 8735: Ensure the correct data type for "hide"
  src/Model/GContact.php
  src/Network/Probe.php
Labels: Bug

#8739 Issue 8732: Fix fetch saved searches
  src/Content/Widget/SavedSearches.php
Labels: Bug

#8741 Add probe_detect hook
  doc/Addons.md
  src/Network/Probe.php
Labels: Addons, Enhancement, Federation

#8742 Replace charged terms with "allowlist", "denylist" and "blocklist"
  CHANGELOG
  database.sql
  doc/Install.md
  doc/database/db_contact.md
  friendica_test_data.sql
  include/items.php
  src/Content/Text/BBCode.php
  src/Database/Database.php
  src/Module/Admin/Blocklist/Server.php
  src/Module/Contact.php
  src/Protocol/Feed.php
  static/dbstructure.config.php
  static/dbview.config.php
  static/defaults.config.php
  update.php
  view/templates/contact_edit.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/vier/templates/contact_edit.tpl
Labels: Translation, UX

#8727 [ActivityPub] Add support for more attachments structures
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Util/JsonLD.php
Labels: Enhancement, Federation

#8750 fix-continue-warnings in AP processor
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#8729 Add tag escaping to BBCode::setTags
  doc/BBCode.md
  include/api.php
  include/enotify.php
  mod/cal.php
  mod/item.php
  mod/photos.php
  mod/poco.php
  mod/videos.php
  src/Content/Text/BBCode.php
  src/Content/Text/HTML.php
  src/Model/Item.php
  src/Model/Notify.php
  src/Module/Debug/Babel.php
  src/Util/Strings.php
  tests/include/ApiTest.php
  tests/src/Util/StringsTest.php
Labels: Bug

#8749 Add quote support in attachment title in ActivityPub\Processor
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement, Federation

#8751 Fix notice "Undefined index: template in src/Network/Probe.php on line 598"
  src/Network/Probe.php
Labels: Bug

#8752 Avoid unneeded database calls when showing posts of contacts
  src/Model/Contact.php
  src/Module/Contact.php
Labels: Enhancement, Performance

#8758 Add missing return variable while replacing tags in mod/item
  mod/item.php
Labels: Bug

#8754 Strip the link preview URL from the end of the body if any in ActivityPub\Processor
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement, Federation

#8740 [frio] Improve share blocks display
  mod/item.php
  src/Content/Item.php
  src/Content/Text/BBCode.php
  src/Model/Contact.php
  src/Network/Probe.php
  view/global.css
  view/theme/frio/css/style.css
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/shared_content.tpl
Labels: Enhancement, Theme-specific, UI, UX

#8761 [frio] Replace only the users table element when reordering on a column in mod_admin.js
  view/theme/frio/js/mod_admin.js
Labels: Bug, Theme-specific, UI, UX

#8753 Remove dependency to App in Contact::createFromProbe
  mod/follow.php
  mod/ostatus_subscribe.php
  mod/repair_ostatus.php
  mod/salmon.php
  src/Model/Contact.php
  src/Module/Contact.php
  src/Worker/AddContact.php
Labels: Bug

#8765 Fix providing the public key
  view/templates/profile/vcard.tpl
  view/theme/duepuntozero/templates/profile/vcard.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/quattro/templates/profile/vcard.tpl
  view/theme/vier/templates/profile/vcard.tpl
Labels: Bug, Federation

#8767 Clear all previous template variables before replacing Macros
  src/Render/FriendicaSmartyEngine.php
  view/theme/frio/php/minimal.php
  view/theme/frio/templates/auto_request.tpl
Labels: Bug, Theme-specific, UI

#8617 (Re)Implement Twitter contact API endpoints
  doc/API-Twitter.md
  include/api.php
  src/DI.php
  src/Factory/Api/Twitter/User.php
  src/Module/Api/Twitter/ContactEndpoint.php
  src/Module/Api/Twitter/FollowersIds.php
  src/Module/Api/Twitter/FollowersList.php
  src/Module/Api/Twitter/FriendsIds.php
  src/Module/Api/Twitter/FriendsList.php
  src/Object/Api/Twitter/User.php
  static/routes.config.php
  tests/FixtureTest.php
  tests/datasets/api.fixture.php
  tests/include/ApiTest.php
  tests/src/Module/Api/Twitter/ContactEndpointMock.php
  tests/src/Module/Api/Twitter/ContactEndpointTest.php
Labels: API, Enhancement, New Feature, Tests Needed

#8770 Reduced network request when probing
  src/Network/Probe.php
  src/Protocol/ActivityPub.php
Labels: Enhancement, Federation, Performance

#8771 Abuse mail received because of "unusual traffic"
  src/Model/GServer.php
Labels: Enhancement, Federation

#8772 Speed up post update for gsid
  src/Database/PostUpdate.php
Labels: Enhancement, Performance

#8774 redir - clicking on title of own post leads to access denied error
  mod/redir.php
Labels: Bug

#8776 Categories are not showing up at the bottom of the post
  src/Model/Post/Category.php
Labels: Bug, UI

#8779 Different comment limits for single view
  include/conversation.php
  src/Module/Admin/Site.php
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement, UX

#8782 Hopefully fixes notice "Undefined index: gravity"
  src/Model/Contact.php
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#8783 Exclude [img] tags from tag replacement
  mod/item.php
  src/Content/Text/BBCode.php
Labels: Bug, UX

#8784 Add constraints on Page Info URLs
  include/items.php
  mod/item.php
  src/Content/PageInfo.php
  src/Module/Debug/Babel.php
  src/Protocol/Feed.php
  src/Util/Strings.php
  src/Worker/OnePoll.php
  tests/src/Content/PageInfoMock.php
  tests/src/Content/PageInfoTest.php
Labels: Bug, Enhancement

#8787 Replace share_header calls with BBCode::getShareOpeningTag
  include/api.php
  mod/share.php
  src/Content/Text/BBCode.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
Labels: Bug

#8786 [Composer] Update dependencies ahead of release
  composer.json
  composer.lock
Labels: Enhancement

#8789 Account for contact.ffi_keyword_denylist field being NULL by default
  src/Protocol/Feed.php
Labels: Bug

#8790 Fix latest notice messages
  src/Model/Item.php
  src/Protocol/OStatus.php
Labels: Bug

#8791 Update composer.phar to Version 1.10.7
  bin/composer.phar
Labels: Enhancement, Installation

#8799 Prevent propagation of escape key press when it was used to close autocomplete dropdown
  view/js/autocomplete.js
Labels: Bug, Theme-specific, UX

#8801 [pre] blocks now preserve spaces
  doc/BBCode.md
  src/Content/Text/BBCode.php
  tests/src/Content/Text/BBCodeTest.php
Labels: Bug, UX

#8802 Update user.login_date for authenticated API calls
  include/api.php
Labels: API, Enhancement, Security

#8792 [frio] Add local post link to share block when guid attribute is present
  include/api.php
  mod/share.php
  src/Content/Text/BBCode.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
  tests/datasets/api.fixture.php
  view/theme/frio/templates/shared_content.tpl
Labels: Enhancement

#8809 Add expected whitespace before Widget::unavailableNetworks() output
  src/Module/Contact.php
Labels: Bug

#8804 Add type hint to Database::insert
  src/Database/Database.php
Labels: Bug

#8805 Add logging to rare condition in Model\Profile::sidebar
  src/Model/Profile.php
Labels: Bug

#8803 [API] Replace unwarranted Item::selectFirstForUser calls in photo endpoints
  include/api.php
Labels: API, Bug

#8813 Issue 8807: Improved feed detecting
  src/Network/Probe.php
Labels: Bug, Federation

#8815 Fix for "PHP Notice: Undefined index: forum in /src/Protocol/OStatus.php on line 2091"
  src/Model/Contact.php
  src/Protocol/OStatus.php
Labels: Bug

#8817 Prevent delivering AP comments to Diaspora
  src/Model/Item.php
  src/Protocol/Diaspora.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#8820 Fix notice "Undefined index: author-network"
  src/Worker/Notifier.php
Labels: Bug

#8811 Add support for mobile profile URL to core twitter probing
  mod/dfrn_request.php
  mod/follow.php
  mod/ostatus_subscribe.php
  src/Model/Contact.php
  src/Model/GContact.php
  src/Model/Mail.php
  src/Module/Acctlink.php
  src/Network/Probe.php
  src/Protocol/OStatus.php
Labels: Enhancement

#8822 [frio] Add missing margin above relocate form in admin site
  view/theme/frio/css/style.css
  view/theme/frio/templates/admin/site.tpl
Labels: Bug, Theme-specific, UI

#8824 Fix processing of received coordinates
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation

#8823 Fix notice "Undefined index: keywords"
  src/Content/PageInfo.php
Labels: Bug

#8821 Improve Module\Admin\Item\Source
  src/Module/Admin/Item/Source.php
Labels: Bug, Enhancement

#8825 Improve render speed by not probing for unknown contacts
  src/Content/Text/BBCode.php
Labels: Enhancement, Performance

#8831 Account for false return value of Repository\Notify->insert in notification()
  include/enotify.php
Labels: Bug

#8826 Replace deprecated Logger calls
  include/api.php
  mod/dfrn_confirm.php
  mod/dfrn_poll.php
  mod/events.php
  mod/salmon.php
  mod/settings.php
  src/Content/Text/BBCode.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Module/Admin/Summary.php
  src/Module/Diaspora/Receive.php
  src/Module/Magic.php
  src/Module/Owa.php
  src/Network/CurlResult.php
  src/Network/FKOAuth1.php
  src/Network/Probe.php
  src/Object/Image.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Protocol/PortableContact.php
  src/Protocol/Salmon.php
  src/Util/Crypto.php
Labels: Enhancement

#8832 Fix database error ""Unknown column 'parent-item.author-id'"
  src/Model/Item.php
Labels: Bug

#8834 Introduce stable branch
  doc/BBCode.md
  doc/Chats.md
  doc/Github.md
  doc/Install.md
  doc/Message-Flow.md
  doc/Update.md
  doc/de/BBCode.md
  doc/de/Chats.md
  doc/de/Install.md
  doc/de/Message-Flow.md
  doc/themes.md
  doc/translations.md
  mod/dfrn_confirm.php
  mod/dfrn_notify.php
  mod/dfrn_request.php
  mods/.drone.yml
  src/Core/Installer.php
  src/Core/Search.php
  src/Module/Admin/Site.php
  src/Module/Admin/Summary.php
  src/Module/BaseAdmin.php
  src/Worker/CheckVersion.php
  view/theme/frio/README.md
Labels: Enhancement
