Repository friendica/friendica, pull requests merged in 2020-02, with the labels that each got.

#8211 Move mod/crepair to src/Module/Contact/Repair
  mod/crepair.php
  src/Module/Contact/Advanced.php
  static/routes.config.php
  view/templates/contact/advanced.tpl
Labels: Enhancement

#8213 Fix Archives Widget on Status Page
  src/Module/Profile/Status.php
Labels: Bug

#8212 Release Cache Buster
  src/App/Page.php
  src/Util/Network.php
  view/templates/admin/federation.tpl
  view/templates/event_head.tpl
  view/templates/filebrowser.tpl
  view/templates/head.tpl
  view/templates/jot-header.tpl
  view/templates/msg-header.tpl
  view/templates/settings/profile/index_head.tpl
  view/templates/settings/profile/photo/crop_head.tpl
  view/theme/duepuntozero/templates/theme_settings.tpl
  view/theme/frio/templates/admin/blocklist/contact.tpl
  view/theme/frio/templates/admin/site.tpl
  view/theme/frio/templates/admin/users.tpl
  view/theme/frio/templates/contacts-head.tpl
  view/theme/frio/templates/event_form.tpl
  view/theme/frio/templates/event_head.tpl
  view/theme/frio/templates/group_edit.tpl
  view/theme/frio/templates/head.tpl
  view/theme/frio/templates/jot-header.tpl
  view/theme/frio/templates/notifications/notifications.tpl
  view/theme/frio/templates/photos_head.tpl
  view/theme/frio/templates/theme_settings.tpl
  view/theme/frio/templates/threaded_conversation.tpl
  view/theme/quattro/templates/events_reminder.tpl
  view/theme/quattro/templates/theme_settings.tpl
  view/theme/smoothly/templates/bottom.tpl
  view/theme/smoothly/templates/jot-header.tpl
  view/theme/vier/templates/event_head.tpl
Labels: Enhancement, UX

#8214 Fix ItemCCMail
  src/Object/EMail/ItemCCEMail.php
Labels: Bug

#8218 Remove next link when there aren't any introductions in Module\Api\Mastodon\FollowRequests
  src/Module/Api/Mastodon/FollowRequests.php
Labels: API, Bug

#8221 Replace old crepair content
  src/Module/Contact.php
  view/global.css
  view/theme/duepuntozero/style.css
  view/theme/frio/templates/contact/advanced.tpl
  view/theme/smoothly/style.css
Labels: Bug

#8222 AP comments from GNU Social are now working
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement, Federation

#8224 Force avatar update for Contact Advanced page
  src/Module/Contact/Advanced.php
Labels: Enhancement

#8226 Fix wait-for-connection script comment
  bin/wait-for-connection
Labels: Bug

#8215 Cleanup enotify & Extract System emails
  boot.php
  include/enotify.php
  mod/lostpass.php
  mod/removeme.php
  src/App.php
  src/Core/Update.php
  src/Model/User.php
  src/Module/Admin/Site.php
  src/Module/Admin/Users.php
  src/Module/Invite.php
  src/Util/EMailer/MailBuilder.php
  src/Util/EMailer/SystemMailBuilder.php
  src/Util/Emailer.php
  tests/Util/SampleMailBuilder.php
  tests/src/Util/Emailer/MailBuilderTest.php
  tests/src/Util/Emailer/SystemMailBuilderTest.php
  view/templates/admin/site.tpl
  view/templates/email/html.tpl
  view/templates/email/notify/html.tpl
  view/templates/email/notify/text.tpl
  view/templates/email/system/html.tpl
  view/templates/email/system/text.tpl
Labels: Enhancement

#8236 Accessibility: A checkbox is a checkbox
  doc/AddonStorageBackend.md
  doc/smarty3-templates.md
  mod/settings.php
  view/js/main.js
  view/templates/admin/features.tpl
  view/templates/dfrn_request.tpl
  view/templates/field_yesno.tpl
  view/templates/settings/features.tpl
  view/templates/settings/profile/hide-friends.tpl
  view/templates/settings/settings.tpl
  view/theme/duepuntozero/style.css
  view/theme/frio/css/style.css
  view/theme/frio/js/theme.js
  view/theme/frio/templates/dfrn_request.tpl
  view/theme/frio/templates/field_yesno.tpl
  view/theme/frio/templates/settings/features.tpl
  view/theme/frio/templates/settings/settings.tpl
  view/theme/quattro/dark/style.css
  view/theme/quattro/green/style.css
  view/theme/quattro/lilac/style.css
  view/theme/quattro/quattro.less
  view/theme/smoothly/style.css
  view/theme/vier/mobile.css
  view/theme/vier/style.css
Labels: Enhancement

#8237 Accessibility: Improve navigation and contact approval
  src/Module/Notifications/Introductions.php
  view/templates/notifications/intros.tpl
  view/templates/notifications/notification.tpl
  view/theme/frio/templates/field_checkbox.tpl
  view/theme/frio/templates/field_radio.tpl
  view/theme/frio/templates/nav.tpl
  view/theme/frio/templates/notifications/intros.tpl
Labels: Enhancement, UX

#8232 Introduce NotifyEmailBuilder
  include/enotify.php
  src/Util/EMailer/MailBuilder.php
  src/Util/EMailer/NotifyMailBuilder.php
  src/Util/EMailer/SystemMailBuilder.php
  src/Util/Emailer.php
  view/templates/email/notify/html.tpl
  view/templates/email/system/html.tpl
Labels: Enhancement

#8240 Accessibility again: Notifications are now accessible
  src/Content/Nav.php
  view/theme/frio/css/style.css
  view/theme/frio/php/default.php
  view/theme/frio/php/standard.php
  view/theme/frio/templates/nav.tpl
Labels: Enhancement, UX

#8241 Remove a notice about a missing variable
  src/Module/Notifications/Introductions.php
Labels: Bug

#8239 Move Notify "type" and "otype" into own enum classes
  boot.php
  include/api.php
  include/enotify.php
  mod/dfrn_confirm.php
  mod/dfrn_request.php
  mod/item.php
  mod/message.php
  mod/ping.php
  mod/settings.php
  src/Model/Contact.php
  src/Model/Mail.php
  src/Model/Notify.php
  src/Model/Notify/ObjectType.php
  src/Model/Notify/Type.php
  src/Module/Delegation.php
  src/Module/Register.php
  src/Protocol/DFRN.php
Labels: Enhancement

#8242 Asynchronously add contacts to avoid timeout problems
  mod/settings.php
  src/Worker/AddContact.php
Labels: Enhancement, Performance

#8243 Cleanup after yesno field removal
  doc/AddonStorageBackend.md
  mod/dfrn_request.php
  mod/follow.php
  mod/settings.php
  src/Model/Storage/IStorage.php
  src/Module/Admin/Site.php
  src/Module/Notifications/Introductions.php
  src/Module/Settings/Profile/Index.php
  view/templates/settings/profile/hide-friends.tpl
  view/templates/settings/settings.tpl
  view/theme/frio/templates/settings/settings.tpl
Labels: Enhancement

#8250 Issue 8233: Fix remote subscriptions
  mod/dfrn_request.php
Labels: Bug, Federation

#8249 Useless links removed / Item menu is moved to the item actions bar
  src/Model/Profile.php
  src/Object/Post.php
  view/templates/settings/profile/link.tpl
  view/theme/frio/css/style.css
  view/theme/frio/templates/nav.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/vier/templates/profile/vcard.tpl
Labels: Enhancement, UI/Theme, UX

#8253 regen messages.po
  view/lang/C/messages.po
Labels: Translation

#8244 Add ActivityPub in the protocol list in dfrn_request
  mod/dfrn_request.php
  mod/follow.php
  mod/settings.php
  view/templates/auto_request.tpl
  view/templates/dfrn_request.tpl
  view/theme/frio/templates/auto_request.tpl
  view/theme/frio/templates/dfrn_request.tpl
Labels: Docs, Enhancement

#8256 Add license to src\App namespace
  src/App/Arguments.php
  src/App/Authentication.php
  src/App/BaseURL.php
  src/App/Mode.php
  src/App/Module.php
  src/App/Page.php
  src/App/Router.php
Labels: Enhancement

#8259 [frio] Fix notification dropdown
  view/theme/frio/css/style.css
  view/theme/frio/templates/nav.tpl
Labels: Bug, UI/Theme, UX

#8257 Switch to second person in dfrn_request "know you" field
  mod/dfrn_request.php
  mod/follow.php
Labels: Enhancement, UI/Theme, UX

#8260 Accept empty values for profile birthday
  src/Module/Settings/Profile/Index.php
Labels: Bug, UX

#8266 Fix Notification subject
  include/enotify.php
Labels: Bug

#8267 Disable drone.io integration
  mods/.drone.yml
Labels: Enhancement

#8263 New page for remote follow requests
  mod/unfollow.php
  src/Model/Profile.php
  src/Module/RemoteFollow.php
  src/Network/Probe.php
  static/routes.config.php
  view/templates/auto_request.tpl
  view/theme/frio/templates/auto_request.tpl
Labels: Enhancement, Federation

#8230 Changed statistics query for nodeinfo
  src/Model/User.php
Labels: Enhancement, Federation

#8270 Add lint check in travis-ci
  .travis.yml
  composer.json
  composer.lock
  tests/src/Console/ConfigConsoleTest.php
Labels: Enhancement

#8271 [frio] Improve back to top button behavior at bottom of page
  view/theme/frio/js/theme.js
Labels: Bug, Mobile, Theme-specific, UX

#8269 [frio] Prevent more action menu to be clipped by the post box
  view/theme/frio/css/style.css
  view/theme/frio/templates/wall_thread.tpl
Labels: Bug, Enhancement, Theme-specific, UI, UX

#8272 Increase specificity of [url][img] capture regex in BBCode::getAttachedData
  src/Content/Text/BBCode.php
Labels: Bug

#8273 [frio] Fix more action button position on Firefox
  view/theme/frio/css/style.css
Labels: Bug, Theme-specific, UI

#8261 Use profile.about for profile description
  database.sql
  doc/database/db_profile.md
  mod/cal.php
  mod/photos.php
  mod/videos.php
  src/Model/Contact.php
  src/Model/Profile.php
  src/Module/Api/Friendica/Profile/Show.php
  src/Module/Directory.php
  src/Module/NoScrape.php
  src/Module/Profile/Profile.php
  src/Module/Settings/Profile/Index.php
  src/Repository/ProfileField.php
  static/dbstructure.config.php
  view/templates/profile/vcard.tpl
  view/templates/settings/profile/index.tpl
  view/templates/widget/vcard.tpl
  view/theme/duepuntozero/style.css
  view/theme/duepuntozero/templates/profile/vcard.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/frio/templates/settings/profile/index.tpl
  view/theme/frio/templates/widget/vcard.tpl
  view/theme/quattro/dark/style.css
  view/theme/quattro/green/style.css
  view/theme/quattro/lilac/style.css
  view/theme/quattro/quattro.less
  view/theme/quattro/templates/profile/vcard.tpl
  view/theme/vier/templates/profile/vcard.tpl
  view/theme/vier/templates/settings/profile/index.tpl
Labels: Enhancement

#8274 Duplicated "hide-friends" setting removed
  src/Module/Settings/Profile/Index.php
  view/templates/settings/profile/hide-friends.tpl
Labels: Enhancement, UX

#8277 Remove profile about field double HTML escaping
  mod/cal.php
  mod/common.php
  mod/photos.php
  mod/videos.php
  view/templates/profile/vcard.tpl
  view/templates/widget/vcard.tpl
  view/theme/duepuntozero/templates/profile/vcard.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/frio/templates/widget/vcard.tpl
  view/theme/quattro/templates/profile/vcard.tpl
  view/theme/vier/templates/profile/vcard.tpl
Labels: Bug, Enhancement, UX

#8278 [frio] Add loading animation on comment form submit
  mod/photos.php
  src/Object/Post.php
  view/theme/frio/js/theme.js
  view/theme/frio/templates/comment_item.tpl
Labels: Enhancement, Theme-specific, UX

#8279 [frio] Add narrow screen short item action button row
  view/theme/frio/css/style.css
  view/theme/frio/templates/wall_thread.tpl
Labels: Bug, Enhancement, Theme-specific, UI, UX

#8283 Frio: Only display item menu separator when there is something to separate
  view/theme/frio/templates/wall_thread.tpl
Labels: Enhancement, Theme-specific, UI

#8282 Frio: unseen notifications background adjustment
  view/theme/frio/css/style.css
  view/theme/frio/scheme/plusminus.css
Labels: Enhancement, Theme-specific, UI

#8284 Correctly initialize post actions button template variable
  include/conversation.php
  src/Object/Post.php
Labels: Bug

#8292 Issue 8290: Clicking on the notification count does work again
  view/theme/frio/templates/nav.tpl
Labels: Bug, Theme-specific, UX

#8294 No more gender
  mod/poco.php
  src/Factory/Notification/Introduction.php
  src/Model/Contact.php
  src/Model/GContact.php
  src/Model/Profile.php
  src/Module/Contact/Hovercard.php
  src/Module/Notifications/Introductions.php
  src/Network/Probe.php
  src/Object/Notification/Introduction.php
  src/Protocol/Diaspora.php
  src/Protocol/PortableContact.php
  src/Repository/ProfileField.php
  static/dbstructure.config.php
  update.php
  view/templates/notifications/intros.tpl
  view/templates/profile/vcard.tpl
  view/theme/duepuntozero/style.css
  view/theme/duepuntozero/templates/profile/vcard.tpl
  view/theme/frio/css/style.css
  view/theme/frio/templates/notifications/intros.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/quattro/templates/profile/vcard.tpl
  view/theme/smoothly/style.css
  view/theme/vier/templates/profile/vcard.tpl
Labels: Enhancement

#8296 Clarify the effect of "net-publish"
  mod/settings.php
  src/Model/Contact.php
  src/Model/GContact.php
  src/Model/Profile.php
  src/Model/User.php
  src/Module/HoverCard.php
  src/Module/NoScrape.php
  src/Module/Profile/Profile.php
  src/Module/Profile/Status.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
Labels: Docs, Enhancement, Privacy

#8297 [API] Add new api/friendica/events endpoint
  doc/API-Entities.md
  doc/API-Friendica.md
  src/Module/Api/Friendica/Events/Index.php
  static/routes.config.php
Labels: API, New Feature

#8301 Replace "suggestme" with "net-publish"
  mod/poco.php
  mod/settings.php
  view/templates/settings/settings.tpl
  view/theme/frio/templates/settings/settings.tpl
Labels: Enhancement, UI

#8302 Added characters to the disallowed hashtag characters
  include/items.php
Labels: Enhancement

#8313 "Delegations" is renamed to "Accounts"
  mod/settings.php
  src/Content/Nav.php
  src/Module/BaseSettings.php
Labels: Enhancement, UX

#8316 Some more unneeded settings removed
  boot.php
  mod/network.php
  mod/settings.php
  src/Core/System.php
  src/Model/Contact.php
  view/templates/settings/display.tpl
  view/theme/frio/templates/settings/display.tpl
Labels: Enhancement, UX

#8315 Update manifest output with config/theme info
  src/Core/Theme.php
  src/Module/Manifest.php
  view/templates/manifest.tpl
  view/theme/duepuntozero/theme.php
  view/theme/frio/theme.php
  view/theme/quattro/theme.php
  view/theme/smoothly/theme.php
  view/theme/vier/theme.php
Labels: Enhancement, Mobile

#8317 [frio] Remove "Enable Compose page" setting
  view/theme/frio/config.php
  view/theme/frio/css/style.css
  view/theme/frio/js/theme.js
  view/theme/frio/templates/jot.tpl
  view/theme/frio/theme.php
Labels: Enhancement, Theme-specific, UX

#8319 Add new hide dislike user setting
  include/conversation.php
  mod/photos.php
  mod/settings.php
  src/Core/Theme.php
  src/Module/Settings/Display.php
  src/Object/Post.php
  static/routes.config.php
  view/templates/like_noshare.tpl
  view/templates/settings/display.tpl
  view/theme/frio/templates/like_noshare.tpl
  view/theme/frio/templates/settings/display.tpl
  view/theme/quattro/templates/search_item.tpl
  view/theme/vier/templates/search_item.tpl
Labels: Enhancement, UX

#8320 Replace "hidewall" with "net-publish" / other "hidewall" stuff
  mod/msearch.php
  mod/poco.php
  src/Model/Contact.php
Labels: Enhancement

#8322 Move Friendica\Test namespace for better auto-recognition
  composer.json
Labels: Enhancement

#8330 Changed heading in user section of admin panel
  src/Module/Admin/Users.php
Labels: Enhancement, UI

#8331 Expand system.no_auto_update to community, profile statuses and contact conversations pages
  mod/update_contact.php
  src/Module/Settings/Display.php
  src/Module/Update/Community.php
  src/Module/Update/Profile.php
Labels: Enhancement, UX

#8332 [frio] Move actions dropdown in search item view
  view/theme/frio/templates/search_item.tpl
Labels: Bug, Theme-specific, UI

#8337 Add rel="noopener noreferrer" to all target="_blank" links
  doc/BBCode.md
  doc/de/BBCode.md
  doc/de/Chats.md
  doc/de/Developers.md
  src/Content/Text/BBCode.php
  src/Content/Text/HTML.php
  src/Model/Item.php
  src/Model/Term.php
  src/Module/Admin/Tos.php
  tests/datasets/content/text/html/bug-7474.html
  tests/src/Content/Text/BBCodeTest.php
  view/templates/event.tpl
  view/templates/events.tpl
  view/templates/profile/vcard.tpl
  view/templates/shared_content.tpl
  view/templates/wall_thread.tpl
  view/templates/widget_forumlist.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/quattro/templates/events.tpl
  view/theme/quattro/templates/widget_forumlist.tpl
  view/theme/vier/templates/profile/vcard.tpl
  view/theme/vier/templates/widget_forumlist_right.tpl
Labels: Enhancement, Security

#8333 Add about field conversion to HTML in Protocol\ActivityPub\Transmitter
  src/Content/Text/BBCode.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#8329 Remove unused conversation response code
  include/conversation.php
  mod/photos.php
  src/Content/BoundariesPager.php
  src/Object/Post.php
  src/Object/Thread.php
Labels: Bug

#8340 Restore removed announce key in conv_response array in include/conversation
  include/conversation.php
Labels: Bug

#8343 Replace Diaspora mentions before the parsing to HTML in Text\Markdown
  src/Content/Text/Markdown.php
Labels: Bug, Federation

#8344 Only show remote follow button for local profiles
  src/Model/Profile.php
Labels: Bug, Federation

#8345 Store the raw data in a different way
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement, Federation

#8348 Empty travis mysql password variable
  .travis.yml
Labels: Bug

#8324 Introduce user management per console
  mod/regmod.php
  src/Console/NewPassword.php
  src/Console/User.php
  src/Content/Pager.php
  src/Core/Console.php
  src/Core/L10n.php
  src/Model/Register.php
  src/Model/User.php
  src/Module/Admin/Users.php
  view/templates/admin/users.tpl
  view/theme/frio/templates/admin/users.tpl
  view/theme/quattro/templates/admin/users.tpl
Labels: New Feature

#8346 Do not cache Contact::getDetailsByURL result if it doesn't come from the DB
  src/Model/Contact.php
Labels: Bug
