Repository friendica/friendica, pull requests merged in 2021-05, with the labels that each got.

#10189 Improved logging for invalid HTTP signatures
  src/Protocol/ActivityPub/Receiver.php
  src/Util/HTTPSignature.php
Labels: Enhancement

#10190 API: photos are now directly stored as attached data and not in the body anymore
  include/api.php
  mod/item.php
  src/Model/Item.php
  src/Model/Photo.php
  src/Model/Post/Delayed.php
  src/Protocol/Feed.php
Labels: Enhancement

#10192 Add initial support for RTL in user-submitted content
  src/Content/Text/BBCode.php
  view/templates/profile/vcard.tpl
  view/templates/wall_thread.tpl
  view/templates/widget/vcard.tpl
  view/theme/duepuntozero/templates/profile/vcard.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/frio/templates/widget/vcard.tpl
  view/theme/quattro/templates/profile/vcard.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/smoothly/templates/wall_thread.tpl
  view/theme/vier/templates/profile/vcard.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: Enhancement, UX

#10194 Admin panel: Add actual command to the worker queue display
  src/Module/Admin/Queue.php
  view/lang/C/messages.po
  view/templates/admin/queue.tpl
  view/theme/frio/templates/admin/queue.tpl
Labels: Enhancement, UI

#10195 Fix console user config set command
  src/Console/User.php
Labels: Bug

#10197 [composer] Update Level-2/Dice
  composer.lock
Labels: Bug, php8.0

#10196 Improved link detection
  src/Content/PageInfo.php
  src/Model/Item.php
  src/Model/Post/Media.php
Labels: Enhancement

#10201 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10200 API: New function to fetch current user id
  include/api.php
  src/Module/BaseApi.php
Labels: API, Enhancement

#10204 Fix fatal error because of parameter type mismatch
  src/Util/ParseUrl.php
Labels: Bug

#10206 No link guessing for Friendica / Don't show redundant data
  src/Model/Item.php
  src/Model/Post/Media.php
  view/templates/content/link.tpl
Labels: Enhancement

#10207 Replace "curl" calls with centralized "head" function
  src/Content/Text/BBCode.php
Labels: Enhancement

#10208 Prevent self block/ignore
  include/conversation.php
  src/Module/Contact.php
  src/Object/Post.php
  view/lang/C/messages.po
Labels: Bug, UX

#10202 Add console contact command
  src/Console/Contact.php
  src/Core/Console.php
Labels: New Feature

#10211 Don't transmit smiley links to external systems
  src/Content/Text/BBCode.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#10213 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10217 Improve data of shared posts
  src/Model/Item.php
  src/Module/Search/Index.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/DFRN.php
Labels: Enhancement, Federation

#10218 Issue 10184: Fix directory search results
  src/Core/Search.php
Labels: Bug

#10221 IT translation update THX Sylke Vicious
  view/lang/it/messages.po
  view/lang/it/strings.php
Labels: Translation

#10203 Automatic release artifact generation
  .github/workflows/releases.yml
  mods/release-list.txt
Labels: Enhancement

#10225 DE and JA translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/ja/messages.po
  view/lang/ja/strings.php
Labels: Translation

#10224 Re-enable DRONE
  .drone.yml
  .github/workflows/transifex.yml
  mods/.drone.yml
Labels: Enhancement

#10229 Fix several fatal errors
  mod/ping.php
  src/Model/APContact.php
  src/Object/Post.php
  src/Util/ParseUrl.php
Labels: Bug

#10234 [frio] Remove obsolete capitalize directives after updating source translation strings
  view/theme/frio/css/style.css
Labels: Bug, Theme-specific

#10238 Drone FollowUp / Update messages.po
  view/lang/C/messages.po
Labels: Enhancement

#10231 Make birthday time comparison 32-bit safe in Protocol\DFRN
  src/Protocol/DFRN.php
Labels: Bug

#10239 Enable PHP linting per Drone
  .drone.yml
  .github/workflows/lint.yml
Labels: Enhancement

#10240 Enable PHP-CS Check per Drone
  .drone.yml
  .github/workflows/lint.yml
Labels: Enhancement

#10241 Optimize PHP-CS check
  .drone.yml
Labels: Enhancement

#10243 API: The instance record had got a malformatted value
  src/Object/Api/Mastodon/Instance.php
Labels: API, Bug

#10245 API: Support OAuth client credentials
  doc/API-Mastodon.md
  src/Module/OAuth/Token.php
Labels: API, Enhancement

#10244 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10248 API: Account actions
  doc/API-Mastodon.md
  src/Factory/Api/Mastodon/Account.php
  src/Factory/Api/Mastodon/Relationship.php
  src/Model/Contact.php
  src/Module/Api/Mastodon/Accounts/Block.php
  src/Module/Api/Mastodon/Accounts/Follow.php
  src/Module/Api/Mastodon/Accounts/Mute.php
  src/Module/Api/Mastodon/Accounts/Unblock.php
  src/Module/Api/Mastodon/Accounts/Unfollow.php
  src/Module/Api/Mastodon/Accounts/Unmute.php
  src/Module/Api/Mastodon/Favourited.php
  src/Object/Api/Mastodon/Relationship.php
  static/routes.config.php
Labels: API, New Feature

#10251 Move PHP tests to Drone
  .drone.yml
  .github/workflows/php.yml
  bin/dev/setup-phpunit.sh
Labels: Enhancement

#10255 DE and JA translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/ja/messages.po
  view/lang/ja/strings.php
Labels: Translation

#10253 API: We now can upload photos
  doc/API-Mastodon.md
  src/Model/Item.php
  src/Model/Photo.php
  src/Module/Api/Mastodon/Media.php
  src/Module/Api/Mastodon/Statuses.php
  static/routes.config.php
Labels: API, Enhancement

#10259 Upgrade PHPUnit tests
  tests/bootstrap.php
  tests/datasets/api.fixture.php
  tests/legacy/ApiTest.php
  tests/src/Content/ItemTest.php
  tests/src/Core/Cache/ArrayCacheTest.php
  tests/src/Core/Cache/MemcacheCacheTest.php
  tests/src/Core/Cache/MemcachedCacheTest.php
  tests/src/Core/Lock/ArrayCacheLockTest.php
  tests/src/Core/Lock/MemcacheCacheLockTest.php
  tests/src/Core/Lock/MemcachedCacheLockTest.php
  tests/src/Core/Lock/SemaphoreLockTest.php
  tests/src/Util/Emailer/MailBuilderTest.php
  tests/src/Util/Logger/StreamLoggerTest.php
Labels: Enhancement

#10257 Fetch Json-LD definitions from local ressources
  src/Model/APContact.php
  src/Util/JsonLD.php
  src/Util/LDSignature.php
  static/activitystreams.jsonld
  static/identity-v1.jsonld
  static/security-v1.jsonld
Labels: Bug

#10260 Fix fatal errors / added some API todo
  doc/API-Mastodon.md
  src/Model/Item.php
  src/Protocol/DFRN.php
Labels: API, Bug

#10261 API: Search endpoint
  doc/API-Mastodon.md
  src/Module/Api/Mastodon/Accounts/Search.php
  src/Module/Api/Mastodon/Notifications.php
  src/Module/Api/Mastodon/Search.php
  src/Module/BaseApi.php
  static/routes.config.php
Labels: API, New Feature

#10265 API: Reworked request parameter handling
  src/Module/Api/Mastodon/Accounts/Followers.php
  src/Module/Api/Mastodon/Accounts/Following.php
  src/Module/Api/Mastodon/Accounts/Search.php
  src/Module/Api/Mastodon/Accounts/Statuses.php
  src/Module/Api/Mastodon/Apps.php
  src/Module/Api/Mastodon/Blocks.php
  src/Module/Api/Mastodon/Bookmarks.php
  src/Module/Api/Mastodon/Directory.php
  src/Module/Api/Mastodon/Favourited.php
  src/Module/Api/Mastodon/FollowRequests.php
  src/Module/Api/Mastodon/Lists/Accounts.php
  src/Module/Api/Mastodon/Mutes.php
  src/Module/Api/Mastodon/Notifications.php
  src/Module/Api/Mastodon/Timelines/Home.php
  src/Module/Api/Mastodon/Timelines/ListTimeline.php
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
Labels: API, Enhancement

#10267 IT and JA translation updates
  view/lang/it/messages.po
  view/lang/it/strings.php
  view/lang/ja/messages.po
  view/lang/ja/strings.php
Labels: Translation

#10268 API: Parameter cleanup
  src/Factory/Api/Mastodon/Error.php
  src/Module/Api/Friendica/Events/Index.php
  src/Module/Api/Mastodon/Accounts/Followers.php
  src/Module/Api/Mastodon/Accounts/Following.php
  src/Module/Api/Mastodon/Accounts/Note.php
  src/Module/Api/Mastodon/Accounts/Relationships.php
  src/Module/Api/Mastodon/Accounts/Statuses.php
  src/Module/Api/Mastodon/Blocks.php
  src/Module/Api/Mastodon/Bookmarks.php
  src/Module/Api/Mastodon/Favourited.php
  src/Module/Api/Mastodon/Lists.php
  src/Module/Api/Mastodon/Lists/Accounts.php
  src/Module/Api/Mastodon/Mutes.php
  src/Module/Api/Mastodon/Notifications.php
  src/Module/Api/Mastodon/Search.php
  src/Module/Api/Mastodon/Suggestions.php
  src/Module/Api/Mastodon/Timelines/Home.php
  src/Module/Api/Mastodon/Timelines/ListTimeline.php
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
  src/Module/Api/Mastodon/Timelines/Tag.php
  src/Module/Api/Mastodon/Trends.php
  src/Module/BaseApi.php
  src/Module/OAuth/Authorize.php
  src/Module/OAuth/Token.php
Labels: API, Enhancement

#10269 updated JA translation THX daingewuvzeevisiddfddd
  view/lang/ja/messages.po
  view/lang/ja/strings.php
Labels: Translation

#10270 Add RTL support for item body in search and photo body
  view/templates/photo_item.tpl
  view/templates/search_item.tpl
  view/templates/wall_thread.tpl
  view/theme/frio/templates/photo_item.tpl
  view/theme/frio/templates/search_item.tpl
  view/theme/quattro/templates/search_item.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/smoothly/templates/search_item.tpl
  view/theme/smoothly/templates/wall_thread.tpl
  view/theme/vier/templates/search_item.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: Bug, UX

#10271 API: New endpoint "verify_credentials" added
  doc/API-Mastodon.md
  src/Module/Api/Mastodon/Apps/VerifyCredentials.php
  static/routes.config.php
Labels: API, New Feature

#10275 Move the 'authenticate' hook deeper into the authentication flow so t…
  doc/Addons.md
  src/Model/User.php
  src/Security/Authentication.php
Labels: Addons, Enhancement

#10276 API: Support for private mails
  doc/API-Mastodon.md
  src/DI.php
  src/Factory/Api/Mastodon/Conversation.php
  src/Factory/Api/Mastodon/Status.php
  src/Module/Api/Mastodon/Conversation.php
  src/Module/Api/Mastodon/Conversations/Read.php
  src/Module/Api/Mastodon/Timelines/Direct.php
  src/Object/Api/Mastodon/Conversation.php
  src/Protocol/ActivityPub/Transmitter.php
  static/routes.config.php
Labels: API, New Feature

#10282 Wrong class path
  src/Module/Api/Mastodon/Conversations.php
  src/Module/Api/Mastodon/Conversations/Read.php
  static/routes.config.php
  view/lang/C/messages.po
Labels: Bug

#10280 Fix Message button.
  src/Model/Profile.php
Labels: Bug

#10284 [vier] Keep the introductions notification badge from claiming its own line!
  view/theme/vier/templates/nav.tpl
Labels: Bug, Theme-specific, UI

#10286 Don't delete local tombstone contacts
  src/Model/Contact.php
  src/Util/HTTPSignature.php
Labels: Bug, Federation

#10288 API: improved mail handling
  database.sql
  src/Content/Text/BBCode.php
  src/Factory/Api/Mastodon/Status.php
  src/Model/Mail.php
  src/Module/Api/Mastodon/Timelines/Direct.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/ExpirePosts.php
  src/Worker/RemoveContact.php
  static/dbstructure.config.php
  update.php
Labels: API, Enhancement

#10290 Fixes notice
  src/Module/NoScrape.php
  src/Module/OAuth/Authorize.php
Labels: Bug

#10296 mention the required function in the install wizard (issue10293)
  src/Core/Installer.php
  view/lang/C/messages.po
Labels: Bug, Installation

#10297 fix failing test for the installer wizard
  tests/src/Core/InstallerTest.php
Labels: Bug

#10299 Issue 10287: Make block and ignore work for the API as well
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
Labels: API, Bug

#10295 Fix PHP 7.0 Coding Standards
  include/api.php
  mod/settings.php
  mod/unfollow.php
  mod/update_notes.php
  src/Content/Widget/TagCloud.php
  src/Module/Attach.php
  src/Network/HTTPRequest.php
  src/Object/Api/Mastodon/Status.php
Labels: Bug

#10292 Fix inserting mails
  src/Model/Mail.php
Labels: Bug

#10304 Fix missing media on posts to Mastodon
  src/Model/Post/Media.php
Labels: Bug

#10300 Issue 10264: Remote comments for visitors
  mod/dfrn_poll.php
  src/App.php
  src/Object/Post.php
Labels: Bug, Federation

#10305 Fix warning "reset() expects parameter 1 to be array, null given"
  src/Object/Api/Mastodon/Status.php
Labels: API, Bug

#10283 Fix message button using a more targeted approach.
  src/Model/Profile.php
Labels: Bug, UX

#10307 Fix PHPUnit 8 warnings
  tests/legacy/ApiTest.php
  tests/src/Model/Storage/FilesystemStorageTest.php
  tests/src/Util/BasePathTest.php
  tests/src/Util/Config/ConfigFileLoaderTest.php
  tests/src/Util/EMailerTest.php
  tests/src/Util/Logger/AbstractLoggerTest.php
  tests/src/Util/Logger/StreamLoggerTest.php
  tests/src/Util/Logger/SyslogLoggerTest.php
Labels: Enhancement

#10308 added #friendica at libera.chat to the community chat rooms
  doc/FAQ.md
  doc/Home.md
  doc/de/FAQ.md
  doc/de/Home.md
Labels: Docs

#10294 New class to process HTTP input data
  src/Module/Api/Mastodon/Accounts/UpdateCredentials.php
  src/Util/HTTPInputData.php
  tests/Util/HTTPInputDataDouble.php
  tests/datasets/http/form-urlencoded-json.httpinput
  tests/datasets/http/form-urlencoded.httpinput
  tests/datasets/http/multipart-file.httpinput
  tests/datasets/http/multipart.httpinput
  tests/src/Util/HTTPInputDataTest.php
Labels: API, Enhancement

#10310 Issue 10287: Don't show ignored and blocked posts
  database.sql
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: API, Bug

#10311 console autoinstall: handle `-f/--file` as single config file
  src/Console/AutomaticInstallation.php
Labels: Enhancement, Installation

#10315 Issue 10219: Don't display follow activities
  mod/photos.php
Labels: Bug, Federation

#10316 Issue 9926: Limit the length of data to store in the apcontact table
  src/Database/DBStructure.php
  src/Model/APContact.php
Labels: Bug, Federation

#10318 Separate the char from the binary handling
  src/Database/DBStructure.php
Labels: Bug

#10317 Re-activate API tests
  .codecov.yml
  .drone.yml
  tests/DatabaseTestTrait.php
  tests/Util/Database/ExtendedPDO.php
  tests/Util/Database/StaticDatabase.php
  tests/legacy/ApiTest.php
  tests/phpunit.xml
Labels: Bug, php8.0

#10319 documentation updates
  doc/FAQ.md
  doc/Home.md
  doc/de/FAQ.md
  doc/de/Home.md
Labels: Docs

#10320 Avoid notices because of empty fields
  src/Model/APContact.php
  src/Util/HTTPSignature.php
Labels: Bug

#10321 Downgrading PHP 7.4 incompatible fread/fwrite checks
  src/Util/HTTPInputData.php
Labels: Bug

#10322 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10323 Issue 10306: Improve local delivery
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Post.php
  src/Model/User.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Util/Network.php
  src/Worker/Delivery.php
  src/Worker/Notifier.php
Labels: Bug

#10324 Issue 10262: Don't accept BCC posts from non followers
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, UX

#10327 Fix resharing Diaspora posts with only pictures
  src/Module/Item/Activity.php
Labels: Bug, Federation

#10328 Enable Drone Caching
  .drone.yml
Labels: Enhancement

#10330 Improved logging for local probing, avoid worker fork
  src/Model/Contact.php
  src/Model/Contact/Relation.php
Labels: Performance

#10329 API: Unified request parameter handling
  doc/API-Mastodon.md
  src/Module/Api/Mastodon/Lists.php
  src/Module/Api/Mastodon/Media.php
  src/Module/Api/Mastodon/Statuses.php
  src/Module/BaseApi.php
Labels: API, Enhancement

#10333 More logging for the contact discovery
  src/Model/Contact/Relation.php
Labels: Enhancement

#10332 simplify the calendar download
  mod/cal.php
  mod/events.php
  src/Content/Widget/CalendarExport.php
Labels: Enhancement, UX

#10335 Fix PHP Notice: Undefined index: isForum in /src/Protocol/ActivityPub/Processor.php on line 605
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation

#10336 Issue 9984: Fix the causer name on reshares
  include/conversation.php
  view/lang/C/messages.po
Labels: Bug

#10339 Avoid warning "array_merge(): Expected parameter 2 to be an array, null given"
  src/Module/Api/Mastodon/Apps.php
Labels: API, Bug

#10337 Replace build.xml with mods/phpdoc-config.xml
  .gitignore
  build.xml
  mods/phpdoc-config.xml
Labels: Docs, Enhancement

#10338 Issue 9923: Fix DB Error 1055
  src/Module/Search/Index.php
  src/Worker/ExpirePosts.php
Labels: Bug

#10340 Add relevant link after media links had been removed
  src/Model/Item.php
Labels: Bug

#10341 Ensure that the public contact exists when a user is created
  src/Model/Contact.php
Labels: Bug, Performance

#10343 DE, JA translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/ja/messages.po
  view/lang/ja/strings.php
Labels: Translation

#10344 Update avatar after user creation
  src/Model/User.php
Labels: Bug

#10345 Ensure nodeinfo-provided protocols are strings in Model\GServer::parseNodeinfo2
  src/Model/GServer.php
Labels: Bug

#10346 Fix several notices
  include/enotify.php
  mod/item.php
  mod/tagrm.php
  src/Content/Item.php
  src/Content/Text/BBCode.php
  src/Model/Item.php
  update.php
Labels: Bug

#10347 Update Composer and its dependencies ahead of the stable release
  bin/composer.phar
  composer.lock
Labels: Enhancement, Security
