Repository friendica/friendica, pull requests merged in 2021-09, with the labels that each got.

#10648 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10649 missing $ in template
  view/templates/admin/site.tpl
Labels: Bug

#10650 Improve translation for Storage module
  src/Module/Admin/Storage.php
  view/lang/C/messages.po
  view/templates/admin/storage.tpl
  view/theme/frio/templates/admin/storage.tpl
Labels: Enhancement, Translation

#10653 Issue 10640 - Inverse user display settings
  src/Module/Settings/Display.php
  view/lang/C/messages.po
  view/templates/settings/display.tpl
  view/theme/frio/templates/settings/display.tpl
Labels: UX, Enhancement

#10655 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10656 updating date of security.txt validity
  security.txt
Labels: Docs

#10654 Issue 10651: remote comments appeared as own posts
  src/Module/Diaspora/Fetch.php
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#10658 Rename Storage Backend labels
  src/Module/Admin/Storage.php
  view/lang/C/messages.po
  view/templates/admin/storage.tpl
  view/theme/frio/templates/admin/storage.tpl
Labels: UX, Enhancement

#10657 Don't offer to unfollow yourself
  src/Content/Widget/VCard.php
Labels: Bug, UX

#10660 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10659 Adding gravity to avoid notices
  src/Module/Diaspora/Fetch.php
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#10258 Create PHP release workflow in drone
  .drone.yml
  .github/workflows/releases.yml
  mods/release-list-exclude.txt
  mods/release-list-include.txt
Labels: Enhancement

#10661 Check for user array key before using it in include/conversation
  include/conversation.php
Labels: Bug

#10662 Drone release fixings
  .drone.yml
Labels: Bug

#10665 RU translations THX Alexander An
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#10667 Fix Photo::delete()
  src/Model/Photo.php
Labels: Bug

#10669 Remove all traces of "rino"
  src/Module/Admin/Site.php
  static/settings.config.php
  view/lang/C/messages.po
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement

#10670 Distinguish between public and private contact in contact actions
  src/Database/DBA.php
  src/Database/Database.php
  src/Module/Contact.php
  view/lang/C/messages.po
  view/templates/contact_edit.tpl
  view/templates/contacts-template.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/frio/templates/contacts-template.tpl
  view/theme/vier/templates/contact_edit.tpl
Labels: Bug

#10674 Convert the two remaining "Disable..." setting names to "Enable..."
  mod/settings.php
  view/lang/C/messages.po
Labels: UX, Enhancement

#10675 Fix for PR 10674: Changing the template variables according to the last changes
  view/templates/settings/connectors.tpl
  view/theme/frio/templates/settings/connectors.tpl
Labels: Bug

#10676 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10677 Add drone graph execution
  .drone.yml
Labels: Bug

#10681 Add GPG signing for drone artifacts
  .drone.yml
Labels: Enhancement

#10682 update to the INSTALL documentation
  doc/Install.md
  doc/de/Install.md
Labels: Docs

#10673 Add form security token to contact actions
  src/Module/Contact.php
  view/templates/contacts-template.tpl
  view/theme/frio/templates/contacts-template.tpl
Labels: New Feature, Security

#10685 HU translation updated THX Balázs Úr
  view/lang/hu/messages.po
  view/lang/hu/strings.php
Labels: Translation

#10688 Move unsecured GET endpoint handlers before security token check in Module\Contact
  src/Module/Contact.php
Labels: Bug, UX

#10689 [frio] Use correct admin endpoint for block/deletion in Admin\Users\Active
  view/theme/frio/templates/admin/users/active.tpl
Labels: Bug

#10694 Fix drone artifact compression parameter
  .drone.yml
Labels: Bug

#10695 Fix commenting on public posts
  src/Model/Item.php
  src/Worker/Notifier.php
Labels: Bug, UX

#10696 Use post type "photo" for multiple photos as well
  src/Content/Text/BBCode.php
Labels: Bug, Federation

#10697 Prevent expandTags to be performed on existing links in Module\Api\Mastodon\Statuses
  src/Content/Text/BBCode.php
  src/Module/Api/Mastodon/Statuses.php
  tests/src/Content/Text/BBCodeTest.php
Labels: Bug

#10701 Fixing #10699 (prohibits blocking and ignoreing from the photo menu)
  include/conversation.php
  src/Object/Post.php
  src/Object/Thread.php
Labels: Bug, UI

#10702 DE, RU translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#10693 Add the possibility to use a different configuration directory
  doc/Config.md
  src/App.php
  src/Factory/ConfigFactory.php
  src/Module/Admin/Summary.php
  src/Util/ConfigFileLoader.php
  static/dependencies.config.php
  tests/Util/VFSTrait.php
  tests/src/Core/Cache/DatabaseCacheTest.php
  tests/src/Core/Lock/DatabaseLockDriverTest.php
  tests/src/Core/StorageManagerTest.php
  tests/src/Model/ProcessTest.php
  tests/src/Model/Storage/DatabaseStorageTest.php
  tests/src/Util/Config/ConfigFileLoaderTest.php
Labels: Enhancement, Security

#10703 update FR translations THX MrPetovan
  view/lang/fr/messages.po
  view/lang/fr/strings.php
Labels: Translation

#10707 Issue 10706: Publish public custom fields in AP
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#10709 HU translation updated THX Balázs Úr
  view/lang/hu/messages.po
  view/lang/hu/strings.php
Labels: Translation

#10711 Fixed indendation
  src/Protocol/ActivityPub.php
Labels: Bug

#10712 Avoid duplicated filed posts
  include/conversation.php
Labels: Bug, UX

#10714 Link to displayed contact URL no matter the "Stay local" setting value
  view/theme/frio/templates/contact_edit.tpl
  view/theme/vier/templates/contact_edit.tpl
Labels: Bug, UX

#10713 Use CSRF token as name and value for contact deletion confirm form
  src/Module/Contact.php
  view/templates/confirm.tpl
  view/theme/frio/templates/confirm.tpl
  view/theme/frio/templates/contact_edit.tpl
Labels: Bug, UX

#10717 Bugfix Drone/Docker: forgot a file
  mods/release-list-include.txt
Labels: Bug

#10715 Simplify max_data parameter for Temporal::getDateTimeField in include/conversation
  include/conversation.php
  src/Module/Item/Compose.php
Labels: Enhancement

#10666 regen CREDITS for the 2021.09 release
  CREDITS.txt
Labels: Docs

#10719 Fix fatal error when following mail accounts
  mod/follow.php
Labels: Bug

#10704 Fix various Notices
  src/Database/Database.php
  src/Model/Contact.php
  src/Module/Contact.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
Labels: Bug

#10721 Issue 10720: Use different path scheme for user avatars
  mod/msearch.php
  src/Model/Contact.php
  src/Model/User.php
  src/Module/Delegation.php
  src/Module/NoScrape.php
  src/Module/Register.php
  src/Module/Xrd.php
  src/Network/Probe.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
Labels: Bug

#10731 Make posts on the profile page writable
  include/conversation.php
  src/Object/Thread.php
Labels: Bug, UX

#10733 Drone: Add database version check
  .drone.yml
Labels: Enhancement

#10730 Display the public contacts for profile visitors
  src/Content/Widget/ContactBlock.php
  src/Model/Profile.php
Labels: Bug, UX

#10749 RU translation updates THX Alexander An
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#10748 Improve compacting error logging in Util\JsonLD
  src/Util/JsonLD.php
Labels: Enhancement

#10621 2021.09 CHANGELOG
  CHANGELOG
Labels: Docs

#10758 Adapt permissions
  .drone.yml
  view/lang/C/messages.po
Labels: Bug

#10761 Add new hook to support unfollow contacts on non-native networks
  doc/Addons.md
  doc/de/Addons.md
  mod/unfollow.php
  src/Model/Contact.php
Labels: New Feature, Addons

#10763 Limit /redir links to private posts
  include/conversation.php
Labels: UX, Enhancement

#10764 Return early when parent-related record isn't found
  src/Model/Mail.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
Labels: Bug

#10770 Issue 10768: Avoid MySQL problems when upgrading both index and structure
  src/Database/DBStructure.php
Labels: Bug

#10771 Handle reading empty file in ReversedFileReader
  src/Util/ReversedFileReader.php
  tests/datasets/log/empty.friendica.log.txt
  tests/src/Model/Log/ParsedLogIteratorTest.php
Labels: Bug

#10775 Fix commenting on profile pages
  mod/item.php
Labels: Bug, UX

#10776 RU translations THX Alexander An
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation
