Repository friendica/friendica, pull requests merged in 2021-01, with the labels that each got.

#9738 update the CREDITS.txt for the 2021.01 release
  CREDITS.txt
Labels: Docs

#9739 2021.01 CHANGELOG
  CHANGELOG
Labels: Docs

#9750 [ImgBot] Optimize images
  doc/img/editor_frio.png
  doc/img/editor_vier.png
  doc/img/vier_icons.png
  images/article.gif
  images/b_drop.gif
  images/b_dropshow.gif
  images/beer_mug.gif
  images/camera-icon.gif
  images/discourse.png
  images/friendica-404_svg_flexy-o-hare.png
  images/friendica-404_svg_hare-bottom-light-inside.png
  images/friendica.svg
  images/globe.gif
  images/humane-tech-badge.svg
  images/larrw.gif
  images/link-icon.gif
  images/lock_icon.gif
  images/pause.gif
  images/person-300.jpg
  images/play.gif
  images/rarrw.gif
  images/rotator.gif
  images/smiley-Oo.gif
  images/smiley-bangheaddesk.gif
  images/smiley-brokenheart.gif
  images/smiley-heart.gif
  images/smiley-shaka.gif
  images/spencil.gif
  images/unlock_icon.gif
  images/youtube_icon.gif
  spec/dfrn2_contact_confirmation.svg
  spec/dfrn2_contact_request.svg
  view/theme/duepuntozero/login-bg.gif
  view/theme/frio/font/open_sans/fonts/Bold/OpenSans-Bold.svg
  view/theme/frio/font/open_sans/fonts/BoldItalic/OpenSans-BoldItalic.svg
  view/theme/frio/font/open_sans/fonts/ExtraBold/OpenSans-ExtraBold.svg
  view/theme/frio/font/open_sans/fonts/ExtraBoldItalic/OpenSans-ExtraBoldItalic.svg
  view/theme/frio/font/open_sans/fonts/Italic/OpenSans-Italic.svg
  view/theme/frio/font/open_sans/fonts/Light/OpenSans-Light.svg
  view/theme/frio/font/open_sans/fonts/LightItalic/OpenSans-LightItalic.svg
  view/theme/frio/font/open_sans/fonts/Regular/OpenSans-Regular.svg
  view/theme/frio/font/open_sans/fonts/Semibold/OpenSans-Semibold.svg
  view/theme/frio/font/open_sans/fonts/SemiboldItalic/OpenSans-SemiboldItalic.svg
  view/theme/frio/frameworks/bootstrap/fonts/glyphicons-halflings-regular.svg
  view/theme/frio/img/friendica-logo.svg
  view/theme/frio/scheme/plusminus.jpg
  view/theme/smoothly/images/icons.svg
  view/theme/smoothly/images/larrow.gif
  view/theme/smoothly/images/login-bg.gif
  view/theme/smoothly/images/rarrow.gif
  view/theme/vier/font/fontawesome-webfont.svg
  view/theme/vier/icons.svg
Labels: Enhancement, Performance

#9752 We can now fork worker
  bin/daemon.php
  bin/worker.php
  index.php
  src/App/Mode.php
  src/Core/Process.php
  src/Core/Worker.php
  static/defaults.config.php
Labels: Enhancement, Performance

#9755 The frontend worker is removed
  doc/Settings.md
  doc/de/Settings.md
  src/App.php
  src/Core/Installer.php
  src/Core/Worker.php
  src/Module/Admin/Site.php
  src/Module/Worker.php
  static/defaults.config.php
  tests/src/Core/InstallerTest.php
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement, Installation

#9757 [non-Frio] Add edited date to post display
  view/templates/wall_thread.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/smoothly/templates/wall_thread.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: Bug, Theme-specific, UX

#9758 reminder that we removed the frontend worker added to the CHANGELOG
  CHANGELOG
Labels: Docs

#9759 Issue 9746: Delete uri-id orphans
  update.php
Labels: Enhancement, Installation

#9756 [frio] Add share dropdown to mobile post view
  src/Object/Post.php
  view/lang/C/messages.po
  view/theme/frio/templates/wall_thread.tpl
Labels: Enhancement, Mobile, Theme-specific, UX

#9768 Fix relay handling
  src/Console/Relay.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#9766 Improved direction and protocol detection
  mod/dfrn_notify.php
  mod/events.php
  mod/item.php
  mod/pubsub.php
  src/Model/Conversation.php
  src/Model/Event.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  src/Worker/Delivery.php
Labels: Enhancement, Federation

#9771 Store server protocol
  database.sql
  src/Model/GServer.php
  src/Model/PushSubscriber.php
  src/Worker/APDelivery.php
  src/Worker/Delivery.php
  static/dbstructure.config.php
Labels: Enhancement, Federation

#9772 Deliver to Friendica via AP if possible
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#9779 Issue 9705: Perform an age check when the post isn't fetched
  src/Model/Item.php
Labels: Bug, Federation, UX

#9780 Create plink if missing
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#9781 Issue 9777: Fix to deliver public posts to Diaspora again
  src/Worker/Notifier.php
Labels: Bug, Federation

#9794 Fix: mobile: Frio dark , +change side bar padding
  view/theme/frio/css/style.css
Labels: Enhancement, Theme-specific, UI

#9793 View for the item/post tables
  database.sql
  src/Model/Item.php
  src/Model/Post.php
  src/Protocol/Diaspora.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement

#9798 Frio - Dim tags and mention
  view/theme/frio/css/style.css
Labels: Enhancement, Theme-specific, UI

#9808 Fix notice "Undefined index: internal-verb"
  include/api.php
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
Labels: Bug

#9810 Fix "Item couldn't be fetched."
  database.sql
  include/api.php
  static/dbstructure.config.php
  static/dbview.config.php
  tests/datasets/api.fixture.php
Labels: Bug

#9815 "item" is replaced by "post-view" / postupdate check added
  boot.php
  database.sql
  include/api.php
  mod/photos.php
  mod/ping.php
  src/Content/ForumManager.php
  src/Content/Widget/TagCloud.php
  src/Core/Update.php
  src/Database/DBA.php
  src/Database/Database.php
  src/Database/PostUpdate.php
  src/Factory/Notification/Notification.php
  src/Model/Event.php
  src/Model/Group.php
  src/Model/Item.php
  src/Model/ItemContent.php
  src/Model/Nodeinfo.php
  src/Model/Notify.php
  src/Model/Tag.php
  src/Model/UserItem.php
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
  src/Module/Profile/Status.php
  src/Module/Update/Profile.php
  src/Object/Api/Friendica/Notification.php
  src/Protocol/DFRN.php
  static/dbstructure.config.php
  static/dbview.config.php
  tests/Util/Database/StaticDatabase.php
  tests/datasets/api.fixture.php
  tests/datasets/config/A.config.php
  tests/datasets/config/B.config.php
  tests/src/Console/AutomaticInstallationConsoleTest.php
  update.php
Labels: Bug, Enhancement

#9822 All item selects are now done by the post class
  database.sql
  include/api.php
  include/enotify.php
  mod/notes.php
  src/Model/Contact/Relation.php
  src/Model/Item.php
  src/Model/Post.php
  src/Model/UserItem.php
  src/Module/Conversation/Community.php
  src/Module/Profile/Status.php
  src/Module/Settings/UserExport.php
  src/Object/Post.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/DFRN.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement

#9826 The "icid" field is deprecated
  database.sql
  src/Model/Item.php
  src/Worker/Expire.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement

#9829 fix: navbar css
  view/theme/frio/css/style.css
Labels: Bug, Mobile, Theme-specific, UI

#9830 fix: undefined search tag, sidebar colors #9789, #9811
  view/theme/frio/css/style.css
  view/theme/frio/js/theme.js
Labels: Bug, Mobile, Theme-specific, UI, UX

#9841 Fix wrong uses of DI::l10n() in Core\Update
  src/Core/Update.php
  view/lang/C/messages.po
Labels: Bug

#9828 Remove strictly numeric tags exception
  src/Content/Text/BBCode.php
Labels: Bug, UX

#9843 Legacy file/category storage is removed
  database.sql
  mod/editpost.php
  mod/item.php
  src/Content/Item.php
  src/Content/Widget.php
  src/Model/FileTag.php
  src/Model/Item.php
  src/Model/Post.php
  src/Model/Post/Category.php
  src/Module/Filer/RemoveTag.php
  src/Module/Filer/SaveTag.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement

#9845 Add eslint, prettier config files to Frio folder
  .editorconfig
  view/theme/frio/.eslintrc.json
  view/theme/frio/.prettierrc
Labels: Enhancement

#9849 Don't create a user-item entry on default
  src/Model/Item.php
  src/Model/Post/User.php
Labels: Bug

#9850 frio: formating, otherwise untouched
  view/theme/frio/css/font-awesome.custom.css
  view/theme/frio/css/hovercard.css
  view/theme/frio/css/mod_admin.css
  view/theme/frio/css/style.css
  view/theme/frio/js/compose.js
  view/theme/frio/js/event_edit.js
  view/theme/frio/js/filebrowser.js
  view/theme/frio/js/hovercard.js
  view/theme/frio/js/jot.js
  view/theme/frio/js/mod_admin.js
  view/theme/frio/js/mod_contacts.js
  view/theme/frio/js/mod_display.js
  view/theme/frio/js/mod_events.js
  view/theme/frio/js/mod_group.js
  view/theme/frio/js/mod_notifications.js
  view/theme/frio/js/mod_photos.js
  view/theme/frio/js/modal.js
  view/theme/frio/js/textedit.js
  view/theme/frio/js/theme.js
  view/theme/frio/scheme/black.css
  view/theme/frio/scheme/dark.css
  view/theme/frio/scheme/koyu-dark.css
  view/theme/frio/scheme/love-music.css
  view/theme/frio/scheme/plusminus.css
  view/theme/frio/templates/nav.tpl
Labels: Enhancement

#9844 [frio] Redo right offcanvas menu
  view/theme/frio/css/style.css
  view/theme/frio/js/theme.js
  view/theme/frio/templates/nav.tpl
Labels: Mobile, Theme-specific, UX

#9851 Replace obsolete call to Item::selectFirstThreadForUser in Module\Item\Ignore
  src/Module/Item/Ignore.php
Labels: Bug

#9852 Prevent hashtag parsing and replacement in image alternative text
  src/Content/Text/BBCode.php
  src/Model/Item.php
Labels: Bug, UX

#9833 [frio] Add block author in post more dropdown
  mod/item.php
  src/App/Page.php
  src/Object/Post.php
  view/lang/C/messages.po
  view/theme/frio/js/textedit.js
  view/theme/frio/templates/js_strings.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: New Feature, Theme-specific, UX

#9857 Remove leading space in displayed public tags in profile page
  src/Module/Profile/Profile.php
Labels: Bug, UX

#9783 FAQ cleanup
  doc/FAQ.md
Labels: Docs

#9860 Rename notify classes according the feature name, not the table name
  boot.php
  include/api.php
  include/enotify.php
  mod/dfrn_confirm.php
  mod/dfrn_request.php
  mod/item.php
  mod/message.php
  mod/ping.php
  mod/settings.php
  src/Collection/Notifications.php
  src/DI.php
  src/Factory/Notification/Notification.php
  src/Model/Contact.php
  src/Model/FContact.php
  src/Model/Mail.php
  src/Model/Notification.php
  src/Model/Notification/ObjectType.php
  src/Model/Notification/Type.php
  src/Module/Delegation.php
  src/Module/Register.php
  src/Object/Api/Friendica/Notification.php
  src/Protocol/DFRN.php
  src/Repository/Notification.php
  tests/datasets/api.fixture.php
  update.php
Labels: Enhancement

#9861 Frio: mobile: secondnav arrow
  view/theme/frio/css/style.css
  view/theme/frio/templates/common_tabs.tpl
Labels: Enhancement, Theme-specific, UI

#9862 FAQ "Find Help" section cleanup
  doc/FAQ.md
Labels: Docs

#9864 correction of contributor name
  CREDITS.txt
Labels: Bug, Docs

#9873 New "post-user" structure, new update functionality
  database.sql
  src/Model/Item.php
  src/Model/Post.php
  src/Model/Post/User.php
  src/Worker/Expire.php
  src/Worker/RemoveContact.php
  static/dbstructure.config.php
  static/dbview.config.php
  tests/datasets/api.fixture.php
  update.php
Labels: Enhancement

#9874 Prevent permissionset foreign key constraint
  src/Worker/ExpireAndRemoveUsers.php
Labels: Bug

#9876 Set thr-parent when importing mails
  src/Worker/OnePoll.php
Labels: Addons, Bug

#9877 Accept "application/json" as application type for ActivityPub
  src/Protocol/ActivityPub.php
Labels: Enhancement, Federation

#9880 Avoid non numeric parameter
  src/Model/User.php
  src/Worker/Notifier.php
Labels: Bug

#9883 Updating support channel information in the docs (DE/EN)
  doc/FAQ.md
  doc/Home.md
  doc/de/FAQ.md
  doc/de/Home.md
Labels: Docs

#9890 New table "post-content"
  database.sql
  include/enotify.php
  src/Content/Text/Plaintext.php
  src/Core/Update.php
  src/Database/DBStructure.php
  src/Database/PostUpdate.php
  src/Model/Item.php
  src/Model/ItemContent.php
  src/Model/Post.php
  src/Model/Post/Content.php
  src/Module/Search/Index.php
  src/Worker/Expire.php
  static/dbstructure.config.php
  static/dbview.config.php
  tests/datasets/api.fixture.php
  update.php
Labels: Enhancement

#9892 Move GET pinned/{id} to POST item/{id}/pin
  src/Module/Item/Pin.php
  static/routes.config.php
  view/js/main.js
  view/templates/wall_thread.tpl
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/smoothly/templates/wall_thread.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: API, Enhancement

#9882 Remove ternary operators from converted .po plural condition
  src/Console/PoToPhp.php
  view/lang/bg/strings.php
  view/lang/ca/strings.php
  view/lang/cs/strings.php
  view/lang/de/strings.php
  view/lang/en-gb/strings.php
  view/lang/en-us/strings.php
  view/lang/eo/strings.php
  view/lang/es/strings.php
  view/lang/et/strings.php
  view/lang/fi-fi/strings.php
  view/lang/fr/strings.php
  view/lang/hu/strings.php
  view/lang/is/strings.php
  view/lang/it/strings.php
  view/lang/ja/strings.php
  view/lang/nb-no/strings.php
  view/lang/nl/strings.php
  view/lang/pl/strings.php
  view/lang/pt-br/strings.php
  view/lang/ro/strings.php
  view/lang/ru/strings.php
  view/lang/sv/strings.php
  view/lang/zh-cn/strings.php
Labels: Bug

#9894 Prevent "No post-content stored"
  src/Model/Item.php
  src/Model/Post/Content.php
Labels: Bug

#9888 Move GET like/{id} to POST item/{id}/activity/{verb}
  src/Module/Item/Activity.php
  static/routes.config.php
  view/js/main.js
  view/templates/like_noshare.tpl
  view/templates/wall_thread.tpl
  view/theme/frio/js/theme.js
  view/theme/frio/templates/like_noshare.tpl
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/quattro/templates/photo_item.tpl
  view/theme/quattro/templates/search_item.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/smoothly/templates/wall_thread.tpl
  view/theme/vier/templates/photo_item.tpl
  view/theme/vier/templates/search_item.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: API, Enhancement

#9893 Skip empty message strings in Console\PoToPhp
  src/Console/PoToPhp.php
  src/Util/Temporal.php
  view/lang/bg/strings.php
  view/lang/ca/strings.php
  view/lang/cs/strings.php
  view/lang/en-gb/strings.php
  view/lang/en-us/strings.php
  view/lang/eo/strings.php
  view/lang/es/strings.php
  view/lang/et/strings.php
  view/lang/fi-fi/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/is/strings.php
  view/lang/it/strings.php
  view/lang/ja/strings.php
  view/lang/nb-no/strings.php
  view/lang/nl/strings.php
  view/lang/pl/strings.php
  view/lang/pt-br/strings.php
  view/lang/ro/strings.php
  view/lang/ru/strings.php
  view/lang/sv/strings.php
  view/lang/zh-cn/strings.php
Labels: Bug, Translation

#9889 Move GET item/ignore/{id} to POST item/{id}/ignore
  src/Module/Item/Ignore.php
  static/routes.config.php
  view/js/main.js
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: API, Enhancement

#9891 Move GET starred/{id} to POST item/{id}/star
  src/Module/Item/Star.php
  static/routes.config.php
  view/js/main.js
  view/templates/wall_thread.tpl
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/quattro/templates/photo_item.tpl
  view/theme/quattro/templates/search_item.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/smoothly/templates/wall_thread.tpl
  view/theme/vier/templates/photo_item.tpl
  view/theme/vier/templates/search_item.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: API, Enhancement
