Repository friendica/friendica, pull requests merged in 2021-07, with the labels that each got.

#10449 Guess the mimetype in advance
  src/Model/Photo.php
  src/Module/Photo.php
Labels: Enhancement

#10450 AP: Support "discoverable"
  database.sql
  doc/database/db_apcontact.md
  src/Model/APContact.php
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Transmitter.php
  static/dbstructure.config.php
Labels: Federation, New Feature

#10452 Avoid Notice: Undefined index: field1 in /src/Module/Register.php on line 253
  src/Module/Register.php
Labels: Bug

#10451 Some more places changed to the new contact avatar path format
  include/conversation.php
  src/Module/Xrd.php
  src/Network/Probe.php
  src/Object/Post.php
  src/Protocol/DFRN.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
Labels: Enhancement

#10455 Fix: Fetching of non public photos
  src/App/Module.php
  src/Core/Session.php
  src/Module/Photo.php
Labels: Bug, Federation

#10456 Quickfix for hashtags in author names in shared posts
  src/Content/Text/BBCode.php
Labels: Bug

#10459 Fixed fetching private local images
  src/Model/Post/Media.php
  src/Model/Profile.php
  src/Module/Photo.php
Labels: Enhancement, Federation

#10289 update the CREDITS.txt for the 2021.06 release
  CREDITS.txt
Labels: Docs

#10460 Issue 10352: Fixing photo entries for contact avatars
  src/Worker/RemoveUnusedAvatars.php
Labels: Bug

#10461 Transmit preview link
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement

#10462 Removal of duplicated photo entries for a contact
  src/Module/Photo.php
  src/Worker/RemoveUnusedAvatars.php
Labels: Enhancement

#10463 Proxy: Avoid access for not logged in users
  src/Module/Proxy.php
Labels: Performance, Security

#10465 Fix local follow (and local contact data update)
  src/Model/Contact.php
Labels: Bug, Federation

#10466 Ensure that the network is set for "self" contacts
  src/Model/Contact.php
  src/Model/User.php
Labels: Bug, Federation

#10467 Use "getOwnerDataById" and "getOwnerDataByNick" to fetch owner data
  mod/cal.php
  mod/photos.php
  mod/videos.php
  src/Model/Profile.php
  src/Module/NoScrape.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement

#10362 2021.06 CHANGELOG
  CHANGELOG
Labels: Docs

#10470 Allow search for only locally published contacts
  src/Model/Contact.php
  view/lang/C/messages.po
Labels: Enhancement

#10478 Fix notice "undefined index: uri"
  src/Model/APContact.php
  src/Model/Contact.php
  src/Protocol/ActivityPub/Receiver.php
  tests/datasets/api.fixture.php
  tests/datasets/storage/database.fixture.php
Labels: Bug

#10479 Merge frio-specific share block template into the base template
  view/global.css
  view/templates/shared_content.tpl
  view/theme/duepuntozero/style.css
  view/theme/frio/css/style.css
  view/theme/frio/templates/shared_content.tpl
  view/theme/quattro/dark/style.css
  view/theme/quattro/green/style.css
  view/theme/quattro/lilac/style.css
  view/theme/quattro/quattro.less
  view/theme/smoothly/style.css
  view/theme/vier/plusminus.css
  view/theme/vier/style.css
Labels: Enhancement, Theme-specific, UI

#10480 Post update: Set "uri-id" in the contact tables
  src/Database/PostUpdate.php
Labels: Enhancement

#10482 Some more "convertForUriId" replacements
  database.sql
  include/api.php
  include/conversation.php
  include/enotify.php
  mod/message.php
  src/Database/PostUpdate.php
  src/Model/Event.php
  src/Model/Profile.php
  src/Module/Api/Friendica/Events/Index.php
  src/Module/Profile/Profile.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  static/dbstructure.config.php
  static/dbview.config.php
  tests/legacy/ApiTest.php
Labels: Bug

#10483 New view that combines all contact tables
  database.sql
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement

#10486 Remove outdated friendica_test_data.sql
  bin/dev/vagrant_provision.sh
  friendica_test_data.sql
Labels: Enhancement

#10489 Fixes "Undefined index: nick"
  src/Model/Contact.php
Labels: Bug

#10490 Fix Uncaught TypeError: Argument 1 passed to Friendica\Model\Item::storeForUserByUriId()
  src/Worker/Notifier.php
Labels: Bug

#10492 Issue 10491: Possibility for simple shortening added
  mod/settings.php
  src/Content/Text/Plaintext.php
  view/lang/C/messages.po
  view/templates/settings/connectors.tpl
  view/theme/frio/templates/settings/connectors.tpl
Labels: New Feature

#10493 Improve how shared posting look on mobile apps
  src/Content/Text/BBCode.php
  src/Object/Api/Mastodon/Status.php
Labels: Enhancement, UI

#10497 Make last status parameter actually optional in Object\Api\Mastodon\Conversation
  src/Object/Api/Mastodon/Conversation.php
Labels: API, Bug

#10496 Subscribe to contacts from a remote AP account
  mod/ostatus_subscribe.php
  mod/salmon.php
  mod/settings.php
  src/Model/User.php
  view/lang/C/messages.po
  view/templates/settings/connectors.tpl
  view/theme/frio/templates/settings/connectors.tpl
Labels: Enhancement, Federation

#10499 Sanitize negative followers count on APContact
  src/Model/APContact.php
Labels: Bug, Federation

#10507 Issue 10506: Fix for multiple picture posts
  src/Model/Post/Media.php
Labels: Bug, Federation

#10509 Issue 10506 - again. Improved check for pictured in body
  src/Model/Item.php
  src/Model/Post/Media.php
Labels: Bug, Federation

#10513 Fix notice in events
  src/Model/Item.php
Labels: Bug

#10512 Move ActivityPub endpoints to an AP class
  src/Module/ActivityPub/Followers.php
  src/Module/ActivityPub/Following.php
  src/Module/ActivityPub/Inbox.php
  src/Module/ActivityPub/Objects.php
  src/Module/ActivityPub/Outbox.php
  src/Protocol/ActivityPub/Transmitter.php
  static/routes.config.php
Labels: Enhancement

#10508 Prevent endless loop when updating contact by probe
  src/Model/APContact.php
  src/Model/Contact.php
  src/Model/Photo.php
  src/Network/HTTPRequest.php
  src/Network/Probe.php
  src/Protocol/ActivityPub.php
  src/Util/Images.php
Labels: Bug

#10521 Manually add Persian to post body language detection
  src/Model/Item.php
Labels: Enhancement, UX

#10522 Fix warning "class 'Friendica\Module\Objects' not found"
  static/routes.config.php
Labels: Bug

#10523 Issue 10519: check for tables and fields before applying changes
  update.php
Labels: Bug, Installation

#10524 Sanitize negative status count on APContact
  src/Model/APContact.php
Labels: Bug, Federation

#10526 The legacy OAuth server is removed
  database.sql
  doc/database.md
  doc/database/db_auth_codes.md
  doc/database/db_clients.md
  doc/database/db_tokens.md
  include/api.php
  mod/api.php
  mod/settings.php
  src/Database/DBStructure.php
  src/Security/FKOAuth1.php
  src/Security/FKOAuthDataStore.php
  src/Security/OAuth1/OAuthServer.php
  src/Worker/OptimizeTables.php
  static/dbstructure.config.php
  update.php
  view/lang/C/messages.po
Labels: Enhancement

#10527 API: Support for deprecated API endpoints and OAuth removal
  CHANGELOG
  doc/API-GNU-Social.md
  doc/API-Mastodon.md
  doc/Addons.md
  doc/api.md
  include/api.php
  src/Factory/Api/Mastodon/Status.php
  src/Module/Api/Mastodon/Search.php
  src/Module/Api/Mastodon/Statuses/Card.php
  static/routes.config.php
  view/templates/oauth_authorize_done.tpl
  view/templates/settings/oauth_edit.tpl
  view/theme/frio/templates/settings/oauth_edit.tpl
Labels: API, Enhancement

#10529 API: Added dummy endpoint for featured tags
  src/Module/Api/Mastodon/Accounts/FeaturedTags.php
  static/routes.config.php
Labels: API, Enhancement

#10530 API: Support for fetching mails with more "statuses" calls
  src/Factory/Api/Mastodon/Status.php
  src/Module/Api/Mastodon/Statuses/Context.php
  src/Module/Api/Mastodon/Timelines/Direct.php
Labels: API, Enhancement

#10528 Avoid "DB Error" messages
  src/Content/Text/BBCode.php
  src/Model/Post/Link.php
  src/Model/Post/UserNotification.php
Labels: Bug

#10533 Improved performance for UpdateContacts
  src/Worker/UpdateContacts.php
Labels: Enhancement, Performance

#10537 Add iOS Metatext, remove Amaroq, fix typo
  doc/FAQ.md
Labels: Docs, Enhancement

#10536 Unneeded legacy DFRN table removed
  database.sql
  doc/database.md
  doc/database/db_profile_check.md
  src/Database/DBStructure.php
  src/Worker/OptimizeTables.php
  static/dbstructure.config.php
  update.php
Labels: Enhancement

#10535 Fix for Mastodon falsely adding previews to mentions
  src/Content/Text/BBCode.php
  src/Object/Api/Mastodon/Status.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#10498 [frio] Move content of event_edit.js to mod_event.js to prevent an unsafe-eval
  view/theme/frio/js/event_edit.js
  view/theme/frio/js/mod_events.js
  view/theme/frio/templates/event_form.tpl
Labels: Bug, Theme-specific, UX

#10538 Some small performance tweaks
  mod/ping.php
  src/Content/ForumManager.php
  src/Model/Tag.php
  src/Worker/ExpirePosts.php
Labels: Enhancement, Performance

#10540 "hovercard" is "hcard"
  src/Module/HCard.php
  static/routes.config.php
  view/lang/C/messages.po
Labels: Enhancement

#10516 Refactor Storage admin section
  src/Module/Admin/Site.php
  src/Module/Admin/Storage.php
  src/Module/BaseAdmin.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/admin/site.tpl
  view/templates/admin/storage.tpl
  view/theme/frio/templates/admin/site.tpl
  view/theme/frio/templates/admin/storage.tpl
Labels: Bug

#10544 Lock before recreate / fix cache key misspelling
  src/App/Router.php
  tests/src/App/ModuleTest.php
  tests/src/App/RouterTest.php
Labels: Bug, Enhancement, Performance

#10548 Replaced argv/argc with replacement functions
  doc/themes.md
  include/api.php
  mod/cal.php
  mod/display.php
  mod/editpost.php
  mod/events.php
  mod/fbrowser.php
  mod/lostpass.php
  mod/message.php
  mod/oexchange.php
  mod/photos.php
  mod/poco.php
  mod/pubsub.php
  mod/pubsubhubbub.php
  mod/redir.php
  mod/salmon.php
  mod/settings.php
  mod/share.php
  mod/tagger.php
  mod/tagrm.php
  mod/update_contact.php
  mod/videos.php
  mod/wall_attach.php
  mod/wall_upload.php
  mod/wallmessage.php
  src/App.php
  src/App/Arguments.php
  src/Content/OEmbed.php
  src/Content/Text/BBCode.php
  src/Core/Renderer.php
  src/Core/Theme.php
  src/Model/Item.php
  src/Module/Attach.php
  src/Module/BaseProfile.php
  src/Module/BaseSettings.php
  src/Module/Contact.php
  src/Module/Debug/ItemBody.php
  src/Module/Diaspora/Fetch.php
  src/Module/Directory.php
  src/Module/Feed.php
  src/Module/Filer/RemoveTag.php
  src/Module/Filer/SaveTag.php
  src/Module/Friendica.php
  src/Module/Group.php
  src/Module/Help.php
  src/Module/Oembed.php
  src/Module/PublicRSAKey.php
  src/Module/Smilies.php
  src/Module/Xrd.php
  src/Security/Authentication.php
  tests/Util/AppMockTrait.php
  tests/legacy/ApiTest.php
  tests/src/Content/SmiliesTest.php
  tests/src/Content/Text/BBCodeTest.php
  view/theme/frio/theme.php
  view/theme/vier/theme.php
Labels: Enhancement

#10554 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10553 Issue 10545: Convert complex zmg BBCode elements
  src/Content/Text/BBCode.php
Labels: Enhancement, Federation
