Repository friendica/friendica, pull requests merged in 2021-02, with the labels that each got.

#9897 BG, DE and IT translation updates
  view/lang/bg/messages.po
  view/lang/bg/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/it/messages.po
  view/lang/it/strings.php
Labels: Translation

#9887 Replace references of mod/subthread with item/{id}/follow
  doc/Addons.md
  doc/de/Addons.md
  include/conversation.php
  mod/subthread.php
  src/Module/Item/Follow.php
  static/routes.config.php
  view/js/main.js
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/frio/theme.php
Labels: API, Enhancement

#9917 The "thread" table isn't used anymore
  database.sql
  src/Database/DBA.php
  src/Database/DBStructure.php
  src/Database/Database.php
  src/Model/Item.php
  src/Model/Post.php
  src/Module/Admin/Site.php
  src/Module/Settings/UserExport.php
  src/Worker/CleanItemUri.php
  src/Worker/Expire.php
  src/Worker/ExpirePosts.php
  src/Worker/MergeContact.php
  src/Worker/RepairDatabase.php
  static/dbstructure.config.php
Labels: Enhancement

#9921 Issue 9906: Improved view speed
  database.sql
  include/api.php
  src/Model/Item.php
  src/Model/Post.php
  static/dbstructure.config.php
  static/dbview.config.php
  tests/datasets/api.fixture.php
  update.php
Labels: Enhancement

#9918 Move vier-specific smileybutton styles to addon
  bin/dev/minifyjs.sh
  doc/Text_comment.md
  doc/Text_editor.md
  doc/de/Text_comment.md
  doc/de/Text_editor.md
  doc/img/editor_frost.png
  doc/img/frost.png
  view/theme/vier/style.css
Labels: Addons, Enhancement

#9915 Harden OEmbed link discovery
  src/Content/OEmbed.php
Labels: Bug

#9922 Try OEmbed first for [audio] and [video] tags
  src/Content/Text/BBCode.php
Labels: Bug

#9916 Babel: Support tweet URL
  src/Module/Debug/Babel.php
Labels: Addons, Enhancement

#9930 The "item" table is now replaced
  database.sql
  include/api.php
  mod/events.php
  mod/item.php
  mod/tagger.php
  src/Content/Widget/TagCloud.php
  src/Core/System.php
  src/Database/DBStructure.php
  src/Database/PostUpdate.php
  src/Factory/Api/Mastodon/Status.php
  src/Model/Contact.php
  src/Model/Event.php
  src/Model/Item.php
  src/Model/Post.php
  src/Module/Conversation/Network.php
  src/Module/Profile/Status.php
  src/Module/Search/Filed.php
  src/Module/Search/Index.php
  src/Module/Update/Profile.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Feed.php
  src/Worker/APDelivery.php
  src/Worker/CleanItemUri.php
  src/Worker/Cron.php
  src/Worker/Delivery.php
  src/Worker/Expire.php
  src/Worker/ExpireAndRemoveUsers.php
  src/Worker/ExpirePosts.php
  src/Worker/Notifier.php
  src/Worker/RemoveContact.php
  src/Worker/RemoveUnusedAvatars.php
  src/Worker/RemoveUnusedContacts.php
  src/Worker/RepairDatabase.php
  src/Worker/UpdateContacts.php
  static/dbstructure.config.php
  static/dbview.config.php
  static/defaults.config.php
  tests/datasets/api.fixture.php
  update.php
Labels: Enhancement

#9932 No implicit mention for top level Diaspora comments
  src/Object/Post.php
  src/Protocol/Diaspora.php
Labels: Enhancement, Federation

#9933 Avoid a possible foreign key constraint
  include/enotify.php
Labels: Enhancement

#9938 Fix several database issues
  database.sql
  mod/editpost.php
  src/Model/Post.php
  src/Module/Update/Profile.php
  src/Worker/RemoveContact.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Bug

#9939 File extension to Mimetype matching fix for filenames with extra periods in them
  src/Util/Mimetype.php
Labels: Bug

#9940 Several speed improvements (magiclink, caching, indexes)
  database.sql
  include/conversation.php
  mod/photos.php
  mod/unfollow.php
  src/Content/ContactSelector.php
  src/Content/ForumManager.php
  src/Content/Text/HTML.php
  src/Content/Widget.php
  src/Core/ACL.php
  src/Model/Contact.php
  src/Model/Event.php
  src/Model/Item.php
  src/Model/Profile.php
  src/Model/Tag.php
  src/Module/Contact.php
  src/Module/Contact/Hovercard.php
  src/Module/Debug/ItemBody.php
  src/Module/RandomProfile.php
  src/Object/Post.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement, Performance

#9944 Use correct Contact\User::setBlocked instead of Contact::block for /item/block endpoint
  mod/item.php
Labels: Bug

#9935 Harden /parseurl
  database.sql
  mod/oexchange.php
  mod/parse_url.php
  src/Content/Text/BBCode.php
  src/Module/ParseUrl.php
  src/Util/ParseUrl.php
  src/Worker/ClearCache.php
  static/dbstructure.config.php
  static/routes.config.php
  update.php
  view/js/linkPreview.js
  view/templates/jot-header.tpl
  view/templates/msg-header.tpl
  view/templates/wallmsg-header.tpl
  view/theme/frio/js/jot.js
  view/theme/frio/js/textedit.js
  view/theme/frio/templates/jot-header.tpl
  view/theme/smoothly/templates/jot-header.tpl
Labels: Bug, Performance, Security

#9945 Get rid of the "item" table
  database.sql
  src/Database/DBStructure.php
  src/Model/Post/UserNotification.php
  src/Protocol/ActivityPub/Processor.php
  src/Worker/APDelivery.php
  src/Worker/Delivery.php
  src/Worker/Expire.php
  src/Worker/Notifier.php
  src/Worker/RemoveContact.php
  static/dbstructure.config.php
  static/dbview.config.php
  update.php
Labels: Enhancement

#9946 Contacts are now removed more ressource friendly
  src/Worker/RemoveContact.php
Labels: Enhancement, Performance

#9947 Several performance improvements
  database.sql
  include/conversation.php
  src/Database/DBA.php
  src/Database/Database.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Nodeinfo.php
  src/Model/Post.php
  src/Module/Conversation/Community.php
  src/Module/Conversation/Network.php
  src/Module/Profile/Status.php
  src/Module/Update/Profile.php
  src/Protocol/Diaspora.php
  src/Worker/CleanItemUri.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement, Performance

#9951 Fix PR #9949
  database.sql
  static/dbstructure.config.php
Labels: Bug

#9952 Issue 9064: referring INSTALL.txt now points to doc/INSTALL.md
  src/Core/Installer.php
  src/Module/Install.php
  view/lang/C/messages.po
Labels: Docs, Installation, Translation

#9953 PHP 8 fatal messages - Quit when message is empty similar to #9681
  src/Content/Text/HTML.php
  src/Network/Probe.php
Labels: Bug

#9955 Use "pdo_emulate_prepares" by default
  static/defaults.config.php
Labels: Enhancement, Installation

#9959 Fixes several database errors, removes "relation" handling
  src/Core/Hook.php
  src/Database/DBA.php
  src/Database/Database.php
  src/Model/Event.php
  src/Model/Item.php
  src/Module/Conversation/Community.php
  src/Worker/Delivery.php
  src/Worker/MergeContact.php
  src/Worker/RemoveContact.php
  static/dbstructure.config.php
Labels: Bug, Enhancement

#9961 Avoid deletion of newly created contacts
  src/Worker/RemoveUnusedContacts.php
Labels: Bug

#9963 Support cid URLs as used in mailstream plugin
  src/Content/Text/BBCode.php
  src/Content/Text/HTMLPurifier_URIScheme_cid.php
Labels: Addons, Enhancement

#9964 Fix link preview with videos
  src/Module/ParseUrl.php
Labels: Bug

#9965 Perform a reload after following a thread
  view/js/main.js
Labels: Bug, UX

#9967 Offer "follow thread" only when you don't already follow
  include/conversation.php
  src/Model/Item.php
  src/Object/Post.php
  view/theme/frio/theme.php
Labels: Enhancement, UX
