Repository friendica/friendica, pull requests merged in 2021-10, with the labels that each got.

#10783 Vagrant updates
  Vagrantfile
  bin/dev/vagrant_provision.sh
  doc/Vagrant.md
Labels: Docs, Enhancement, Hackathon 2021

#10785 Fix typo in test for ParsedLogIterator
  tests/src/Model/Log/ParsedLogIteratorTest.php
Labels: Bug, Hackathon 2021

#10784 cleanup adminpanel messages
  src/Module/Admin/Logs/View.php
  view/lang/C/messages.po
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement, Hackathon 2021

#10786 Sanitize the addon author if it is not a valid URL but a handle
  src/Core/Addon.php
Labels: Bug, Addons, Hackathon 2021

#10787 Mark string translatable in View logs
  src/Module/Admin/Logs/View.php
  view/lang/C/messages.po
  view/templates/admin/logs/view.tpl
  view/theme/frio/templates/admin/logs/view.tpl
Labels: Bug, Translation, Hackathon 2021

#10789 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10790 add a hint about the phpmailer addon to the install docs
  doc/Install.md
  doc/de/Install.md
Labels: Docs, Installation, Hackathon 2021

#10792 API: No special handling for Diaspora reshares
  include/api.php
  tests/legacy/ApiTest.php
Labels: Enhancement, API, Hackathon 2021

#10793 Issue 10747: Improved check for blocked domains
  src/Model/APContact.php
  src/Network/Probe.php
Labels: Enhancement, Hackathon 2021

#10794 "q" call is replaced
  src/Security/Security.php
Labels: Enhancement, Hackathon 2021

#10759 Insert a `user-contact` for every contact
  database.sql
  doc/database/db_contact.md
  doc/database/db_user-contact.md
  include/api.php
  mod/pubsub.php
  mod/unfollow.php
  src/Console/ArchiveContact.php
  src/Console/GlobalCommunitySilence.php
  src/Model/Contact.php
  src/Model/Contact/Relation.php
  src/Model/Contact/User.php
  src/Model/Introduction.php
  src/Model/Item.php
  src/Model/User.php
  src/Module/Api/Mastodon/Accounts/Note.php
  src/Module/Contact.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  src/Protocol/Relay.php
  src/Worker/ExpirePosts.php
  src/Worker/OnePoll.php
  src/Worker/RemoveUnusedAvatars.php
  static/dbstructure.config.php
  static/dbview.config.php
  update.php
  view/lang/C/messages.po
Labels: Enhancement, Hackathon 2021

#10769 Rework contact termination to separate protocol-level and contact-level
  doc/Addons.md
  include/api.php
  mod/unfollow.php
  src/Console/Contact.php
  src/Core/Protocol.php
  src/Model/Contact.php
  src/Worker/Notifier.php
  view/lang/C/messages.po
Labels: Bug, Addons

#10788 Fix `run_xgettext.sh` code and make it work on osx
  bin/run_xgettext.sh
Labels: Enhancement, Hackathon 2021

#10797 Replaced deprecated code from the Diaspora implementation
  src/Protocol/Diaspora.php
Labels: Federation, Enhancement, Hackathon 2021

#10796 Add revoke follow feature
  doc/Addons.md
  doc/de/Addons.md
  mod/photos.php
  src/Core/Protocol.php
  src/Model/Contact.php
  src/Module/Contact.php
  src/Module/Contact/Revoke.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/confirm.tpl
  view/templates/contact_drop_confirm.tpl
  view/templates/contact_edit.tpl
  view/theme/frio/templates/confirm.tpl
  view/theme/frio/templates/contact_drop_confirm.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/vier/templates/contact_edit.tpl
Labels: New Feature, Hackathon 2021

#10798 Some more "q" calls replaced
  mod/events.php
  mod/message.php
  mod/photos.php
Labels: Enhancement

#10799 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation, Hackathon 2021

#10795 Contact-media
  doc/Accesskeys.md
  mod/videos.php
  src/Model/Contact.php
  src/Module/BaseProfile.php
  src/Module/Contact.php
  src/Module/Contact/Media.php
  src/Module/Profile/Media.php
  static/routes.config.php
  view/lang/C/messages.po
Labels: Enhancement, UI, Hackathon 2021

#10762 Remove contact drop feature
  src/Model/Contact.php
  src/Module/Contact.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/contact_edit.tpl
  view/templates/contacts-template.tpl
  view/theme/frio/css/style.css
  view/theme/frio/templates/contact_edit.tpl
  view/theme/frio/templates/contact_template.tpl
  view/theme/frio/templates/contacts-template.tpl
  view/theme/vier/templates/contact_edit.tpl
Labels: UX, Enhancement

#10802 Remove disturbing/superfluous logging messages
  src/Core/Session/Handler/Cache.php
  src/Factory/SessionFactory.php
  src/Network/GuzzleResponse.php
Labels: Enhancement, Hackathon 2021

#10800 Add block and unblock hooks
  doc/Addons.md
  doc/de/Addons.md
  include/api.php
  mod/unfollow.php
  src/Core/Protocol.php
  src/Model/Contact.php
  src/Model/Contact/User.php
  src/Module/Api/Mastodon/Accounts/Block.php
  src/Module/Contact.php
  view/lang/C/messages.po
Labels: New Feature

#10801 Fixing "Unknown column 'network-thread-view.uri-id'"
  src/Module/Conversation/Network.php
Labels: Bug

#10803 Forgot one Logpoint ..
  src/Network/CurlResult.php
Labels: Enhancement, Hackathon 2021

#10805 Switch uid with nickname in user picture URLs
  mod/msearch.php
  src/Model/Contact.php
  src/Model/Photo.php
  src/Model/User.php
  src/Module/Delegation.php
  src/Module/NoScrape.php
  src/Module/Photo.php
  src/Module/Register.php
  src/Module/Xrd.php
  src/Network/Probe.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  static/routes.config.php
Labels: Enhancement, Security, Privacy

#10806 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation, Hackathon 2021

#10807 Don't store emoji images as media but links
  src/Model/Post/Link.php
  src/Model/Post/Media.php
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement, Hackathon 2021

#10808 Replace remaining reference to Model\Photo::stripExtension
  src/Module/Photo.php
Labels: Bug, Hackathon 2021

#10809 Code Style: Replace "AS" with "as"
  src/Console/CreateDoxygen.php
  src/Content/Text/BBCode.php
  src/Database/DBA.php
  src/Database/DBStructure.php
  src/Database/Database.php
  src/Database/View.php
  src/Module/WellKnown/XSocialRelay.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Protocol/Relay.php
Labels: Enhancement, Hackathon 2021

#10810 Fix regular expression in the user avatar photo routes
  static/routes.config.php
Labels: Bug, Hackathon 2021

#10811 Add missing Module\Photo route for contact avatar
  src/Module/Photo.php
  static/routes.config.php
Labels: Bug, Hackathon 2021

#10812 Add missing Module\Photo route for post-media id with no customsize
  src/Module/Photo.php
  static/routes.config.php
Labels: Bug, Hackathon 2021

#10813 added length counter for postings in themes other then frio
  view/templates/jot-header.tpl
  view/templates/jot.tpl
  view/theme/vier/style.css
Labels: Theme-specific, Enhancement, UI, Hackathon 2021

#10815 update FR translations THX MrPetovan
  view/lang/fr/messages.po
  view/lang/fr/strings.php
Labels: Translation, Hackathon 2021

#10814 More "q" calls have been replaced
  include/api.php
  mod/fbrowser.php
  mod/photos.php
  mod/repair_ostatus.php
  mod/settings.php
  mod/uimport.php
  mod/wall_upload.php
  mod/wallmessage.php
  src/Model/FContact.php
  src/Protocol/DFRN.php
Labels: Enhancement, Hackathon 2021

#10816 Check if the string representation of Notify->link is empty in Module\Notifications\Notification
  src/Module/Notifications/Notification.php
Labels: Bug, Hackathon 2021

#10817 Explicitly cast Url objects to string
  src/Navigation/Notifications/Depository/Notify.php
Labels: Bug, Hackathon 2021

#10818 Display the current timezone in date time picker fields
  database.sql
  doc/API-Entities.md
  doc/database/db_event.md
  doc/events.md
  mod/cal.php
  mod/events.php
  mod/item.php
  mod/ping.php
  mod/settings.php
  src/App.php
  src/Content/Text/BBCode.php
  src/Core/Worker.php
  src/Model/Event.php
  src/Model/Item.php
  src/Model/Profile.php
  src/Module/Api/Friendica/Events/Index.php
  src/Module/Conversation/Network.php
  src/Module/Events/Json.php
  src/Module/Profile/Status.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Security/Authentication.php
  src/Util/DateTimeFormat.php
  src/Util/Temporal.php
  static/dbstructure.config.php
  static/dbview.config.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/event_form.tpl
  view/theme/duepuntozero/style.css
  view/theme/frio/js/mod_events.js
  view/theme/frio/templates/event_form.tpl
  view/theme/quattro/templates/event_form.tpl
  view/theme/smoothly/style.css
  view/theme/vier/templates/event_form.tpl
Labels: New Feature, Enhancement, Hackathon 2021

#10820 Some more "q" calls and deprecated logging replaced
  include/api.php
  mod/ping.php
  src/Model/Contact/Group.php
Labels: Hackathon 2021

#10819 Cast object parameters to string in Database\Database
  src/Database/Database.php
  src/Navigation/Notifications/Depository/Notify.php
Labels: Enhancement, Hackathon 2021

#10822 Trim XML before emptiness check in Protocol\Feed::import
  src/Protocol/Feed.php
Labels: Bug

#10821 Relax check on id parameter in /photo
  src/Model/User.php
  src/Module/Photo.php
Labels: Bug, Enhancement

#10824 DE and RU translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation, Hackathon 2021

#10826 Remove messages.po if it does exist :-)
  bin/run_xgettext.sh
Labels: Bug

#10828 Some Bugfixings
  mod/fbrowser.php
  mod/ping.php
Labels: Bug

#10823 Access contact avatars by guid
  database.sql
  src/Model/Contact.php
  src/Module/Photo.php
  static/dbstructure.config.php
  static/dbview.config.php
  static/routes.config.php
  view/lang/C/messages.po
Labels: Enhancement, Hackathon 2021

#10831 HU translation updated THX Balázs Úr
  view/lang/hu/messages.po
  view/lang/hu/strings.php
Labels: Translation, Hackathon 2021

#10833 Drone - Don't deploy artifacts with config files
  mods/release-list-include.txt
Labels: Bug

#10834 The legacy reshare functionality is removed
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
Labels: Bug

#10842 Issue 10841: Redirect always to the same page
  src/Module/Contact.php
Labels: Bug, UX

#10843 Issue 10837: Display the public item when the personal one does not exist
  mod/display.php
Labels: Bug, UX
