Repository friendica/friendica, pull requests merged in 2021-12, with the labels that each got.

#11052 RU translations THX Alexander An
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#11054 Diaspora reshares via API are fixed now
  include/api.php
  src/Module/Api/Twitter/Statuses/Retweet.php
  src/Module/Item/Activity.php
  src/Protocol/Diaspora.php
Labels: Bug, API

#11057 Remove all-numeric usernames condition
  src/Network/Probe.php
Labels: Bug, Federation

#11059 Suppress notice messages related to the VCard::getHTML call in mod/display
  mod/display.php
  src/Content/Widget/VCard.php
Labels: Bug

#11053 Bump minimum required PHP version to 7.3
  composer.json
  composer.lock
Labels: Enhancement

#11062 HU translation updated THX Balázs Úr
  view/lang/hu/messages.po
  view/lang/hu/strings.php
Labels: Translation

#11056 Fix URI structure condition in Probe::detect
  src/Network/Probe.php
  src/Util/Network.php
  tests/src/Network/ProbeTest.php
Labels: Bug, Federation

#11064 Add expected second parameter to BaseApi::getRequest in a few put() methods
  src/Module/Api/Mastodon/Lists.php
  src/Module/Api/Mastodon/Media.php
  src/Module/Api/Mastodon/PushSubscription.php
Labels: Bug, API

#11065 Fix media handling upon creation and display
  src/Model/Item.php
  src/Protocol/Feed.php
Labels: Federation, Enhancement

#11066 Issue 11063: Fix check for current user
  src/Module/BaseApi.php
Labels: Bug, API

#11067 Friendica now requires PHP 7.3 or above
  doc/Install.md
  doc/de/Install.md
Labels: Docs

#11068 Improved page info detection
  src/Util/ParseUrl.php
Labels: Enhancement

#11058 Replace references to UTC_TIMESTAMP()/NOW() in SQL queries with a DateTimeFormat generated parameter
  mod/photos.php
  mod/wallmessage.php
  src/Core/Cache/Type/DatabaseCache.php
  src/Core/Worker.php
  src/Model/Item.php
  src/Model/PushSubscriber.php
  src/Model/Tag.php
  src/Module/Api/ApiResponse.php
  src/Module/OAuth/Token.php
  src/Security/OAuth.php
  src/Util/DateTimeFormat.php
  src/Worker/CleanWorkerQueue.php
  src/Worker/ClearCache.php
  src/Worker/ExpireAndRemoveUsers.php
  src/Worker/ExpireConversations.php
  src/Worker/ExpirePosts.php
  src/Worker/PollContacts.php
  src/Worker/RemoveUnusedContacts.php
  src/Worker/UpdateGServers.php
Labels: Bug

#11070 Fix: array_reverse returns the reversed content as return value
  src/Module/Api/Mastodon/Accounts/Followers.php
  src/Module/Api/Mastodon/Accounts/Following.php
  src/Module/Api/Mastodon/Accounts/Statuses.php
  src/Module/Api/Mastodon/Blocks.php
  src/Module/Api/Mastodon/Bookmarks.php
  src/Module/Api/Mastodon/Conversations.php
  src/Module/Api/Mastodon/Favourited.php
  src/Module/Api/Mastodon/Lists/Accounts.php
  src/Module/Api/Mastodon/Mutes.php
  src/Module/Api/Mastodon/ScheduledStatuses.php
  src/Module/Api/Mastodon/Search.php
  src/Module/Api/Mastodon/Timelines/Direct.php
  src/Module/Api/Mastodon/Timelines/Home.php
  src/Module/Api/Mastodon/Timelines/ListTimeline.php
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
  src/Module/Api/Mastodon/Timelines/Tag.php
  src/Module/Api/Twitter/Blocks/Ids.php
  src/Module/Api/Twitter/Blocks/Lists.php
  src/Module/Api/Twitter/Followers/Ids.php
  src/Module/Api/Twitter/Followers/Lists.php
  src/Module/Api/Twitter/Friends/Ids.php
  src/Module/Api/Twitter/Friends/Lists.php
  src/Module/Api/Twitter/Friendships/Incoming.php
Labels: Bug, API

#11069 Some Fixings & Reenabling some tests
  src/Module/Api/ApiResponse.php
  src/Module/Api/Mastodon/Accounts/VerifyCredentials.php
  src/Module/Api/Twitter/Account/UpdateProfile.php
  src/Module/Api/Twitter/Blocks/Lists.php
  src/Module/Api/Twitter/Followers/Lists.php
  src/Module/Api/Twitter/Friends/Lists.php
  src/Module/Api/Twitter/Friendships/Incoming.php
  src/Module/Api/Twitter/Lists/Statuses.php
  tests/datasets/api.fixture.php
  tests/legacy/ApiTest.php
  tests/src/Module/Api/GnuSocial/GnuSocial/ConfigTest.php
  tests/src/Module/Api/Mastodon/Accounts/StatusesTest.php
  tests/src/Module/Api/Mastodon/Accounts/VerifyCredentialsTest.php
  tests/src/Module/Api/Mastodon/ConversationsTest.php
  tests/src/Module/Api/Mastodon/SearchTest.php
  tests/src/Module/Api/Mastodon/Timelines/HomeTest.php
  tests/src/Module/Api/Mastodon/Timelines/PublicTimelineTest.php
  tests/src/Module/Api/Twitter/Account/RateLimitStatusTest.php
  tests/src/Module/Api/Twitter/Account/UpdateProfileTest.php
  tests/src/Module/Api/Twitter/Account/UpdateTest.php
  tests/src/Module/Api/Twitter/Blocks/ListsTest.php
  tests/src/Module/Api/Twitter/Followers/ListsTest.php
  tests/src/Module/Api/Twitter/Friends/ListsTest.php
  tests/src/Module/Api/Twitter/Friendships/IncomingTest.php
  tests/src/Module/Api/Twitter/Lists/StatusesTest.php
Labels: Bug, Enhancement

#11073 Suppress Undefined property message in Core\Protocol
  src/Core/Protocol.php
Labels: Bug

#11074 Initialize $permissions variable in ActivityPub\Transmitter::fetchPermissionBlockFromConversation
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#11075 developer intro the ! was missing in the #!
  doc/Developers-Intro.md
Labels: Docs

#11060 Fix typo
  src/Module/Admin/Blocklist/Contact.php
Labels: Enhancement, Translation

#11076 regen messages.po file
  view/lang/C/messages.po
Labels: Translation

#11077 Obsolete functionality removed
  mod/display.php
  src/Content/Text/BBCode.php
  src/Core/Protocol.php
Labels: Federation

#11079 Fix attachment handling
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Util/ParseUrl.php
  view/lang/C/messages.po
Labels: Federation, Enhancement

#11080 ZRL: Simplify the code structure
  src/App.php
Labels: Enhancement

#11081 Fix for ParseUrl ('type' was already in use)
  src/Util/ParseUrl.php
Labels: Bug

#11082 Fix the performance calculation for the content
  src/App.php
  src/App/Page.php
Labels: Enhancement

#11083 Fix redirect url in Guzzle Responses
  src/Network/HTTPClient/Response/GuzzleResponse.php
Labels: Bug

#11084 Another bunch of reeanbled tests & some minor API fixings
  src/Module/Api/Twitter/Favorites.php
  src/Module/Api/Twitter/Statuses/Destroy.php
  src/Module/Api/Twitter/Statuses/Retweet.php
  src/Module/Api/Twitter/Statuses/Show.php
  src/Module/Api/Twitter/Statuses/Update.php
  src/Module/Api/Twitter/Statuses/UserTimeline.php
  src/Module/Api/Twitter/Users/Lookup.php
  src/Module/Api/Twitter/Users/Search.php
  src/Module/Api/Twitter/Users/Show.php
  tests/datasets/api.fixture.php
  tests/legacy/ApiTest.php
  tests/src/Module/Api/ApiTest.php
  tests/src/Module/Api/Friendica/NotificationTest.php
  tests/src/Module/Api/Friendica/Photo/DeleteTest.php
  tests/src/Module/Api/Friendica/Photoalbum/DeleteTest.php
  tests/src/Module/Api/Friendica/Photoalbum/UpdateTest.php
  tests/src/Module/Api/GnuSocial/GnuSocial/ConfigTest.php
  tests/src/Module/Api/GnuSocial/Help/TestTest.php
  tests/src/Module/Api/Mastodon/Accounts/StatusesTest.php
  tests/src/Module/Api/Mastodon/Accounts/VerifyCredentialsTest.php
  tests/src/Module/Api/Twitter/Account/RateLimitStatusTest.php
  tests/src/Module/Api/Twitter/Account/UpdateProfileTest.php
  tests/src/Module/Api/Twitter/Blocks/ListsTest.php
  tests/src/Module/Api/Twitter/ContactEndpointTest.php
  tests/src/Module/Api/Twitter/Favorites/CreateTest.php
  tests/src/Module/Api/Twitter/Favorites/DestroyTest.php
  tests/src/Module/Api/Twitter/FavoritesTest.php
  tests/src/Module/Api/Twitter/Followers/ListsTest.php
  tests/src/Module/Api/Twitter/Friends/ListsTest.php
  tests/src/Module/Api/Twitter/Friendships/IncomingTest.php
  tests/src/Module/Api/Twitter/Lists/StatusesTest.php
  tests/src/Module/Api/Twitter/Media/UploadTest.php
  tests/src/Module/Api/Twitter/SavedSearchesTest.php
  tests/src/Module/Api/Twitter/Statuses/DestroyTest.php
  tests/src/Module/Api/Twitter/Statuses/MentionsTest.php
  tests/src/Module/Api/Twitter/Statuses/NetworkPublicTimelineTest.php
  tests/src/Module/Api/Twitter/Statuses/RetweetTest.php
  tests/src/Module/Api/Twitter/Statuses/ShowTest.php
  tests/src/Module/Api/Twitter/Statuses/UpdateTest.php
  tests/src/Module/Api/Twitter/Statuses/UserTimelineTest.php
  tests/src/Module/Api/Twitter/Users/LookupTest.php
  tests/src/Module/Api/Twitter/Users/SearchTest.php
  tests/src/Module/Api/Twitter/Users/ShowTest.php
Labels: Bug, Enhancement, API

#11086 Add Dice logging for Module creation
  src/App/Router.php
  static/defaults.config.php
Labels: Enhancement, Performance

#11087 Tests - avoid deprecation notices
  composer.json
  composer.lock
  tests/src/Core/Config/ConfigTest.php
  tests/src/Core/InstallerTest.php
  tests/src/Core/PConfig/PConfigTest.php
  tests/src/Module/Api/Twitter/Statuses/UpdateTest.php
  tests/src/Module/BaseApiTest.php
  tests/src/Util/ImagesTest.php
Labels: Enhancement

#11090 Use 100% width for audio elements
  view/global.css
Labels: Enhancement, UI

#11095 Change redirect page after delegation switch
  src/Module/Delegation.php
  view/lang/C/messages.po
Labels: UX, Enhancement

#11097 Remove deprecated /worker route
  static/routes.config.php
Labels: Bug

#11088 Make Friendica PHP8 compatible & fix 2FA AppSpecificPassword
  composer.json
  composer.lock
  src/Module/Settings/TwoFactor/Verify.php
  src/Security/TwoFactor/Model/AppSpecificPassword.php
Labels: Bug, Enhancement, PHP 8

#11096 Replace assertRegExp() assertMatchesRegularExpression() & Upgrade phpunit.xml
  tests/phpunit.xml
  tests/src/Core/Logger/AbstractLoggerTest.php
  tests/src/Core/Logger/WorkerLoggerTest.php
  tests/src/Core/SystemTest.php
  tests/src/Util/ProfilerTest.php
Labels: Enhancement

#11098 Enhance syslog logging
  src/Core/Logger/Factory/Logger.php
  src/Core/Logger/Type/SyslogLogger.php
  static/defaults.config.php
  static/env.config.php
Labels: Enhancement

#11092 Suppress Type error exception in ActivityPub\Processor
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#11099 Add own distribution cache for Sessions
  src/Core/Cache/Factory/Cache.php
  src/Core/Lock/Factory/Lock.php
  src/Core/Session/Factory/Session.php
  static/defaults.config.php
  static/dependencies.config.php
  static/env.config.php
Labels: Enhancement

#11100 Migrate distributed cache config value
  database.sql
  src/Core/Config/Util/ConfigFileLoader.php
  src/Core/Config/ValueObject/Cache.php
  static/dbstructure.config.php
  update.php
Labels: Bug

#11106 Issue 11101: Fix API authentification
  src/Module/Api/Mastodon/Apps.php
  src/Module/BaseApi.php
Labels: Bug, API

#11107 API: Fix for OAuth endpoints that mustn't be authorized
  src/Module/Api/Mastodon/Apps.php
  src/Module/OAuth/Acknowledge.php
  src/Module/OAuth/Revoke.php
  src/Module/OAuth/Token.php
Labels: Bug, API

#11110 Issue 11109: Fix server detection
  src/Model/GServer.php
Labels: Bug

#11113 RU translations THX Alexander An
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#11115 ET translation updated THX Rain Hawk
  view/lang/et/messages.po
  view/lang/et/strings.php
Labels: Translation

#11116 RU translations THX Alexander An
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#11118 Don't count the system user on the administration page
  src/Module/Admin/BaseUsers.php
  src/Module/Admin/Users/Active.php
  src/Module/Admin/Users/Index.php
Labels: UI

#11122 Issue 11120: Delete tables in the correct order
  src/Database/DBStructure.php
Labels: Bug

#11105 API: Direct Messages moved to new place
  include/api.php
  src/Factory/Api/Twitter/DirectMessage.php
  src/Module/Api/Friendica/DirectMessages/Search.php
  src/Module/Api/Twitter/ContactEndpoint.php
  src/Module/Api/Twitter/DirectMessages/All.php
  src/Module/Api/Twitter/DirectMessages/Conversation.php
  src/Module/Api/Twitter/DirectMessages/Destroy.php
  src/Module/Api/Twitter/DirectMessages/Inbox.php
  src/Module/Api/Twitter/DirectMessages/NewDM.php
  src/Module/Api/Twitter/DirectMessages/Sent.php
  src/Module/Api/Twitter/DirectMessagesEndpoint.php
  src/Object/Api/Twitter/DirectMessage.php
  static/routes.config.php
  tests/datasets/mail/mail.fixture.php
  tests/legacy/ApiTest.php
  tests/src/Module/Api/Friendica/DirectMessages/SearchTest.php
Labels: Enhancement, API

#11123 API: Set "dismissed" instead of "seen"
  database.sql
  doc/database/db_notification.md
  include/api.php
  src/Module/Api/Mastodon/Notifications.php
  src/Module/Api/Mastodon/Notifications/Clear.php
  src/Module/Api/Mastodon/Notifications/Dismiss.php
  src/Navigation/Notifications/Collection/Notifications.php
  src/Navigation/Notifications/Entity/Notification.php
  src/Navigation/Notifications/Repository/Notification.php
  static/dbstructure.config.php
Labels: API

#11112 Replace .drone.yml with .woodpecker tests
  .drone.yml
  .woodpecker/.code_standards_check.yml
  .woodpecker/.continuous-deployment.yml
  .woodpecker/.database_checks.yml
  .woodpecker/.messages.po_check.yml
  .woodpecker/.phpunit.yml
  .woodpecker/.releaser.yml
Labels: Enhancement

#11126 Improve woodpecker settings
  .woodpecker/.continuous-deployment.yml
  .woodpecker/.releaser.yml
Labels: Enhancement
