Repository friendica/friendica, pull requests merged in 2021-11, with the labels that each got.

#10946 DE, RU translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#10944 Add default value for PermissionSet Regex
  src/Security/PermissionSet/Exception/PermissionSetNotFoundException.php
  src/Security/PermissionSet/Exception/PermissionSetPersistenceException.php
  src/Security/PermissionSet/Repository/PermissionSet.php
  tests/src/Security/PermissionSet/Repository/PermissionSetTest.php
Labels: Bug

#10949 Accept photo fetching for octet-stream as well
  src/Module/Photo.php
Labels: Federation, Enhancement

#10948 Improve the JSON output of the log entries
  src/Core/Logger/Type/AbstractLogger.php
  tests/src/Core/Logger/AbstractLoggerTest.php
Labels: Enhancement

#10950 Issue 10947: Send correct accept-header for AP
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Receiver.php
  src/Util/HTTPSignature.php
Labels: Bug, Federation

#10905 Move contact deleted check from RemoveContent to Remove task
  src/Worker/Contact/Remove.php
  src/Worker/Contact/RemoveContent.php
Labels: Bug

#10951 Replaced deprecated "log" function call
  src/Core/Logger.php
  src/Core/System.php
  src/Core/UserImport.php
  src/Model/Profile.php
  src/Model/PushSubscriber.php
  src/Model/User.php
  src/Object/Post.php
  src/Object/Thread.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Email.php
  src/Worker/Delivery.php
  src/Worker/Notifier.php
  src/Worker/OnePoll.php
Labels: Enhancement

#10952 AR translation updates THX abidin toumi
  view/lang/ar/messages.po
  view/lang/ar/strings.php
Labels: Translation

#10953 The boot.php had been cleared of most functions
  boot.php
  include/api.php
  mod/photos.php
  mod/ping.php
  mod/settings.php
  mod/uimport.php
  mod/wall_upload.php
  src/App.php
  src/App/Page.php
  src/Content/Conversation.php
  src/Content/Nav.php
  src/Content/Widget.php
  src/Core/Lock/Type/SemaphoreLock.php
  src/Core/Renderer.php
  src/Core/System.php
  src/Core/Worker.php
  src/Model/Item.php
  src/Model/Photo.php
  src/Model/User.php
  src/Module/ActivityPub/Inbox.php
  src/Module/Admin/Site.php
  src/Module/BaseAdmin.php
  src/Module/Invite.php
  src/Module/Special/HTTPException.php
  src/Module/WellKnown/XSocialRelay.php
  src/Network/HTTPClient/Factory/HttpClient.php
  src/Object/Image.php
  src/Protocol/DFRN.php
  src/Protocol/Relay.php
  src/Render/FriendicaSmartyEngine.php
  src/Worker/OnePoll.php
  src/Worker/SpoolPost.php
  static/defaults.config.php
  static/settings.config.php
  tests/datasets/config/.htconfig.php
  tests/src/Core/Lock/SemaphoreLockTest.php
  view/theme/frio/config.php
Labels: Enhancement

#10941 Paradigm Restructuring Part 4 - Process
  bin/daemon.php
  bin/worker.php
  src/App.php
  src/Core/Logger/Type/WorkerLogger.php
  src/Core/Process.php
  src/Core/System.php
  src/Core/Worker.php
  src/Core/Worker/Entity/Process.php
  src/Core/Worker/Exception/ProcessPersistenceException.php
  src/Core/Worker/Factory/Process.php
  src/Core/Worker/Repository/Process.php
  src/DI.php
  src/Model/Process.php
  src/Module/Admin/Site.php
  src/Network/HTTPException/MovedPermanentlyException.php
  static/dependencies.config.php
  static/settings.config.php
  tests/src/Core/Logger/WorkerLoggerTest.php
  tests/src/Model/ProcessTest.php
  view/lang/C/messages.po
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement

#10956 Some removed escapeTags calls
  mod/lostpass.php
  mod/pubsub.php
  mod/pubsubhubbub.php
  mod/salmon.php
  mod/tagrm.php
  mod/unfollow.php
  src/Model/Item.php
  src/Model/User.php
  src/Module/Admin/Item/Delete.php
  src/Module/Admin/Logs/Settings.php
  src/Module/Admin/Storage.php
  src/Module/Register.php
  src/Module/Xrd.php
  src/Network/Probe.php
  src/Security/Authentication.php
  src/Worker/OnePoll.php
Labels: Enhancement

#10958 Some more "escapeTags" removed
  mod/message.php
  mod/photos.php
  mod/settings.php
  mod/wallmessage.php
  src/Module/Admin/Site.php
  src/Module/Contact.php
  src/Module/Directory.php
  src/Module/Group.php
  src/Module/Help.php
  src/Module/Install.php
  src/Module/Search/Acl.php
  src/Module/Security/Login.php
  src/Module/Settings/Display.php
  src/Module/Settings/Profile/Index.php
  view/theme/frio/templates/photo_view.tpl
  view/theme/quattro/templates/photo_view.tpl
  view/theme/vier/templates/photo_view.tpl
Labels: Enhancement

#10957 Add `hostname` to `Process` entity
  database.sql
  src/Core/Worker/Entity/Process.php
  src/Core/Worker/Exception/ProcessPersistenceException.php
  src/Core/Worker/Factory/Process.php
  src/Core/Worker/Repository/Process.php
  src/Database/DBStructure.php
  src/Model/Host.php
  static/dbstructure.config.php
  static/dependencies.config.php
  tests/src/Core/Worker/Repository/ProcessTest.php
Labels: Enhancement

#10963 Drone | check database.sql
  .drone.yml
Labels: Enhancement

#10965 DE, RU translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#10967 API: some Functionality is transferred to new places
  include/api.php
  mod/wall_upload.php
  src/Module/Api/Friendica/Events/Index.php
  src/Module/Api/Friendica/Profile/Show.php
  src/Module/Api/GNUSocial/GNUSocial/Version.php
  src/Module/Api/GNUSocial/Help/Test.php
  src/Module/Api/Twitter/Account/RateLimitStatus.php
  src/Module/Api/Twitter/SavedSearches.php
  src/Module/BaseApi.php
  src/Object/Api/Twitter/SavedSearch.php
  src/Util/Arrays.php
  static/routes.config.php
  tests/legacy/ApiTest.php
Labels: Enhancement, API

#10975 Some more API functions moved
  include/api.php
  src/Module/Api/Friendica/Group/Delete.php
  src/Module/Api/GNUSocial/GNUSocial/Config.php
  static/routes.config.php
  tests/legacy/ApiTest.php
Labels: Enhancement, API

#10984 updated dica entry
  doc/FAQ.md
  doc/de/FAQ.md
Labels: Docs, Enhancement

#10985 split admin FAQs
  doc/FAQ-admin.md
  doc/FAQ.md
  doc/Home.md
  doc/de/FAQ-admin.md
  doc/de/FAQ.md
  doc/de/Home.md
Labels: Docs, Enhancement

#10980 [frio] Wire edit form formatting button aria labels
  mod/editpost.php
  view/lang/C/messages.po
Labels: Bug, Theme-specific, UX

#10982 [frio] Check for role="presentation" uses throughout the templates
  view/theme/frio/js/filebrowser.js
  view/theme/frio/templates/filebrowser.tpl
  view/theme/frio/templates/jot.tpl
  view/theme/frio/templates/nav.tpl
Labels: Bug, Theme-specific, UX

#10986 Issue 10983: Use the user's settings for the help language
  src/Module/Help.php
Labels: Docs, UX, Enhancement

#10992 Hotfix: Deleted content
  src/App/Page.php
Labels: Bug

#10994 Replace Module::init() with Constructors
  mod/display.php
  src/App/ModuleController.php
  src/BaseModule.php
  src/Capabilities/ICanHandleRequests.php
  src/LegacyModule.php
  src/Module/Admin/Themes/Embed.php
  src/Module/Admin/Tos.php
  src/Module/Api/Twitter/ContactEndpoint.php
  src/Module/Apps.php
  src/Module/BaseNotifications.php
  src/Module/Contact/Advanced.php
  src/Module/Contact/Revoke.php
  src/Module/Debug/Feed.php
  src/Module/Diaspora/Receive.php
  src/Module/Filer/SaveTag.php
  src/Module/FriendSuggest.php
  src/Module/Install.php
  src/Module/Magic.php
  src/Module/Notifications/Introductions.php
  src/Module/Notifications/Notifications.php
  src/Module/Owa.php
  src/Module/Profile/Index.php
  src/Module/Register.php
  src/Module/RemoteFollow.php
  src/Module/Search/Saved.php
  src/Module/Security/Logout.php
  src/Module/Security/TwoFactor/Recovery.php
  src/Module/Settings/TwoFactor/AppSpecific.php
  src/Module/Settings/TwoFactor/Recovery.php
  src/Module/Settings/TwoFactor/Trusted.php
  src/Module/Settings/TwoFactor/Verify.php
  src/Module/Statistics.php
  src/Module/Tos.php
  tests/src/App/ModuleControllerTest.php
  tests/src/Module/Api/Friendica/NotificationTest.php
  tests/src/Module/Api/Friendica/Photo/DeleteTest.php
  tests/src/Module/Api/Friendica/Photoalbum/DeleteTest.php
  tests/src/Module/Api/Friendica/Photoalbum/UpdateTest.php
  tests/src/Module/Api/GnuSocial/GnuSocial/VersionTest.php
  tests/src/Module/Api/GnuSocial/Help/TestTest.php
  tests/src/Module/Api/Twitter/Account/RateLimitStatusTest.php
  tests/src/Module/Api/Twitter/SavedSearchesTest.php
  view/lang/C/messages.po
Labels: Enhancement

#10987 API: moved classes / unified user array creation
  include/api.php
  mod/wall_upload.php
  src/Factory/Api/Twitter/User.php
  src/Module/Api/Friendica/Profile/Show.php
  src/Module/Api/Twitter/Account/RateLimitStatus.php
  src/Module/Api/Twitter/Followers/Ids.php
  src/Module/Api/Twitter/Followers/Lists.php
  src/Module/Api/Twitter/Friends/Ids.php
  src/Module/Api/Twitter/Friends/Lists.php
  src/Module/BaseApi.php
  src/Object/Api/Twitter/User.php
  src/Security/BasicAuth.php
  src/Util/DateTimeFormat.php
  static/routes.config.php
  tests/legacy/ApiTest.php
  tests/src/Contact/FriendSuggest/Factory/FriendSuggestTest.php
  tests/src/Module/Api/Twitter/ContactEndpointTest.php
Labels: Enhancement, API

#11002 Replace `Modules::init()` with Constructors (Retry)
  mod/display.php
  src/App/ModuleController.php
  src/BaseModule.php
  src/Capabilities/ICanHandleRequests.php
  src/LegacyModule.php
  src/Module/Admin/Themes/Embed.php
  src/Module/Admin/Tos.php
  src/Module/Api/Twitter/ContactEndpoint.php
  src/Module/Apps.php
  src/Module/BaseNotifications.php
  src/Module/Contact/Advanced.php
  src/Module/Contact/Revoke.php
  src/Module/Debug/Feed.php
  src/Module/Diaspora/Receive.php
  src/Module/Filer/SaveTag.php
  src/Module/FriendSuggest.php
  src/Module/Install.php
  src/Module/Magic.php
  src/Module/Notifications/Introductions.php
  src/Module/Notifications/Notifications.php
  src/Module/Owa.php
  src/Module/Profile/Index.php
  src/Module/Register.php
  src/Module/RemoteFollow.php
  src/Module/Search/Saved.php
  src/Module/Security/Logout.php
  src/Module/Security/TwoFactor/Recovery.php
  src/Module/Settings/TwoFactor/AppSpecific.php
  src/Module/Settings/TwoFactor/Recovery.php
  src/Module/Settings/TwoFactor/Trusted.php
  src/Module/Settings/TwoFactor/Verify.php
  src/Module/Statistics.php
  src/Module/Tos.php
  tests/src/App/ModuleControllerTest.php
  tests/src/Module/Api/Friendica/NotificationTest.php
  tests/src/Module/Api/Friendica/Photo/DeleteTest.php
  tests/src/Module/Api/Friendica/Photoalbum/DeleteTest.php
  tests/src/Module/Api/Friendica/Photoalbum/UpdateTest.php
  tests/src/Module/Api/GnuSocial/GnuSocial/VersionTest.php
  tests/src/Module/Api/GnuSocial/Help/TestTest.php
  tests/src/Module/Api/Twitter/Account/RateLimitStatusTest.php
  tests/src/Module/Api/Twitter/SavedSearchesTest.php
  view/lang/C/messages.po
Labels: Enhancement

#10999 Fix Installer setup
  src/Module/Install.php
Labels: Bug, Installation

#11004 `Module::init()` Fixings
  src/App.php
Labels: Bug

#11009 Updated FAQ Client section
  doc/FAQ.md
  doc/de/FAQ.md
Labels: Docs

#11003 Fix legacy API
  include/api.php
  src/Module/Api/ApiResponse.php
  src/Module/Api/Friendica/Index.php
  src/Module/BaseApi.php
  tests/datasets/api.fixture.php
  tests/legacy/ApiTest.php
  tests/src/Module/Api/ApiResponseTest.php
Labels: Bug, API

#11010 re-add gnusocial to FAQ Client API info
  doc/FAQ.md
  doc/de/FAQ.md
Labels: Docs

#11012 Fix followers/following for the Mastodon API
  src/Module/Api/Mastodon/Accounts/Followers.php
  src/Module/Api/Mastodon/Accounts/Following.php
  src/Module/Api/Mastodon/Blocks.php
  src/Module/Api/Mastodon/Lists/Accounts.php
  src/Module/Api/Mastodon/Mutes.php
Labels: Bug, API

#11013 Fix followers/following for the Friendica API
  include/api.php
  src/Module/Api/Twitter/ContactEndpoint.php
  src/Module/Api/Twitter/Followers/Ids.php
  src/Module/Api/Twitter/Followers/Lists.php
  src/Module/Api/Twitter/Friends/Ids.php
  src/Module/Api/Twitter/Friends/Lists.php
  src/Module/BaseApi.php
  src/Object/Api/Twitter/User.php
  tests/legacy/ApiTest.php
  tests/src/Module/Api/Twitter/ContactEndpointTest.php
  view/lang/C/messages.po
Labels: Bug, API

#10969 Move individual contact modules to their own class
  database.sql
  doc/database/db_user-contact.md
  mod/repair_ostatus.php
  mod/update_contact.php
  src/Contact/LocalRelationship/Entity/LocalRelationship.php
  src/Contact/LocalRelationship/Exception/LocalRelationshipPersistenceException.php
  src/Contact/LocalRelationship/Factory/LocalRelationship.php
  src/Contact/LocalRelationship/Repository/LocalRelationship.php
  src/Core/Protocol.php
  src/Model/Contact.php
  src/Model/Contact/User.php
  src/Model/User.php
  src/Module/Api/Mastodon/Accounts/Follow.php
  src/Module/Contact.php
  src/Module/Contact/Conversations.php
  src/Module/Contact/Posts.php
  src/Module/Contact/Profile.php
  static/dbstructure.config.php
  static/routes.config.php
  update.php
  view/lang/C/messages.po
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: Enhancement

#11016 one sentence per line
  doc/FAQ.md
  doc/de/FAQ.md
Labels: Docs

#11017 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11015 Move title attribute to <time> tag
  src/Content/Conversation.php
  src/Module/Settings/TwoFactor/Trusted.php
  src/Security/TwoFactor/Model/AppSpecificPassword.php
  view/templates/settings/twofactor/app_specific.tpl
  view/templates/settings/twofactor/trusted_browsers.tpl
  view/templates/wall_thread.tpl
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/smoothly/templates/wall_thread.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: UX, Enhancement

#11019 FAQ: removed windows client
  doc/FAQ.md
  doc/de/FAQ.md
Labels: Docs, Enhancement

#11018 API: The status is now an object
  database.sql
  include/api.php
  mod/photos.php
  mod/poco.php
  src/DI.php
  src/Factory/Api/Friendica/Activities.php
  src/Factory/Api/Twitter/Attachment.php
  src/Factory/Api/Twitter/Hashtag.php
  src/Factory/Api/Twitter/Media.php
  src/Factory/Api/Twitter/Mention.php
  src/Factory/Api/Twitter/Status.php
  src/Factory/Api/Twitter/Url.php
  src/Factory/Api/Twitter/User.php
  src/Module/Api/ApiResponse.php
  src/Module/Api/Friendica/Notification/Seen.php
  src/Module/Api/GNUSocial/Statusnet/Conversation.php
  src/Module/Api/Twitter/Account/UpdateProfile.php
  src/Module/Api/Twitter/Account/VerifyCredentials.php
  src/Module/Api/Twitter/Favorites.php
  src/Module/Api/Twitter/Lists/Statuses.php
  src/Module/Api/Twitter/Search/Tweets.php
  src/Module/Api/Twitter/Statuses/Destroy.php
  src/Module/Api/Twitter/Statuses/HomeTimeline.php
  src/Module/Api/Twitter/Statuses/Mentions.php
  src/Module/Api/Twitter/Statuses/NetworkPublicTimeline.php
  src/Module/Api/Twitter/Statuses/PublicTimeline.php
  src/Module/Api/Twitter/Statuses/Show.php
  src/Module/Api/Twitter/Statuses/UserTimeline.php
  src/Module/Api/Twitter/Users/Lookup.php
  src/Module/Api/Twitter/Users/Search.php
  src/Module/Api/Twitter/Users/Show.php
  src/Module/BaseApi.php
  src/Object/Api/Twitter/Attachment.php
  src/Object/Api/Twitter/Hashtag.php
  src/Object/Api/Twitter/Media.php
  src/Object/Api/Twitter/Mention.php
  src/Object/Api/Twitter/Status.php
  src/Object/Api/Twitter/Url.php
  src/Object/Api/Twitter/User.php
  src/Security/BasicAuth.php
  static/dbstructure.config.php
  static/dbview.config.php
  static/routes.config.php
  tests/legacy/ApiTest.php
Labels: Enhancement, API

#11031 Escape dollar sign in replace string to prevent placeholder replacement in Model\Item::addShareDataFromOriginal
  src/Model/Item.php
Labels: Bug

#11030 Add backward compatibility with user contacts in Module\Group
  src/Model/Group.php
  src/Module/Group.php
  static/routes.config.php
  view/lang/C/messages.po
Labels: Bug

#11025 Improve connector hooks
  doc/Addons.md
  src/Model/Item.php
  src/Network/Probe.php
Labels: Addons, Enhancement

#11036 Bugfixing Module Method syntax
  src/LegacyModule.php
  src/Module/Api/Friendica/Notification/Seen.php
  src/Module/Api/GNUSocial/Statusnet/Conversation.php
  src/Module/Api/Mastodon/Filters.php
  src/Module/Api/Twitter/Account/UpdateProfile.php
  src/Module/Api/Twitter/Account/VerifyCredentials.php
  src/Module/Api/Twitter/Blocks/Ids.php
  src/Module/Api/Twitter/Blocks/Lists.php
  src/Module/Api/Twitter/Favorites.php
  src/Module/Api/Twitter/Friendships/Incoming.php
  src/Module/Api/Twitter/Lists/Statuses.php
  src/Module/Api/Twitter/Search/Tweets.php
  src/Module/Api/Twitter/Statuses/Destroy.php
  src/Module/Api/Twitter/Statuses/HomeTimeline.php
  src/Module/Api/Twitter/Statuses/Mentions.php
  src/Module/Api/Twitter/Statuses/NetworkPublicTimeline.php
  src/Module/Api/Twitter/Statuses/PublicTimeline.php
  src/Module/Api/Twitter/Statuses/Show.php
  src/Module/Api/Twitter/Statuses/UserTimeline.php
  src/Module/Api/Twitter/Users/Lookup.php
  src/Module/Api/Twitter/Users/Search.php
  src/Module/Api/Twitter/Users/Show.php
  src/Module/Contact.php
  src/Module/OAuth/Revoke.php
  tests/legacy/ApiTest.php
  tests/src/Module/Api/GnuSocial/GnuSocial/ConfigTest.php
  tests/src/Module/Api/Mastodon/Accounts/StatusesTest.php
  tests/src/Module/Api/Mastodon/Accounts/VerifyCredentialsTest.php
  tests/src/Module/Api/Mastodon/ConversationsTest.php
  tests/src/Module/Api/Mastodon/SearchTest.php
  tests/src/Module/Api/Mastodon/Timelines/HomeTest.php
  tests/src/Module/Api/Mastodon/Timelines/PublicTimelineTest.php
  tests/src/Module/Api/Twitter/Account/UpdateTest.php
  tests/src/Module/Api/Twitter/Blocks/ListsTest.php
  tests/src/Module/Api/Twitter/FavoritesTest.php
  tests/src/Module/Api/Twitter/Followers/ListsTest.php
  tests/src/Module/Api/Twitter/Friends/ListsTest.php
  tests/src/Module/Api/Twitter/Friendships/IncomingTest.php
  tests/src/Module/Api/Twitter/Lists/StatusesTest.php
  tests/src/Module/Api/Twitter/Statuses/DestroyTest.php
  tests/src/Module/Api/Twitter/Statuses/MentionsTest.php
  tests/src/Module/Api/Twitter/Statuses/NetworkPublicTimelineTest.php
  tests/src/Module/Api/Twitter/Statuses/ShowTest.php
  tests/src/Module/Api/Twitter/Statuses/UserTimelineTest.php
  tests/src/Module/Api/Twitter/Users/LookupTest.php
  tests/src/Module/Api/Twitter/Users/SearchTest.php
  tests/src/Module/Api/Twitter/Users/ShowTest.php
Labels: Bug

#11042 Some Fixings
  database.sql
  src/Content/Text/BBCode.php
  src/Module/BaseApi.php
  tests/Util/AppDouble.php
  tests/Util/AppMockTrait.php
  tests/src/Content/SmiliesTest.php
  tests/src/Content/Text/BBCodeTest.php
  tests/src/Content/Text/HTMLTest.php
  tests/src/Content/Text/MarkdownTest.php
  tests/src/Module/Api/ApiTest.php
  view/lang/C/messages.po
Labels: Bug

#11046 Fix remaining references to BaseModule->parameters
  src/Module/Api/Friendica/Group/Delete.php
  src/Module/Api/Friendica/Group/Update.php
  src/Module/Contact/Profile.php
Labels: Bug

#11037 Fix Api\Friendica\Photo|album\Delete endpoints
  src/Module/Api/Friendica/Photo/Delete.php
  src/Module/Api/Friendica/Photoalbum/Delete.php
  tests/datasets/photo/photo.fixture.php
  tests/datasets/photo/test_photo.content
  tests/src/Module/Api/Friendica/Photo/DeleteTest.php
  tests/src/Module/Api/Friendica/Photoalbum/DeleteTest.php
  tests/src/Module/Api/Friendica/Photoalbum/UpdateTest.php
Labels: Bug, API

#11048 Add expected field uri-id to Post query in prepare_photo_data()
  include/api.php
Labels: Bug, API

#11045 Use user-specific id to fetch the list of group appartenance in Module\Contact\Profile
  src/Module/Contact/Profile.php
Labels: Bug

#11014 [frio] Make accordions keyboard actionable
  doc/Addons.md
  mod/settings.php
  view/lang/C/messages.po
  view/templates/settings/addon/connector.tpl
  view/templates/settings/addon/link.tpl
  view/templates/settings/addon/panel.tpl
  view/templates/settings/addons.tpl
  view/templates/settings/connectors.tpl
  view/theme/frio/css/style.css
  view/theme/frio/templates/admin/blocklist/contact.tpl
  view/theme/frio/templates/admin/features.tpl
  view/theme/frio/templates/admin/site.tpl
  view/theme/frio/templates/admin/storage.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/frio/templates/settings/addon/connector.tpl
  view/theme/frio/templates/settings/addon/link.tpl
  view/theme/frio/templates/settings/addon/panel.tpl
  view/theme/frio/templates/settings/addons.tpl
  view/theme/frio/templates/settings/connectors.tpl
  view/theme/frio/templates/settings/display.tpl
  view/theme/frio/templates/settings/features.tpl
  view/theme/frio/templates/settings/profile/index.tpl
  view/theme/frio/templates/settings/settings.tpl
Labels: UX, Enhancement

#11050 Prevent API-submitted public pictures to be published as statuses
  include/api.php
Labels: Enhancement, API
