Repository friendica/friendica, pull requests merged in 2021-03, with the labels that each got.

#9970 Avoid lock problems, fix foreign key problems with contact-relation
  src/Model/Contact.php
  src/Model/Tag.php
  src/Worker/ExpirePosts.php
  src/Worker/MergeContact.php
Labels: Bug

#9974 Fix slow queries
  database.sql
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Post.php
  src/Worker/UpdateContacts.php
  static/dbstructure.config.php
  update.php
Labels: Enhancement, Performance

#9973 Update Composer executable to version 1.10.20 to add PHP 8 support
  bin/composer.phar
Labels: Installation, php8.0

#9976 Call post and item-uri expiry in sequence
  src/Worker/CleanItemUri.php
  src/Worker/Cron.php
  src/Worker/Expire.php
  src/Worker/ExpirePosts.php
Labels: Bug

#9972 Make frio the default theme
  static/settings.config.php
  tests/datasets/config/.htconfig.php
  tests/src/Util/Config/ConfigFileLoaderTest.php
Labels: Installation

#9979 Reduce blocks when removing orphans
  src/Worker/ExpirePosts.php
  src/Worker/UpdateContacts.php
  static/settings.config.php
Labels: Enhancement

#9982 Issue 9975: Remove unused views
  src/Database/View.php
Labels: Bug

#9981 Issue 9977: Check for existance of the "item" table on postupdate
  src/Database/PostUpdate.php
Labels: Bug

#9987 Small performance improvements, new view for future use
  database.sql
  src/Model/Group.php
  src/Model/Post.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement, Performance

#9991 Issue 9968: Avoid blocking update calls
  database.sql
  src/Model/Contact.php
  static/dbstructure.config.php
Labels: Bug, Installation

#9994 Issue 9986: Improve contact search
  src/Core/Search.php
  src/Model/Contact.php
  src/Module/Contact.php
  src/Module/Search/Acl.php
Labels: Enhancement, Performance, UX

#10000 issue-9992
  include/enotify.php
  src/Model/Item.php
Labels: Bug, Translation

#10001 issue 9925: Fixes database error with MySQL 8
  src/Module/Update/Profile.php
Labels: Bug

#10003 issue-9799: Ensure that the first post date is after the registration
  src/Content/Widget.php
  src/Model/Item.php
  src/Model/Post.php
Labels: Bug, UX

#10004 API: Resize uploaded images
  mod/wall_upload.php
Labels: API, Bug

#10005 Issue 8547: Improve page load speed
  src/Content/ContactSelector.php
  src/Module/Contact.php
  src/Module/Group.php
Labels: Enhancement, Performance

#10006 Use "failed" instead of "archive" for contact update check
  src/Worker/UpdateContacts.php
Labels: Enhancement

#10007 issue 9980: Field "type" does not exist anymore
  include/api.php
Labels: API, Bug

#10008 Don't check for table_open_cache when pdo_emulate_prepares is activated
  src/Module/Admin/Summary.php
Labels: Enhancement, UX

#10009 The template "maitnenance.tpl" isn't used anymore
  view/templates/maintenance.tpl
Labels: Enhancement

#10010 issue 9996: "bd" cannot be ""
  src/Model/Contact.php
Labels: Bug

#10011 Issue 9743: Added translatable texts
  src/Module/Admin/Item/Source.php
  src/Module/Debug/ActivityPubConversion.php
  src/Module/Debug/Babel.php
  src/Module/Debug/Probe.php
  src/Module/Debug/WebFinger.php
  view/lang/C/messages.po
  view/templates/admin/item/source.tpl
  view/templates/babel.tpl
  view/templates/debug/activitypubconversion.tpl
  view/templates/probe.tpl
  view/templates/webfinger.tpl
Labels: Enhancement, Translation

#10014 issue 9906: Provide index hints to speed up community page loading
  src/Model/Post.php
Labels: Enhancement, Performance

#10016 Added missing type-hints
  view/theme/frio/theme.php
Labels: Enhancement

#10023 Issue 9906: Hopefully fixes the speed issues
  database.sql
  src/Model/Post.php
  static/dbstructure.config.php
Labels: Enhancement, Performance

#10024 Block tags from the trending tags
  src/Model/Tag.php
  static/defaults.config.php
Labels: Enhancement

#10018 Remove dead friendica-wiki.de from German help page
  doc/de/Home.md
Labels: Docs

#10025 Index improvements / Improvements fetching "pinned"
  database.sql
  src/Model/Post.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement, Performance

#10026 Fixes notice: "Undefined index: type"
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug

#10028 Add security.txt file
  security.txt
  src/Module/WellKnown/SecurityTxt.php
  static/routes.config.php
Labels: Enhancement, Security

#10027 Improve maintenance page
  src/App.php
  src/Module/Maintenance.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/exception.tpl
Labels: Enhancement, UX

#10029 We now set the protocol in "gserver" on receiving as well
  mod/pubsub.php
  mod/salmon.php
  src/Model/GServer.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
Labels: Enhancement, Federation

#10022 Add setting for proxy file chmod value
  src/Module/Proxy.php
  static/defaults.config.php
Labels: Enhancement

#10033 Update value interpolation syntax in Model\Event::getListById
  src/Model/Event.php
Labels: Bug

#10034 Trending tags are now sort by different users
  database.sql
  src/Model/Tag.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement, UX

#10035 Part of bugfix for storage move problem
  src/Core/StorageManager.php
Labels: Bug

#10036 Installer: install themes as last action
  src/Module/Install.php
Labels: Bug, Installation

#10040 Only set file permissions when configured
  src/Module/Proxy.php
  static/defaults.config.php
Labels: Enhancement, Installation

#10042 Increase video tag regular expression specificity to decrease backtrack in BBCode::convert
  src/Content/Text/BBCode.php
Labels: Bug, Performance

#10045 Fix notifications for public posts
  include/enotify.php
Labels: Bug, UX

#10046 Use system.allowed_oembed config to allow iframe source
  src/Content/Text/BBCode.php
  src/Content/Text/HTML.php
  src/Module/Admin/Site.php
  src/Module/Debug/Babel.php
  tests/src/Content/Text/BBCodeTest.php
  view/lang/C/messages.po
Labels: Bug

#10048 Bug/10047 translation back to top
  view/lang/C/messages.po
  view/theme/frio/php/default.php
  view/theme/frio/php/standard.php
Labels: Enhancement, Translation

#10056 PM: skip messages from missing contacts
  mod/message.php
Labels: Bug, UX

#10057 Issue 10050: Improved order of deletions
  src/Worker/ExpireAndRemoveUsers.php
Labels: Enhancement

#10058 Issue 10050: Improve photo deletions
  src/Model/Photo.php
Labels: Enhancement

#10061 Issue 10050: Ensure to not create contacts for expired users
  src/Model/Contact.php
  src/Model/User.php
Labels: Bug

#10063 Check media links when fetching page information
  src/Util/ParseUrl.php
Labels: Enhancement

#10064 Avoid foreign key violations
  src/Worker/MergeContact.php
Labels: Bug

#10065 Display the provider and author of a shared post
  src/Content/Text/BBCode.php
  src/Util/ParseUrl.php
Labels: Enhancement

#10066 ParseUrl: Perform entity decode afterwards
  src/Util/ParseUrl.php
Labels: Bug

#10069 Avoid fatal errors and notices
  src/Object/Image.php
  src/Util/ParseUrl.php
Labels: Bug

#10073 Avoid foreign key violations when deleting unused tables
  src/Database/DBStructure.php
Labels: Bug

#10075 Fixes PHP Warning: " array_unshift() expects parameter 1 to be array, int given"
  src/Core/Worker.php
Labels: Bug

#10074 Don't automatically post hashtags when sharing links
  mod/item.php
Labels: Enhancement

#10076 Delete ActivityPub comments
  src/Model/Item.php
  src/Module/Objects.php
  src/Object/Post.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#10077 Remove dead profile link from help page
  doc/Home.md
Labels: Bug, Docs

#10078 Improved checks when adding contacts
  mod/settings.php
  src/Model/Contact.php
Labels: Bug

#10079 Added support for Mobilizon on the federation page
  src/Module/Admin/Federation.php
Labels: Enhancement, Federation

#10080 [Composer] Update dependencies before release
  composer.lock
Labels: Enhancement

#10081 Limit the size of contact avatars
  src/Model/Photo.php
  src/Object/Image.php
Labels: Enhancement, Performance

#10082 Deletions are now done via DFRN as well
  src/Worker/Notifier.php
Labels: Enhancement, Federation

#10083 Use the "post-user" table instead of the "post" table for deletion checks
  src/Worker/ExpirePosts.php
Labels: Bug

#10084 Fix Warning "key() expects parameter 1 to be array, string given"
  src/Util/ParseUrl.php
Labels: Bug

#10086 Workaround for cURL troubles in container environments
  src/Core/Installer.php
Labels: Enhancement, Installation

#10089 Issue 4755: Use the system mail address as sender
  src/Module/Invite.php
Labels: Bug, Federation

#10092 Fix the display of mentions on Pleroma
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Federation

#10090 FollowUp #10086
  src/Core/Installer.php
  view/lang/C/messages.po
Labels: Enhancement, Installation, Translation

#10094 Fix license text
  LICENSE
Labels: Docs

#10095 Fix: ParseUrl now fetches images again
  src/Util/ParseUrl.php
Labels: Bug

#10096 ParseUrl: Remove image when it doesn't fit the requirements
  src/Util/ParseUrl.php
Labels: Bug

#10098 ParseUrl: Avoid HTML in returned content
  src/Util/ParseUrl.php
Labels: Bug, Security

#10101 Fix object handling inside log arrays
  src/Util/Logger/AbstractLogger.php
  src/Util/Logger/StreamLogger.php
  src/Util/Logger/SyslogLogger.php
  tests/src/Util/Logger/AbstractLoggerTest.php
Labels: Bug

#10102 HU, IT, RU translations
  view/lang/hu/messages.po
  view/lang/hu/strings.php
  view/lang/it/messages.po
  view/lang/it/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#10104 Fix JIT Config Adapter caching
  src/Core/Config/JitConfig.php
  src/Core/Config/PreloadConfig.php
  tests/src/Core/Config/CacheTest.php
  tests/src/Core/Config/ConfigTest.php
  tests/src/Core/Config/JitConfigTest.php
  tests/src/Core/Config/PreloadConfigTest.php
Labels: Bug
