Repository friendica/friendica, pull requests merged in 2021-08, with the labels that each got.

#10562 Fix legacy storage config
  src/Module/Admin/Storage.php
  view/lang/C/messages.po
Labels: Bug

#10563 Issue 8038: Scheduled posts via the frontend
  doc/Accesskeys.md
  include/conversation.php
  mod/item.php
  src/Model/Item.php
  src/Module/BaseProfile.php
  src/Module/Item/Compose.php
  src/Module/Profile/Schedule.php
  src/Util/Temporal.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/item/compose.tpl
  view/templates/jot.tpl
  view/theme/frio/templates/jot.tpl
  view/theme/quattro/templates/jot.tpl
  view/theme/smoothly/templates/jot.tpl
Labels: New Feature

#10566 Use the general function ro create an avatar path
  src/Module/Delegation.php
  src/Network/Probe.php
Labels: Enhancement

#10569 Issue 10568: Deleting of scheduled posts didn't work
  view/templates/profile/schedule.tpl
Labels: Bug

#10570 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10571 Display the publish time in the local timezone
  src/Module/Profile/Schedule.php
Labels: Enhancement

#10572 Don't use the system user for participation messages
  src/Protocol/Diaspora.php
Labels: Enhancement, Federation

#10573 HU translation updated THX Balázs Úr
  view/lang/hu/messages.po
  view/lang/hu/strings.php
Labels: Translation

#10574 Create the Diaspora signature for the correct user
  include/conversation.php
  src/Model/Item.php
  src/Model/User.php
  src/Module/Xrd.php
  src/Network/Probe.php
  src/Protocol/Diaspora.php
Labels: Federation, Enhancement

#10576 Fix multiple display problems in conversations
  include/conversation.php
Labels: Bug, UX

#10575 Extract MP4 video URL from PeerTube ActivityPub metadata to enable video embed
  src/Protocol/ActivityPub/Receiver.php
Labels: Federation, Enhancement

#10579 Avoid some HTTP errors
  src/Model/Storage/ExternalResource.php
  src/Module/Photo.php
  src/Module/Proxy.php
  static/routes.config.php
  view/lang/C/messages.po
Labels: Bug

#10589 Fix profile probing via Pleroma
  src/Module/Xrd.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#10590 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10591 Handles PHP Notice: Undefined index: addr in src/Protocol/Diaspora.php on line 3091
  src/Protocol/Diaspora.php
Labels: Bug

#10592 Simplify event storing
  src/Model/Event.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/DFRN.php
Labels: Bug, Calendar, Federation

#10593 The Matrix and XMPP address is now transported via AP as well
  database.sql
  doc/database/db_apcontact.md
  src/Model/APContact.php
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Transmitter.php
  static/dbstructure.config.php
Labels: Federation, Enhancement

#10580 Simplify attachment processing in Protocol\ActivityPub\Receiver
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement

#10594 docs, remove freenode from the IRC list
  doc/FAQ.md
  doc/Home.md
  doc/de/FAQ.md
  doc/de/Home.md
Labels: Docs

#10597 Fixes "PHP Warning: key() expects parameter 1 to be array, string given"
  src/Util/JsonLD.php
Labels: Bug

#10596 Follow, file and star does now work for all items
  include/conversation.php
  mod/display.php
  src/Content/Item.php
  src/Module/Item/Star.php
  src/Module/Search/Filed.php
  src/Object/Post.php
  view/lang/C/messages.po
  view/templates/jot-header.tpl
  view/theme/frio/templates/jot-header.tpl
  view/theme/frio/theme.php
  view/theme/smoothly/templates/jot-header.tpl
Labels: Enhancement

#10600 AutomaticInstallation - Fix last example
  src/Console/AutomaticInstallation.php
Labels: Bug, Docs

#10605 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10602 Transmit push subscriptions
  CHANGELOG
  composer.json
  composer.lock
  src/Factory/Api/Mastodon/Subscription.php
  src/Model/Subscription.php
  src/Worker/PushSubscription.php
  static/defaults.config.php
Labels: New Feature, Federation

#10610 Add phpunit 8.5
  composer.json
  composer.lock
Labels: Enhancement

#10607 Add the attachments to the $item for the prepare_body_content_filter hook
  src/Model/Item.php
  src/Model/Post/Media.php
Labels: Addons, Enhancement

#10609 Issue 10514: add TLS check to the installer
  src/Core/Installer.php
  view/lang/C/messages.po
Labels: Installation, Enhancement, Security

#10612 Various Fatal error fixes
  mod/photos.php
  src/Module/RemoteFollow.php
  src/Network/Probe.php
Labels: Bug

#10608 Remove remaining mentions of $a->argc/argv
  doc/Addons.md
  doc/de/Addons.md
  view/theme/frio/php/default.php
  view/theme/frio/php/standard.php
Labels: Bug

#10614 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10611 Allow contact creation in Module\Debug\Feed
  src/Module/Debug/Feed.php
Labels: Enhancement

#10613 The push api payload content is improved
  src/Worker/PushSubscription.php
  view/lang/C/messages.po
Labels: Enhancement, API

#10604 ActivityPub: Add support for non-link mentions
  src/Protocol/ActivityPub/Processor.php
  tests/src/Protocol/ActivityPub/ProcessorMock.php
  tests/src/Protocol/ActivityPub/ProcessorTest.php
Labels: Federation, Enhancement

#10615 DE translation updats
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10616 Meaningful notification message
  src/Content/Text/Plaintext.php
  src/Model/Notification.php
  src/Worker/PushSubscription.php
  view/lang/C/messages.po
Labels: Enhancement

#10618 Escape url tags before attempting to add missing mention links in Protocol\ActivityPub\Processor
  src/Protocol/ActivityPub/Processor.php
  tests/src/Protocol/ActivityPub/ProcessorTest.php
Labels: Bug

#10309 Display structured logs in admin
  src/DI.php
  src/Model/Log/ParsedLogIterator.php
  src/Module/Admin/Logs/View.php
  src/Object/Log/ParsedLogLine.php
  src/Util/ReversedFileReader.php
  static/dependencies.config.php
  tests/datasets/log/friendica.log.txt
  tests/src/Model/Log/ParsedLogIteratorTest.php
  tests/src/Object/Log/ParsedLogLineTest.php
  view/js/module/admin/logs/view.js
  view/templates/admin/logs/view.tpl
  view/theme/frio/css/style.css
  view/theme/frio/js/module/admin/logs/view.js
  view/theme/frio/templates/admin/logs/view.tpl
Labels: Enhancement

#10620 The desktop notifications have been reworked
  include/enotify.php
  mod/settings.php
  src/Model/Notification.php
  src/Model/Subscription.php
  view/lang/C/messages.po
  view/templates/settings/settings.tpl
  view/theme/frio/templates/settings/settings.tpl
Labels: Enhancement

#10619 PSR-7 Part 1: Use Guzzle PSR-7 library for HTTPRequest->get()
  composer.json
  composer.lock
  src/Content/Text/BBCode.php
  src/Model/GServer.php
  src/Model/Photo.php
  src/Model/Post/Link.php
  src/Model/Post/Media.php
  src/Network/CurlResult.php
  src/Network/GuzzleResponse.php
  src/Network/HTTPRequest.php
  src/Network/IHTTPRequest.php
  src/Network/IHTTPResult.php
  src/Network/Probe.php
  src/Protocol/DFRN.php
  src/Protocol/OStatus.php
  src/Protocol/Salmon.php
  src/Util/ParseUrl.php
  tests/datasets/curl/about.head.php
  tests/datasets/curl/about.redirect.php
  tests/src/Core/InstallerTest.php
  tests/src/Network/CurlResultTest.php
Labels: Enhancement

#10622 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10627 Reliably display "like" and "share" notifications
  include/enotify.php
  mod/ping.php
  src/Model/Notification.php
Labels: Enhancement

#10628 Set profile fields for system user in Model\User::getOwnerDataById
  src/Model/Profile.php
  src/Model/User.php
  src/Module/HCard.php
  src/Module/Profile/Contacts.php
Labels: Bug

#10630 Unused parts of the old notification system are removed
  include/enotify.php
  src/Model/Item.php
  view/lang/C/messages.po
Labels: Enhancement

#10631 Allow a GuzzleResponse body to be queried more than once
  mod/follow.php
  src/Console/Contact.php
  src/Module/Debug/Probe.php
  src/Network/GuzzleResponse.php
Labels: Bug, Enhancement

#10632 Fix vanished notifications
  mod/ping.php
Labels: Bug

#10633 PSR-7 Part 2: Optimize HTTPRequest
  composer.json
  composer.lock
  src/Core/Search.php
  src/DI.php
  src/Factory/HTTPClientFactory.php
  src/Model/GServer.php
  src/Model/Storage/ExternalResource.php
  src/Module/Magic.php
  src/Module/Proxy.php
  src/Network/HTTPClient.php
  src/Network/HTTPRequest.php
  src/Network/IHTTPClient.php
  src/Network/Probe.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Protocol/Salmon.php
  src/Util/HTTPSignature.php
  src/Worker/PubSubPublish.php
  static/dependencies.config.php
  tests/DiceHttpMockHandlerTrait.php
  tests/datasets/curl/image.content
  tests/src/Core/InstallerTest.php
  tests/src/Core/StorageManagerTest.php
  tests/src/Network/ProbeTest.php
  tests/src/Util/HTTPSignatureTest.php
  tests/src/Util/ImagesTest.php
Labels: Enhancement

#10641 Fix HTTPClient Errors
  src/Network/HTTPClient.php
  src/Network/IHTTPClient.php
  src/Protocol/Feed.php
  tests/src/Network/HTTPClientTest.php
  view/lang/C/messages.po
Labels: Bug

#10643 Avoid notices
  src/Model/Contact.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#10644 Issue 10640: Use consistent settings to enable protocol support
  mod/settings.php
  src/Module/Admin/Site.php
  src/Module/NodeInfo120.php
  src/Module/NodeInfo210.php
  src/Worker/Delivery.php
  src/Worker/Notifier.php
  view/lang/C/messages.po
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
  view/theme/vier/theme.php
Labels: UX, Enhancement

#10645 DE translation updats
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#10646 Fix translations for singular/plural strings
  src/Core/L10n.php
Labels: Bug

#10647 Issue 10640: Some more inversed settings
  src/Module/Admin/Site.php
  view/lang/C/messages.po
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: UX, Enhancement
