Repository friendica/friendica, pull requests merged in 2022-02, with the labels that each got.

#11197 Issue 11156: Display "49+" notifications if there are 50 or more
  mod/ping.php
Labels: UI

#11199 Add rel="tag" to the HTML Purifier allow list in BBCode::convert
  src/Content/Text/HTML.php
Labels: Bug, Federation

#11204 Issue 10966: Ignore "only sharer" setting for forum accounts
  src/Model/Contact.php
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation

#11205 Fix for PR #11204 - Forums are now correctly detected
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation

#11206 regen CREDITS for the 2021.12 release
  CREDITS.txt
Labels: Docs

#11208 More system are added to the federation page
  src/Module/Admin/Federation.php
Labels: Enhancement

#11211 Issue 10914: Display events in the feed in the author's timezone
  src/Protocol/Feed.php
Labels: UX, Enhancement

#11210 Detect pump.io servers
  src/Model/GServer.php
Labels: Federation, Enhancement

#11213 Platforms: only use and show trusted detections
  src/Model/GServer.php
  src/Module/Admin/Federation.php
Labels: Federation, Enhancement

#11214 Follow-up for PR #11213 - Improved server probing
  src/Model/GServer.php
  src/Module/Admin/Federation.php
Labels: Federation, Enhancement

#11041 2022.02 CHANGELOG
  CHANGELOG
Labels: Docs

#11215 Store week, month and halfyear usage / number of posts
  database.sql
  doc/database/db_gserver.md
  src/Model/GServer.php
  src/Module/Admin/Federation.php
  static/dbstructure.config.php
  view/lang/C/messages.po
  view/templates/admin/federation.tpl
Labels: Enhancement

#11221 forgot to update the CHANGELOG file for the 2022.05-dev phase
  CHANGELOG
Labels: Docs

#11225 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11229 DE translation updats
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11227 Display followers for followers of private forums
  src/Module/ActivityPub/Followers.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement

#11233 added two help texts in the admin panel site config
  src/Module/Admin/Site.php
  view/lang/C/messages.po
Labels: Docs

#11237 Contact ex- and import should work with Misskey CSV files as well
  doc/Export-Import-Contacts.md
  doc/de/Export-Import-Contacts.md
Labels: Docs

#11239 Simplify author contact fetching
  mod/display.php
Labels: Bug

#11240 Avoid thread completion on activities
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement

#11241 Workaround for timing problems / Avoid a notice in the scheduled posts
  src/Object/Api/Mastodon/ScheduledStatus.php
  src/Util/HTTPSignature.php
Labels: Federation, Enhancement

#11242 Private forums are now working via AP
  database.sql
  doc/database/db_post-thread-user.md
  mod/item.php
  src/Model/Contact.php
  src/Model/Group.php
  src/Model/Item.php
  src/Model/Post/UserNotification.php
  src/Module/Api/Twitter/Lists/Ownership.php
  src/Module/Diaspora/Receive.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Worker/Delivery.php
  src/Worker/Notifier.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Federation, Enhancement

#11247 Check the existence of the `uid` field before accessing it in Module\Photo
  src/Module/Photo.php
Labels: Bug

#11250 Don't use empty values for redis password and port
  src/Console/Config.php
  src/Core/Cache/Type/RedisCache.php
  tests/src/Console/ConfigConsoleTest.php
Labels: Bug

#11251 Fix for private communities
  src/Model/Item.php
  src/Module/ActivityPub/Objects.php
Labels: Bug

#11252 Note about breaking changes in private forums
  CHANGELOG
Labels: Docs

#11246 Expand system.accept_only_sharer pconfig value to include previous behavior with likes
  mod/settings.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/OStatus.php
  view/lang/C/messages.po
  view/templates/settings/connectors.tpl
  view/theme/frio/templates/settings/connectors.tpl
Labels: UX, Enhancement

#11249 Hash the URL before using it as cache key in Util\Images::getInfoFromURLCached
  src/Util/Images.php
Labels: Bug

#11256 Check for array content before querying keys in Worker\Notifier
  src/Worker/Notifier.php
Labels: Bug

#11258 Show only the user's categories on their profile
  src/Content/Widget.php
  src/Module/Profile/Status.php
Labels: Bug, UX

#11262 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11263 Fix for warnings in smarty templates
  view/templates/search_item.tpl
  view/templates/wall_thread.tpl
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/quattro/templates/search_item.tpl
  view/theme/quattro/templates/wall_item_tag.tpl
  view/theme/quattro/templates/wall_thread.tpl
  view/theme/smoothly/templates/search_item.tpl
  view/theme/smoothly/templates/wall_thread.tpl
  view/theme/vier/templates/search_item.tpl
  view/theme/vier/templates/wall_item_tag.tpl
  view/theme/vier/templates/wall_thread.tpl
Labels: Bug, PHP 8

#11260 API: add list members editing
  src/Model/Group.php
  src/Module/Api/Mastodon/Lists/Accounts.php
Labels: New Feature, API

#11266 Display the post receivers
  src/Database/PostUpdate.php
  src/Module/PermissionTooltip.php
  src/Object/Post.php
  static/settings.config.php
  view/lang/C/messages.po
  view/theme/frio/css/style.css
  view/theme/frio/templates/wall_thread.tpl
Labels: Enhancement, UI

#11268 Display announces identical for starting posts and comments
  src/Content/Conversation.php
Labels: Enhancement, UI

#11269 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11267 Update Mastodon API version string to include Mastodon version compatibility
  src/Module/Api/Mastodon/Instance.php
  src/Object/Api/Mastodon/Instance.php
  src/Object/Api/Mastodon/Stats.php
Labels: Enhancement, API

#11275 Prevent tagsinput select element to be submitted without a value when they are required
  src/Core/ACL.php
  src/Model/Mail.php
  tests/datasets/api.fixture.php
  view/js/friendica-tagsinput/friendica-tagsinput.js
  view/templates/acl/message_recipient.tpl
Labels: Bug, UX, Privacy

#11280 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11265 Enable MySQL unix socket connection
  src/Console/AutomaticInstallation.php
  src/Database/Database.php
  static/defaults.config.php
  static/env.config.php
Labels: Enhancement

#11283 regen CREDITS
  CREDITS.txt
Labels: Docs
