Repository friendica/friendica, pull requests merged in 2022-11, with the labels that each got.

#12088 Also look for Atom feeds when probing link URLs
  src/Network/Probe.php
Labels: Bug, Federation

#12089 (Hopefully) query performance improvements
  src/Model/Contact/Group.php
  src/Model/Contact/Relation.php
  src/Model/Post.php
  src/Module/Api/Mastodon/Timelines/Home.php
  src/Module/Api/Mastodon/Timelines/ListTimeline.php
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
  src/Module/Api/Mastodon/Timelines/Tag.php
  src/Module/Conversation/Community.php
  src/Protocol/Diaspora.php
  src/Worker/RemoveUnusedAvatars.php
  src/Worker/RemoveUnusedContacts.php
  src/Worker/RemoveUnusedTags.php
Labels: Enhancement, Performance

#12092 Replace remaining "follow" route instances to "contact/follow"
  src/Module/Notifications/Introductions.php
  view/templates/widget/follow.tpl
  view/theme/frio/templates/widget/follow.tpl
  view/theme/smoothly/templates/widget/follow.tpl
Labels: Bug, UX

#12091 Fix wrong class name in logs view template
  view/theme/frio/templates/admin/logs/view.tpl
Labels: Bug, UX

#12086 Move event export to src/Module/Events/Export
  mod/cal.php
  src/Model/Event.php
  src/Module/Calendar/Export.php
  src/Module/Calendar/Json.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/event_head.tpl
  view/templates/widget/events.tpl
  view/theme/quattro/templates/events_reminder.tpl
  view/theme/vier/templates/event_head.tpl
Labels: Bug, Enhancement

#12087 Move mod/uimport.php to src/Module
  doc/Move-Account.md
  doc/de/Move-Account.md
  mod/uimport.php
  src/Core/UserImport.php
  src/Module/User/Import.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/uimport.tpl
  view/templates/user/import.tpl
Labels: Enhancement

#12093 Move mod/tagrm.php to src/Module
  mod/photos.php
  mod/tagrm.php
  src/App/Mode.php
  src/Module/Post/Tag/Remove.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/post/tag/remove.tpl
Labels: Bug, Enhancement

#12095 Improved bulk delivery / don't redistribute activities
  src/Core/Worker/Cron.php
  src/Protocol/ActivityPub/Delivery.php
  src/Worker/Notifier.php
  static/defaults.config.php
Labels: Bug, Federation, Enhancement

#12100 Move mod/tagger.php to src/Module
  mod/tagger.php
  src/Module/Post/Tag/Add.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/jot-header.tpl
  view/theme/frio/templates/jot-header.tpl
  view/theme/smoothly/templates/jot-header.tpl
Labels: Enhancement

#12103 Move mod/suggest.php to src/Module
  mod/match.php
  mod/suggest.php
  src/Module/BaseSearch.php
  src/Module/Contact/Suggestions.php
  src/Module/Conversation/Network.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/contact/entry.tpl
  view/templates/contact/list.tpl
  view/theme/frio/templates/contact/entry.tpl
  view/theme/frio/templates/contact/list.tpl
  view/theme/frio/templates/contact_drop_confirm.tpl
  view/theme/frio/templates/contacts-template.tpl
  view/theme/frio/templates/directory_header.tpl
  view/theme/frio/templates/groupeditor.tpl
  view/theme/frio/templates/profile/contacts.tpl
  view/theme/frio/templates/widget/peoplefind.tpl
  view/theme/quattro/templates/contact/entry.tpl
  view/theme/vier/templates/contact/entry.tpl
Labels: Enhancement

#12105 Move mod/share.php to src/Module
  mod/share.php
  src/Module/Post/Share.php
  static/routes.config.php
  view/templates/jot-header.tpl
  view/theme/frio/templates/jot-header.tpl
  view/theme/smoothly/templates/jot-header.tpl
Labels: Enhancement

#12102 [frio] Make the main contact row template link to the contact page
  view/theme/frio/templates/contact/entry.tpl
Labels: UX, Mobile, Enhancement

#12110 Transmit the quoted part in the source
  src/Content/Item.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation, Enhancement

#12115 Issue 12096: Improve account search
  src/Model/Contact.php
  src/Module/Api/Mastodon/Accounts/Search.php
  src/Module/Api/Mastodon/Search.php
Labels: Enhancement, API

#12116 Issue 11846: Fix client behaviour when following hash tags
  src/Content/Text/BBCode.php
  src/Object/Api/Mastodon/Status.php
Labels: Enhancement, API

#12104 Deprecate themes duepuntozero, quattro and smoothly
  doc/Text_comment.md
  doc/Text_editor.md
  doc/de/Text_comment.md
  doc/de/Text_editor.md
  doc/img/darkbubble.png
  doc/img/darkzero.png
  doc/img/dispy.png
  doc/img/editor_darkbubble.png
  doc/img/editor_dpzero.png
  doc/img/editor_zero.png
  doc/themes.md
  static/settings.config.php
  tests/datasets/config/.htconfig.php
  tests/src/Core/Config/Cache/ConfigFileLoaderTest.php
  view/theme/duepuntozero/unsupported
  view/theme/frio/js/jquery.tools.min.js
  view/theme/frio/templates/theme_settings.tpl
  view/theme/quattro/unsupported
  view/theme/smoothly/unsupported
Labels: Theme-specific, Enhancement

#12114 Fix capitalization of unfollow links in Model\Contact
  src/Model/Contact.php
  view/lang/C/messages.po
Labels: Bug, Translation

#12117 Suppress InvalidArgument exceptions handling URLs in Model\Item::containsLink
  src/Model/Item.php
Labels: Bug

#12124 Issue 11832: Avoid error when fetching group members
  src/Module/Api/Mastodon/Lists/Accounts.php
Labels: New Feature, API

#12122 Issue 2657: Mentions will now be recognized by clients
  src/Content/Text/BBCode.php
  src/Module/Api/Mastodon/Accounts/Search.php
  src/Module/Api/Mastodon/Search.php
Labels: Enhancement, API

#12125 Don't show following/followed_by on pending
  src/Object/Api/Mastodon/Relationship.php
Labels: Bug, API

#12126 Support "fedifinder" to import contacts
  src/Module/Settings/Account.php
Labels: Enhancement

#12129 the filebrowser.tpl file was missing an "
  view/templates/filebrowser.tpl
Labels: Bug, Theme-specific, UI

#12128 [vier] Fix contacts display
  view/templates/contacts-template.tpl
Labels: Bug, Theme-specific

#12130 Use different parser modes for Mastodon and Twitter-API
  src/Content/Text/BBCode.php
  src/Content/Text/Plaintext.php
  src/Factory/Api/Twitter/DirectMessage.php
  src/Factory/Api/Twitter/Status.php
  src/Model/Event.php
  src/Module/Api/Friendica/Profile/Show.php
  src/Object/Api/Mastodon/ScheduledStatus.php
  src/Object/Api/Mastodon/Status.php
Labels: Enhancement

#12118 Add follow/unfollow link to the contact actions menu
  src/Module/Contact/Profile.php
  view/lang/C/messages.po
  view/templates/contact_edit.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/vier/templates/contact_edit.tpl
Labels: New Feature

#12109 Verify homepage by checking for a rel-me link back to the user profile
  database.sql
  doc/database/db_profile.md
  src/Module/Settings/Profile/Index.php
  src/Worker/CheckRelMeProfileLink.php
  src/Worker/Cron.php
  static/dbstructure.config.php
  static/dbview.config.php
  view/lang/C/messages.po
  view/templates/profile/vcard.tpl
  view/templates/settings/profile/index.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/quattro/templates/profile/vcard.tpl
  view/theme/vier/templates/profile/vcard.tpl
  view/theme/vier/templates/settings/profile/index.tpl
Labels: New Feature

#12131 Move mod/salmon.php to src/Module
  mod/salmon.php
  src/Module/DFRN/Notify.php
  src/Module/OStatus/Salmon.php
  static/routes.config.php
Labels: Enhancement

#12134 Added type-hints
  src/Content/Text/Plaintext.php
Labels: Enhancement

#12136 Quoted reshares containing quoted reshares should now look fine
  src/Content/Item.php
  src/Model/Item.php
Labels: Bug, Federation

#12138 Move mod/repair_ostatus.php to src/Module
  mod/repair_ostatus.php
  mod/settings.php
  src/Module/OStatus/Repair.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/ostatus/repair.tpl
Labels: Enhancement

#12143 Replace remaining occurrences of admin/users route by moderation/users
  src/Module/Moderation/Users/Create.php
  src/Module/Moderation/Users/Pending.php
  src/Module/Notifications/Ping.php
  src/Module/Register.php
  view/templates/moderation/users/active.tpl
  view/templates/moderation/users/blocked.tpl
  view/templates/moderation/users/index.tpl
  view/templates/moderation/users/pending.tpl
  view/theme/frio/templates/moderation/users/active.tpl
  view/theme/frio/templates/moderation/users/blocked.tpl
  view/theme/frio/templates/moderation/users/index.tpl
  view/theme/frio/templates/moderation/users/pending.tpl
  view/theme/quattro/templates/admin/users/active.tpl
  view/theme/quattro/templates/admin/users/blocked.tpl
  view/theme/quattro/templates/admin/users/index.tpl
  view/theme/quattro/templates/admin/users/pending.tpl
Labels: Bug

#12142 Add title to homepage verified check mark
  src/Core/Cache/Type/MemcachedCache.php
  src/Model/Profile.php
  view/lang/C/messages.po
  view/templates/profile/vcard.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/quattro/templates/profile/vcard.tpl
  view/theme/vier/templates/profile/vcard.tpl
Labels: Enhancement

#12144 Add missing links to moderation section
  view/theme/frio/templates/nav.tpl
  view/theme/vier/templates/nav.tpl
Labels: Bug, UI

#12140 For debug reasons we now can store all incoming sources
  src/Model/Item.php
  src/Module/Moderation/Item/Source.php
  static/defaults.config.php
  view/lang/C/messages.po
  view/templates/moderation/item/source.tpl
Labels: Bug, Enhancement

#12145 Performance improvements in public timeline
  database.sql
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement, Performance

#12141 Move mod/removeme.php to src/Module
  doc/Remove-Account.md
  doc/de/Remove-Account.md
  mod/removeme.php
  src/Model/User.php
  src/Module/BaseSettings.php
  src/Module/Settings/RemoveMe.php
  src/Module/Tos.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/removeme.tpl
  view/templates/settings/removeme.tpl
  view/theme/frio/templates/removeme.tpl
Labels: Enhancement

#12146 Move mod/redir.php to src/Module
  mod/photos.php
  mod/redir.php
  src/Content/Conversation.php
  src/Content/Item.php
  src/Content/Text/BBCode.php
  src/Content/Text/HTML.php
  src/Model/Contact.php
  src/Module/Contact.php
  src/Module/Contact/Hovercard.php
  src/Module/Contact/Profile.php
  src/Module/Contact/Redir.php
  src/Object/Post.php
  static/routes.config.php
  view/lang/C/messages.po
  view/theme/frio/theme.php
Labels: Enhancement

#12147 Fix warning: Undefined array key "public"
  src/Factory/Api/Mastodon/Relationship.php
  src/Worker/CheckRelMeProfileLink.php
Labels: Bug, API

#12150 Replace remaining "admin" instances in moderation templates
  view/templates/moderation/aside.tpl
  view/templates/moderation/blocklist/contact.tpl
  view/templates/moderation/blocklist/server/add.tpl
  view/templates/moderation/blocklist/server/import.tpl
  view/templates/moderation/blocklist/server/index.tpl
  view/templates/moderation/item/delete.tpl
  view/templates/moderation/summary.tpl
  view/theme/frio/templates/moderation/blocklist/contact.tpl
Labels: Bug

#12106 Move mod/settings.php to src/Module
  doc/Connectors.md
  mod/settings.php
  src/Module/BaseSettings.php
  src/Module/Security/OpenID.php
  src/Module/Settings/Addons.php
  src/Module/Settings/Connectors.php
  src/Module/Settings/Features.php
  src/Module/Settings/OAuth.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/settings/addons.tpl
  view/templates/settings/addons/connector.tpl
  view/templates/settings/addons/link.tpl
  view/templates/settings/addons/panel.tpl
  view/templates/settings/connectors.tpl
  view/templates/settings/oauth.tpl
  view/theme/frio/templates/settings/addons.tpl
  view/theme/frio/templates/settings/addons/connector.tpl
  view/theme/frio/templates/settings/addons/link.tpl
  view/theme/frio/templates/settings/addons/panel.tpl
  view/theme/frio/templates/settings/connectors.tpl
  view/theme/frio/templates/settings/oauth.tpl
Labels: Enhancement

#12152 Move mod/mod/msearch & mod/match to src/Module
  mod/match.php
  mod/msearch.php
  src/Module/Contact/MatchInterests.php
  src/Module/Search/Tags.php
  src/Network/HTTPClient/Capability/ICanSendHttpRequests.php
  src/Network/HTTPClient/Client/HttpClient.php
  src/Network/HTTPClient/Client/HttpClientOptions.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/widget/peoplefind.tpl
  view/theme/frio/templates/widget/peoplefind.tpl
Labels: Bug, Enhancement

#12153 Woodpecker: Update PHP version
  .woodpecker/.continuous-deployment.yml
  .woodpecker/.database_checks.yml
  .woodpecker/.phpunit.yml
  .woodpecker/.releaser.yml
  src/App/Page.php
  src/Core/L10n.php
  src/Util/Network.php
  src/Util/ReversedFileReader.php
Labels: Enhancement

#12154 Remove RTL Override character from display names to show in notifications
  src/Module/Notifications/Ping.php
  src/Navigation/Notifications/Factory/FormattedNavNotification.php
  src/Navigation/Notifications/ValueObject/FormattedNavNotification.php
Labels: Bug, UX

#12157 Fix constructor parameters in Module\Settings\RemoveMe
  src/Module/Settings/RemoveMe.php
Labels: Bug

#12162 Avoid link parsing problems in front of "share" elements
  src/Content/Text/BBCode.php
Labels: Bug, UX

#12164 Remove superfluous property declaration in Settings\UserExport
  src/Module/Settings/RemoveMe.php
  src/Module/Settings/UserExport.php
Labels: Bug

#12168 Update message_recipient.tpl
  view/templates/acl/message_recipient.tpl
Labels: Bug, UI

#12173 mail() requires additional headers to be separated by CRLF
  src/Object/Email.php
  src/Util/Emailer.php
Labels: Bug

#12174 Avoid duplicate media elements
  src/Model/Item.php
  src/Model/Post/Media.php
Labels: Bug

#12156 Move remainder of OStatus stack to src/Module
  mod/ostatus_subscribe.php
  mod/poco.php
  mod/pubsub.php
  mod/pubsubhubbub.php
  src/Model/Contact.php
  src/Module/OStatus/PubSub.php
  src/Module/OStatus/PubSubHubBub.php
  src/Module/OStatus/Subscribe.php
  src/Module/Profile/Profile.php
  src/Module/Settings/Connectors.php
  src/Module/User/PortableContacts.php
  src/Module/Xrd.php
  static/routes.config.php
  view/lang/C/messages.po
Labels: Enhancement

#12177 Ensure Post::toArray returns an array
  src/Model/Post.php
Labels: Bug

#12169 Centralize config.admin_email management in Model\User
  database.sql
  doc/database/db_user.md
  mod/lostpass.php
  src/App.php
  src/Core/Update.php
  src/Model/Nodeinfo.php
  src/Model/Post/UserNotification.php
  src/Model/User.php
  src/Module/Api/GNUSocial/GNUSocial/Config.php
  src/Module/Moderation/BaseUsers.php
  src/Module/Register.php
  src/Module/Settings/Account.php
  src/Module/Settings/RemoveMe.php
  src/Navigation/Notifications/Repository/Notify.php
  src/Object/Api/Mastodon/Instance.php
  src/Protocol/ActivityPub/Transmitter.php
  static/dbstructure.config.php
  view/lang/C/messages.po
Labels: Bug, Enhancement

#12178 Allow anonymous reports
  database.sql
  doc/database/db_report.md
  static/dbstructure.config.php
Labels: Enhancement

#12181 Address a couple of warnings
  mod/photos.php
  src/Navigation/Notifications/Repository/Notify.php
Labels: Bug

#12179 Move mod/(update_)display.php to src\Module
  mod/display.php
  mod/update_display.php
  src/Content/Conversation.php
  src/Model/Contact.php
  src/Module/Item/Display.php
  src/Module/Item/Feed.php
  src/Module/Update/Display.php
  static/routes.config.php
  view/js/main.js
  view/lang/C/messages.po
Labels: Enhancement

#12184 This fixes duplicated media in quoted posts
  src/Model/Item.php
Labels: Bug

#12190 Fix memory issue on displaying conversations
  src/Content/Conversation.php
  src/Module/Admin/Summary.php
Labels: Bug, UI

#12186 Move mod/editpost.php to src\Module\Post\Edit
  doc/Addons.md
  doc/de/Addons.md
  mod/editpost.php
  src/Module/Post/Edit.php
  src/Object/Post.php
  static/routes.config.php
  view/lang/C/messages.po
  view/theme/smoothly/templates/jot.tpl
Labels: Enhancement

#12194 Replace remaining references to contact_template.tpl by contact/entry.tpl
  view/templates/contact_drop_confirm.tpl
  view/templates/directory_header.tpl
  view/templates/nogroup-template.tpl
  view/templates/profile/contacts.tpl
  view/theme/frio/theme.php
Labels: Bug, Theme-specific

#12196 Add global styles for .icon
  view/global.css
Labels: Bug, UI

#12198 Update README.md
  README.md
Labels: Docs, Enhancement

#12200 "View" activities are now ignored
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  static/defaults.config.php
Labels: Federation, Enhancement, Performance

#12202 Add meta tag to attachment to show images in mastodon app.
  .ddev/config.yaml
  src/Object/Api/Mastodon/Attachment.php
  view/js/main.js
Labels: Enhancement, API

#12211 Fix route for user import.
  view/templates/register.tpl
  view/theme/frio/templates/register.tpl
Labels: Bug, UI

#12207 Ensure register records aren't created with uid = 0
  src/Model/Register.php
  src/Module/Register.php
  view/lang/C/messages.po
Labels: Bug, UX

#12213 Fix that users property should be an object instead of array.
  src/Model/Nodeinfo.php
Labels: Bug, API

#12214 Prevent division by zero in Mastodon Attachment.
  src/Object/Api/Mastodon/Attachment.php
Labels: Bug, API

#12216 Fix constructor compatibility with BaseSettings parent class
  src/Module/Settings/TwoFactor/AppSpecific.php
  src/Module/Settings/TwoFactor/Recovery.php
  src/Module/Settings/TwoFactor/Trusted.php
  src/Module/Settings/TwoFactor/Verify.php
Labels: Bug

#12215 Fix support for `/contact/redir` URLs in Module\Contact\Hovercard
  src/Module/Contact/Hovercard.php
Labels: Bug, Theme-specific

#12208 Improve error message when conversation isn't available in Module\Item\Display
  src/Module/Item/Display.php
  view/lang/C/messages.po
  view/templates/exception.tpl
Labels: UX, Enhancement

#12223 Add support for Mastodon /authorize_interaction route
  src/Module/Contact/Follow.php
  static/routes.config.php
Labels: New Feature, Federation

#12222 Fix support for `/contact/123456/conversations` URLs in Module\Contact\Hovercard
  src/Module/Contact/Hovercard.php
Labels: Bug

#12218 [frio] Improve search list display for web and mobile
  src/Content/Conversation.php
  view/theme/frio/templates/conversation.tpl
  view/theme/frio/templates/search_item.tpl
Labels: Theme-specific, UX, Enhancement, UI

#12221 Fix various PHP 8 deprecations
  src/App/Page.php
  src/Content/Nav.php
  src/Database/Database.php
  src/Model/APContact.php
  src/Model/Item.php
  src/Model/Log/ParsedLogIterator.php
  src/Model/Post/Media.php
  src/Module/Home.php
  src/Network/HTTPClient/Client/HttpClient.php
  src/Object/EMail/IEmail.php
  src/Object/Email.php
  src/Protocol/Diaspora.php
  src/Render/FriendicaSmartyEngine.php
  src/Worker/Notifier.php
  static/defaults.config.php
  view/theme/frio/php/PHPColors/Color.php
Labels: Enhancement, PHP 8.1

#12226 Use guid from shared post in Protocol\Diaspora::getReshareDetails
  src/Protocol/Diaspora.php
Labels: Bug

#12225 Remove config/addon-sample.config.php file in favor of per-addon configuration files
  .gitignore
  config/addon-sample.config.php
  doc/Config.md
Labels: Bug

#12228 Create /profile/{nickname}/photos route
  doc/FAQ.md
  doc/de/FAQ.md
  mod/photos.php
  src/Content/Item.php
  src/Content/Nav.php
  src/Model/Contact.php
  src/Model/Photo.php
  src/Module/BaseProfile.php
  src/Module/Profile/Photos/Index.php
  src/Module/Settings/Profile/Index.php
  src/Module/Settings/Profile/Photo/Index.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/photo_albums.tpl
  view/templates/photos_upload.tpl
  view/theme/frio/templates/photo_albums.tpl
  view/theme/frio/templates/photos_upload.tpl
  view/theme/frio/theme.php
Labels: Enhancement

#12231 Fix unfavourite (and related) endpoints
  src/Model/Item.php
Labels: Bug, Federation

#12234 Update Notify->iid to itemId for notification endpoint
  src/Module/Api/Friendica/Notification/Seen.php
Labels: Bug, API

#12240 Update sample-nginx.config
  mods/sample-nginx.config
Labels: Installation, Enhancement

#12243 No more automated posts via mod/item.php
  mod/item.php
  mod/oexchange.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Post/Delayed.php
  src/Module/Contact/Profile.php
  view/lang/C/messages.po
Labels: Enhancement

#12244 Address various Warning messages
  src/Factory/Api/Mastodon/Attachment.php
  src/Factory/Api/Mastodon/Notification.php
  src/Object/Api/Mastodon/Attachment.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#12248 Added information that max image upload size on admin page does not a…
  src/Module/Admin/Site.php
  view/lang/C/messages.po
Labels: Docs, Enhancement

#12251 "MIRROR_FORWARDED" is no more
  database.sql
  src/Model/Item.php
  static/dbstructure.config.php
  update.php
Labels: Bug, Federation

#12255 Silently quit on unfollow of invalid contacts
  src/Core/Protocol.php
Labels: Bug, Federation

#12254 Reorder search to try redirecting to post first
  src/Module/Search/Index.php
Labels: Bug, UX

#12264 Fix "Argument #1 ($parts) must be of type array, bool given"
  src/Model/GServer.php
Labels: Bug

#12246 Ensure the existence of various keys in decoded data in Diaspora::decodeRaw
  src/Protocol/Diaspora.php
Labels: Bug

#12249 Address several PHP 8.1 deprecation notices
  composer.json
  composer.lock
  src/BaseCollection.php
  src/Content/Conversation.php
  src/Core/Session/Handler/Database.php
  src/Database/Database.php
  src/Model/Post/Media.php
  src/Module/Admin/Site.php
  src/Module/Contact/Profile.php
  src/Module/OStatus/Salmon.php
  src/Module/PublicRSAKey.php
  src/Module/User/PortableContacts.php
  src/Network/Probe.php
  src/Object/Email.php
  src/Protocol/Salmon.php
  src/Protocol/Salmon/Format/Magic.php
  src/Util/Crypto.php
  src/Util/Proxy.php
  src/Util/Strings.php
  tests/datasets/crypto/rsa/salmon-public-magic
  tests/datasets/crypto/rsa/salmon-public-pem
  tests/src/Protocol/SalmonTest.php
  tests/src/Util/CryptoTest.php
Labels: Bug, PHP 8.1

#12270 Remove addon-sample.config.php from build pipeline
  mods/release-list-include.txt
Labels: Bug

#12271 Issue 12266: APISuggestions should now work
  src/Module/Api/Mastodon/Suggestions.php
Labels: Enhancement, API

#12272 Issue 12133: Account data can now be updated via API
  doc/API-Mastodon.md
  src/Module/Api/Mastodon/Accounts/UpdateCredentials.php
Labels: API

#12278 Address a couple of warnings
  src/Model/GServer.php
  src/Model/Post/Delayed.php
Labels: Bug

#12276 Address a couple of fatal errors
  src/Core/Worker.php
  view/theme/frio/templates/contact/entry.tpl
Labels: Bug

#12280 Remove related notifications when marking an item for deletion
  src/Model/Item.php
  src/Navigation/Notifications/Repository/Notification.php
  src/Navigation/Notifications/Repository/Notify.php
Labels: Bug, UX

#12277 Move mod/fbrowser to src\Modules\Attachment|Photos\Browser
  mod/fbrowser.php
  src/App/Arguments.php
  src/App/Router.php
  src/Model/Photo.php
  src/Module/Attach.php
  src/Module/Media/Attachment/Browser.php
  src/Module/Media/Attachment/Upload.php
  src/Module/Media/Photo/Browser.php
  src/Module/Media/Photo/Upload.php
  src/Module/Profile/Photos.php
  static/routes.config.php
  view/global.css
  view/js/filebrowser.js
  view/js/main.js
  view/js/module/media/browser.js
  view/lang/C/messages.po
  view/templates/jot-header.tpl
  view/templates/media/browser.tpl
  view/theme/frio/css/style.css
  view/theme/frio/js/filebrowser.js
  view/theme/frio/js/modal.js
  view/theme/frio/js/module/media/browser.js
  view/theme/frio/templates/jot-header.tpl
  view/theme/frio/templates/media/browser.tpl
  view/theme/quattro/dark/style.css
  view/theme/quattro/green/style.css
  view/theme/quattro/lilac/style.css
  view/theme/quattro/quattro.less
  view/theme/vier/style.css
Labels: Bug, Enhancement

#12279 Return only one result in case of exact match in Api\Mastodon\Search
  src/Model/Contact.php
  src/Module/Api/Mastodon/Search.php
Labels: Bug, API

#12281 Issue 12149: Show that a post was reshared
  src/Factory/Api/Mastodon/Status.php
Labels: Bug, API

#12284 DE translation update THX MarekBenjamin
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#12287 Fix Legacy Router class routing
  src/App/Router.php
Labels: Bug

#12283 Issue 12191: API tag handling
  .htaccess-dist
  CHANGELOG
  database.sql
  doc/API-Mastodon.md
  src/Content/Widget/SavedSearches.php
  src/Model/Post.php
  src/Module/Api/Mastodon/FollowedTags.php
  src/Module/Api/Mastodon/Tags.php
  src/Module/Api/Mastodon/Tags/Follow.php
  src/Module/Api/Mastodon/Tags/Unfollow.php
  src/Module/Api/Mastodon/Trends/Statuses.php
  src/Module/Api/Mastodon/Trends/Tags.php
  src/Object/Api/Mastodon/Tag.php
  static/dbstructure.config.php
  static/dbview.config.php
  static/routes.config.php
Labels: New Feature, API

#12289 Fix fatal errors because of unknown function/variable names
  src/Object/Post.php
Labels: Bug

#12292 API: Speed improvements
  database.sql
  src/Model/GServer.php
  src/Module/Api/Mastodon/Accounts/Statuses.php
  static/dbstructure.config.php
  static/dbview.config.php
  static/routes.config.php
Labels: Enhancement, API, Performance

#12290 [frio] Add page wrapper to contact follow page
  view/theme/frio/css/style.css
  view/theme/frio/templates/auto_request.tpl
Labels: Bug, Theme-specific, UI

#12293 Added status to the report
  database.sql
  doc/database/db_report-post.md
  doc/database/db_report.md
  static/dbstructure.config.php
Labels: Enhancement

#12294 Fix warning 'Undefined array key "name"'
  src/Module/Api/Mastodon/FollowedTags.php
  src/Module/Api/Mastodon/Tags.php
  src/Module/Api/Mastodon/Tags/Follow.php
  src/Module/Api/Mastodon/Tags/Unfollow.php
Labels: Bug, API

#12296 Address some PHP 8.1 deprecation notices
  src/Model/APContact.php
  src/Navigation/Notifications/ValueObject/Introduction.php
  src/Protocol/DFRN.php
Labels: Bug

#12299 Check that an auto reshare is only done on the expected contact
  src/Model/Item.php
Labels: Bug, UX

#12267 Show image size limit in Frio as "usagemessage" for photo_upload
  mod/photos.php
  src/Model/Photo.php
  src/Module/Admin/Site.php
  src/Module/Media/Photo/Upload.php
  src/Module/Settings/Profile/Photo/Index.php
  src/Util/Strings.php
  view/lang/C/messages.po
  view/theme/frio/css/mod_admin.css
Labels: Enhancement

#12303 Fix broken dismiss endpoint on Mastodon notifications API
  src/Module/Api/Mastodon/Notifications/Dismiss.php
Labels: Bug, API

#12304 Add dismissed field to mastodon notifications
  src/Factory/Api/Mastodon/Notification.php
  src/Module/Api/Mastodon/Notifications.php
  src/Object/Api/Mastodon/Notification.php
Labels: Enhancement, API
