Repository friendica/friendica, pull requests merged in 2022-08, with the labels that each got.

#11806 The post-reason / protocol is now filled in most cases
  database.sql
  src/Model/Conversation.php
  src/Model/Item.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Worker/OnePoll.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: UX, Enhancement

#11810 Add password length limit if using the Blowfish hashing algorithm
  src/Core/Session.php
  src/Core/Session/Capability/IHandleSessions.php
  src/Core/Session/Type/AbstractSession.php
  src/Model/User.php
  src/Module/Security/Login.php
  src/Module/Security/OpenID.php
  src/Module/Security/PasswordTooLong.php
  src/Module/Security/TwoFactor/Recovery.php
  src/Module/Security/TwoFactor/Trust.php
  src/Module/Settings/Account.php
  src/Security/Authentication.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/field_password.tpl
  view/templates/security/password_too_long.tpl
  view/theme/frio/templates/field_password.tpl
Labels: UX, Enhancement

#11812 Hopefully fixes loops during message processing
  src/Model/Contact.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Queue.php
  src/Protocol/ActivityPub/Receiver.php
  src/Worker/Cron.php
  static/defaults.config.php
Labels: Enhancement

#11815 Missing 'private' array key
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#11819 Fix WSOD when Renderer throws exception
  src/Module/Special/HTTPException.php
Labels: Enhancement

#11827 Improvements for message processing
  database.sql
  doc/database.md
  doc/database/db_arrived-activity.md
  doc/database/db_processed-activity.md
  src/Model/Item.php
  src/Model/ItemURI.php
  src/Module/Debug/ActivityPubConversion.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Queue.php
  src/Protocol/ActivityPub/Receiver.php
  src/Util/ParseUrl.php
  static/dbstructure.config.php
Labels: Federation, Enhancement, Performance

#11833 added Gàidhlig language translation
  src/Core/L10n.php
  view/lang/gd/messages.po
  view/lang/gd/strings.php
Labels: Translation

#11830 Use L10n->tt instead of t() for plural strings
  src/Core/L10n.php
  src/Model/Item.php
  src/Module/Admin/Federation.php
  src/Module/BaseApi.php
  view/lang/C/messages.po
Labels: Bug, Translation

#11820 Add smarty3 dirs config
  src/Render/FriendicaSmarty.php
  src/Render/FriendicaSmartyEngine.php
  static/defaults.config.php
  view/lang/C/messages.po
Labels: Enhancement

#11835 Improve SQL-Queries / fixed "fetch_parents" setting
  src/Protocol/ActivityPub/Processor.php
  src/Worker/RemoveUnusedAvatars.php
  src/Worker/RemoveUnusedContacts.php
  src/Worker/UpdateContacts.php
Labels: Bug, Enhancement

#11836 DE, ZH CN translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/zh-cn/messages.po
  view/lang/zh-cn/strings.php
Labels: Translation

#11838 Conversation entries will now be stored asynchronous if possible
  database.sql
  doc/database.md
  doc/database/db_fetched-activity.md
  doc/database/db_processed-activity.md
  src/Content/Conversation.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  static/dbstructure.config.php
Labels: Federation, Enhancement, Performance

#11840 Reformatting and using [] instead of discouraged array()
  src/Console/Extract.php
  src/Content/Widget.php
  src/Network/Probe.php
Labels: Enhancement

#11837 Remove poke feature
  doc/API-Entities.md
  doc/Addons.md
  doc/de/Addons.md
  src/Content/Item.php
  src/Core/L10n.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Notification/Type.php
  src/Module/Contact/Poke.php
  src/Module/Settings/Account.php
  src/Navigation/Notifications/Repository/Notify.php
  src/Protocol/Activity.php
  src/Protocol/ActivityPub/Delivery.php
  src/Protocol/DFRN.php
  src/Worker/Delivery.php
  src/Worker/Notifier.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/contact/poke.tpl
  view/templates/hovercard.tpl
  view/templates/settings/account.tpl
  view/theme/frio/js/theme.js
  view/theme/frio/php/frio_boot.php
  view/theme/frio/templates/contact_template.tpl
  view/theme/frio/templates/poke_content.tpl
  view/theme/frio/templates/settings/account.tpl
  view/theme/frio/theme.php
  view/theme/smoothly/style.css
Labels: Enhancement

#11842 Improved performance when updating contacts
  database.sql
  doc/database/db_contact.md
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Post.php
  src/Worker/UpdateContacts.php
  static/dbstructure.config.php
  update.php
Labels: Enhancement, Performance

#11844 Fixed "get() on NULL", PHP is case-sensitive here
  src/Console/MoveToAvatarCache.php
  src/Module/Xrd.php
  src/Render/FriendicaSmartyEngine.php
Labels: Bug

#11845 Several performance improvements
  database.sql
  doc/database/db_contact.md
  doc/database/db_notification.md
  doc/database/db_post-collection.md
  doc/database/db_post-user.md
  src/Content/Pager.php
  src/Model/APContact.php
  src/Model/FContact.php
  src/Model/Item.php
  src/Model/Post.php
  src/Model/Post/Collection.php
  src/Module/Api/Mastodon/Statuses/Pin.php
  src/Module/Item/Pin.php
  src/Module/Update/Profile.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
  static/dbstructure.config.php
  static/dbview.config.php
  update.php
Labels: Enhancement, Performance

#11847 Improved checks in "storeForUserByUriId" to reduce recursion depth
  src/Model/Item.php
  src/Model/Tag.php
  src/Protocol/Diaspora.php
Labels: Enhancement, Performance

#11849 Improved contact-id detection
  src/Model/Contact.php
  src/Model/Item.php
Labels: Bug

#11852 Fixes/double quotes single
  src/Module/Api/ApiResponse.php
  src/Module/Blocklist/Domain/Download.php
  src/Util/Mimetype.php
  src/Util/Network.php
  src/Util/ParseUrl.php
  src/Util/PidFile.php
  src/Util/Profiler.php
  src/Util/Proxy.php
  src/Util/Strings.php
  src/Util/Temporal.php
Labels: Enhancement

#11854 Ensure Util\Profiler->rendertime is bool
  src/Util/Profiler.php
Labels: Bug

#11860 FR translation update
  view/lang/fr/messages.po
  view/lang/fr/strings.php
Labels: Translation

#11863 Avoid some database errors
  src/Model/Post/Media.php
  src/Navigation/Notifications/Repository/Notification.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug

#11869 Issue 11853/11867: Fix reshare of public posts
  src/Contact/Avatar.php
  src/Database/Database.php
  src/Model/FContact.php
  src/Model/Item.php
  src/Module/Item/Activity.php
  src/Protocol/ActivityPub/Processor.php
  src/Util/ParseUrl.php
Labels: Bug, Federation

#11871 Issue 11870: Weeks can now start at every day
  src/Module/Settings/Display.php
Labels: UX, Enhancement

#11872 Some more warnings and errors are fixed
  src/Model/GServer.php
  src/Model/Item.php
  src/Network/HTTPClient/Client/HttpClient.php
  src/Util/ParseUrl.php
Labels: Bug

#11877 Loglevels are adjusted
  mod/display.php
  mod/item.php
  mod/photos.php
  mod/settings.php
  mod/tagger.php
  src/Contact/Avatar.php
  src/Content/PageInfo.php
  src/Content/Text/BBCode.php
  src/Core/Addon.php
  src/Core/System.php
  src/Core/Worker.php
  src/Core/Worker/Cron.php
  src/Model/Contact.php
  src/Model/Contact/Relation.php
  src/Model/Item.php
  src/Model/Mail.php
  src/Model/Photo.php
  src/Model/Post.php
  src/Model/Tag.php
  src/Module/BaseApi.php
  src/Module/DFRN/Notify.php
  src/Module/OAuth/Revoke.php
  src/Module/OAuth/Token.php
  src/Module/Photo.php
  src/Module/Proxy.php
  src/Protocol/ActivityPub/Delivery.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Email.php
  src/Protocol/OStatus.php
  src/Security/OAuth.php
  src/Util/DateTimeFormat.php
  src/Util/ParseUrl.php
  src/Util/XML.php
  src/Worker/Delivery.php
  src/Worker/OnePoll.php
  src/Worker/RemoveUnusedAvatars.php
  src/Worker/RemoveUnusedContacts.php
  src/Worker/SpoolPost.php
  view/theme/vier/style.php
Labels: Enhancement
