Repository friendica/friendica, pull requests merged in 2022-04, with the labels that each got.

#11387 PL translation update THX strebski
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#11385 Added handling of some previously unhandled activities
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Federation, Enhancement

#11392 Store all known incoming actitivies
  database.sql
  doc/database/db_apcontact.md
  src/Model/APContact.php
  src/Protocol/Activity.php
  src/Protocol/ActivityNamespace.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  static/dbstructure.config.php
Labels: Federation, Enhancement

#11394 Added processing of incoming block notices
  database.sql
  doc/database/db_user-contact.md
  src/Model/Contact/User.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  static/dbstructure.config.php
Labels: Federation, Enhancement

#11396 Issue 11393: Fix failing preview
  src/Model/Item.php
Labels: Bug

#11397 doc/themes.md,FAQ-admin: point to live friendica-themes.com mirror
  doc/FAQ-admin.md
  doc/themes.md
Labels: Docs

#11398 PL translation update THX strebski
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#11400 Display featured posts for contacts
  database.sql
  doc/database/db_post-thread-user.md
  src/Content/Conversation.php
  src/Factory/Api/Mastodon/Status.php
  src/Model/Contact.php
  src/Model/Post.php
  src/Model/Post/Collection.php
  src/Model/Post/ThreadUser.php
  src/Module/Api/Mastodon/Accounts/Statuses.php
  src/Module/Api/Mastodon/Statuses/Pin.php
  src/Module/Api/Mastodon/Statuses/Unpin.php
  src/Module/Item/Pin.php
  src/Module/Profile/Status.php
  src/Object/Post.php
  src/Protocol/ActivityPub/Processor.php
  src/Worker/ExpirePosts.php
  static/dbstructure.config.php
  static/dbview.config.php
  update.php
  view/lang/C/messages.po
  view/templates/search_item.tpl
  view/theme/frio/templates/search_item.tpl
  view/theme/vier/templates/search_item.tpl
Labels: Federation, Enhancement

#11389 Introduce explicit HttpClient "Accept" parameter
  mod/ostatus_subscribe.php
  mod/redir.php
  src/Content/OEmbed.php
  src/Content/Text/BBCode.php
  src/Core/Search.php
  src/Core/Storage/Type/ExternalResource.php
  src/Model/APContact.php
  src/Model/GServer.php
  src/Model/Photo.php
  src/Model/Post/Link.php
  src/Model/Post/Media.php
  src/Model/Profile.php
  src/Model/User.php
  src/Module/Admin/Summary.php
  src/Module/Debug/Feed.php
  src/Module/Magic.php
  src/Module/Photo.php
  src/Module/Proxy.php
  src/Network/HTTPClient/Capability/ICanSendHttpRequests.php
  src/Network/HTTPClient/Client/HttpClient.php
  src/Network/HTTPClient/Client/HttpClientAccept.php
  src/Network/Probe.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Protocol/Salmon.php
  src/Security/ExAuth.php
  src/Util/HTTPSignature.php
  src/Util/Images.php
  src/Util/ParseUrl.php
  src/Worker/CheckVersion.php
  src/Worker/Directory.php
  src/Worker/NodeInfo.php
  src/Worker/OnePoll.php
  src/Worker/PullDirectory.php
  src/Worker/SearchDirectory.php
  src/Worker/UpdateServerDirectory.php
  src/Worker/UpdateServerPeers.php
Labels: Enhancement

#11408 Fix several notices
  src/Model/GServer.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/Diaspora.php
Labels: Bug

#11409 Avoid wrong server type detection / Owncast added
  src/Model/GServer.php
  src/Module/Admin/Federation.php
Labels: Enhancement

#11411 Experimental feature to enter a custom creation date
  mod/item.php
  src/Content/Conversation.php
  src/Model/Item.php
  src/Module/Item/Compose.php
  src/Protocol/ActivityPub/Transmitter.php
  static/defaults.config.php
  view/lang/C/messages.po
  view/templates/item/compose.tpl
  view/templates/jot.tpl
  view/theme/frio/templates/jot.tpl
  view/theme/quattro/templates/jot.tpl
  view/theme/smoothly/templates/jot.tpl
Labels: New Feature

#11413 Preparation for storing incoming polls
  src/Protocol/ActivityPub/Receiver.php
Labels: New Feature, Federation

#11418 Update FAQ.md
  doc/FAQ.md
Labels: Docs, Enhancement

#11420 Add informational Codecov status checks
  .codecov.yml
Labels: Enhancement

#11421 Update FAQ: Remove Roma iOS and Husky Android, both EOL
  doc/FAQ.md
Labels: Docs, Enhancement

#11423 Renamed "share" with "share via"
  src/Object/Post.php
  view/lang/C/messages.po
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: Enhancement, UI

#11424 We can now store incoming questions
  database.sql
  doc/database.md
  doc/database/db_post-question-option.md
  doc/database/db_post-question.md
  src/Model/Post/Question.php
  src/Model/Post/QuestionOption.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: New Feature, Federation

#11426 Avoid warning " Undefined variable $browsershare"
  src/Object/Post.php
Labels: Bug

#11428 Issue 11425: Additional sorting by creation date
  doc/Accesskeys.md
  src/Content/Conversation.php
  src/Module/Conversation/Network.php
  src/Module/Update/Network.php
  view/lang/C/messages.po
Labels: New Feature, UX

#11429 Issue 11427: id values of OrderedCollections have to contain the page number
  src/Module/ActivityPub/Featured.php
  src/Module/ActivityPub/Followers.php
  src/Module/ActivityPub/Following.php
  src/Module/ActivityPub/Outbox.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, Federation

#11430 Order starred posts and posts with mention by the last comment date
  src/Module/Conversation/Network.php
Labels: UX, Enhancement

#11433 API: New Mastodon endpoints added
  doc/API-Mastodon.md
  src/Module/Api/Mastodon/Statuses.php
  static/routes.config.php
Labels: Enhancement, API

#11435 API: We can now display polls
  doc/API-Mastodon.md
  src/DI.php
  src/Factory/Api/Mastodon/Poll.php
  src/Factory/Api/Mastodon/Status.php
  src/Model/Post/Question.php
  src/Model/Post/QuestionOption.php
  src/Module/Api/Mastodon/Polls.php
  src/Object/Api/Mastodon/Poll.php
  src/Object/Api/Mastodon/Status.php
  static/routes.config.php
Labels: New Feature, API

#11436 Store the tag type for the post targets
  database.sql
  doc/database/db_tag.md
  src/Model/Tag.php
  src/Module/PermissionTooltip.php
  src/Protocol/ActivityPub/Processor.php
  static/dbstructure.config.php
  static/dbview.config.php
  view/lang/C/messages.po
Labels: Federation, Enhancement

#11439 Removed unused tag entries
  src/Model/Tag.php
  src/Worker/Cron.php
  src/Worker/RemoveUnusedTags.php
Labels: Enhancement, Performance

#11438 Enclose account settings panels in separate forms
  CHANGELOG
  doc/Addons.md
  doc/de/Addons.md
  mod/settings.php
  src/Module/Settings/Account.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/settings/account.tpl
  view/templates/settings/nick_set.tpl
  view/theme/frio/templates/settings/account.tpl
Labels: Bug, UX

#11443 We now store uncommon endpoints
  database.sql
  doc/database.md
  doc/database/db_endpoint.md
  src/Model/APContact.php
  src/Model/APContact/Endpoint.php
  src/Util/JsonLD.php
  static/dbstructure.config.php
Labels: Federation, Enhancement

#11446 Use central function to fetch the global directory
  src/Content/Widget.php
  src/Core/Search.php
  src/Model/Contact.php
  src/Model/User.php
  src/Module/Api/Friendica/Profile/Show.php
  src/Module/Api/Mastodon/Accounts/Search.php
  src/Module/Api/Mastodon/Search.php
  src/Module/BaseSearch.php
  src/Module/Directory.php
  src/Module/Invite.php
  src/Module/Settings/Account.php
  src/Worker/Directory.php
  src/Worker/PullDirectory.php
Labels: Enhancement

#11447 Fix: Show reshared posts on the contact page
  src/Model/Contact.php
Labels: Bug

#11448 Some small API documentation rearrangements
  doc/API-Mastodon.md
Labels: Docs

#11452 Update app manifest icons
  images/friendica-maskable-192.png
  images/friendica-maskable-512.png
  images/friendica-maskable.svg
  src/Module/Manifest.php
Labels: Mobile, Enhancement

#11455 Update contact when the avatar hadn't been found
  src/Module/Contact/Profile.php
  src/Module/Photo.php
  src/Util/ParseUrl.php
Labels: Enhancement
