Repository friendica/friendica, pull requests merged in 2022-06, with the labels that each got.

#11586 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11590 FR, RU translation updates
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#11596 Fix: Like/Dislike/Reshare actions should now be visible
  mod/display.php
  src/Content/Conversation.php
Labels: Bug, UX

#11599 Fix avatar for messages and feeds
  mod/message.php
  src/Content/Widget/VCard.php
Labels: Bug

#11600 Don't make photo item visible
  mod/photos.php
Labels: Bug

#11601 Issue 11594: Ensure to create notifications in the user language
  mod/removeme.php
  src/Navigation/Notifications/Factory/Notification.php
Labels: Bug

#11588 New command to merge duplicated contacts
  src/Console/DatabaseStructure.php
  src/Console/MergeContacts.php
  src/Core/Console.php
  src/Database/DBA.php
  src/Database/Database.php
  view/lang/C/messages.po
Labels: Bug

#11603 DE, HU translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
Labels: Translation

#11606 Issue 11566: More detailled notification configuration
  database.sql
  doc/database/db_post-user-notification.md
  src/Model/Post/UserNotification.php
  src/Module/Settings/Account.php
  src/Navigation/Notifications/Factory/Notification.php
  src/Navigation/Notifications/Repository/Notify.php
  static/dbstructure.config.php
  view/lang/C/messages.po
  view/templates/settings/account.tpl
  view/theme/frio/templates/settings/account.tpl
Labels: UX, Enhancement

#11608 Use the user id instead of "local_user()"
  src/Navigation/Notifications/Repository/Notify.php
Labels: Enhancement

#11610 Issue 11602: Fix error during contact merhe
  src/Console/MergeContacts.php
  view/lang/C/messages.po
Labels: Bug

#11611 Hopefully make threads writable
  src/Content/Conversation.php
Labels: Bug, UX

#11612 Rearrange the notification settings
  src/Module/Settings/Account.php
  src/Navigation/Notifications/Repository/Notification.php
  src/Navigation/Notifications/Repository/Notify.php
  view/lang/C/messages.po
  view/templates/settings/account.tpl
  view/theme/frio/templates/settings/account.tpl
Labels: UX, Enhancement

#11615 API: Support for markers added
  database.sql
  doc/API-Mastodon.md
  doc/database.md
  doc/database/db_application-marker.md
  src/Module/Api/Mastodon/Markers.php
  static/dbstructure.config.php
  static/routes.config.php
Labels: New Feature, API

#11616 DE, FR, HU, RU translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#11618 Fix forced updates on the display page
  mod/display.php
  static/routes.config.php
Labels: Bug, UX

#11619 Fix: respected the account type on the community page update
  src/Content/Conversation.php
Labels: Bug, UX

#11620 DR, RU translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#11621 Avoid notice when a contact couldn't be fetched
  src/Content/Item.php
Labels: Bug

#11622 Switched maximum database update with currently worked on to "current/max
  src/Module/Friendica.php
Labels: Bug, UX

#11626 API: Speed improvements when fetching posts
  database.sql
  src/App.php
  src/App/Page.php
  src/Core/System.php
  src/Factory/Api/Mastodon/Account.php
  src/Factory/Api/Mastodon/Status.php
  src/Object/Api/Mastodon/Account.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement, API

#11627 API: Improve the performance for fetching pinned posts
  src/Module/Api/Mastodon/Accounts/Statuses.php
Labels: Enhancement, Performance

#11628 API: Use the type field in the query for pinned posts
  src/Module/Api/Mastodon/Accounts/Statuses.php
Labels: Enhancement

#11629 Issue 11625: Don't parse the title through Markdown
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#11532 CHANGELOG for the 2022.06 release
  CHANGELOG
Labels: Docs

#11641 AR, FR and HU translation updates
  view/lang/ar/messages.po
  view/lang/ar/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
Labels: Translation

#11642 Some more default avatars
  images/default/corgidon.png
  images/default/gotosocial.svg
  images/default/hometown.png
  images/default/koyuspace.png
  images/default/plume.png
  src/Model/Contact.php
Labels: Enhancement

#11643 You can now store the avatar in a separate folder and host
  src/Contact/Avatar.php
  static/defaults.config.php
Labels: Enhancement

#11645 Fixed possible "Trying to access array offset on value of type bool" E_NOTICE
  src/Database/PostUpdate.php
Labels: Bug

#11647 Followup PR for bad #11624 PR
  src/Content/Text/HTML.php
  src/Model/APContact.php
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#11652 Misspelled braces causing "undefined index 'causer-id'" message
  src/Content/Conversation.php
Labels: Bug

#11654 post-media has too small sizes for video files
  database.sql
  doc/database/db_post-media.md
  static/dbstructure.config.php
Labels: Installation, Enhancement

#11658 Accesskey was used twice
  doc/Accesskeys.md
  src/Module/BaseSettings.php
Labels: Bug, UI

#11657 Size "mediumint" wasn't enough
  database.sql
  doc/database/db_post-media.md
  src/Protocol/Feed.php
  static/dbstructure.config.php
Labels: Installation, Enhancement

#11659 Add missing identifier quote in Database->replaceInTableFields
  src/Database/Database.php
Labels: Bug, Installation

#11663 Updated composer.phar
  bin/composer.phar
Labels: Installation, Enhancement

#11660 More type-hints - Batch 003
  mod/fbrowser.php
  mod/photos.php
  src/Console/Addon.php
  src/Core/Addon.php
  src/Core/Hook.php
  src/Core/L10n.php
  src/Core/Renderer.php
  src/Core/Theme.php
  src/Database/DBA.php
  src/Database/Database.php
  src/Database/View.php
  src/Factory/Api/Mastodon/Status.php
  src/Model/APContact.php
  src/Model/GServer.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Feed.php
  src/Protocol/Salmon.php
  src/Render/FriendicaSmartyEngine.php
  src/Render/TemplateEngine.php
  src/Util/Strings.php
  src/Util/XML.php
  src/Worker/Notifier.php
  tests/Util/Database/ExtendedPDO.php
  tests/Util/Database/StaticDatabase.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
  tests/src/Util/StringsTest.php
  view/theme/frio/style.php
Labels: Bug

#11662 Ensure parameter 4 of Post\Media::splitAttachment is a boolean value
  src/Model/Item.php
Labels: Bug

#11664 update FR translations THX kalon33
  view/lang/fr/messages.po
  view/lang/fr/strings.php
Labels: Translation

#11668 Renamings in logger class to make them more clear
  src/Core/Logger.php
  tests/Util/Database/StaticDatabase.php
Labels: Enhancement

#11669 Remove email subject encoding from ItemCCEmail constructor
  src/Object/EMail/ItemCCEMail.php
Labels: Bug

#11674 Bump guzzlehttp/guzzle from 6.5.5 to 6.5.8
  composer.lock
Labels: dependencies

#11678 Fix for Transmitter::sendContactAccept() wrong 2nd parameter type
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#11679 Rewrite of autotest.sh
  .gitignore
  bin/dev/autotest.sh
Labels: Enhancement

#11680 Respect Forwarded-For headers
  src/App/Request.php
  src/Core/Logger/Type/Monolog/DevelopHandler.php
  src/Model/User/Cookie.php
  src/Module/HTTPException/PageNotFound.php
  src/Module/Search/Index.php
  src/Security/Authentication.php
  static/defaults.config.php
  static/dependencies.config.php
  static/env.config.php
  tests/src/App/RequestTest.php
  tests/src/Model/User/CookieTest.php
Labels: Enhancement

#11681 Allowing Item::getFromUri()'s 2nd parameter a null value
  src/Model/Item.php
  src/Protocol/Feed.php
  src/Util/LDSignature.php
Labels: Bug

#11683 Fix a couple Fatal Errors
  src/Contact/LocalRelationship/Factory/LocalRelationship.php
  src/Model/GServer.php
  src/Worker/Delivery.php
Labels: Bug

#11686 Fix off-by-one error in Message ID header count check in Util\Emailer
  src/Util/Emailer.php
Labels: Bug

#11685 Add explicit gserver.site_name string truncate in Model\GServer
  src/Model/GServer.php
Labels: Bug

#11688 Replace obsolete posted sort field by created in mod\photos
  mod/photos.php
  src/Content/Text/BBCode.php
  src/Model/Item.php
  tests/src/Content/Text/BBCodeTest.php
Labels: Bug

#11689 Changed more double-quotes to single
  bin/daemon.php
  mod/item.php
  src/App.php
  src/Content/Text/BBCode.php
  src/Content/Text/Plaintext.php
  src/Database/Database.php
  src/Model/Contact.php
  src/Model/FContact.php
  src/Module/Contact/Profile.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Util/ReversedFileReader.php
  src/Worker/OnePoll.php
Labels: Enhancement

#11690 2 Factor Authentication improvements
  database.sql
  doc/database/db_2fa_trusted_browser.md
  src/Model/User/Cookie.php
  src/Module/Security/Logout.php
  src/Module/Security/TwoFactor/SignOut.php
  src/Module/Security/TwoFactor/Trust.php
  src/Module/Security/TwoFactor/Verify.php
  src/Module/Settings/TwoFactor/Index.php
  src/Module/Settings/TwoFactor/Trusted.php
  src/Security/Authentication.php
  src/Security/TwoFactor/Factory/TrustedBrowser.php
  src/Security/TwoFactor/Model/TrustedBrowser.php
  static/dbstructure.config.php
  static/routes.config.php
  tests/src/Security/TwoFactor/Factory/TrustedBrowserTest.php
  tests/src/Security/TwoFactor/Model/TrustedBrowserTest.php
  view/lang/C/messages.po
  view/templates/settings/twofactor/trusted_browsers.tpl
  view/templates/twofactor/signout.tpl
  view/templates/twofactor/trust.tpl
  view/templates/twofactor/verify.tpl
Labels: Enhancement

#11692 Convert potential spaces in Memcache(d) key names
  src/Core/Cache/Type/MemcacheCache.php
  src/Core/Cache/Type/MemcachedCache.php
  src/Protocol/OStatus.php
  tests/src/Core/Cache/CacheTest.php
Labels: Bug

#11684 Create ActivityPub\FetchQueue and ActivityPub\FetchQueueItem classes
  src/Model/Item.php
  src/Module/Debug/ActivityPubConversion.php
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/FetchQueue.php
  src/Protocol/ActivityPub/FetchQueueItem.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug

#11693 Use labels for woodpecker continuous deployments
  .woodpecker/.continuous-deployment.yml
  .woodpecker/.releaser.yml
Labels: Bug, Enhancement

#11696 Fixed "Argument 1 passed to Friendica\Content\Text\BBCode::toPlaintext() must be of the type string, null given"
  src/Object/Api/Twitter/User.php
Labels: Bug

#11699 Type-hints added, method renamed
  mod/editpost.php
  src/Content/BoundariesPager.php
  src/Content/Conversation.php
  src/Content/Item.php
  src/Content/Nav.php
  src/Content/OEmbed.php
  src/Content/PageInfo.php
  src/Content/Pager.php
  src/Content/Smilies.php
  src/Content/Text/BBCode.php
  src/Content/Widget.php
  src/Core/Update.php
  src/Database/DBStructure.php
  src/Database/PostUpdate.php
  src/Model/Contact.php
  src/Model/Photo.php
  src/Module/Contact.php
  src/Module/Contact/Contacts.php
  src/Module/Conversation/Community.php
  src/Module/Conversation/Network.php
  src/Module/Photo.php
  src/Object/Post.php
  update.php
Labels: Enhancement
