Repository friendica/friendica, pull requests merged in 2022-10, with the labels that each got.

#11948 Support for transmitting quoted posts
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Federation, Enhancement

#11955 Fix picture link removal in "getAttachedData"
  src/Content/Text/BBCode.php
  src/Content/Text/Plaintext.php
Labels: Enhancement

#11957 Issue 11891: Enable search for user@domain.tld
  src/Module/BaseSearch.php
  src/Module/Contact.php
Labels: UX, Enhancement

#11958 Issue 11938: Fix weird date formats
  src/Util/DateTimeFormat.php
Labels: Federation, Enhancement

#11959 Fix: Undefined array key "object_object_type"
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, Federation

#11960 Issue 11880: Provide "alt" description from uploaded file
  mod/fbrowser.php
  view/js/filebrowser.js
  view/templates/filebrowser.tpl
  view/theme/frio/js/filebrowser.js
  view/theme/frio/templates/filebrowser.tpl
Labels: UX, Enhancement

#11961 regen CREDITS for the next release
  CREDITS.txt
Labels: Docs

#11964 Added sharing check for DFRN
  src/Protocol/DFRN.php
Labels: Bug, Federation

#11966 Juts another date format fix
  src/Util/DateTimeFormat.php
Labels: Federation, Enhancement

#11968 [frio] Add left sidebar toggle button for mobile anonymous view
  view/theme/frio/templates/nav.tpl
Labels: Bug, Theme-specific, Mobile, UI

#11967 Improve quote share ("message_id" added)
  mod/item.php
  mod/share.php
  src/App/Router.php
  src/Content/Text/BBCode.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/Diaspora.php
  src/Protocol/Email.php
  tests/src/Content/Text/BBCodeTest.php
  view/js/autocomplete.js
Labels: UX, Federation, Enhancement

#11971 And another weird date format
  src/Util/DateTimeFormat.php
Labels: Federation, Enhancement

#11972 Issue 11969: Only use the simple share with federated posts
  mod/share.php
Labels: Bug, UX

#11974 Issue 11969: Simplified share
  mod/share.php
  src/Content/Text/BBCode.php
  src/Model/Item.php
Labels: Federation, Enhancement

#11973 Add tests for DateTimeFormat::fix()
  src/Util/DateTimeFormat.php
  tests/src/Util/DateTimeFormatTest.php
Labels: Enhancement

#11977 Add a couple new cases to DateTimeFormat::fix()
  src/Util/DateTimeFormat.php
  tests/src/Util/DateTimeFormatTest.php
Labels: Bug, Federation

#11978 The quote functionality is simplified
  mod/item.php
  mod/share.php
  src/Contact/Avatar.php
  src/Content/Item.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
Labels: Federation, Enhancement

#11979 Notices
  src/Model/GServer.php
  src/Util/ParseUrl.php
Labels: Bug

#11980 Use "maxloadavg" when "worker_load_cooldown" is not defined
  src/Core/Worker.php
Labels: Enhancement

#11981 Quote of quotes are visually improved
  src/Content/Item.php
  src/Protocol/Diaspora.php
Labels: Federation, Enhancement

#11982 Quoted posts from Twitter now contain media again
  src/Content/Item.php
Labels: Bug, Federation

#11983 Contact array can be empty in Model\Contact::getAvatarPath
  src/Model/Contact.php
Labels: Bug

#11987 Fix attached media in quoted posts
  src/Content/Item.php
  src/Model/Post/Media.php
Labels: Bug, Federation

#11988 Add missing post keys to retrieve pLink in Model\Event::prepareListForTemplate()
  src/Model/Event.php
Labels: Bug

#11989 Only add images for non-federated quote shares
  src/Content/Item.php
Labels: Bug, Federation

#11990 Return the pageinfo when feed is shared
  src/Content/Item.php
Labels: Enhancement

#11913 Updates for the CHANGELOG for 2022.09
  CHANGELOG
Labels: Docs

#11995 New field "quote-uri-id" for quoted posts
  database.sql
  doc/database/db_post-content.md
  src/Content/Text/BBCode.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Transmitter.php
  static/dbstructure.config.php
  static/dbview.config.php
  view/lang/C/messages.po
Labels: Federation, Enhancement

#11999 Improve quote generation
  src/Content/Item.php
  src/Content/Text/BBCode.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Federation, Enhancement

#12000 updates to the vagrant VM provision and config
  Vagrantfile
  bin/dev/vagrant_provision.sh
  doc/Vagrant.md
  mods/local.config.vagrant.php
Labels: Bug, Docs

#12001 [docs] note the preference of MariaDB over other MySQL implementation…
  doc/Install.md
  doc/de/Install.md
Labels: Docs

#12002 [frio] Add new frio.always_open_compose setting
  src/Content/Conversation.php
  src/Module/Item/Compose.php
  view/lang/C/messages.po
  view/templates/item/compose.tpl
  view/theme/frio/config.php
  view/theme/frio/js/theme.js
  view/theme/frio/templates/jot.tpl
  view/theme/frio/templates/theme_settings.tpl
Labels: Theme-specific, UX, Enhancement

#12004 The priority is now a class constant
  boot.php
  mod/events.php
  mod/item.php
  mod/tagger.php
  src/Console/Relocate.php
  src/Core/Search.php
  src/Core/Update.php
  src/Core/UserImport.php
  src/Core/Worker.php
  src/Core/Worker/Cron.php
  src/Model/Contact.php
  src/Model/FContact.php
  src/Model/GServer.php
  src/Model/Item.php
  src/Model/Mail.php
  src/Model/Post/Delayed.php
  src/Model/Profile.php
  src/Model/PushSubscriber.php
  src/Model/Subscription.php
  src/Model/User.php
  src/Module/Admin/Blocklist/Contact.php
  src/Module/Admin/Blocklist/Server/Add.php
  src/Module/Admin/Site.php
  src/Module/Api/Friendica/Events/Create.php
  src/Module/Api/Mastodon/Statuses.php
  src/Module/Contact.php
  src/Module/FriendSuggest.php
  src/Module/Photo.php
  src/Module/Register.php
  src/Module/Settings/Account.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Worker/CheckDeletedContacts.php
  src/Worker/Cron.php
  src/Worker/Directory.php
  src/Worker/ExpirePosts.php
  src/Worker/MoveStorage.php
  src/Worker/Notifier.php
  src/Worker/PollContacts.php
  src/Worker/RemoveUser.php
  src/Worker/UpdateContacts.php
  src/Worker/UpdateGServers.php
  static/defaults.config.php
  update.php
Labels: Enhancement

#12005 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#12006 Some more constants are moved to their specific classes
  boot.php
  src/Content/Nav.php
  src/Core/Update.php
  src/Module/Admin/Site.php
  src/Module/Api/GNUSocial/GNUSocial/Config.php
  src/Module/Conversation/Community.php
  view/lang/C/messages.po
Labels: Enhancement

#12007 The friendica constants have been moved to the app class
  boot.php
  src/App.php
  src/App/Page.php
  src/Core/Console.php
  src/Module/Admin/Federation.php
  src/Module/Admin/Summary.php
  src/Module/Api/GNUSocial/GNUSocial/Config.php
  src/Module/Friendica.php
  src/Module/NodeInfo110.php
  src/Module/NodeInfo120.php
  src/Module/NodeInfo210.php
  src/Module/Settings/UserExport.php
  src/Module/Statistics.php
  src/Network/HTTPClient/Factory/HttpClient.php
  src/Object/Api/Mastodon/Instance.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  src/Util/EMailer/MailBuilder.php
  src/Util/Writer/DbaDefinitionSqlWriter.php
  tests/src/Module/NodeInfoTest.php
Labels: Enhancement

#12015 Check the readability before acessing /proc/loadavg
  src/Core/System.php
Labels: Bug

#12014 The user related functions moved to the session class
  boot.php
  src/App.php
  src/BaseModule.php
  src/Core/Session.php
Labels: Enhancement

#12012 Move Monolog to Addons
  bin/console.php
  composer.json
  composer.lock
  doc/Addons.md
  doc/de/Addons.md
  src/Core/Logger/Factory/Logger.php
  src/Core/Logger/Type/Monolog/DevelopHandler.php
  src/Core/Logger/Type/Monolog/IntrospectionProcessor.php
  src/Core/Logger/Type/README.md
  src/Database/Database.php
  tests/src/Core/Cache/DatabaseCacheTest.php
  tests/src/Core/Storage/DatabaseStorageTest.php
  tests/src/Core/Storage/Repository/StorageManagerTest.php
Labels: Addons, Enhancement

#12016 The EOL constant is removed
  boot.php
  mod/wall_attach.php
  mod/wall_upload.php
  src/Content/Conversation.php
  src/Core/Installer.php
  src/Database/DBStructure.php
  src/Model/Contact.php
  src/Model/User.php
  src/Module/Install.php
  src/Object/EMail/ItemCCEMail.php
Labels: Enhancement

#11996 Fixed: "Argument 1 passed to Friendica\Util\Temporal::getRelativeDate() must be of the type string, null given"
  src/Util/Temporal.php
Labels: Bug

#12017 Fix errors introduced by PR #11997
  src/Content/Item.php
  src/Module/Profile/Status.php
Labels: Bug

#12018 Replace Core\Session functions with DI::session methods
  mod/redir.php
  src/App.php
  src/Content/Conversation.php
  src/Content/Nav.php
  src/Core/Session.php
  src/Model/Profile.php
  src/Module/Conversation/Network.php
  src/Module/Delegation.php
  src/Module/Profile/Status.php
  src/Module/Settings/Delegation.php
  src/Module/Settings/Display.php
  src/Module/Settings/TwoFactor/Index.php
  src/Module/Settings/TwoFactor/Verify.php
  src/Module/Update/Profile.php
  src/Object/Post.php
  view/theme/frio/theme.php
Labels: Enhancement

#12019 FR translation update THX Nicolas Derive
  view/lang/fr/messages.po
  view/lang/fr/strings.php
Labels: Translation

#12030 Fix ERROR IHandleSessions
  src/Content/Conversation.php
Labels: Bug

#12022 old boot.php functions replaced in various places
  doc/Addons.md
  doc/Developer-Domain-Driven-Design.md
  doc/themes.md
  src/Navigation/Notifications/Factory/FormattedNavNotification.php
  src/Navigation/Notifications/Factory/FormattedNotify.php
  src/Navigation/Notifications/Factory/Introduction.php
  src/Network/Probe.php
  src/Object/Post.php
  src/Object/Thread.php
  src/Security/BasicAuth.php
  src/Security/Security.php
  src/Util/Temporal.php
  view/theme/duepuntozero/config.php
  view/theme/duepuntozero/theme.php
  view/theme/frio/config.php
  view/theme/frio/php/scheme.php
  view/theme/frio/theme.php
  view/theme/quattro/config.php
  view/theme/vier/config.php
  view/theme/vier/theme.php
Labels: Enhancement

#12024 old boot.php functions replaced in varous placed under /src
  src/App.php
  src/App/Page.php
  src/App/Router.php
  src/Content/Conversation.php
  src/Content/ForumManager.php
  src/Content/Item.php
  src/Content/Nav.php
  src/Content/Smilies.php
  src/Content/Widget.php
  src/Content/Widget/SavedSearches.php
  src/Content/Widget/VCard.php
  src/Core/ACL.php
  src/Core/Search.php
  src/Model/Contact.php
  src/Model/Contact/Group.php
  src/Model/Event.php
  src/Model/Group.php
  src/Model/Item.php
  src/Model/Mail.php
  src/Model/Photo.php
  src/Model/Post.php
  src/Model/Profile.php
Labels: Enhancement

#12026 old boot.php functions replaced in src/module (2)
  src/Module/Admin/BaseUsers.php
  src/Module/Contact/Posts.php
  src/Module/Contact/Profile.php
  src/Module/Contact/Revoke.php
  src/Module/Conversation/Community.php
  src/Module/Conversation/Network.php
  src/Module/Debug/ActivityPubConversion.php
  src/Module/Debug/Feed.php
  src/Module/Debug/ItemBody.php
  src/Module/Debug/Probe.php
  src/Module/Debug/WebFinger.php
  src/Module/Events/Json.php
  src/Module/Filer/RemoveTag.php
  src/Module/Filer/SaveTag.php
  src/Module/Item/Activity.php
  src/Module/Item/Compose.php
  src/Module/Item/Follow.php
  src/Module/Item/Ignore.php
  src/Module/Item/Pin.php
  src/Module/Item/Star.php
  src/Module/Notifications/Notification.php
Labels: Enhancement

#12027 old boot.php functions replaced in src/module (3)
  src/Module/Admin/Users/Index.php
  src/Module/Contact/Advanced.php
  src/Module/Contact/Contacts.php
  src/Module/Contact/Conversations.php
  src/Module/Contact/Hovercard.php
  src/Module/Notifications/Introductions.php
  src/Module/Notifications/Ping.php
  src/Module/OAuth/Authorize.php
  src/Module/Profile/Common.php
  src/Module/Settings/Delegation.php
  src/Module/Settings/Display.php
  src/Module/Settings/Profile/Index.php
  src/Module/Settings/Profile/Photo/Crop.php
  src/Module/Settings/Profile/Photo/Index.php
  src/Module/Settings/TwoFactor/AppSpecific.php
  src/Module/Settings/TwoFactor/Index.php
  src/Module/Settings/TwoFactor/Recovery.php
  src/Module/Settings/TwoFactor/Trusted.php
  src/Module/Settings/TwoFactor/Verify.php
  src/Module/Settings/UserExport.php
  src/Module/Update/Community.php
  src/Module/Update/Profile.php
Labels: Enhancement

#12032 Fix Error: Uncaught Exception Error: "Class "Friendica\Content\Session" not found"
  src/Content/Conversation.php
Labels: Bug

#12033 All references to boot.php are now removed
  Doxyfile
  bin/daemon.php
  bin/worker.php
  boot.php
  composer.json
  doc/Composer.md
  doc/Developers-Intro.md
  doc/autoloader.md
  mods/release-list-include.txt
  src/Console/Extract.php
  src/Core/Theme.php
  src/Module/Admin/Site.php
  src/Module/BaseAdmin.php
  src/Module/Group.php
  view/lang/C/messages.po
  view/templates/settings/pagetypes.tpl
Labels: Enhancement

#12036 added a breaking note for custom addons to the CHANGELOG
  CHANGELOG
Labels: Addons, Docs

#12037 Fix using wrong variable in DomainPatterBlocklist::extractFromCSVFile
  src/Moderation/DomainPatternBlocklist.php
Labels: Bug

#12021 UserSession class [1] - Add class and tests
  src/Core/Session.php
  src/Core/Session/Capability/IHandleUserSessions.php
  src/Core/Session/Handler/AbstractSessionHandler.php
  src/Core/Session/Handler/Cache.php
  src/Core/Session/Handler/Database.php
  src/Core/Session/Model/UserSession.php
  src/Core/Session/Type/ArraySession.php
  src/DI.php
  src/Model/Contact.php
  static/dependencies.config.php
  tests/src/Core/Session/UserSessionTest.php
Labels: Enhancement

#12038 UserSession class [2] - Refactor mod/ files
  mod/cal.php
  mod/display.php
  mod/editpost.php
  mod/events.php
  mod/fbrowser.php
  mod/follow.php
  mod/item.php
  mod/match.php
  mod/message.php
  mod/notes.php
  mod/oexchange.php
  mod/ostatus_subscribe.php
  mod/photos.php
  mod/redir.php
  mod/removeme.php
  mod/repair_ostatus.php
  mod/settings.php
  mod/share.php
  mod/suggest.php
  mod/tagger.php
  mod/tagrm.php
  mod/unfollow.php
  mod/update_contact.php
  mod/wall_attach.php
  mod/wall_upload.php
Labels: Enhancement

#12044 Fix CI pipeline
  .woodpecker/.continuous-deployment.yml
  .woodpecker/.releaser.yml
Labels: Bug

#12040 UserSession class [4] - Refactor src/Model/ files
  src/Model/Contact.php
  src/Model/Contact/Group.php
  src/Model/Event.php
  src/Model/Group.php
  src/Model/Item.php
  src/Model/Mail.php
  src/Model/Photo.php
  src/Model/Post.php
  src/Model/Profile.php
Labels: Enhancement

#12045 Fix messages.po issue
  mod/repair_ostatus.php
  src/Module/Debug/ActivityPubConversion.php
  src/Module/Debug/Babel.php
  view/lang/C/messages.po
Labels: Bug

#12046 Add missing DI
  src/Model/Contact/Group.php
Labels: Bug

#12047 Revert "Fix CI pipeline"
  .woodpecker/.continuous-deployment.yml
  .woodpecker/.releaser.yml
Labels: Bug

#12039 UserSession class [3] - Refactor src/ files excluding Module/Model
  mod/removeme.php
  mod/settings.php
  src/App.php
  src/App/Page.php
  src/App/Router.php
  src/Content/Conversation.php
  src/Content/ForumManager.php
  src/Content/Item.php
  src/Content/Nav.php
  src/Content/Smilies.php
  src/Content/Widget.php
  src/Content/Widget/SavedSearches.php
  src/Content/Widget/VCard.php
  src/Core/ACL.php
  src/Core/Search.php
  src/Core/Session.php
  src/Core/Session/Capability/IHandleUserSessions.php
  src/Core/Session/Model/UserSession.php
  src/Module/Admin/Users/Blocked.php
  src/Module/Admin/Users/Index.php
  src/Module/BaseAdmin.php
  src/Module/Contact/Profile.php
  src/Module/Delegation.php
  src/Module/Settings/Delegation.php
  src/Navigation/Notifications/Factory/FormattedNavNotification.php
  src/Navigation/Notifications/Factory/FormattedNotify.php
  src/Navigation/Notifications/Factory/Introduction.php
  src/Network/Probe.php
  src/Object/Post.php
  src/Object/Thread.php
  src/Security/Authentication.php
  src/Security/BasicAuth.php
  src/Security/Security.php
  src/Util/Temporal.php
  tests/FixtureTest.php
Labels: Enhancement

#12048 RU translation update THX SpcCw
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#12049 Fix CI with Session
  tests/FixtureTest.php
Labels: Bug

#12050 Fix missing/wrong IHandleUserSessions usages
  src/Module/Notifications/Introductions.php
  src/Module/Notifications/Notifications.php
  src/Module/ParseUrl.php
Labels: Bug

#12051 Hotfix: One `$` to much ...
  src/Module/Admin/Blocklist/Server/Index.php
Labels: Bug

#12058 Fixed: Undefined property: Friendica\Core\Session\Model\UserSession::$getRemoteUserId
  mod/display.php
  mod/redir.php
Labels: Bug

#12057 Added missing type-hints and formatted some arrays
  src/Content/OEmbed.php
  src/Content/Widget/CalendarExport.php
  src/Content/Widget/ContactBlock.php
  src/Content/Widget/SavedSearches.php
  src/Content/Widget/TagCloud.php
  src/Content/Widget/TrendingTags.php
  src/Content/Widget/VCard.php
Labels: Enhancement

#12060 Fix condition for follows export
  src/Module/Settings/UserExport.php
  static/routes.config.php
  view/lang/C/messages.po
Labels: Bug

#12055 Extend `IHandleUserSessions` from `IHandleSessions` and adapt classes
  src/App.php
  src/Content/Conversation.php
  src/Core/Session/Capability/IHandleUserSessions.php
  src/Core/Session/Factory/Session.php
  src/Core/Session/Model/UserSession.php
  src/DI.php
  src/Module/Security/Login.php
  src/Module/Security/Logout.php
  src/Module/Security/TwoFactor/Recovery.php
  src/Module/Security/TwoFactor/SignOut.php
  src/Module/Security/TwoFactor/Trust.php
  src/Module/Security/TwoFactor/Verify.php
  src/Navigation/Notifications/Factory/Introduction.php
  src/Security/Authentication.php
Labels: Enhancement

#12061 The "share" handling is improved
  mod/display.php
  mod/share.php
  src/Content/Item.php
  src/Content/Text/BBCode.php
  src/Factory/Api/Mastodon/Status.php
  src/Factory/Api/Twitter/Status.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Post/Media.php
  src/Model/Tag.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Worker/Delivery.php
Labels: Enhancement

#12063 Added more type-hints + reformatted code
  src/Model/Contact.php
  src/Model/GServer.php
  src/Module/Admin/Summary.php
  src/Network/Probe.php
Labels: Enhancement

#12064 Unit test added for Temporal utilities class
  tests/src/Util/TemporalTest.php
Labels: Enhancement

#12065 Cleanups: renaming variables and more logging
  mod/update_notes.php
  mod/wall_attach.php
  mod/wall_upload.php
Labels: Enhancement

#12066 Revert "Add email notification to all users on server domain pattern block list update"
  src/Moderation/DomainPatternBlocklist.php
  view/lang/C/messages.po
Labels: Enhancement

#12069 DE translation update
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#12067 Cleanup: missing type-hints, double-quotes, reformatted array
  src/Model/Item.php
  src/Model/Post.php
  src/Object/Post.php
  src/Worker/Delivery.php
  src/Worker/Notifier.php
  src/Worker/OnePoll.php
Labels: Enhancement

#12070 Some more improvements for posts with shares
  mod/display.php
  mod/item.php
  mod/share.php
  src/Content/Item.php
  src/Content/Text/BBCode.php
  src/Database/PostUpdate.php
  src/Factory/Api/Mastodon/Status.php
  src/Factory/Api/Twitter/Status.php
  src/Model/Item.php
  src/Model/Post/Media.php
  src/Model/Tag.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  tests/src/Factory/Api/Twitter/StatusTest.php
Labels: Federation, Enhancement

#12071 fix exception when adding a poll option without votes
  src/Model/Item.php
Labels: Bug

#12072 [Composer] Remove bower-asset/vue dependency
  composer.json
  composer.lock
Labels: Bug

#12074 Accepting contact request does finally work per Mastodon API
  src/Factory/Api/Mastodon/Notification.php
  src/Module/Api/Mastodon/FollowRequests.php
Labels: Bug, API

#12076 Improved handling of native quotes
  mod/item.php
  src/Content/Item.php
  src/Content/Text/BBCode.php
  src/Factory/Api/Mastodon/Status.php
  src/Factory/Api/Twitter/Status.php
  src/Model/Item.php
  src/Model/Post/Media.php
  src/Model/Tag.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
Labels: Enhancement

#12078 Move mod/wallmessage.php to src/Module
  mod/wallmessage.php
  src/Core/Session/Capability/IHandleUserSessions.php
  src/Core/Session/Model/UserSession.php
  src/Model/Profile.php
  src/Module/Profile/UnkMail.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/profile/unkmail-header.tpl
  view/templates/profile/unkmail.tpl
  view/templates/wallmessage.tpl
  view/templates/wallmsg-header.tpl
Labels: Enhancement

#12081 Move mod/wall_upload.php to src/Module
  mod/wall_upload.php
  src/Module/Profile/Photos/Upload.php
  static/routes.config.php
  view/js/filebrowser.js
  view/lang/C/messages.po
  view/templates/msg-header.tpl
  view/theme/frio/js/filebrowser.js
  view/theme/smoothly/templates/jot-header.tpl
Labels: Enhancement

#12082 Move mod/wall_attach.php to src/Module
  mod/wall_attach.php
  src/Module/Profile/Attachment/Upload.php
  static/routes.config.php
  view/js/filebrowser.js
  view/lang/C/messages.po
  view/theme/frio/js/filebrowser.js
  view/theme/smoothly/templates/jot-header.tpl
Labels: Enhancement

#12083 Move mod/unfollow.php to src/Module
  mod/follow.php
  mod/unfollow.php
  src/Content/Widget/VCard.php
  src/Model/Contact.php
  src/Model/Profile.php
  src/Module/Contact/Unfollow.php
  src/Module/Profile/RemoteFollow.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/auto_request.tpl
  view/theme/frio/templates/auto_request.tpl
Labels: Bug, UX, Enhancement

#12077 Move mod/follow.php to src/Module
  mod/follow.php
  src/Content/Item.php
  src/Content/Widget/VCard.php
  src/Model/APContact.php
  src/Model/Contact.php
  src/Model/Profile.php
  src/Module/Contact/Follow.php
  src/Module/Xrd.php
  src/Network/Probe.php
  static/routes.config.php
  view/lang/C/messages.po
  view/theme/vier/theme.php
Labels: Enhancement
