Repository friendica/friendica, pull requests merged in 2022-03, with the labels that each got.

#11289 HU translation updated THX Balázs Úr
  view/lang/hu/messages.po
  view/lang/hu/strings.php
Labels: Translation

#11288 API: Only display active incoming contact requests
  mod/item.php
  src/Content/Item.php
  src/Module/Api/Mastodon/Statuses.php
  src/Module/Api/Twitter/Friendships/Incoming.php
  src/Module/Api/Twitter/Statuses/Update.php
Labels: API

#11292 API: We can now post to groups via the Mastodon endpoint
  doc/API-Mastodon.md
  src/Module/Api/Mastodon/Statuses.php
Labels: API

#11293 API: Support for the "direct" visibility
  src/Content/Item.php
  src/Module/Api/Mastodon/Statuses.php
Labels: API

#11295 AR translation updates THX abidin toumi
  view/lang/ar/messages.po
  view/lang/ar/strings.php
Labels: Translation

#11296 Improved support for Mastodon style content warnings
  src/Content/Feature.php
  src/Model/Item.php
  src/Object/Post.php
  view/lang/C/messages.po
Labels: Enhancement

#11297 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11298 Exclude symbolic links from tar transformation
  .woodpecker/.continuous-deployment.yml
  .woodpecker/.releaser.yml
Labels: Bug

#11305 API: Improve support for the summary field
  src/Factory/Api/Mastodon/Status.php
  src/Module/Api/Mastodon/Statuses.php
  src/Object/Api/Mastodon/Status.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, API

#11306 Replace abstract content with a space to prevent missing spaces
  src/Content/Text/BBCode.php
Labels: Bug, Federation

#11307 API: Fix "in_reply_to_status_id"
  src/Module/Api/Twitter/Statuses/Update.php
Labels: Bug, API

#11308 API: Fixed the bookmarking
  src/Module/Api/Mastodon/Statuses/Bookmark.php
  src/Module/Api/Mastodon/Statuses/Unbookmark.php
Labels: Bug, API

#11314 Estimate active server users when not provided by the system
  src/Model/GServer.php
Labels: Federation, Enhancement

#11318 Issue 11315: Fix for all receivers in "to"
  src/Factory/Api/Mastodon/Status.php
  src/Model/Tag.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug, UX, Federation

#11322 Reduce amount of notifications by communities
  src/Model/Post/UserNotification.php
Labels: UX, Enhancement

#11321 Normalize base URL usage in admin templates
  mod/ping.php
  src/Module/Admin/Logs/View.php
  src/Module/Admin/Site.php
  src/Module/Admin/Themes/Details.php
  src/Module/Admin/Themes/Embed.php
  src/Module/Admin/Themes/Index.php
  src/Module/Register.php
  view/lang/C/messages.po
  view/templates/admin/logs/view.tpl
  view/templates/admin/summary.tpl
  view/theme/frio/templates/admin/logs/view.tpl
  view/theme/frio/templates/admin/summary.tpl
Labels: Bug, Installation

#11326 Don't send notifications for activities caused by the community contact
  src/Model/Post/UserNotification.php
Labels: UX, Enhancement

#11327 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11330 Some small improvements for importing feeds
  src/Protocol/Feed.php
Labels: Enhancement

#11331 Send community posts only to the community
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#11332 Don't send forum posts to the user's followers
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#11273 Add follow notifications for soapbox accounts
  database.sql
  doc/Addons.md
  doc/database.md
  doc/database/db_notify.md
  doc/de/Addons.md
  mod/ping.php
  src/Core/System.php
  src/DI.php
  src/Model/Contact.php
  src/Model/Post/UserNotification.php
  src/Module/BaseNotifications.php
  src/Module/Notifications/Notification.php
  src/Module/Notifications/Notifications.php
  src/Module/Notifications/Ping.php
  src/Navigation/Notifications/Collection/FormattedNotifies.php
  src/Navigation/Notifications/Collection/Notifications.php
  src/Navigation/Notifications/Entity/Notification.php
  src/Navigation/Notifications/Entity/Notify.php
  src/Navigation/Notifications/Factory/FormattedNavNotification.php
  src/Navigation/Notifications/Factory/FormattedNotify.php
  src/Navigation/Notifications/Factory/Notification.php
  src/Navigation/Notifications/Factory/Notify.php
  src/Navigation/Notifications/Repository/Notification.php
  src/Navigation/Notifications/Repository/Notify.php
  src/Navigation/Notifications/ValueObject/FormattedNavNotification.php
  src/Navigation/Notifications/ValueObject/FormattedNotify.php
  src/Worker/PushSubscription.php
  static/dbstructure.config.php
  static/routes.config.php
  tests/datasets/api.fixture.php
  tests/src/Module/Api/Friendica/NotificationTest.php
  view/js/main.js
  view/lang/C/messages.po
  view/templates/nav.tpl
  view/templates/notifications/nav/notify.tpl
  view/theme/duepuntozero/templates/nav.tpl
  view/theme/frio/templates/nav.tpl
  view/theme/frio/templates/notifications/nav/notify.tpl
  view/theme/quattro/templates/nav.tpl
  view/theme/smoothly/templates/nav.tpl
  view/theme/vier/templates/nav.tpl
  view/theme/vier/templates/notifications/nav/notify.tpl
Labels: UX, Enhancement

#11333 Don't use the GUID value directly
  src/Protocol/Feed.php
Labels: Federation, Enhancement

#11336 Add exception when message is empty in FormatteNavNotification::createFromNotification
  src/Module/Notifications/Ping.php
  src/Navigation/Notifications/Exception/NoMessageException.php
  src/Navigation/Notifications/Factory/FormattedNavNotification.php
  src/Navigation/Notifications/Factory/Notification.php
  src/Navigation/Notifications/Repository/Notification.php
  src/Navigation/Notifications/ValueObject/FormattedNavNotification.php
  view/lang/C/messages.po
Labels: Bug

#11341 PHP deprecation warning due wrong order of function parameters
  src/Worker/UpdateContacts.php
Labels: Enhancement, PHP 8

#11342 Add correct ordering for detailed notifications
  src/Module/Notifications/Ping.php
Labels: Bug, UX

#11349 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11351 .htaccess-dist deny access to some backup files
  .htaccess-dist
Labels: Installation, Enhancement, Security

#11347 Fix the problem that the post update never stopped on larger systems
  src/Database/PostUpdate.php
Labels: Bug, Installation

#11352 Add support for notification visibility settings
  mod/settings.php
  src/Module/Notifications/Ping.php
  src/Navigation/Notifications/Repository/Notification.php
Labels: Bug, UX

#11334 Use a nicer GUID style format
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement

#11357 Improve the description of the federation statistics
  src/Module/Admin/Federation.php
  view/lang/C/messages.po
Labels: Enhancement, UI

#11358 RU translations THX Alexander An
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#11359 Avoid empty notifications / fixed link to the content
  src/Navigation/Notifications/Factory/Notification.php
  src/Navigation/Notifications/Repository/Notification.php
Labels: UX, Enhancement

#11360 Don't create empty announce notifications
  src/Model/Post/UserNotification.php
  src/Module/Notifications/Ping.php
  src/Navigation/Notifications/Repository/Notification.php
Labels: Enhancement

#11362 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11364 Fix link to post in notification
  src/Navigation/Notifications/Factory/Notification.php
  view/lang/C/messages.po
Labels: Bug, UX

#11366 Issue 11310: Show pinned posts when not logged in
  src/Content/Conversation.php
  src/Module/Profile/Status.php
Labels: Bug, UX

#11367 Prioritize the title over the summary (content warning)
  src/Content/Conversation.php
  src/Object/Post.php
Labels: UX, Enhancement

#11370 PL translation update THX strebski
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#11372 Issue 11368: Prevent namespace prefix warning
  src/Util/XML.php
Labels: Enhancement

#11373 PL translation update THX strebski
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#11374 Prevent unwarranted password manager auto-completion in settings form fields
  mod/settings.php
Labels: Bug, UX

#11375 Improve the compatibility with Lemmy
  src/Protocol/ActivityPub/Transmitter.php
Labels: Federation, Enhancement

#11376 Don't display Peertube groups as forums
  database.sql
  src/Content/ForumManager.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Bug, UX

#11377 PL translation update THX strebski
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#11378 Add Default Accept for HTTP Calls
  src/Network/HTTPClient/Client/HttpClient.php
Labels: Bug, Enhancement

#11382 Some more "accept" parameters are added
  mod/ostatus_subscribe.php
  mod/redir.php
  src/Content/OEmbed.php
  src/Content/Text/BBCode.php
  src/Core/Search.php
  src/Core/Storage/Type/ExternalResource.php
  src/Model/GServer.php
  src/Model/Photo.php
  src/Model/Post/Link.php
  src/Model/Post/Media.php
  src/Model/Profile.php
  src/Model/User.php
  src/Module/Admin/Summary.php
  src/Module/Debug/Feed.php
  src/Module/Magic.php
  src/Module/Photo.php
  src/Module/Proxy.php
  src/Network/HTTPClient/Client/HttpClient.php
  src/Network/Probe.php
  src/Protocol/Diaspora.php
  src/Protocol/OStatus.php
  src/Protocol/Salmon.php
  src/Security/ExAuth.php
  src/Util/HTTPSignature.php
  src/Util/Images.php
  src/Util/ParseUrl.php
  src/Worker/CheckVersion.php
  src/Worker/Directory.php
  src/Worker/NodeInfo.php
  src/Worker/OnePoll.php
  src/Worker/PullDirectory.php
  src/Worker/SearchDirectory.php
  src/Worker/UpdateServerDirectory.php
  src/Worker/UpdateServerPeers.php
Labels: Enhancement

#11384 API: Enable picture upload via Tusky again
  static/routes.config.php
Labels: Bug, Mobile, API
