Repository friendica/friendica, pull requests merged in 2022-07, with the labels that each got.

#11703 Fix fatal errors
  src/Content/Smilies.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#11705 Fix for "Argument 1 passed to Friendica\Content\Text\BBCode::toPlaintext() must be of the type string, null given"
  mod/display.php
  src/Content/Text/BBCode.php
Labels: Bug

#11709 Avoid TypeError because of missing "uri-id" entry
  src/Factory/Api/Mastodon/Account.php
Labels: Bug, API

#11710 Type-hint has to be string, instead of int
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#11715 DE translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11717 DE translation updates THX FOSS+
  view/lang/de/messages.po
  view/lang/de/strings.php
Labels: Translation

#11718 Feature optional network group count
  src/Module/Admin/Site.php
  src/Module/Notifications/Ping.php
  static/settings.config.php
  view/lang/C/messages.po
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement, Performance

#11720 Remove unused uid parameter in Item::newURI
  mod/item.php
  mod/photos.php
  mod/tagger.php
  src/Model/Event.php
  src/Model/Item.php
  src/Model/Mail.php
  src/Module/Api/Mastodon/Statuses.php
  src/Module/Contact/Poke.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Feed.php
Labels: Bug

#11719 adhere `use` and type-hints :-)
  src/Module/Security/TwoFactor/Trust.php
  src/Security/TwoFactor/Exception/TrustedBrowserNotFoundException.php
  src/Security/TwoFactor/Exception/TrustedBrowserPersistenceException.php
  src/Security/TwoFactor/Repository/TrustedBrowser.php
Labels: Bug

#11725 Fix type hint typo in Protocol\Email::messageGetPart
  src/Protocol/Email.php
Labels: Bug

#11727 Fix HTTP Client redirect Bug
  src/Network/HTTPClient/Factory/HttpClient.php
  tests/src/Network/HTTPClient/Client/HTTPClientTest.php
Labels: Bug

#11728 Split DBStructure & View
  src/Console/AutomaticInstallation.php
  src/Console/DatabaseStructure.php
  src/Core/Installer.php
  src/DI.php
  src/Database/DBStructure.php
  src/Database/Database.php
  src/Database/Definition/DbaDefinition.php
  src/Database/Definition/ViewDefinition.php
  src/Database/View.php
  src/Model/APContact.php
  src/Model/Attach.php
  src/Model/Contact/User.php
  src/Model/GServer.php
  src/Model/Photo.php
  src/Model/Post.php
  src/Model/Post/Content.php
  src/Model/Post/History.php
  src/Model/Post/Question.php
  src/Model/Post/QuestionOption.php
  src/Model/Post/Thread.php
  src/Model/Post/ThreadUser.php
  src/Model/Post/User.php
  src/Model/Post/UserNotification.php
  src/Module/Install.php
  src/Module/Settings/UserExport.php
  src/Util/Writer/DbaDefinitionSqlWriter.php
  src/Util/Writer/DocWriter.php
  src/Util/Writer/ViewDefinitionSqlWriter.php
  src/Worker/ExpirePosts.php
  static/dependencies.config.php
  tests/Util/VFSTrait.php
  tests/src/Core/Cache/DatabaseCacheTest.php
  tests/src/Core/Storage/DatabaseStorageTest.php
  tests/src/Core/Storage/Repository/StorageManagerTest.php
Labels: Enhancement

#11729 Enable the view module in maintenance mode
  src/App.php
  view/theme/duepuntozero/style.php
  view/theme/duepuntozero/theme.php
  view/theme/frio/style.php
  view/theme/frio/theme.php
  view/theme/quattro/style.php
  view/theme/quattro/theme.php
  view/theme/smoothly/theme.php
  view/theme/vier/style.php
  view/theme/vier/theme.php
Labels: Bug

#11733 Added returned type-int "int"
  src/Console/Addon.php
  src/Console/ArchiveContact.php
  src/Console/AutomaticInstallation.php
  src/Console/Cache.php
  src/Console/Config.php
  src/Console/Contact.php
  src/Console/CreateDoxygen.php
  src/Console/DatabaseStructure.php
  src/Console/DocBloxErrorChecker.php
  src/Console/Extract.php
  src/Console/FixAPDeliveryWorkerTaskParameters.php
  src/Console/GlobalCommunityBlock.php
  src/Console/GlobalCommunitySilence.php
  src/Console/Lock.php
  src/Console/Maintenance.php
  src/Console/MergeContacts.php
  src/Console/MoveToAvatarCache.php
  src/Console/PhpToPo.php
  src/Console/PoToPhp.php
  src/Console/PostUpdate.php
  src/Console/Relay.php
  src/Console/Relocate.php
  src/Console/ServerBlock.php
  src/Console/Storage.php
  src/Console/Test.php
  src/Console/Typo.php
  src/Console/User.php
  src/Core/Console.php
Labels: Enhancement

#11734 $link_item might be boolean (no record found) under rare conditions
  src/Navigation/Notifications/Factory/Notification.php
Labels: Bug

#11735 [frio] Accept 0 as a valid content background transparency in frio/style.php
  view/theme/frio/style.php
Labels: Bug, Theme-specific

#11741 Fixed E_NOTICE due to wrong array
  src/Protocol/OStatus.php
Labels: Bug

#11739 Fixes/missing return statements
  src/Console/ServerBlock.php
  tests/src/Core/Config/Cache/ConfigFileLoaderTest.php
Labels: Bug

#11745 Fix CI / CD woodpecker pipeline
  .woodpecker/.continuous-deployment.yml
  .woodpecker/.releaser.yml
Labels: Bug

#11747 Emergency fixes to fix a bunch of fatal errors
  src/Model/Contact.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Email.php
  src/Util/XML.php
Labels: Bug, Federation

#11750 Fixes/type hints doctag
  mod/photos.php
  src/Console/User.php
  src/Core/Search.php
  src/Model/Profile.php
  src/Module/BaseSearch.php
  src/Module/Search/Acl.php
Labels: Bug

#11753 Fixed missing $contact array, at least initialize it empty
  src/Protocol/Diaspora.php
Labels: Bug

#11754 Rewrote a lot local variables in createProfileData() + other changes
  src/Protocol/Diaspora.php
Labels: Enhancement

#11756 PL translation update THX strebski
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#11755 wrong parameter for BaseURL get in smoothly theme
  view/theme/smoothly/theme.php
Labels: Bug, Theme-specific

#11757 Fix processing of incoming Diaspora messages
  src/Protocol/Diaspora.php
  src/Util/XML.php
Labels: Bug, Federation

#11758 Fixed variable name + used empty()
  src/Protocol/Diaspora.php
Labels: Bug

#11761 update to the zh-cn translation THX shykana
  view/lang/zh-cn/messages.po
  view/lang/zh-cn/strings.php
Labels: Translation

#11766 Add expected "usage.users" property to all versions of NodeInfo
  src/Model/Nodeinfo.php
  src/Module/NodeInfo110.php
  src/Module/NodeInfo120.php
  src/Module/NodeInfo210.php
Labels: Bug, Federation

#11767 Doubles-quotes to single, type-hints, doc
  src/Model/FContact.php
  src/Model/Profile.php
  src/Model/User.php
Labels: Enhancement

#11759 Fetch missing posts via a queue
  database.sql
  doc/database.md
  doc/database/db_inbox-entry-receiver.md
  doc/database/db_inbox-entry.md
  doc/database/db_post-thread-user.md
  doc/database/db_post-thread.md
  src/Model/APContact.php
  src/Model/Item.php
  src/Model/Post/User.php
  src/Module/Debug/ActivityPubConversion.php
  src/Protocol/ActivityPub.php
  src/Protocol/ActivityPub/FetchQueue.php
  src/Protocol/ActivityPub/FetchQueueItem.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Queue.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Util/JsonLD.php
  src/Worker/Cron.php
  src/Worker/ExpirePosts.php
  src/Worker/FetchMissingActivity.php
  static/dbstructure.config.php
  static/dbview.config.php
  static/defaults.config.php
  static/funkwhale.audio.jsonld
Labels: Bug, Enhancement

#11769 Fix wrong type-hint in Module/DFRN/Notify
  src/Module/DFRN/Notify.php
Labels: Bug

#11771 Rewrote to almost one block of array initialization
  src/Model/Event.php
Labels: Enhancement

#11770 Handle rare case where contact doesn't exist in Model\Group::getIdsByContactId
  src/Model/Group.php
Labels: Bug

#11777 Add download/upload feature for domain pattern block list
  boot.php
  src/App.php
  src/DI.php
  src/Module/Admin/Blocklist/Server/Import.php
  src/Module/Admin/Blocklist/Server/Index.php
  src/Module/Blocklist/Domain/Download.php
  src/Module/Friendica.php
  src/Module/Notifications/Ping.php
  src/Navigation/SystemMessages.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/admin/blocklist/server/import.tpl
  view/templates/admin/blocklist/server/index.tpl
  view/templates/friendica.tpl
Labels: New Feature

#11780 Improved handling of incoming posts / new activity relay
  database.sql
  doc/database.md
  doc/database/db_apcontact.md
  doc/database/db_post-activity.md
  mod/item.php
  src/Database/DBStructure.php
  src/Model/APContact.php
  src/Model/Conversation.php
  src/Model/GServer.php
  src/Model/Item.php
  src/Model/Post/Activity.php
  src/Model/Tag.php
  src/Module/Admin/Item/Source.php
  src/Navigation/Notifications/Factory/Notification.php
  src/Protocol/ActivityPub/Delivery.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Queue.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/OStatus.php
  src/Worker/Cron.php
  src/Worker/ExpireActivities.php
  src/Worker/Notifier.php
  src/Worker/ProcessQueue.php
  src/Worker/ProcessReplyByUri.php
  static/dbstructure.config.php
  view/lang/C/messages.po
Labels: Federation, Enhancement

#11783 Added logging of unsupported meta-tag records
  src/Util/ParseUrl.php
Labels: Enhancement

#11785 Decoupling of relay posts / endless loop removed
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Queue.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Enhancement, Performance

#11787 fix(frio): "Data" move header in template w/ l10n
  view/theme/frio/js/module/admin/logs/view.js
  view/theme/frio/templates/admin/logs/view.tpl
Labels: Theme-specific, Enhancement, Translation

#11788 Replace SFTP-publish with docker-publish
  .woodpecker/.continuous-deployment.yml
  .woodpecker/.releaser.yml
Labels: Enhancement

#11789 Caching for fetched activities
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/OStatus.php
  src/Util/HTTPSignature.php
Labels: Federation, Enhancement, Performance

#11784 Add email notification to all users on server domain pattern block list update
  src/Console/ServerBlock.php
  src/Database/DBA.php
  src/Database/Database.php
  src/Moderation/DomainPatternBlocklist.php
  src/Module/Admin/Blocklist/Server/Add.php
  src/Module/Admin/Blocklist/Server/Import.php
  src/Module/Admin/Blocklist/Server/Index.php
  src/Module/Blocklist/Domain/Download.php
  tests/src/Console/ServerBlockConsoleTest.php
  view/lang/C/messages.po
Labels: New Feature

#11790 Negative caching / config for receiver / fix fatals
  src/Module/Photo.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/Diaspora.php
  static/defaults.config.php
Labels: Bug, Enhancement, Performance

#11791 Fixed wrong type-hint
  src/Model/OpenWebAuthToken.php
  src/Module/Diaspora/Receive.php
  src/Protocol/Diaspora.php
Labels: Bug

#11792 Wrong variable name fixed (maybe copy-paste mistake) + used method instead of direct array access
  src/Model/Contact.php
  src/Module/Api/Friendica/DirectMessages/Search.php
  src/Module/Api/Friendica/Group/Delete.php
  src/Module/Api/Friendica/Notification/Seen.php
  src/Module/Api/GNUSocial/Statusnet/Conversation.php
  src/Module/Api/Twitter/Account/RateLimitStatus.php
  src/Module/Api/Twitter/DirectMessages/Conversation.php
  src/Module/Api/Twitter/DirectMessages/Destroy.php
  src/Module/Api/Twitter/DirectMessages/NewDM.php
  src/Module/Api/Twitter/DirectMessagesEndpoint.php
  src/Module/Api/Twitter/Favorites/Create.php
  src/Module/Api/Twitter/Favorites/Destroy.php
  src/Module/Api/Twitter/Followers/Ids.php
  src/Module/Api/Twitter/Followers/Lists.php
  src/Module/Api/Twitter/Friends/Ids.php
  src/Module/Api/Twitter/Friends/Lists.php
  src/Module/Api/Twitter/Friendships/Destroy.php
  src/Module/Api/Twitter/Friendships/Show.php
  src/Module/Api/Twitter/Statuses/UserTimeline.php
  src/Module/Api/Twitter/Users/Show.php
  src/Module/Feed.php
Labels: Bug, Enhancement

#11793 Reformatted some arrays for better readability
  src/Model/Contact.php
  src/Model/User.php
Labels: Enhancement

#11801 Don't add zero as receiver
  src/Protocol/ActivityPub/Queue.php
Labels: Bug, Federation

#11802 Issue 11800: Remove entry from queue in any case.
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation
