Repository friendica/friendica, pull requests merged in 2022-09, with the labels that each got.

#11883 Use AP data when possible
  src/Model/FContact.php
  view/lang/C/messages.po
Labels: Federation, Enhancement

#11884 Improved language detection
  src/Model/Item.php
  view/lang/C/messages.po
Labels: Enhancement

#11893 Issue 11890: Don't use empty contexts
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#11892 Pagecache for frequently fetched pages
  src/Model/Contact.php
  src/Model/ItemURI.php
  src/Module/ActivityPub/Objects.php
  src/Module/Settings/Account.php
  src/Protocol/ActivityPub/Transmitter.php
  static/dbstructure.config.php
  static/defaults.config.php
Labels: Enhancement, Performance

#11895 Smarty: Configuration added to store without sub directories
  src/Render/FriendicaSmarty.php
  src/Render/FriendicaSmartyEngine.php
  static/defaults.config.php
Labels: Enhancement

#11898 HU translation updates THX Balázs Úr
  view/lang/hu/messages.po
  view/lang/hu/strings.php
Labels: Translation

#11888 [frio] Add support for asynchronous call to /filerm module for post categories and folders
  src/Core/System.php
  src/Module/Filer/RemoveTag.php
  static/routes.config.php
  view/lang/C/messages.po
  view/theme/frio/templates/jot-header.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: Bug, Theme-specific, UX

#11899 Template based XML generation is replaced with native XML
  mod/oexchange.php
  mod/poco.php
  src/Module/WellKnown/HostMeta.php
  src/Module/Xrd.php
  view/templates/oexchange_xrd.tpl
  view/templates/poco_entry_xml.tpl
  view/templates/poco_xml.tpl
  view/templates/xrd_host.tpl
  view/templates/xrd_person.tpl
Labels: Enhancement

#11904 [Composer] Update dependencies ahead of 2022.09 release
  composer.lock
Labels: Installation, Enhancement

#11905 The fcontact table is now updated in the background to improve performance
  database.sql
  doc/database/db_fcontact.md
  src/Model/Contact.php
  src/Model/FContact.php
  src/Module/NoScrape.php
  src/Network/Probe.php
  static/dbstructure.config.php
Labels: Enhancement, Performance

#11908 Allow to reject specific languages on receiving posts via the relay
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/Relay.php
  src/Util/Profiler.php
  static/defaults.config.php
Labels: New Feature

#11902 Detect and remove contact duplicates
  database.sql
  doc/database.md
  doc/database/db_account-user.md
  src/Console/MergeContacts.php
  src/Database/PostUpdate.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Module/Xrd.php
  src/Protocol/ActivityPub/Delivery.php
  src/Worker/Contact/Remove.php
  src/Worker/MergeContact.php
  src/Worker/Notifier.php
  src/Worker/PushSubscription.php
  src/Worker/RemoveUnusedContacts.php
  static/dbstructure.config.php
Labels: Enhancement

#11918 Worker for updating fcontact entries
  src/Worker/UpdateFContact.php
Labels: Enhancement

#11923 Check for network key existence before calling Probe::isProbable in Model\Contact
  src/Model/Contact.php
Labels: Bug

#11922 Ward against missing keys in Model\APContact::isRelay
  src/Model/APContact.php
Labels: Bug

#11924 Fix error "Class 'Friendica\Worker\Worker' not found"
  src/Worker/UpdateServerPeers.php
Labels: Bug

#11926 (Hopefully) SQL improvements
  mod/pubsub.php
  src/Core/Worker/Cron.php
  src/Model/Nodeinfo.php
  src/Module/Api/Mastodon/Notifications.php
  src/Module/Api/Mastodon/Search.php
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
  src/Module/Contact.php
  src/Module/Conversation/Community.php
  src/Module/Conversation/Network.php
  src/Module/Profile/Status.php
  src/Worker/ExpirePosts.php
Labels: Enhancement, Performance

#11925 Do not remove trailing slash from URIs
  src/Network/Probe.php
Labels: Federation, Enhancement

#11763 new event APIs
  doc/API-Entities.md
  doc/API-Friendica.md
  src/Module/Api/Friendica/Events/Create.php
  src/Module/Api/Friendica/Events/Delete.php
  src/Module/Api/Friendica/Events/Index.php
  static/routes.config.php
Labels: Calendar, API

#11927 Add the uri-id if missing
  src/Database/PostUpdate.php
Labels: Bug

#11928 Fix removing falsy text nodes in HTML::tagToBBCodeSub
  src/Content/Text/HTML.php
  tests/src/Content/Text/HTMLTest.php
Labels: Bug

#11929 Issue 11919: Avoid possible memory problems
  src/Module/Conversation/Community.php
  view/lang/C/messages.po
Labels: Enhancement, Performance

#11935 Issue 11932: Restore SQL performance
  src/Worker/ExpirePosts.php
Labels: Bug, Performance

#11933 Fix /api/v1/push/subscription
  src/Module/Api/Mastodon/PushSubscription.php
  tests/src/Module/Api/Mastodon/PushSubscriptionTest.php
Labels: Bug, API

#11936 Added support for the "Youtube Shorts" URL
  src/Content/Text/BBCode.php
  src/Content/Text/Markdown.php
Labels: Enhancement

#11921 We can now configure the worker runtime limits
  src/Core/Worker.php
  src/Core/Worker/Cron.php
  static/defaults.config.php
Labels: Enhancement

#11939 Minor l10n issue
  src/Moderation/DomainPatternBlocklist.php
Labels: Bug

#11940 Issue 11876: Fix local message distribution
  src/Model/Item.php
Labels: Bug

#11942 Only display reshared thread starting posts
  src/Model/Contact.php
Labels: UX, Enhancement

#11944 Added logging of unexpected follow messages
  src/Protocol/ActivityPub/Receiver.php
Labels: Federation, Enhancement

#11945 FR translation update THX Nicolas Derive
  view/lang/fr/messages.po
  view/lang/fr/strings.php
Labels: Translation

#11947 Support for quoted links is added
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Util/JsonLD.php
  static/litepub-0.1.jsonld
Labels: Federation, Enhancement
