Repository friendica/friendica, pull requests merged in 2022-01, with the labels that each got.

#11127 Transform legacy API tests into new structure
  src/Factory/Api/Twitter/DirectMessage.php
  src/Factory/Api/Twitter/Status.php
  src/Module/Api/Twitter/DirectMessages/Destroy.php
  src/Object/Api/Twitter/Status.php
  tests/datasets/api.fixture.php
  tests/datasets/mail/mail.fixture.php
  tests/legacy/ApiTest.php
  tests/src/Core/Lock/DatabaseLockDriverTest.php
  tests/src/Factory/Api/Twitter/ActivitiesTest.php
  tests/src/Factory/Api/Twitter/DirectMessageTest.php
  tests/src/Factory/Api/Twitter/StatusTest.php
  tests/src/Factory/Api/Twitter/UserTest.php
  tests/src/Model/Post/MediaTest.php
  tests/src/Module/Api/ApiResponseTest.php
  tests/src/Module/Api/Friendica/DirectMessages/SearchTest.php
  tests/src/Module/Api/Friendica/NotificationTest.php
  tests/src/Module/Api/Friendica/Photo/DeleteTest.php
  tests/src/Module/Api/Friendica/Photoalbum/DeleteTest.php
  tests/src/Module/Api/Friendica/Photoalbum/UpdateTest.php
  tests/src/Module/Api/GnuSocial/GnuSocial/ConfigTest.php
  tests/src/Module/Api/GnuSocial/GnuSocial/VersionTest.php
  tests/src/Module/Api/GnuSocial/Help/TestTest.php
  tests/src/Module/Api/Mastodon/Accounts/VerifyCredentialsTest.php
  tests/src/Module/Api/Twitter/Account/RateLimitStatusTest.php
  tests/src/Module/Api/Twitter/Account/UpdateProfileTest.php
  tests/src/Module/Api/Twitter/Blocks/ListsTest.php
  tests/src/Module/Api/Twitter/DirectMessages/AllTest.php
  tests/src/Module/Api/Twitter/DirectMessages/ConversationTest.php
  tests/src/Module/Api/Twitter/DirectMessages/DestroyTest.php
  tests/src/Module/Api/Twitter/DirectMessages/InboxTest.php
  tests/src/Module/Api/Twitter/DirectMessages/NewDMTest.php
  tests/src/Module/Api/Twitter/DirectMessages/SentTest.php
  tests/src/Module/Api/Twitter/Favorites/CreateTest.php
  tests/src/Module/Api/Twitter/Favorites/DestroyTest.php
  tests/src/Module/Api/Twitter/FavoritesTest.php
  tests/src/Module/Api/Twitter/Followers/ListsTest.php
  tests/src/Module/Api/Twitter/Friends/ListsTest.php
  tests/src/Module/Api/Twitter/Friendships/IncomingTest.php
  tests/src/Module/Api/Twitter/Lists/StatusesTest.php
  tests/src/Module/Api/Twitter/Media/UploadTest.php
  tests/src/Module/Api/Twitter/SavedSearchesTest.php
  tests/src/Module/Api/Twitter/Statuses/DestroyTest.php
  tests/src/Module/Api/Twitter/Statuses/MentionsTest.php
  tests/src/Module/Api/Twitter/Statuses/NetworkPublicTimelineTest.php
  tests/src/Module/Api/Twitter/Statuses/RetweetTest.php
  tests/src/Module/Api/Twitter/Statuses/ShowTest.php
  tests/src/Module/Api/Twitter/Statuses/UpdateTest.php
  tests/src/Module/Api/Twitter/Statuses/UserTimelineTest.php
  tests/src/Module/Api/Twitter/Users/LookupTest.php
  tests/src/Module/Api/Twitter/Users/SearchTest.php
  tests/src/Module/Api/Twitter/Users/ShowTest.php
  tests/src/Module/NodeInfoTest.php
Labels: Bug, Enhancement, API

#11136 Mark error message as translatable
  src/App.php
  view/lang/C/messages.po
Labels: Translation

#11135 Add OPTIONS endpoint
  mod/pubsub.php
  mod/pubsubhubbub.php
  src/App/Arguments.php
  src/App/Page.php
  src/App/Router.php
  src/BaseModule.php
  src/Capabilities/ICanCreateResponses.php
  src/Core/System.php
  src/Factory/Api/Mastodon/Error.php
  src/Module/Api/Mastodon/Accounts/Followers.php
  src/Module/Api/Mastodon/Accounts/Following.php
  src/Module/BaseApi.php
  src/Module/Response.php
  src/Module/Special/HTTPException.php
  src/Module/Special/Options.php
  src/Util/HTTPSignature.php
  src/Util/Router/FriendicaGroupCountBased.php
  tests/FixtureTest.php
  tests/src/App/ArgumentsTest.php
  tests/src/Module/Api/Friendica/DirectMessages/SearchTest.php
  tests/src/Module/Api/Friendica/Photo/DeleteTest.php
  tests/src/Module/Api/Friendica/Photoalbum/DeleteTest.php
  tests/src/Module/Api/Friendica/Photoalbum/UpdateTest.php
  tests/src/Module/Api/GnuSocial/GnuSocial/ConfigTest.php
  tests/src/Module/Api/Mastodon/Accounts/VerifyCredentialsTest.php
  tests/src/Module/Api/Twitter/Account/RateLimitStatusTest.php
  tests/src/Module/Api/Twitter/Account/UpdateProfileTest.php
  tests/src/Module/Api/Twitter/Blocks/ListsTest.php
  tests/src/Module/Api/Twitter/DirectMessages/AllTest.php
  tests/src/Module/Api/Twitter/DirectMessages/ConversationTest.php
  tests/src/Module/Api/Twitter/DirectMessages/DestroyTest.php
  tests/src/Module/Api/Twitter/DirectMessages/InboxTest.php
  tests/src/Module/Api/Twitter/DirectMessages/NewDMTest.php
  tests/src/Module/Api/Twitter/DirectMessages/SentTest.php
  tests/src/Module/Api/Twitter/Favorites/CreateTest.php
  tests/src/Module/Api/Twitter/Favorites/DestroyTest.php
  tests/src/Module/Api/Twitter/FavoritesTest.php
  tests/src/Module/Api/Twitter/Followers/ListsTest.php
  tests/src/Module/Api/Twitter/Friends/ListsTest.php
  tests/src/Module/Api/Twitter/Friendships/IncomingTest.php
  tests/src/Module/Api/Twitter/Lists/StatusesTest.php
  tests/src/Module/Api/Twitter/Media/UploadTest.php
  tests/src/Module/Api/Twitter/Statuses/DestroyTest.php
  tests/src/Module/Api/Twitter/Statuses/MentionsTest.php
  tests/src/Module/Api/Twitter/Statuses/NetworkPublicTimelineTest.php
  tests/src/Module/Api/Twitter/Statuses/RetweetTest.php
  tests/src/Module/Api/Twitter/Statuses/ShowTest.php
  tests/src/Module/Api/Twitter/Statuses/UpdateTest.php
  tests/src/Module/Api/Twitter/Statuses/UserTimelineTest.php
  tests/src/Module/Api/Twitter/Users/LookupTest.php
  tests/src/Module/Api/Twitter/Users/SearchTest.php
  tests/src/Module/Api/Twitter/Users/ShowTest.php
  tests/src/Module/Special/OptionsTest.php
  tests/src/Util/Router/FriendicaGroupCountBasedTest.php
Labels: Bug, API

#11140 Fix getBirthdays() method
  src/Model/Profile.php
  view/lang/C/messages.po
Labels: Bug

#11149 Add missing Twitter API routes for IDs
  src/Module/Api/Twitter/Statuses/Retweet.php
  static/routes.config.php
Labels: Bug, API

#11153 [frio] Add a conditional browser share button
  src/Model/Item.php
  src/Object/Post.php
  view/lang/C/messages.po
  view/theme/frio/js/theme.js
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: Bug, Theme-specific, UX, Mobile, UI

#11155 Cleaned advanced contact tab
  src/Module/Contact/Advanced.php
  view/lang/C/messages.po
  view/templates/contact/advanced.tpl
  view/theme/frio/templates/contact/advanced.tpl
Labels: Enhancement, UI

#11158 Bump smarty/smarty from 3.1.40 to 3.1.43
  composer.lock
Labels: Security

#11161 Fix bidi support in shared posts
  src/Content/Text/BBCode.php
  view/templates/shared_content.tpl
Labels: Bug, UI

#11165 Remove "include/" folder from release-list
  mods/release-list-include.txt
Labels: Bug

#11164 Fix wrong default value in Module\Api\Friendica\Photo\Create::post
  src/Model/Photo.php
  src/Module/Api/Friendica/Photo/Create.php
Labels: Bug, API

#11166 Issue 10935: Improved "GROUP BY" handling
  src/Database/Database.php
  src/Module/Api/Friendica/Photo/Create.php
  src/Module/Update/Profile.php
  src/Worker/Notifier.php
Labels: Enhancement

#11167 missing "as" in string
  src/Content/Nav.php
  view/lang/C/messages.po
Labels: UI

#11168 Issue 8845: Signature support for "created" and "expires" added
  src/Util/HTTPSignature.php
Labels: Federation, Enhancement

#11171 DE, HU, SV and RU translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
  view/lang/sv/messages.po
  view/lang/sv/strings.php
Labels: Translation

#11173 Move last legacy API tests
  tests/Util/DateTimeFormatMockTrait.php
  tests/legacy/ApiTest.php
  tests/phpunit.xml
  tests/src/Core/ACLTest.php
  tests/src/Module/BaseApiTest.php
  tests/src/Security/BasicAuthTest.php
  tests/src/Util/ArraysTest.php
  tests/src/Util/DateTimeFormatTest.php
Labels: Enhancement

#11170 Lemmy support added
  src/Protocol/ActivityPub/Receiver.php
  src/Util/ParseUrl.php
Labels: Federation, Enhancement

#11174 Handle null value for last_used fields in TrustedBrowsers and AppSpecificPassword
  src/Module/Settings/TwoFactor/Trusted.php
  src/Security/TwoFactor/Model/AppSpecificPassword.php
Labels: Bug

#11176 RU translations THX Alexander An
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#11175 Improved handling of several object types
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/Diaspora.php
Labels: Federation, Enhancement

#11150 First support for user header banner image
  images/diaspora-banner.jpg
  images/friendica-banner.jpg
  src/Model/Contact.php
  src/Model/Photo.php
  src/Model/User.php
  src/Module/Photo.php
Labels: Enhancement, API

#11179 Fix Addons-Load for StorageManager
  src/Core/Storage/Repository/StorageManager.php
  tests/src/Core/Storage/Repository/StorageManagerTest.php
Labels: Bug

#11141 Add native language names to language selector & fix config during install
  src/Core/Config/Repository/Config.php
  src/Core/L10n.php
  src/Core/PConfig/Repository/PConfig.php
  tests/src/Core/Storage/Repository/StorageManagerTest.php
Labels: Bug, Enhancement, Translation, UI

#11183 Fix typo in URL
  doc/Developers-Intro.md
Labels: Bug, Docs

#11180 Desktop notification for announced posts
  src/Model/Post/UserNotification.php
  src/Navigation/Notifications/Factory/Notification.php
  view/lang/C/messages.po
Labels: Enhancement

#11184 DE, HU translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
Labels: Translation

#11185 Issue 10906: prevent personal notes from being altered
  mod/item.php
Labels: Bug, Privacy

#11186 Improve contact search speed / assume octet-stream on missing content type
  src/Module/Search/Acl.php
  src/Util/ParseUrl.php
Labels: Enhancement, Performance

#11187 SV update to the strings THX Kristoffer Grundström
  view/lang/sv/messages.po
  view/lang/sv/strings.php
Labels: Translation

#11191 IT translation update THX fabrixxm
  view/lang/it/messages.po
  view/lang/it/strings.php
Labels: Translation

#11190 Improved support for "Page" type
  src/Model/Post/Media.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Enhancement, API

#11192 Issue 11189: Fix notifications for new posts
  src/Navigation/Notifications/Factory/Notification.php
  view/lang/C/messages.po
Labels: Bug

#11194 [Database version 1449] Coalesce null values in post-content.body field of post-user-view view
  database.sql
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Bug, API

#11195 Issue 10966: Improved logging / reworked forum functionality
  src/Model/Item.php
  src/Network/Probe.php
Labels: Bug, Federation
