Repository friendica/friendica, pull requests merged in 2023-09, with the labels that each got.

#13396 Simplified context definitions
  static/security-data-integrity-v1.jsonld
  static/security-multikey-v1.jsonld
Labels: Bug, Federation

#13394 New functions for the language library
  src/Core/L10n.php
  src/Model/Item.php
  src/Model/User.php
  src/Module/Conversation/Channel.php
  src/Module/Settings/Display.php
Labels: Enhancement

#13395 Some more platform icons added
  src/Content/ContactSelector.php
Labels: Enhancement

#13404 Fixes the score calculation concerning the relation-cid / cid interaction
  database.sql
  doc/database/db_contact-relation.md
  src/Model/Contact/Relation.php
  src/Module/Conversation/Channel.php
  src/Worker/Cron.php
  static/dbstructure.config.php
  view/lang/C/messages.po
Labels: Bug

#13400 "Channel" is split into three classes
  doc/Accesskeys.md
  src/Content/Conversation/Collection/Channels.php
  src/Content/Conversation/Entity/Channel.php
  src/Content/Conversation/Factory/Channel.php
  src/Module/Conversation/Channel.php
  static/defaults.config.php
  view/lang/C/messages.po
Labels: Enhancement

#13407 The query condition for active users are unified
  mod/lostpass.php
  src/Model/Contact.php
  src/Model/Profile.php
  src/Model/User.php
  src/Module/Moderation/BaseUsers.php
  src/Module/Moderation/Users/Active.php
  src/Module/OStatus/PubSub.php
  src/Module/OStatus/PubSubHubBub.php
  src/Module/OStatus/Salmon.php
  src/Module/Profile/Profile.php
  src/Module/Security/OpenID.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Worker/Cron.php
  src/Worker/Directory.php
  src/Worker/ExpireAndRemoveUsers.php
  src/Worker/PollContacts.php
  src/Worker/UpdatePhotoAlbums.php
  src/Worker/UpdateScores.php
  tests/src/Model/UserTest.php
Labels: Enhancement

#13417 Network, Channels and Community are children of timeline
  src/Content/Conversation.php
  src/Content/Conversation/Collection/Timelines.php
  src/Content/Conversation/Entity/Timeline.php
  src/Content/Conversation/Factory/Channel.php
  src/Content/Conversation/Factory/Timeline.php
  src/Content/Nav.php
  src/Content/Widget.php
  src/DI.php
  src/Module/BaseSettings.php
  src/Module/Conversation/Channel.php
  src/Module/Conversation/Community.php
  src/Module/Conversation/Network.php
  src/Module/Conversation/Timeline.php
  src/Module/Settings/Display.php
  src/Module/Update/Channel.php
  src/Module/Update/Community.php
  src/Module/Update/Network.php
  static/routes.config.php
  tests/src/Model/UserTest.php
  view/lang/C/messages.po
  view/templates/settings/display.tpl
  view/templates/widget/filter.tpl
  view/theme/frio/templates/settings/display.tpl
  view/theme/quattro/templates/widget/filter.tpl
Labels: Enhancement

#13438 "cascade" for "post-engagement" / fixes for "report" definition
  database.sql
  doc/database/db_report.md
  src/Database/DBA.php
  src/Database/DBStructure.php
  src/Module/BaseModeration.php
  src/Module/Moderation/Reports.php
  static/dbstructure.config.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/moderation/report/overview.tpl
Labels: Enhancement

#13442 Channel frequency rules can now be set for each contact
  database.sql
  doc/database/db_post-thread-user.md
  doc/database/db_report.md
  doc/database/db_user-contact.md
  src/Database/DBStructure.php
  src/Model/Contact/User.php
  src/Module/Contact/Profile.php
  src/Module/Conversation/Channel.php
  src/Module/Conversation/Community.php
  src/Module/Conversation/Network.php
  src/Module/Conversation/Timeline.php
  src/Module/Update/Channel.php
  src/Module/Update/Community.php
  src/Module/Update/Network.php
  static/dbstructure.config.php
  static/defaults.config.php
  view/js/main.js
  view/lang/C/messages.po
  view/templates/contact_edit.tpl
  view/theme/frio/templates/contact_edit.tpl
Labels: New Feature

#13446 Use channels for non public content
  database.sql
  doc/database/db_post-engagement.md
  src/Model/Item.php
  src/Model/Post.php
  src/Model/Post/Engagement.php
  src/Module/Contact/Profile.php
  src/Module/Conversation/Timeline.php
  src/Protocol/Relay.php
  static/dbstructure.config.php
  view/lang/C/messages.po
Labels: Enhancement

#13451 Avoid jumps in the timeline after "received" has been selected
  src/Module/Conversation/Network.php
Labels: Bug, UX

#13449 Fix missing closing tag + updated links.
  doc/FAQ-admin.md
  doc/de/FAQ-admin.md
Labels: Docs, Enhancement

#13464 Restore attendance icons in event posts
  src/Model/Item.php
Labels: Bug

#13465 Avoid quoting the own post
  src/Content/Item.php
  src/Content/Text/Plaintext.php
  src/Model/Item.php
  src/Model/Post/Media.php
  src/Model/Post/UserNotification.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#13463 Rework image grid to horizontal masonry, allocate space for images to load
  src/Model/Item.php
  src/Model/Post/Media.php
  src/Model/Profile.php
  src/Module/Photo.php
  view/global.css
  view/templates/content/image.tpl
  view/templates/content/image_grid.tpl
  view/theme/frio/scheme/black.css
  view/theme/frio/scheme/dark.css
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: Enhancement, UI

#13469 Revert pull request #13463
  src/Model/Item.php
  src/Model/Post/Media.php
  src/Model/Profile.php
  src/Module/Photo.php
  view/global.css
  view/templates/content/image.tpl
  view/templates/content/image_grid.tpl
  view/theme/frio/scheme/black.css
  view/theme/frio/scheme/dark.css
Labels: Bug

#13473 There is now a time limit when fetching AP endpoints
  src/Core/Worker.php
  src/Protocol/ActivityPub.php
Labels: Enhancement, Performance

#13477 [frio] add styling to event reminder
  view/theme/frio/css/style.css
Labels: Theme-specific, Enhancement, UI

#13479 Add Google-Extended to default robots.txt
  src/Module/RobotsTxt.php
Labels: Enhancement, Privacy

#13482 [frio] Fix undefined Javascript function contains
  view/theme/frio/templates/jot-header.tpl
Labels: Bug, Theme-specific, UX
