Repository friendica/friendica, pull requests merged in 2023-06, with the labels that each got.

#13187 resolves #13180, changed "Foren" to "Gruppen" in german translation
  doc/Forums.md
  doc/de/FAQ-admin.md
  doc/de/FAQ.md
  doc/de/Forums.md
  doc/de/Home.md
  doc/de/Install.md
  doc/de/Making-Friends.md
  doc/de/Quick-Start-groupsandpages.md
Labels: Docs, Enhancement

#13188 Improved profile summary for notifications
  src/Model/Post/UserNotification.php
Labels: Bug

#13190 Fix wrong CSS class name after renaming "forum" to "group"
  view/global.css
Labels: Bug

#13194 Language check moved to a separate function
  src/Contact/Avatar.php
  src/Content/Text/BBCode.php
  src/Content/Text/Plaintext.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Protocol/Relay.php
Labels: Enhancement

#13197 translation updates
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/fi-fi/messages.po
  view/lang/fi-fi/strings.php
Labels: Translation

#13196 [frio] New Group button on group widget
  src/Content/GroupManager.php
  view/lang/C/messages.po
  view/templates/widget/group_list.tpl
  view/theme/frio/css/style.css
  view/theme/smoothly/style.css
  view/theme/vier/style.css
Labels: New Feature, Theme-specific, UI

#13203 Remove the "www." from the styled URL
  src/Util/Strings.php
Labels: Enhancement

#13204 [frio] Remove reference to nonexistent CSS file
  view/theme/frio/templates/head.tpl
Labels: Bug, Theme-specific

#13218 [frio] Added content warning button
  src/Content/Conversation.php
  src/Module/Item/Compose.php
  src/Object/Post.php
  view/lang/C/messages.po
  view/templates/item/compose.tpl
  view/theme/frio/templates/comment_item.tpl
  view/theme/frio/templates/jot.tpl
Labels: Theme-specific, UX

#13223 fix issue #13174
  src/Module/Magic.php
  tests/src/Util/HTTPSignatureTest.php
Labels: Bug, Federation

#13229 Fix Mastodon API Status->Context endpoint so doesn't return deleted statuses
  src/Module/Api/Mastodon/Statuses/Context.php
Labels: Enhancement, API

#13226 Better support for "audience" / simplified Lemmy processing
  database.sql
  mod/photos.php
  src/Content/Conversation.php
  src/Content/GroupManager.php
  src/Content/Item.php
  src/Content/Text/HTML.php
  src/Content/Widget.php
  src/Content/Widget/ContactBlock.php
  src/Content/Widget/VCard.php
  src/Model/APContact.php
  src/Model/Contact.php
  src/Model/Event.php
  src/Model/Item.php
  src/Model/Tag.php
  src/Module/Contact.php
  src/Module/Contact/Unfollow.php
  src/Module/Magic.php
  src/Object/Post.php
  src/Protocol/ActivityPub/Delivery.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
  static/dbstructure.config.php
  static/dbview.config.php
  view/lang/C/messages.po
Labels: Federation, Enhancement

#13230 Fix warnings because of missing field
  database.sql
  src/Model/Contact.php
  src/Model/Item.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Bug

#13231 Fiy typo in author-alias
  src/Content/Item.php
Labels: Bug, UI

#13234 Fix: Unseen marker wasn't set / Don't mark activities as unseen
  src/Model/Post/User.php
  src/Module/Conversation/Network.php
Labels: Bug, UX, Enhancement

#13233 Add Vary header in case of content negotiation
  src/Module/ActivityPub/Objects.php
  src/Module/Friendica.php
  src/Module/Item/Display.php
  src/Module/Profile/Profile.php
  src/Module/Xrd.php
Labels: Enhancement

#13235 Dedicated circle name for groups
  src/Content/Item.php
  src/Model/Circle.php
  src/Model/Contact.php
  src/Model/User.php
  src/Module/Conversation/Network.php
  src/Module/Settings/Account.php
  src/Protocol/ActivityPub/Processor.php
  view/lang/C/messages.po
  view/templates/circle_selection.tpl
  view/templates/settings/account.tpl
  view/theme/frio/templates/settings/account.tpl
Labels: New Feature

#13238 Issue 13221: Diaspora posts are now stored correctly
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#13237 Added group detection for via exclusive mentions
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement

#13244 "kbin" now has got an own section in the federation statistics
  src/Module/Admin/Federation.php
Labels: Enhancement
