Repository friendica/friendica, pull requests merged in 2023-04, with the labels that each got.

#12966 Fix a couple of namespace issues
  composer.json
  composer.lock
  src/Core/Worker/Repository/Process.php
  src/Model/User.php
Labels: Bug

#12969 Use new codecov uploader
  .woodpecker/.phpunit.yml
Labels: Enhancement

#12967 Adapt logging & temppath creation
  src/Core/System.php
Labels: Installation, Enhancement

#12968 Make conversation activity singular/plural translatable
  src/Content/Conversation.php
  view/lang/C/messages.po
Labels: Enhancement, Translation

#12972 Address a couple of fatal errors
  src/Model/Item.php
Labels: Bug

#12971 Account for null title when instantiating FriendicaExtension in Factory\Api\Mastodon\Status
  src/Factory/Api/Mastodon/Status.php
  src/Object/Api/Mastodon/Status/FriendicaExtension.php
Labels: Bug, API

#12973 Fix DateTimeFormat issue
  src/Util/DateTimeFormat.php
  tests/src/Util/DateTimeFormatTest.php
Labels: Bug

#12976 NPF functionality added
  composer.json
  composer.lock
  src/Content/Text/BBCode.php
  src/Content/Text/NPF.php
  src/Model/Post/Media.php
Labels: New Feature

#12978 Issue 12977: Ensure to fetch quoted posts
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, Federation

#12981 Don't perform BasicAuth on public endpoints
  src/Module/BaseApi.php
Labels: Enhancement, API

#12982 update translations for 2023.03
  view/lang/ar/messages.po
  view/lang/ar/strings.php
  view/lang/bg/messages.po
  view/lang/bg/strings.php
  view/lang/ca/messages.po
  view/lang/ca/strings.php
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/da-dk/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/eo/messages.po
  view/lang/eo/strings.php
  view/lang/es/messages.po
  view/lang/es/strings.php
  view/lang/et/messages.po
  view/lang/et/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/gd/messages.po
  view/lang/gd/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
  view/lang/is/messages.po
  view/lang/is/strings.php
  view/lang/it/messages.po
  view/lang/it/strings.php
  view/lang/ja/messages.po
  view/lang/ja/strings.php
  view/lang/nl/messages.po
  view/lang/nl/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
  view/lang/sv/messages.po
  view/lang/sv/strings.php
Labels: Translation

#12984 [frio] Add Dropzone dictionary strings to l10n
  src/App/Page.php
  view/js/dropzone-factory.js
  view/lang/C/messages.po
  view/templates/head.tpl
  view/theme/frio/templates/head.tpl
  view/theme/frio/templates/js_strings.tpl
Labels: Bug, Theme-specific, Translation

#12991 Fixed check for likes in notification mail
  src/Navigation/Notifications/Repository/Notify.php
Labels: Bug

#12989 Fixes "Trying to access array offset on value of type bool"
  src/Factory/Api/Mastodon/Attachment.php
Labels: Bug

#12988 Fix Diaspora signature creation for comments on comments
  src/Protocol/Diaspora.php
Labels: Bug, Federation

#12992 Replace the Diaspora signature upon update
  src/Model/Item.php
Labels: Bug, Federation

#12987 regen CREDITS for the next release
  CREDITS.txt
Labels: Docs

#12996 Fix: Attached images from Lemmy can now be processed
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, Federation

#13001 [vier] Remove duplicate variable declaration
  view/templates/head.tpl
Labels: Bug, Theme-specific, UX

#13004 Fixes warning: Undefined array key "pending"
  src/Navigation/Notifications/Factory/FormattedNavNotification.php
Labels: Bug

#13008 remove scrollbar from dropzone in jot too fixes #13002
  view/theme/frio/templates/jot.tpl
Labels: Bug, Theme-specific, UI

#13009 [frio] Fix jS error that was preventing further script execution in theme settings
  view/theme/frio/templates/theme_settings.tpl
Labels: Bug, Theme-specific, UX

#13010 Harmonize Youtube/Vimeo-Link behaviour
  src/Content/Text/BBCode.php
Labels: UX, Enhancement

#13012 Fix: Only add link preview for selected networks
  src/Model/Post/Media.php
Labels: UX, Enhancement

#13014 [Composer] Update dependencies ahead of release
  composer.lock
Labels: Enhancement

#13017 FR, HU and RU translation updates
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#12954 Filter contact search by blocked remote domains
  src/Core/Search.php
  src/Module/BaseSearch.php
  src/Object/Search/ContactResult.php
  view/lang/C/messages.po
  view/templates/contact/list.tpl
  view/theme/frio/templates/contact/list.tpl
Labels: Bug

#13018 Only share from federated posts
  src/Module/Post/Share.php
  src/Object/Post.php
Labels: Federation, Enhancement

#13019 Move calls to json_encode from Smarty templates to variable lists
  src/Core/ACL.php
  view/templates/acl/full_selector.tpl
  view/templates/acl/message_recipient.tpl
Labels: Bug

#12985 2023.04 CHANGELOG file
  CHANGELOG
Labels: Docs

#13028 Separate JSON output of contact lists in message_recipient template
  src/Core/ACL.php
  view/templates/acl/message_recipient.tpl
Labels: Bug

#13000 Store "audience" and "attributedTo" data
  src/Content/Conversation.php
  src/Model/Item.php
  src/Model/Tag.php
  src/Module/PermissionTooltip.php
  src/Protocol/ActivityPub/ClientToServer.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  view/lang/C/messages.po
Labels: Federation, Enhancement

#13033 AR, CA, CS, DE, ES, FR, GD, HU, IT, JA, NL, PL, RU translation updates
  view/lang/ar/messages.po
  view/lang/ar/strings.php
  view/lang/ca/messages.po
  view/lang/ca/strings.php
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/es/messages.po
  view/lang/es/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/gd/messages.po
  view/lang/gd/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
  view/lang/it/messages.po
  view/lang/it/strings.php
  view/lang/ja/messages.po
  view/lang/ja/strings.php
  view/lang/nl/messages.po
  view/lang/nl/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#13046 Fix link to user category in label
  src/Content/Item.php
Labels: Bug, UX

#13049 [frio] Show post privacy scope in mobile view
  view/theme/frio/templates/wall_thread.tpl
Labels: Bug, Theme-specific, UI

#13047 Account for null value in Entity\Notify->msg
  src/Navigation/Notifications/Entity/Notify.php
  src/Navigation/Notifications/Factory/FormattedNotify.php
Labels: Bug

#13048 Wrap last remaining system.maximagesize config retrieval in Strings::getBytesFromShorthand call
  src/Module/Api/Mastodon/InstanceV2.php
Labels: Bug

#13051 "audience" is set for forum posts / followers posts are directed to the followers collection
  src/Model/Group.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Federation, Enhancement

#13059 Issue 13058: BasicAuth can now be disabled
  src/Security/BasicAuth.php
  static/defaults.config.php
Labels: Enhancement
