Repository friendica/friendica, pull requests merged in 2023-05, with the labels that each got.

#13065 Rename tests/src/Util/AclFormatter file to match class name
  tests/src/Util/ACLFormatterTest.php
Labels: Bug

#13067 Issue 13052: The limit parameter now behaves like the Mastodon counterpart
  src/Module/Api/Mastodon/Notifications.php
Labels: Bug, API

#13066 Issue 13041: API activities for reshared posts are now performed on the original posts
  src/Factory/Api/Mastodon/StatusSource.php
  src/Model/Post.php
  src/Module/Api/Mastodon/Statuses.php
  src/Module/Api/Mastodon/Statuses/Bookmark.php
  src/Module/Api/Mastodon/Statuses/Card.php
  src/Module/Api/Mastodon/Statuses/Context.php
  src/Module/Api/Mastodon/Statuses/Favourite.php
  src/Module/Api/Mastodon/Statuses/FavouritedBy.php
  src/Module/Api/Mastodon/Statuses/Mute.php
  src/Module/Api/Mastodon/Statuses/Pin.php
  src/Module/Api/Mastodon/Statuses/Reblog.php
  src/Module/Api/Mastodon/Statuses/RebloggedBy.php
  src/Module/Api/Mastodon/Statuses/Unbookmark.php
  src/Module/Api/Mastodon/Statuses/Unfavourite.php
  src/Module/Api/Mastodon/Statuses/Unmute.php
  src/Module/Api/Mastodon/Statuses/Unpin.php
  src/Module/Api/Mastodon/Statuses/Unreblog.php
Labels: Bug, API

#13068 Improved fetching of attached activities
  src/Factory/Api/Mastodon/Status.php
  src/Model/Item.php
  src/Module/Media/Photo/Upload.php
Labels: Enhancement

#13070 change test for navigator.share - fixes #13054
  view/theme/frio/js/theme.js
Labels: Theme-specific, Enhancement

#13076 Add Fancybox to the core
  src/Model/Item.php
  src/Model/Post/Media.php
  view/js/fancybox/README.md
  view/js/fancybox/fancybox.config.js
  view/js/fancybox/jquery.fancybox.css
  view/js/fancybox/jquery.fancybox.js
  view/js/fancybox/jquery.fancybox.min.css
  view/js/fancybox/jquery.fancybox.min.js
  view/templates/content/image.tpl
  view/templates/head.tpl
  view/theme/frio/js/modal.js
  view/theme/frio/templates/head.tpl
  view/theme/vier/dark.css
  view/theme/vier/mobile.css
Labels: UX, Enhancement

#13084 The Emojipicker is added to Frio for new posts
  src/Content/Conversation.php
  src/Module/Post/Edit.php
  src/Object/Post.php
  view/js/vanillaEmojiPicker/LICENSE
  view/js/vanillaEmojiPicker/README.md
  view/js/vanillaEmojiPicker/index.html
  view/js/vanillaEmojiPicker/indextest.html
  view/js/vanillaEmojiPicker/screenshot.png
  view/js/vanillaEmojiPicker/vanillaEmojiPicker.js
  view/js/vanillaEmojiPicker/vanillaEmojiPicker.min.js
  view/lang/C/messages.po
  view/templates/item/compose.tpl
  view/theme/frio/templates/head.tpl
  view/theme/frio/templates/jot.tpl
Labels: New Feature, Theme-specific, UX

#13088 Introduce settings for overriding php.ini values
  src/App.php
  static/defaults.config.php
Labels: Installation, Enhancement

#13090 improve OpenWebAuth client support
  src/Module/Magic.php
Labels: Federation, Enhancement

#13092 Fixes #13082
  view/js/dropzone-factory.js
Labels: UX, Enhancement

#13093 The emoji selector is now available for comments
  view/templates/item/compose.tpl
  view/theme/frio/templates/comment_item.tpl
  view/theme/frio/templates/head.tpl
  view/theme/frio/templates/jot.tpl
Labels: UX, Enhancement

#13094 Support for feeds that follow the ATOM 0.3 specification
  src/Protocol/ActivityNamespace.php
  src/Protocol/Feed.php
Labels: Federation, Enhancement

#13095 Improved ATOM distinction, added OPML
  src/Model/Conversation.php
  src/Protocol/Feed.php
Labels: Federation, Enhancement

#13096 Added host check on xrd request
  src/Module/Xrd.php
Labels: Federation, Enhancement

#13097 Vier: The emojipicker is now integrated
  view/templates/head.tpl
  view/templates/jot.tpl
  view/theme/vier/style.css
  view/theme/vier/templates/comment_item.tpl
Labels: Theme-specific, UX, Enhancement

#13101 Fix: Feeds had been imported with the wrong body
  src/Protocol/Feed.php
Labels: Bug, Federation

#13099 Address several warnings
  src/Model/GServer.php
  src/Module/Hashtag.php
  src/Protocol/Feed.php
Labels: Bug

#13100 Wrap HTTP client call in try catch in Network\Probe
  src/Network/Probe.php
Labels: Bug

#13103 Improved preview size
  src/Model/Photo.php
  src/Model/Post/Media.php
  src/Module/Item/Compose.php
  src/Module/Media/Photo/Upload.php
  src/Module/Profile/Photos.php
  view/lang/C/messages.po
Labels: UX, Enhancement

#13110 [frio] Changed mobile icon for sidebar
  view/theme/frio/templates/nav.tpl
Labels: Theme-specific, Enhancement, UI

#13113 Ensure that the baseurl return value is a string
  mod/message.php
  src/Content/Smilies.php
  src/Model/Photo.php
  src/Model/User.php
  src/Module/HCard.php
  src/Module/OpenSearch.php
  src/Module/Register.php
  src/Module/WellKnown/HostMeta.php
  src/Protocol/ActivityPub/Transmitter.php
  view/theme/frio/php/default.php
  view/theme/smoothly/theme.php
  view/theme/vier/theme.php
Labels: Enhancement

#13116 Remove misleading concatenation in XPath expression in Protocol\Feed
  src/Protocol/Feed.php
Labels: Bug

#13118 DB encapsulations
  src/Core/Update.php
  src/Core/Worker/Cron.php
  src/Database/DBA.php
  src/Database/DBStructure.php
  src/Database/Database.php
  src/Database/DatabaseException.php
  src/Federation/Repository/DeliveryQueueItem.php
  src/Model/Post/Delivery.php
  src/Model/Post/DeliveryData.php
  src/Protocol/ActivityPub/Queue.php
  src/Worker/Cron.php
  src/Worker/OptimizeTables.php
  tests/datasets/api.fixture.php
  tests/src/Database/DatabaseTest.php
Labels: Enhancement

#13123 Escape notification text in /notifications module
  view/templates/notifications/notification.tpl
Labels: Bug, Security

#13125 Escape message for notifications
  src/Navigation/Notifications/Entity/Notify.php
  tests/src/Navigation/Notifications/Entity/NotifyTest.php
Labels: Bug, Security

#13128 OWA: reworked code
  src/Module/Magic.php
Labels: Federation, Enhancement

#13124 fix for probe loop in case that network of contact has changed
  src/Model/Contact.php
Labels: Bug, Performance

#13115 Fix: Contacts can now be searched with a leading @ again.
  src/Core/Search.php
  src/Module/BaseSearch.php
  view/lang/C/messages.po
Labels: Bug

#13133 Unify the heading levels
  src/Content/Text/BBCode.php
  tests/src/Content/Text/BBCodeTest.php
Labels: Federation, Enhancement

#13131 Replace "Probe::isProbable" with "Protocol::supportsProbe"
  src/Core/Protocol.php
  src/Model/Contact.php
Labels: Enhancement

#13135 Fix magic links in contact photo menu
  src/Content/Item.php
  src/Model/Contact.php
Labels: Bug

#13107 Unifiy the creation of photo links
  mod/photos.php
  src/Content/Text/HTML.php
  src/Model/Post/Media.php
  src/Module/Media/Photo/Upload.php
  src/Module/Profile/Photos.php
  src/Util/Images.php
Labels: Enhancement

#13137 PL translation update THX tatonuta
  view/lang/pl/messages.po
  view/lang/pl/strings.php
Labels: Translation

#13139 Logging for an exception when processing activities
  database.sql
  src/Protocol/ActivityPub/Receiver.php
  view/lang/C/messages.po
Labels: Enhancement

#13140 Fix: Prevent an endless loop when fetching quoted content
  src/Factory/Api/Mastodon/Status.php
  view/lang/C/messages.po
Labels: Bug

#13142 Add menu entry to directly collapse posts
  mod/item.php
  src/App/Page.php
  src/Object/Post.php
  view/lang/C/messages.po
  view/theme/frio/js/textedit.js
  view/theme/frio/templates/js_strings.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: New Feature, Enhancement

#13143 Support special characters in category widget links
  src/Content/Widget.php
Labels: Bug

#13144 Update tag cloud link to conversations
  src/Content/Widget/TagCloud.php
Labels: Bug

#13145 Refer to correct contact field in Core/Search
  src/Core/Search.php
Labels: Bug

#13147 [frio] Remove scrollbars from preview close button and restore pointer cursor
  view/theme/frio/css/dropzone.frio.css
  view/theme/frio/css/dropzone.min.frio.css
Labels: Bug, Theme-specific

#13146 Move current table property from PDOStatement to Database class
  src/Database/Database.php
Labels: Bug

#13154 Updated HU translation
  view/lang/hu/messages.po
  view/lang/hu/strings.php
Labels: Translation

#13155 updating Transifex URL
  CONTRIBUTING.md
  doc/translations.md
Labels: Docs

#13132 Updated the CHANGELOG file
  CHANGELOG
Labels: Docs

#13160 Remove direct call to is_string() from templates
  view/templates/settings/addons/connector.tpl
  view/templates/settings/addons/panel.tpl
  view/theme/frio/templates/settings/addons/connector.tpl
  view/theme/frio/templates/settings/addons/panel.tpl
Labels: Bug

#13161 Support for Bluesky reshares in the core
  src/Model/Item.php
  src/Object/Post.php
Labels: Enhancement

#13163 Add support for reverse proxy to system.force_ssl feature
  src/App.php
Labels: Bug

#13169 Remove support for user.parent-uid = 0
  database.sql
  src/Model/User.php
  src/Module/Delegation.php
  src/Module/Settings/Delegation.php
  static/dbstructure.config.php
  tests/src/Model/UserTest.php
  update.php
Labels: Enhancement

#13176 Restore is_string() as a Smarty modifier
  src/Render/FriendicaSmarty.php
  view/templates/settings/addons/panel.tpl
  view/theme/frio/templates/settings/addons/panel.tpl
Labels: Bug

#13177 Pass the "uid" when calling the "follow" hook
  src/Model/Contact.php
Labels: Bug
