Repository friendica/friendica, pull requests merged in 2023-03, with the labels that each got.

#12836 [frio] Use all available space for post interaction buttons (mobile)
  view/theme/frio/css/style.css
  view/theme/frio/templates/wall_thread.tpl
Labels: Theme-specific, Enhancement, UI

#12861 API: Fix dateformat on status
  src/Object/Api/Mastodon/Account.php
  src/Object/Api/Mastodon/Status.php
  src/Object/Api/Mastodon/Status/FriendicaExtension.php
Labels: Bug, API

#12865 Fix missing attached links in posts
  src/Factory/Api/Mastodon/Status.php
  src/Factory/Api/Twitter/Status.php
  src/Model/Post/Media.php
  src/Module/Post/Edit.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  src/Worker/Notifier.php
Labels: Bug, Federation

#12866 The function "getAttachedData" has been removed
  src/Content/Item.php
  src/Content/Text/BBCode.php
  src/Content/Text/Plaintext.php
  src/Factory/Api/Mastodon/Card.php
  src/Model/Post/Media.php
  src/Protocol/Diaspora.php
  src/Protocol/Feed.php
Labels: Enhancement

#12867 Fix plaintext function by partly reverting function removal
  src/Content/Text/BBCode.php
  src/Content/Text/Plaintext.php
Labels: Bug

#12875 Use the built in function to create a query string
  src/Security/OAuth1/OAuthUtil.php
Labels: Enhancement

#12878 Mastodon edit title spoiler update
  src/Module/Api/Mastodon/Statuses.php
Labels: Enhancement, API

#12882 Cast the base URL as string in /friendica/json
  src/Module/Friendica.php
Labels: Bug, API

#12879 [Database 1517] Increase the size of the process.hostname field
  database.sql
  doc/database/db_process.md
  static/dbstructure.config.php
Labels: Bug

#12889 "edited_at" must only be displayed when the entry had been updated
  src/Object/Api/Mastodon/Status.php
Labels: Bug, API

#12854 Adding and removing of pictures via API is now possible
  src/Factory/Api/Mastodon/Attachment.php
  src/Factory/Api/Mastodon/StatusSource.php
  src/Model/Post/Media.php
  src/Module/Api/Mastodon/Media.php
  src/Module/Api/Mastodon/Statuses.php
Labels: New Feature, API

#12877 [frio] Like buttons improvement
  src/App/Page.php
  view/lang/C/messages.po
  view/theme/frio/js/theme.js
  view/theme/frio/templates/js_strings.tpl
  view/theme/frio/templates/like_noshare.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: Theme-specific, Enhancement, UI

#12891 More reliable system variables
  src/Core/System.php
  src/Core/Worker.php
Labels: Enhancement

#12893 Improved handling of images with links
  src/Model/Post/Media.php
Labels: Bug

#12894 Fix tag and mention updates in Mastodon status edit endpoint
  src/Module/Api/Mastodon/Statuses.php
Labels: Bug, API

#12896 Fix being able to change/remove attached links.
  src/Module/Api/Mastodon/Statuses.php
Labels: Enhancement, API

#12895 Fix being able to remove all images from post through Mastodon editing
  src/Module/Api/Mastodon/Statuses.php
Labels: Bug, API

#12899 Fix custom CSS examples in BBCode doc
  doc/BBCode.md
  doc/de/BBCode.md
Labels: Bug

#12900 HTML: Use paragraphs instead of double line breaks
  src/Content/Text/BBCode.php
  src/Factory/Api/Twitter/Status.php
  tests/src/Content/Text/BBCodeTest.php
  tests/src/Factory/Api/Twitter/StatusTest.php
Labels: Enhancement

#12903 Fix Mastodon InstanceV2 structure needs image max size under mediaAttachment
  src/Module/Api/Mastodon/InstanceV2.php
  src/Object/Api/Mastodon/InstanceV2/Configuration.php
  src/Object/Api/Mastodon/InstanceV2/MediaAttachmentsConfig.php
Labels: Bug, API

#12904 Fix paging on mastodon timeline and status endpoints
  src/Module/Api/Mastodon/Accounts/Statuses.php
  src/Module/Api/Mastodon/Timelines/ListTimeline.php
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
Labels: Enhancement, API

#12905 Issue 12858: Peertube avatars can now be fetched
  src/Model/APContact.php
  src/Util/Images.php
Labels: Bug

#12906 Issue 12870: Support for zmg elements from Hubzilla
  src/Content/Text/BBCode.php
Labels: Bug, Federation

#12907 Issue 12863: Convert Hubzilla mentions to Friendica mentions
  src/Protocol/ActivityPub/Processor.php
Labels: Bug, Federation

#12908 Takahē and Wildebeest added, Nomad detection improved
  src/Model/GServer.php
  src/Module/Admin/Federation.php
Labels: Enhancement

#12909 Simplified Nomad detection
  src/Model/GServer.php
Labels: Federation, Enhancement, Performance

#12910 Blocked servers can now be deleted
  src/Worker/UpdateBlockedServers.php
  static/defaults.config.php
Labels: New Feature

#12912 Fix cant remove attachment
  src/Model/Item.php
  view/js/linkPreview.js
Labels: Bug

#12913 Fix posting/editing empty text image posts through Mastodon API
  src/Model/Item.php
Labels: Bug

#12898 Ensure FactorySession->create returns an object no matter what
  src/Core/Session/Factory/Session.php
  static/dependencies.config.php
  tests/src/Core/KeyValueStorage/DBKeyValueStorageTest.php
Labels: Bug

#12914 Rework new lines around list BBCode
  src/Content/Text/BBCode.php
  src/Content/Text/HTML.php
  tests/src/Content/Text/BBCodeTest.php
  tests/src/Content/Text/HTMLTest.php
Labels: Bug

#12892 Prevent template generation in media/[photo|attachment]/upload output
  src/Module/Media/Attachment/Upload.php
  src/Module/Media/Photo/Upload.php
Labels: Bug

#12915 Force correct string casting for BaseUrl
  src/Model/Profile.php
Labels: Bug

#12883 [frio] Easy image attach
  composer.json
  composer.lock
  mod/photos.php
  src/App/Page.php
  view/js/dropzone-factory.js
  view/templates/item/compose.tpl
  view/theme/frio/css/dropzone.frio.css
  view/theme/frio/css/dropzone.min.frio.css
  view/theme/frio/js/modal.js
  view/theme/frio/templates/comment_item.tpl
  view/theme/frio/templates/head.tpl
  view/theme/frio/templates/jot.tpl
Labels: New Feature, Theme-specific, UX

#12916 Adapt loglevels to reduce log-noise
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
Labels: Enhancement

#12917 Remove tabs if followed by new lines (or vice versa)
  src/Content/Text/BBCode.php
  tests/src/Content/Text/BBCodeTest.php
Labels: Enhancement

#12920 Issue 12701: Fix Markdown problems with Quotes
  src/Content/Text/BBCode.php
  tests/src/Content/Text/BBCodeTest.php
Labels: Bug

#12922 Fetch platform and version of nomad implementations
  src/Model/GServer.php
  src/Module/Admin/Federation.php
Labels: Enhancement

#12921 Add visibility to user's statuses in Mastodon API
  src/Factory/Api/Mastodon/Status.php
  src/Object/Api/Mastodon/Status/FriendicaExtension.php
  src/Object/Api/Mastodon/Status/FriendicaVisibility.php
Labels: Enhancement, API

#12927 Handles warning: Undefined array key "gravity"
  src/Module/Post/Edit.php
Labels: Bug

#12946 Set different permissions for comments via API
  src/Content/Item.php
  src/Model/Item.php
  src/Module/Api/Mastodon/Statuses.php
Labels: Enhancement, API

#12947 Documentation: installation on Unraid, Ubuntu 22.04 and systemd, troubleshooting, link updates
  doc/Improve-Performance.md
  doc/Install.md
  doc/de/FAQ-admin.md
  doc/de/Improve-Performance.md
Labels: Docs

#12950 Return `disliked` in Mastodon API
  doc/API-Friendica.md
  doc/API-Mastodon.md
  src/Factory/Api/Mastodon/Status.php
  src/Object/Api/Mastodon/Status/FriendicaExtension.php
Labels: New Feature, API

#12949 Disable setting fields in case we use environment variables
  .woodpecker/.phpunit.yml
  src/Core/Config/Capability/IManageConfigValues.php
  src/Core/Config/Model/DatabaseConfig.php
  src/Core/Config/Model/ReadOnlyFileConfig.php
  src/Core/Config/ValueObject/Cache.php
  src/Module/Admin/Logs/Settings.php
  src/Module/Admin/Site.php
  src/Module/Admin/Storage.php
  tests/Util/VFSTrait.php
  tests/src/Core/Config/ConfigTest.php
  view/lang/C/messages.po
  view/templates/admin/storage.tpl
  view/templates/field_select.tpl
  view/theme/frio/templates/admin/storage.tpl
  view/theme/frio/templates/field_select.tpl
Labels: Bug, Enhancement

#12956 Don't search for contacts on blocked or failed systems
  database.sql
  src/Core/Search.php
  src/Model/Contact.php
  src/Module/Api/Mastodon/Accounts/Search.php
  src/Module/Api/Mastodon/Search.php
  static/dbstructure.config.php
  static/dbview.config.php
  update.php
Labels: UX, Enhancement

#12960 Add posix_kill() SIGTERM for Friendica
  bin/daemon.php
Labels: Enhancement

#12952 Address a few fatal errors
  src/Core/Session/Capability/IHandleUserSessions.php
  src/Core/Session/Model/UserSession.php
  src/Factory/Api/Mastodon/Relationship.php
  src/Model/Profile.php
  src/Module/Contact/Follow.php
  src/Module/Profile/Contacts.php
  src/Object/Api/Mastodon/Relationship.php
  src/Security/Authentication.php
Labels: Bug

#12963 Fix some warnings
  src/Module/Api/Mastodon/Statuses.php
  src/Protocol/ActivityPub/ClientToServer.php
Labels: Bug

#12964 Add receiver name extraction case
  src/Protocol/ActivityPub/Processor.php
Labels: Bug
