Repository friendica/friendica, pull requests merged in 2023-01, with the labels that each got.

#12587 The inbox-status can now be archived for a whole server
  database.sql
  doc/database/db_inbox-status.md
  src/Core/Worker/Cron.php
  src/Database/PostUpdate.php
  src/Model/APContact.php
  src/Model/GServer.php
  src/Util/HTTPSignature.php
  src/Worker/Notifier.php
  static/dbstructure.config.php
Labels: Federation, Enhancement

#12592 Set the server status directly after transmission
  src/Core/Worker/Cron.php
  src/Model/GServer.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Util/HTTPSignature.php
Labels: Federation, Enhancement

#12596 Checks if the Photo order argument is a valid column
  mod/photos.php
Labels: Bug

#12562 Ward againt contact_id = 0 in UpdateContact worker
  src/Model/Contact.php
  src/Module/Contact.php
  src/Module/Photo.php
  src/Worker/UpdateContact.php
  src/Worker/UpdateContacts.php
Labels: Bug

#12589 Address a few warnings in Search\Acl
  src/Core/Search.php
  src/Module/Search/Acl.php
Labels: Bug

#12586 Add Entity-Factory-Repository for deliver-queue
  src/Core/Worker/Cron.php
  src/DI.php
  src/Database/DBA.php
  src/Federation/Collection/DeliveryQueueAggregates.php
  src/Federation/Collection/DeliveryQueueItems.php
  src/Federation/Entity/DeliveryQueueAggregate.php
  src/Federation/Entity/DeliveryQueueItem.php
  src/Federation/Factory/DeliveryQueueItem.php
  src/Federation/Repository/DeliveryQueueItem.php
  src/Protocol/Delivery.php
  src/Worker/BulkDelivery.php
  src/Worker/Notifier.php
Labels: Enhancement

#12597 Don't distribute unsigned remote activities
  src/Worker/Notifier.php
Labels: Federation, Enhancement

#12585 Remove obsolete OExchange module and reference
  mod/oexchange.php
  src/Core/System.php
  src/Module/Api/ApiResponse.php
  src/Module/OpenSearch.php
  src/Module/ReallySimpleDiscovery.php
  src/Module/WellKnown/HostMeta.php
  src/Module/Xrd.php
  src/Protocol/Diaspora.php
  src/Protocol/Salmon.php
  src/Util/XML.php
Labels: Enhancement

#12593 Replace `config` with `node.config.php`
  bin/daemon.php
  database.sql
  doc/database.md
  doc/database/db_config.md
  src/App.php
  src/App/Mode.php
  src/Console/Cache.php
  src/Console/Config.php
  src/Console/Lock.php
  src/Console/Maintenance.php
  src/Console/Relocate.php
  src/Core/Config/Capability/IManageConfigValues.php
  src/Core/Config/Capability/ISetConfigValuesTransactionally.php
  src/Core/Config/Factory/Config.php
  src/Core/Config/Model/Config.php
  src/Core/Config/Model/ConfigTransaction.php
  src/Core/Config/Repository/Config.php
  src/Core/Config/Type/AbstractConfig.php
  src/Core/Config/Type/JitConfig.php
  src/Core/Config/Type/PreloadConfig.php
  src/Core/Config/Util/ConfigFileManager.php
  src/Core/Config/Util/ConfigFileTransformer.php
  src/Core/Config/ValueObject/Cache.php
  src/Core/KeyValueStorage/Type/DBKeyValueStorage.php
  src/Core/PConfig/Repository/PConfig.php
  src/Core/PConfig/Util/ValueConversion.php
  src/Core/Update.php
  src/Core/Worker.php
  src/Database/DBStructure.php
  src/Module/Admin/Site.php
  src/Module/Friendica.php
  src/Worker/DBUpdate.php
  static/dbstructure.config.php
  static/dependencies.config.php
  tests/FixtureTest.php
  tests/Util/VFSTrait.php
  tests/datasets/api.fixture.php
  tests/datasets/config/A.node.config.php
  tests/datasets/config/B.node.config.php
  tests/datasets/config/C.node.config.php
  tests/datasets/config/node.config.php
  tests/functional/DependencyCheckTest.php
  tests/src/App/ModeTest.php
  tests/src/Core/Config/Cache/CacheTest.php
  tests/src/Core/Config/Cache/ConfigFileManagerTest.php
  tests/src/Core/Config/ConfigTest.php
  tests/src/Core/Config/ConfigTransactionTest.php
  tests/src/Core/Config/JitConfigTest.php
  tests/src/Core/Config/PreloadConfigTest.php
  tests/src/Core/Config/Util/ConfigFileTransformerTest.php
  tests/src/Core/Lock/SemaphoreLockTest.php
  tests/src/Core/Storage/Repository/StorageManagerTest.php
  tests/src/Database/DBATest.php
  tests/src/Database/DBStructureTest.php
  tests/src/Module/Api/GnuSocial/GnuSocial/ConfigTest.php
  update.php
  view/theme/frio/style.php
Labels: Enhancement

#12604 Some Bugfixings (thx to Marco R.)
  src/Core/Storage/Type/ExternalResource.php
  src/Model/Post/Link.php
Labels: Bug

#12611 small typo
  view/theme/frio/templates/photo_view.tpl
Labels: Bug

#12614 improve previous / next function in photo gallery
  mod/photos.php
Labels: Bug

#12606 Fix config read/write locking
  bin/daemon.php
  src/App/BaseURL.php
  src/Core/Config/Capability/ISetConfigValuesTransactionally.php
  src/Core/Config/Model/ConfigTransaction.php
  src/Core/Config/Util/ConfigFileManager.php
  tests/src/Core/Config/Cache/ConfigFileManagerTest.php
  tests/src/Core/Config/ConfigTransactionTest.php
  tests/src/Util/BaseURLTest.php
Labels: Bug

#12605 Move table `addons` into `node.config.php`
  database.sql
  src/Core/Addon.php
  src/Core/Config/Capability/IManageConfigValues.php
  src/Core/Config/Model/Config.php
  src/Core/L10n.php
  src/Database/DBStructure.php
  static/dbstructure.config.php
  static/settings.config.php
  tests/src/Core/Config/Cache/CacheTest.php
  tests/src/Core/Config/ConfigTest.php
  update.php
Labels: Addons, Enhancement

#12618 Don't wipe `config` or `addon` data
  update.php
Labels: Enhancement

#12621 Cast alert types to boolean in Api\Mastodon\Subscription
  src/Object/Api/Mastodon/Subscription.php
Labels: Bug, API

#12619 Remove system.no_auto_update personal config key and assume default value of true
  mod/update_contact.php
  src/Module/Settings/Display.php
  src/Module/Update/Community.php
  src/Module/Update/Network.php
  src/Module/Update/Profile.php
  view/lang/C/messages.po
  view/templates/settings/display.tpl
  view/theme/frio/templates/settings/display.tpl
Labels: UX, Enhancement

#12622 `node.config.php` bugfixings
  bin/auth_ejabberd.php
  bin/daemon.php
  bin/worker.php
  src/App.php
  src/Core/Config/Factory/Config.php
  src/Core/Config/Model/Config.php
  src/Core/Config/Model/ConfigTransaction.php
  src/Core/Config/Util/ConfigFileManager.php
  src/Core/Config/Util/ConfigFileTransformer.php
  src/Core/Config/ValueObject/Cache.php
  src/Core/Update.php
  src/Core/Worker.php
  src/Module/Admin/Summary.php
  static/dependencies.config.php
  tests/FixtureTest.php
  tests/src/Core/Cache/DatabaseCacheTest.php
  tests/src/Core/Config/Cache/CacheTest.php
  tests/src/Core/Config/Cache/ConfigFileManagerTest.php
  tests/src/Core/Config/ConfigTest.php
  tests/src/Core/Config/ConfigTransactionTest.php
  tests/src/Core/Storage/DatabaseStorageTest.php
  tests/src/Core/Storage/Repository/StorageManagerTest.php
Labels: Bug

#12627 Check `node.config.php` file permission
  src/Core/Config/Util/ConfigFileManager.php
  src/DI.php
  src/Module/Admin/Summary.php
  view/lang/C/messages.po
Labels: Enhancement

#12609 Code cleanup for mod/item.php
  mod/item.php
  src/Content/Item.php
  src/Model/Item.php
  view/lang/C/messages.po
Labels: Enhancement

#12628 Don't ksort() or loop without an addon array
  src/Core/Addon.php
Labels: Bug

#12632 Fix loading empty node.config.php
  src/Core/Addon.php
  src/Core/Config/Util/ConfigFileManager.php
  src/Core/Config/ValueObject/Cache.php
  tests/src/Core/Config/Cache/CacheTest.php
  tests/src/Core/Config/Cache/ConfigFileManagerTest.php
Labels: Bug

#12634 Treat unsupported API call as HTTP error
  src/Module/Api/ApiResponse.php
  view/lang/C/messages.po
Labels: Bug, API

#12633 Change "thumbnail" for default Friendica banner image in Api\Mastodon\Instance
  src/Object/Api/Mastodon/Instance.php
Labels: Bug, API

#12636 Update API unsupported test
  tests/src/Module/Api/ApiResponseTest.php
Labels: Enhancement

#12638 Posts from contacts can now be collapsed
  database.sql
  src/Content/Item.php
  src/Model/Item.php
  src/Module/Contact.php
  src/Module/Contact/Profile.php
  static/dbstructure.config.php
  static/routes.config.php
  update.php
  view/lang/C/messages.po
  view/templates/contact_edit.tpl
  view/theme/frio/templates/contact_edit.tpl
Labels: New Feature

#12641 Add yet another case to DateTimeFormat::fix
  src/Util/DateTimeFormat.php
  tests/src/Util/DateTimeFormatTest.php
Labels: Bug

#12642 Address a few Fatal Errors
  src/Core/System.php
  src/Model/ItemURI.php
  src/Model/Post/Media.php
  src/Model/Tag.php
  src/Object/Image.php
Labels: Bug

#12644 Improve the ignore behaviour
  mod/item.php
  src/App/Page.php
  src/Model/Item.php
  src/Model/Post.php
  src/Model/Post/UserNotification.php
  src/Object/Post.php
  view/lang/C/messages.po
  view/theme/frio/js/textedit.js
  view/theme/frio/templates/js_strings.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: UX, Enhancement

#12645 Replace HTML regular expression by HTML::extractCharset in ParseUrl::getSiteInfo
  src/Content/Text/HTML.php
  src/Core/System.php
  src/Protocol/HTTP/MediaType.php
  src/Util/ParseUrl.php
  tests/src/Content/Text/HTMLTest.php
  tests/src/Protocol/HTTP/MediaTypeTest.php
Labels: Bug

#12647 Enable profile user theme on single photo display
  mod/photos.php
Labels: Bug, UX

#12635 Replace remaining mentions of "Status" by "Conversations" or "Posts"
  index.php
  src/App.php
  src/App/Page.php
  src/Content/Nav.php
  src/Module/Apps.php
  src/Module/BaseProfile.php
  src/Module/Contact.php
  src/Module/Contact/Follow.php
  src/Module/Contact/Unfollow.php
  src/Module/Post/Tag/Add.php
  src/Module/Profile/Conversations.php
  src/Module/Profile/Index.php
  static/routes.config.php
  view/lang/C/messages.po
Labels: UX, Enhancement

#12655 Fix: Forum posts from some contacts weren't distributed
  src/Module/ActivityPub/Objects.php
  src/Module/DFRN/Poll.php
  src/Module/Feed.php
Labels: Bug, Federation

#12657 Mode depending control for the behaviour with blocked contacts
  mod/item.php
  mod/notes.php
  src/Content/Conversation.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Module/Conversation/Community.php
  src/Module/Conversation/Network.php
  src/Module/Item/Display.php
  src/Module/Profile/Conversations.php
  src/Module/Search/Filed.php
  src/Module/Search/Index.php
  src/Module/Update/Community.php
  src/Module/Update/Network.php
  src/Module/Update/Profile.php
  src/Util/Strings.php
  view/lang/C/messages.po
Labels: UX, Enhancement

#12659 Properly handle feed item urls with surrounding whitespace
  src/Util/Network.php
Labels: Bug, Federation

#12663 Security: Use htmlspecialchars() for user input in Arguments class
  src/App/Page.php
  view/theme/frio/php/default.php
Labels: Bug, Security

#12670 Ensure to reset the avatar paths when deleting avatar cache
  src/Contact/Avatar.php
  src/Model/Contact.php
Labels: Bug

#12671 Added default config for the lock driver
  static/defaults.config.php
Labels: Installation, Enhancement

#12667 Remove App dependency from Hook::callSingle
  doc/Addons.md
  doc/de/Addons.md
  src/Core/Hook.php
  src/Module/Settings/Addons.php
  src/Module/Settings/Connectors.php
  src/Worker/Expire.php
  src/Worker/ForkHook.php
  tests/Util/SampleStorageBackendInstance.php
  tests/Util/authtest/authtest.php
  view/theme/frio/theme.php
Labels: Bug, Addons

#12666 Enable calendar export for public_calendar = true
  src/Module/Calendar/Export.php
  src/Module/Calendar/Show.php
Labels: Bug, Calendar

#12673 API: Accept "redirect_uris" as both array and string
  src/Factory/Api/Mastodon/Error.php
  src/Module/Api/Mastodon/Apps.php
  src/Module/OAuth/Token.php
  view/lang/C/messages.po
Labels: Mobile, Enhancement, API

#12662 Security Hotfix Release
  images/default/corgidon.png
  images/default/gotosocial.svg
  images/default/hometown.png
  images/default/koyuspace.png
  images/default/plume.png
  images/diaspora-banner.jpg
  images/friendica-banner.jpg
  images/friendica-maskable-512.png
  images/friendica-maskable.svg
  images/friendica.svg
  mods/fpostit/friendica.svg
  src/App/Page.php
  src/Core/Protocol.php
  src/Model/GServer.php
  src/Module/ActivityPub/Objects.php
  src/Module/DFRN/Poll.php
  src/Module/Feed.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Util/Network.php
  src/Worker/UpdateContact.php
  src/Worker/UpdateGServer.php
  src/Worker/UpdateGServers.php
  tests/src/Model/GServerTest.php
  view/theme/frio/php/default.php
Labels: Bug, Security

#12675 Add Hotfix 2022.12-1 Changelog
  CHANGELOG
Labels: Docs

#12674 Config: Improve the node.config.php transformation
  src/Core/Config/Util/ConfigFileTransformer.php
  tests/datasets/config/B.node.config.php
  tests/datasets/config/transformer/C.node.config.php
  tests/datasets/config/transformer/D.node.config.php
  tests/datasets/config/transformer/object.node.config.php
  tests/datasets/config/transformer/ressource.node.config.php
  tests/datasets/config/transformer/small_types.node.config.php
  tests/datasets/config/transformer/types.node.config.php
  tests/src/Core/Config/Util/ConfigFileTransformerTest.php
Labels: Bug, Enhancement

#12678 Remove App dependency from addon admin form method
  src/Module/Admin/Addons/Details.php
Labels: Bug

#12679 Replace Config-Cache dependency with Config-Model
  src/App.php
  src/App/Mode.php
  src/Console/DatabaseStructure.php
  src/Core/PConfig/Factory/PConfig.php
  src/Database/Database.php
  src/Module/Admin/Summary.php
  src/Util/Profiler.php
  static/dependencies.config.php
  tests/FixtureTest.php
  tests/Util/CreateDatabaseTrait.php
  tests/functional/DependencyCheckTest.php
  tests/src/App/ModeTest.php
  tests/src/Core/Cache/DatabaseCacheTest.php
  tests/src/Core/KeyValueStorage/DBKeyValueStorageTest.php
  tests/src/Core/Lock/DatabaseLockDriverTest.php
  tests/src/Core/Storage/DatabaseStorageTest.php
  tests/src/Core/Storage/Repository/StorageManagerTest.php
  tests/src/Util/BaseURLTest.php
  tests/src/Util/ProfilerTest.php
Labels: Enhancement

#12688 News "blocked" field on the gserver table
  database.sql
  doc/database/db_gserver.md
  src/Console/ServerBlock.php
  src/Model/GServer.php
  src/Module/Api/Mastodon/Instance/Peers.php
  src/Module/Moderation/Blocklist/Server/Add.php
  src/Module/Moderation/Blocklist/Server/Import.php
  src/Module/Moderation/Blocklist/Server/Index.php
  src/Worker/Cron.php
  src/Worker/UpdateBlockedServers.php
  src/Worker/UpdateGServer.php
  src/Worker/UpdateGServers.php
  src/Worker/UpdateServerPeers.php
  static/dbstructure.config.php
Labels: Federation, Enhancement, Performance

#12680 Introduce new Hook logic
  composer.json
  composer.lock
  mods/patches/level-2-dice-dice-php.patch
  src/Core/Hooks/Capabilities/IAmAStrategy.php
  src/Core/Hooks/Capabilities/ICanManageInstances.php
  src/Core/Hooks/Exceptions/HookInstanceException.php
  src/Core/Hooks/Exceptions/HookRegisterArgumentException.php
  src/Core/Hooks/Model/InstanceManager.php
  src/Core/Logger/Exception/LoggerInvalidException.php
  src/Core/Logger/Factory/Logger.php
  src/Core/Logger/Type/AbstractLogger.php
  src/Core/Logger/Type/StreamLogger.php
  src/Core/Logger/Type/SyslogLogger.php
  src/Database/Database.php
  static/dependencies.config.php
  tests/Util/CreateDatabaseTrait.php
  tests/Util/Hooks/InstanceMocks/FakeInstance.php
  tests/Util/Hooks/InstanceMocks/FakeInstanceDecorator.php
  tests/Util/Hooks/InstanceMocks/IAmADecoratedInterface.php
  tests/functional/DependencyCheckTest.php
  tests/src/Core/Cache/DatabaseCacheTest.php
  tests/src/Core/Hooks/Model/InstanceManagerTest.php
  tests/src/Core/Logger/AbstractLoggerTest.php
  tests/src/Core/Logger/StreamLoggerTest.php
  tests/src/Core/Logger/SyslogLoggerTest.php
  tests/src/Core/Logger/SyslogLoggerWrapper.php
Labels: Enhancement

#12690 Nodeinfo data has moved to key values
  database.sql
  src/Model/Nodeinfo.php
  src/Module/Statistics.php
  src/Object/Api/Mastodon/Stats.php
  static/dbstructure.config.php
  update.php
Labels: Installation, Enhancement

#12694 Allow colon in password
  src/Model/User.php
  src/Module/OAuth/Token.php
  src/Module/Security/PasswordTooLong.php
  src/Module/Settings/Account.php
  view/lang/C/messages.po
Labels: Enhancement, Security

#12695 Address a few fatal errors
  src/Database/Definition/DbaDefinition.php
  src/Module/Maintenance.php
  view/templates/sub/direction.tpl
Labels: Bug

#12699 [frio] Various UX improvements (mostly larger clickable areas)
  view/templates/item/compose.tpl
  view/theme/frio/css/style.css
  view/theme/frio/templates/calendar/calendar.tpl
  view/theme/frio/templates/comment_item.tpl
  view/theme/frio/templates/common_tabs.tpl
  view/theme/frio/templates/contact/entry.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/frio/templates/contacts-template.tpl
  view/theme/frio/templates/group_side.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/frio/templates/settings/profile/index.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/frio/templates/widget/peoplefind.tpl
  view/theme/frio/templates/widget/vcard.tpl
Labels: Theme-specific, Enhancement, UI

#12707 Fix connection acknowledgement not appearing on contact page
  src/Model/Contact.php
  src/Module/Contact/Profile.php
  view/lang/C/messages.po
  view/templates/contact_edit.tpl
  view/theme/vier/templates/contact_edit.tpl
Labels: Bug

#12711 Config Fixings & Dice update
  composer.json
  composer.lock
  mods/patches/level-2-dice-dice-php.patch
  src/Core/Config/Util/ConfigFileTransformer.php
  src/Database/DBStructure.php
  tests/Util/SerializableObjectDouble.php
  tests/datasets/config/transformer/object_valid.node.config.php
  tests/src/Core/Config/Util/ConfigFileTransformerTest.php
Labels: Bug

#12712 Remove BaseURL Auto-Check
  bin/worker.php
  config/local-sample.config.php
  mods/local.config.vagrant.php
  src/App.php
  src/App/BaseURL.php
  src/App/Request.php
  tests/src/Util/BaseURLTest.php
Labels: Bug, Installation, Enhancement

#12697 Fix a few PHP8.2 deprecation messages
  src/Content/OEmbed.php
  src/Content/Smilies.php
  src/Content/Text/BBCode.php
  src/Content/Text/HTML.php
  src/Content/Widget/TagCloud.php
  src/Database/DBA.php
  src/Model/Event.php
  src/Navigation/Notifications/Repository/Notify.php
  src/Network/HTTPClient/Client/HttpClient.php
  src/Object/Api/Mastodon/Card.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Util/ParseUrl.php
  src/Util/Proxy.php
Labels: Bug

#12717 Improved block check for redirects
  src/Model/GServer.php
  src/Worker/UpdateServerPeers.php
Labels: Enhancement

#12719 Fetch data from basic auth when one of the parameters is missing
  src/Module/OAuth/Token.php
Labels: Bug, API

#12718 More configs moved to key values
  database.sql
  src/Module/Admin/Summary.php
  src/Worker/CheckVersion.php
  static/dbstructure.config.php
  update.php
Labels: Enhancement

#12720 Issue 12702: Let the user decide how to handle spoiler texts
  src/Module/Api/Mastodon/Statuses.php
  src/Module/Settings/Connectors.php
  view/lang/C/messages.po
  view/templates/settings/connectors.tpl
  view/theme/frio/templates/settings/connectors.tpl
Labels: New Feature, Federation

#12724 Issue 12682: Fix ids of reshared posts
  src/Factory/Api/Mastodon/Status.php
  src/Module/Api/Mastodon/Statuses.php
Labels: Enhancement, API

#12726 Remove Text\BBCode::scaleExternalImage
  src/Content/Item.php
  src/Content/Text/BBCode.php
  src/Content/Text/Markdown.php
Labels: Bug

#12730 Fix labels in contact request modal
  view/theme/frio/templates/notifications/intros.tpl
Labels: Bug, UX

#12727 API: added positiv list for quote support
  src/Content/Item.php
  src/Factory/Api/Mastodon/Status.php
  src/Module/Api/Mastodon/Accounts/Statuses.php
  src/Module/Api/Mastodon/Bookmarks.php
  src/Module/Api/Mastodon/Favourited.php
  src/Module/Api/Mastodon/Search.php
  src/Module/Api/Mastodon/Statuses.php
  src/Module/Api/Mastodon/Statuses/Bookmark.php
  src/Module/Api/Mastodon/Statuses/Context.php
  src/Module/Api/Mastodon/Statuses/Favourite.php
  src/Module/Api/Mastodon/Statuses/Mute.php
  src/Module/Api/Mastodon/Statuses/Pin.php
  src/Module/Api/Mastodon/Statuses/Reblog.php
  src/Module/Api/Mastodon/Statuses/Unbookmark.php
  src/Module/Api/Mastodon/Statuses/Unfavourite.php
  src/Module/Api/Mastodon/Statuses/Unmute.php
  src/Module/Api/Mastodon/Statuses/Unpin.php
  src/Module/Api/Mastodon/Statuses/Unreblog.php
  src/Module/Api/Mastodon/Timelines/Home.php
  src/Module/Api/Mastodon/Timelines/ListTimeline.php
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
  src/Module/Api/Mastodon/Timelines/Tag.php
  src/Module/Api/Mastodon/Trends/Statuses.php
  src/Module/BaseApi.php
Labels: New Feature, API

#12731 Quote for notifications
  src/Factory/Api/Mastodon/Notification.php
  src/Module/Api/Mastodon/Notifications.php
Labels: New Feature, API

#12732 Catch not fetchable posts
  src/Factory/Api/Mastodon/Status.php
  src/Module/Api/Mastodon/Bookmarks.php
  src/Module/Api/Mastodon/Favourited.php
  src/Module/Api/Mastodon/Search.php
  src/Module/Api/Mastodon/Timelines/Home.php
  src/Module/Api/Mastodon/Timelines/ListTimeline.php
  src/Module/Api/Mastodon/Timelines/Tag.php
  src/Module/Api/Mastodon/Trends/Statuses.php
Labels: Enhancement, API

#12738 Avoid local network communication / invalid url requests
  src/Content/Text/BBCode.php
  src/Model/APContact.php
  src/Model/Contact.php
  src/Model/Post/Media.php
  src/Model/Tag.php
  src/Module/Photo.php
  src/Network/Probe.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/Feed.php
  src/Protocol/OStatus.php
  src/Worker/Notifier.php
  src/Worker/OnePoll.php
Labels: Enhancement

#12736 Replace custom WebFinger implementation by Probe::getWebfingerArray in APContact::fetchWebfingerData
  src/Model/APContact.php
  src/Network/Probe.php
Labels: Bug, Federation

#12735 Address a couple of Fatal errors
  src/Model/Photo.php
  src/Object/Api/Mastodon/Stats.php
Labels: Bug

#12741 Avoid more local links and bad http requests
  src/Model/APContact.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Photo.php
  src/Model/Tag.php
  src/Network/Probe.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Queue.php
  src/Protocol/ActivityPub/Receiver.php
  src/Worker/OnePoll.php
  src/Worker/PollContacts.php
  tests/FixtureTest.php
Labels: Enhancement

#12745 Read local files instead of performing self HTTP requests in JsonLD::documentLoader
  src/Util/BasePath.php
  src/Util/JsonLD.php
Labels: Enhancement, Performance

#12746 Remove Feed contacts from profile contact list
  src/Module/Profile/Contacts.php
Labels: Bug

#12747 Address a couple of warnings
  src/Factory/Api/Mastodon/Status.php
  src/Module/Photo.php
Labels: Bug
