Repository friendica/friendica, pull requests merged in 2024-11, with the labels that each got.

#14521 Improved delivery / fix falsely delivery content via DFRN
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/Notifier.php
Labels: Federation

#14528 Process deletions via ActivityPub
  src/Model/Contact.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Util/HTTPSignature.php
  src/Worker/Notifier.php
Labels: Federation

#14531 Only transmit via AP if the relayed post is an AP post
  src/Worker/Notifier.php
Labels: Federation

#14530 Fix installation
  src/Module/Install.php
Labels: Installation

#14534 "Connector" added as parcel
  src/Model/Conversation.php
Labels: Enhancement

#14533 Fixes "foreach() argument must be of type array|object, string given"
  src/Worker/UpdateServerDirectory.php
Labels: Bug

#14523 Update to Composer v2
  bin/composer.phar
  composer.json
  composer.lock
  view/templates/admin/federation.tpl
Labels: Installation, Enhancement

#14547 New option to disable SVG icons / Functionality added to Vier
  src/Content/ContactSelector.php
  src/Module/Settings/Display.php
  view/templates/wall_thread.tpl
  view/theme/vier/style.css
Labels: Theme-specific, Enhancement, UI

#14552 Fix notice because of missing "gsid"
  database.sql
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Bug, Federation

#14553 Issue 14524: Fix Open Search
  src/Module/OpenSearch.php
  view/lang/C/messages.po
Labels: Bug

#14529 Add static code analysis with PHPStan level 0
  .phpstan.neon
  composer.json
  composer.lock
  src/App/Mode.php
  src/BaseCollection.php
  src/Console/Addon.php
  src/Console/AutomaticInstallation.php
  src/Console/Contact.php
  src/Console/FixAPDeliveryWorkerTaskParameters.php
  src/Console/User.php
  src/Content/Post/Entity/PostMedia.php
  src/Content/Widget/ContactBlock.php
  src/Content/Widget/VCard.php
  src/Core/Cache/Type/APCuCache.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Module/Api/Mastodon/Search.php
  src/Module/Debug/ActivityPubConversion.php
  src/Module/Debug/Babel.php
  src/Module/Debug/ItemBody.php
  src/Object/Api/Mastodon/Preferences.php
  src/Protocol/ActivityPub/Receiver.php
  src/Util/Temporal.php
  tests/Unit/Object/Api/Mastodon/PreferencesTest.php
  view/lang/C/messages.po
Labels: Enhancement

#14558 Add phpstan check in woodpecker ci
  .woodpecker/.phpunit.yml
  src/Core/Cache/Type/APCuCache.php
  src/Module/Debug/Babel.php
  view/lang/C/messages.po
Labels: Enhancement

#14561 Create AppHelper interface
  src/App.php
  src/AppHelper.php
  src/AppLegacy.php
  src/DI.php
  static/dependencies.config.php
  view/lang/C/messages.po
Labels: Enhancement

#14566 Differentiate both UserGServer types used in Content/Conversation
  src/Content/Conversation.php
Labels: Bug

#14574 Preparation for the Bluesky Jetstream firehose
  composer.json
  composer.lock
  src/Model/Contact/User.php
  src/Model/Conversation.php
Labels: New Feature

#14577 No restrictions check on connector networks
  src/Model/Item.php
Labels: Federation, Enhancement

#14580 Added check for shortcut icon url parts
  src/Module/OpenSearch.php
Labels: Bug

#14570 [Refactoring] Replace App with AppHelper
  mod/item.php
  mod/lostpass.php
  mod/notes.php
  mod/photos.php
  mod/update_contact.php
  mod/update_notes.php
  src/Core/Addon.php
  src/LegacyModule.php
  src/Module/Admin/Addons/Details.php
  src/Module/Admin/DBSync.php
  src/Module/Directory.php
  src/Module/Invite.php
  src/Module/NoScrape.php
  src/Module/Profile/Media.php
  src/Module/Profile/Schedule.php
  src/Object/Post.php
  src/Security/BasicAuth.php
Labels: Refactoring
