Repository friendica/friendica, pull requests merged in 2024-08, with the labels that each got.

#14340 Issue 14312: fix uimport path / restore POST endpoints
  src/Module/Admin/Addons/Index.php
  src/Module/Admin/Themes/Details.php
  src/Module/Admin/Themes/Index.php
  src/Module/Debug/ActivityPubConversion.php
  src/Module/Debug/Babel.php
  src/Module/Moderation/Item/Source.php
  src/Module/Moderation/Reports.php
  src/Module/Notifications/Introductions.php
  src/Module/Notifications/Notifications.php
  src/Module/Security/Logout.php
  static/routes.config.php
  view/templates/user/import.tpl
Labels: Bug

#14347 Improved redirect for contact actions
  src/Module/Contact.php
  view/templates/contacts-template.tpl
  view/theme/frio/templates/contacts-template.tpl
Labels: Enhancement

#14345 Statistics: Inbound/Outbound for more protocols
  src/Module/Feed.php
  src/Module/Stats.php
  src/Protocol/Email.php
  src/Worker/OnePoll.php
Labels: Enhancement

#14354 Issue 14121: Don't display contacts from unavailable networks via API
  src/Module/Api/Mastodon/Accounts/Followers.php
  src/Module/Api/Mastodon/Accounts/Following.php
Labels: Bug, API

#14352 Fix for fetching the target inboxes
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#14353 Increment inbound/outbound on mails per result
  src/Protocol/Email.php
Labels: Enhancement

#14358 update AR, DE, FR, GD, HU, PL, RU translations
  view/lang/ar/messages.po
  view/lang/ar/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/gd/messages.po
  view/lang/gd/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
Labels: Translation

#14359 Configurable recursion depth when fetching replies
  src/Protocol/ActivityPub/Processor.php
  static/defaults.config.php
Labels: Bug

#14362 Remove apcontact and diaspora-contact entries that aren't connected to contacts
  src/Worker/RemoveUnusedContacts.php
Labels: Performance

#14357 Additional checks against fetch loops
  src/Protocol/ActivityPub/Queue.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Performance

#14365 Additional checks for deleting old contacts
  src/Worker/RemoveUnusedContacts.php
Labels: Enhancement

#14360 CHANGELOG for 2024.08
  CHANGELOG
Labels: Docs

#14361 added FEDERATION.md / FEP-67ff
  FEDERATION.md
Labels: Docs, Federation

#14379 Issue 14368: Fix access to the global timeline
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
Labels: Bug

#14380 Issue 14377: Support for "postingRestrictedToMods" added
  database.sql
  doc/database/db_apcontact.md
  src/Model/APContact.php
  src/Protocol/ActivityPub/Processor.php
  src/Protocol/ActivityPub/Receiver.php
  src/Util/JsonLD.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: New Feature, Federation

#14378 Remove unused contacts
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/RemoveUnusedContacts.php
  static/defaults.config.php
Labels: New Feature, Performance

#14376 added initial REUSE stuff
  .codecov.yml
  .ddev/config.yaml
  .editorconfig
  .gitattributes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/dependabot.yml
  .gitignore
  .htaccess-dist
  .php-cs-fixer.dist.php
  .php_cs.dist
  .tx/config
  .woodpecker/.code_standards_check.yml
  .woodpecker/.continuous-deployment.yml
  .woodpecker/.database_checks.yml
  .woodpecker/.license_check.yml
  .woodpecker/.messages.po_check.yml
  .woodpecker/.phpunit.yml
  .woodpecker/.releaser.yml
  CHANGELOG.license
  CONTRIBUTING.md.license
  CREDITS.txt.license
  Doxyfile.license
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  README.md.license
  REUSE.toml
  REUSE.toml.license
  VERSION.license
  Vagrantfile.license
  bin/.htaccess.license
  bin/auth_ejabberd.php
  bin/composer.phar.license
  bin/console
  bin/console.bat
  bin/console.php
  bin/daemon.php
  bin/run_xgettext.sh
  bin/testargs.php
  bin/worker.php
  index.php
  mod/item.php
  mod/lostpass.php
  mod/message.php
  mod/notes.php
  mod/photos.php
  mod/update_contact.php
  mod/update_notes.php
  security.txt.license
  translations.txt.license
  update.php
Labels: Docs

#14390 Issue 14381: Fix automated register policy on first install
  src/Module/Register.php
Labels: Bug, Installation

#14385 [PHP-CS] Moving the php-cs-fixer dependency to the right place
  .php-cs-fixer.dist.php
  .php_cs.dist
  bin/dev/php-cs-fixer/composer.json
  bin/dev/php-cs-fixer/composer.lock
  composer.json
  composer.lock
Labels: Bug

#14389 Delete unused media attachments
  database.sql
  doc/database/db_post-media.md
  src/Model/Item.php
  src/Model/Post/Media.php
  src/Module/Admin/Site.php
  src/Module/Api/Mastodon/Instance.php
  src/Module/Api/Mastodon/InstanceV2.php
  src/Module/Api/Mastodon/Media.php
  src/Module/Media/Attachment/Upload.php
  src/Object/Api/Mastodon/InstanceV2/MediaAttachmentsConfig.php
  src/Protocol/ActivityPub/Processor.php
  src/Worker/ExpirePosts.php
  static/dbstructure.config.php
  update.php
  view/lang/C/messages.po
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement, Performance

#14396 Issue 14307: prevent exception on post update
  src/Database/PostUpdate.php
Labels: Bug

#14404 Fix exception "($shorthand) must be of type string, null given,"
  src/Module/Api/Mastodon/Instance.php
  src/Module/Api/Mastodon/InstanceV2.php
Labels: Bug
