Repository friendica/friendica, pull requests merged in 2024-04, with the labels that each got.

#14068 Don't set posts to seen on channel ping
  src/Module/Conversation/Network.php
  src/Module/Conversation/Timeline.php
  src/Module/Ping/Network.php
Labels: Bug, UX

#14069 Avoid exception "Unable to retrieve the host in URL" in the search
  src/Model/Item.php
  view/lang/C/messages.po
Labels: Bug, UX

#14074 Menu option to display the search text
  src/Content/Item.php
  src/Model/Post/Engagement.php
  src/Module/Item/Language.php
  src/Module/Item/Searchtext.php
  src/Object/Post.php
  static/routes.config.php
  view/js/main.js
  view/lang/C/messages.po
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: New Feature, UX

#14082 Issue 14055: Set link to group server for group posts
  src/Model/Item.php
Labels: UX, UI

#14083 Issue 13812: Public groups with manual request approval
  mod/photos.php
  src/Model/Contact.php
  src/Model/User.php
  src/Module/ActivityPub/Whoami.php
  src/Module/Api/Mastodon/Accounts/UpdateCredentials.php
  src/Module/HCard.php
  src/Module/Moderation/BaseUsers.php
  src/Module/Notifications/Ping.php
  src/Module/Profile/Conversations.php
  src/Module/Profile/Profile.php
  src/Module/Settings/Account.php
  src/Network/Probe.php
  src/Protocol/DFRN.php
  view/lang/C/messages.po
  view/templates/settings/pagetypes.tpl
  view/theme/frio/templates/moderation/users/active.tpl
  view/theme/frio/templates/moderation/users/blocked.tpl
  view/theme/frio/templates/moderation/users/index.tpl
Labels: New Feature

#14089 Prevent concurring ping requests
  src/Module/Notifications/Ping.php
  src/Module/Ping/Network.php
Labels: Enhancement, Performance

#14080 Issue #14079: Shorten the displayed URL
  src/Content/Text/BBCode.php
  src/Util/Strings.php
  tests/src/Content/Text/BBCodeTest.php
Labels: New Feature

#14075 round scaled dimensions up to avoid zero size
  src/Object/Image.php
  src/Util/Images.php
  tests/src/Util/ImagesTest.php
Labels: Enhancement

#14093 allow overriding password during local testing
  bin/dev/autotest.sh
Labels: Enhancement

#14090 The BBCode conversion is split into several smaller functions
  src/Content/Text/BBCode.php
  src/Content/Text/HTML.php
  tests/src/Factory/Api/Twitter/DirectMessageTest.php
  view/lang/C/messages.po
Labels: Enhancement

#14095 Fix warning: Undefined array key "post-reason"
  mod/item.php
  src/Module/Api/Mastodon/Statuses.php
  src/Network/Probe.php
Labels: Bug

#14097 Enable user defined channels upon adding/editing
  src/Module/Settings/Channels.php
Labels: UX, Enhancement

#14100 Performance improvements when displaying local posts
  database.sql
  doc/database.md
  doc/database/db_post-origin.md
  src/Content/Widget/TrendingTags.php
  src/Model/Item.php
  src/Model/Post.php
  src/Model/Post/Origin.php
  src/Module/Api/Mastodon/Timelines/PublicTimeline.php
  src/Module/Conversation/Timeline.php
  src/Module/Feed.php
  src/Module/Profile/Conversations.php
  src/Protocol/Feed.php
  src/Worker/ExpirePosts.php
  static/dbstructure.config.php
  static/dbview.config.php
  update.php
Labels: Enhancement, Performance

#14101 "self::" should be "$this->" on non static functions
  src/Module/Conversation/Timeline.php
Labels: Enhancement

#14103 API: Access channels and groups via lists
  src/Factory/Api/Mastodon/ListEntity.php
  src/Module/Api/Mastodon/Lists.php
  src/Module/Api/Mastodon/Timelines/ListTimeline.php
  src/Module/Conversation/Channel.php
  src/Module/Conversation/Network.php
  src/Module/Conversation/Timeline.php
  src/Module/Ping/Network.php
  src/Module/Update/Channel.php
  src/Module/Update/Network.php
  src/Object/Api/Mastodon/ListEntity.php
  src/Object/Api/Mastodon/Status.php
  static/routes.config.php
Labels: Enhancement, API

#14114 Rework reports query in Moderation\Reports module class
  src/Module/Moderation/Reports.php
Labels: Bug

#14119 [ImgBot] Optimize images
  images/bluesky.jpg
  images/screenshots/friendica-2023-10-frio-mobile-options-dark-blue.png
  images/screenshots/friendica-2023-10-frio-mobile-options-light-blue.png
  images/screenshots/friendica-2023-10-frio-mobile-timeline-dark-blue.png
  images/screenshots/friendica-2023-12-frio-desktop.png
  view/js/vanillaEmojiPicker/screenshot.png
Labels: Enhancement
