Repository friendica/friendica, pull requests merged in 2024-03, with the labels that each got.

#13951 Issue 13949: Block access via OAuth
  database.sql
  src/Module/OAuth/Revoke.php
  src/Module/OAuth/Token.php
  src/Security/OAuth.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Bug, API

#13954 Issue 13953: Fix warning during postupdate
  src/Content/Item.php
  src/Model/Post/SearchIndex.php
Labels: Bug

#13942 Fix API fixture data
  src/Factory/Api/Twitter/User.php
  tests/DatabaseTestTrait.php
  tests/Util/Database/StaticDatabase.php
  tests/datasets/api.fixture.php
  tests/src/Factory/Api/Twitter/UserTest.php
  tests/src/Module/Api/Friendica/NotificationTest.php
  tests/src/Module/Api/Twitter/Statuses/UserTimelineTest.php
Labels: Bug

#13948 [frio] Remove legacy schemes
  view/lang/C/messages.po
  view/theme/frio/config.php
  view/theme/frio/php/default.php
  view/theme/frio/php/scheme.php
  view/theme/frio/scheme/blue.php
  view/theme/frio/scheme/koyu-dark.css
  view/theme/frio/scheme/koyu-dark.php
  view/theme/frio/scheme/love-music.css
  view/theme/frio/scheme/love-music.php
  view/theme/frio/scheme/plusminus.css
  view/theme/frio/scheme/plusminus.jpg
  view/theme/frio/scheme/plusminus.php
  view/theme/frio/scheme/red.php
  view/theme/frio/style.php
  view/theme/frio/templates/theme_settings.tpl
  view/theme/frio/theme.php
Labels: Enhancement

#13960 Oembed: Some more cleanup
  src/Content/OEmbed.php
  src/Model/Post/Media.php
  src/Util/ParseUrl.php
Labels: Enhancement

#13961 Issue 13765: Fixed creation of self user contact for approval
  src/Model/Contact.php
Labels: Bug

#13962 translation updates
  view/lang/ar/messages.po
  view/lang/ar/strings.php
  view/lang/bg/messages.po
  view/lang/bg/strings.php
  view/lang/ca/messages.po
  view/lang/ca/strings.php
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/eo/messages.po
  view/lang/eo/strings.php
  view/lang/es/messages.po
  view/lang/es/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/gd/messages.po
  view/lang/gd/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
  view/lang/is/messages.po
  view/lang/is/strings.php
  view/lang/it/messages.po
  view/lang/it/strings.php
  view/lang/ja/messages.po
  view/lang/ja/strings.php
  view/lang/nl/messages.po
  view/lang/nl/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
  view/lang/ro/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
  view/lang/sv/messages.po
  view/lang/sv/strings.php
Labels: Translation

#13967 Issue 13939: Fix avatars for Diaspora
  database.sql
  src/Protocol/Diaspora.php
  static/dbstructure.config.php
  update.php
Labels: Bug

#13973 Change the last activity for delegation parents and siblings as well
  src/Model/User.php
  src/Security/OAuth.php
Labels: Enhancement

#13974 Set default value for max video height
  src/Model/Item.php
  static/defaults.config.php
Labels: Enhancement

#13975 Check for the content type before fetching the content
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#13976 Centralized logging for a wrong JSON content-type
  src/Model/APContact.php
  src/Model/Item.php
  src/Protocol/ActivityPub/Processor.php
  src/Util/HTTPSignature.php
Labels: Federation, Enhancement

#13977 Don't retry when fetching invalid content
  src/Protocol/ActivityPub/Processor.php
Labels: Enhancement

#13980 Fix: Subject for private messages from Friendica systems
  src/Protocol/ActivityPub/Processor.php
Labels: Bug

#13982 Fix: Don't attach unknown media
  src/Content/Post/Repository/PostMedia.php
Labels: Bug

#13983 Fix notice when sending private messages
  src/Protocol/ActivityPub/Transmitter.php
Labels: Bug

#13990 Escape HTML characters in profile RSS titles
  src/Module/Profile/Profile.php
Labels: Bug, Security

#13993 Systems added to the federation statistics
  src/Module/Admin/Federation.php
Labels: Enhancement

#13998 Fix: "unsearchable" is now stored
  database.sql
  src/Model/APContact.php
  src/Model/Contact.php
  src/Network/Probe.php
  src/Protocol/Relay.php
  static/dbstructure.config.php
  update.php
Labels: Bug

#14000 [CI] Add PHP 8.3 and upgrade CI images
  .woodpecker/.continuous-deployment.yml
  .woodpecker/.database_checks.yml
  .woodpecker/.messages.po_check.yml
  .woodpecker/.phpunit.yml
  .woodpecker/.releaser.yml
Labels: Enhancement

#14007 Slightly updated API documentation
  doc/API-Mastodon.md
Labels: Docs, Enhancement

#14008 Update API-Mastodon.md
  doc/API-Mastodon.md
Labels: Docs, Enhancement

#14009 Update FAQ.md
  doc/FAQ.md
Labels: Docs, Enhancement

#14010 updated the credits
  CREDITS.txt
Labels: Docs

#14011 Update Composer dependencies ahead of release
  composer.lock
Labels: Enhancement

#14013 Update FAQ.md
  doc/FAQ.md
Labels: Docs, Enhancement

#13963 CHANGELOG for 2024.03
  CHANGELOG
Labels: Docs

#14018 Improved Content-Type check on incoming requests
  database.sql
  src/Module/ActivityPub/Inbox.php
  src/Protocol/ActivityPub.php
Labels: Enhancement

#14016 Issue 13787: Filter in circles editor by contact relation
  src/Module/Circle.php
Labels: Enhancement

#14020 Issue 13714: Support for "commentsEnabled" and "capabilities"
  database.sql
  doc/database/db_post-engagement.md
  doc/database/db_post-searchindex.md
  doc/database/db_post-user.md
  src/Model/Item.php
  src/Object/Post.php
  src/Protocol/ActivityPub/Processor.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: New Feature, Federation

#14015 Internal support for Bluesky tokens
  src/App.php
  src/Protocol/ATProtocol/DID.php
Labels: New Feature, Federation

#14033 Add a link to the post if "no preview" is selected
  src/Model/Item.php
Labels: Enhancement, UI

#14032 Implementation of FEP-e232 for quoted posts
  src/Content/Item.php
  src/Protocol/ActivityPub/Receiver.php
  src/Protocol/ActivityPub/Transmitter.php
Labels: Federation, Enhancement

#14036 Add `'$VERSION'` template variable to make Friendica version available in templates
  src/Content/Conversation.php
  src/Core/Renderer.php
  src/Module/Admin/Federation.php
  src/Module/Admin/Summary.php
  src/Module/Moderation/Blocklist/Contact.php
  src/Module/Moderation/Blocklist/Server/Add.php
  src/Module/Moderation/Blocklist/Server/Import.php
  src/Module/Moderation/Blocklist/Server/Index.php
  src/Module/Moderation/Reports.php
  src/Module/Moderation/Users/Active.php
  src/Module/Settings/Channels.php
  view/templates/admin/federation.tpl
  view/templates/admin/summary.tpl
  view/templates/calendar/calendar_head.tpl
  view/templates/head.tpl
  view/templates/jot-header.tpl
  view/templates/media/browser.tpl
  view/templates/msg-header.tpl
  view/templates/settings/profile/index_head.tpl
  view/templates/settings/profile/photo/crop_head.tpl
  view/theme/frio/templates/admin/site.tpl
  view/theme/frio/templates/admin/storage.tpl
  view/theme/frio/templates/admin/summary.tpl
  view/theme/frio/templates/calendar/calendar_head.tpl
  view/theme/frio/templates/circle_edit.tpl
  view/theme/frio/templates/contacts-head.tpl
  view/theme/frio/templates/head.tpl
  view/theme/frio/templates/jot-header.tpl
  view/theme/frio/templates/moderation/blocklist/contact.tpl
  view/theme/frio/templates/moderation/users/active.tpl
  view/theme/frio/templates/moderation/users/blocked.tpl
  view/theme/frio/templates/moderation/users/deleted.tpl
  view/theme/frio/templates/moderation/users/index.tpl
  view/theme/frio/templates/moderation/users/pending.tpl
  view/theme/frio/templates/notifications/notifications.tpl
  view/theme/frio/templates/photos_head.tpl
  view/theme/frio/templates/theme_settings.tpl
  view/theme/frio/templates/threaded_conversation.tpl
Labels: Bug

#14038 Constants for features
  src/Content/Conversation.php
  src/Content/Feature.php
  src/Content/GroupManager.php
  src/Content/Item.php
  src/Content/Widget.php
  src/Model/Event.php
  src/Module/BaseProfile.php
  src/Module/Calendar/Export.php
  src/Module/Calendar/Show.php
  src/Module/Conversation/Channel.php
  src/Module/Conversation/Community.php
  src/Module/Conversation/Network.php
  src/Module/Item/Compose.php
  src/Module/Post/Edit.php
  src/Module/Profile/Photos.php
  src/Module/Profile/Profile.php
  src/Object/Post.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Diaspora.php
  view/lang/C/messages.po
Labels: Enhancement

#14037 Add expected field 'uri-id' in Mastodon\Statuses\Bookmark
  src/Module/Api/Mastodon/Statuses/Bookmark.php
Labels: Bug

#14039 Configuration for widgets
  src/Content/Feature.php
  src/Content/Nav.php
  src/Module/Admin/Features.php
  src/Module/Conversation/Network.php
  src/Module/Settings/Features.php
  view/lang/C/messages.po
  view/theme/frio/templates/admin/features.tpl
Labels: Enhancement, UI

#14040 The visibility of network widgets can now be locked
  src/Content/Feature.php
  src/Module/Admin/Features.php
  view/theme/frio/templates/admin/features.tpl
Labels: Bug

#14041 Simplified admin frontend for features
  src/Module/Admin/Features.php
  view/lang/C/messages.po
  view/templates/admin/features.tpl
  view/theme/frio/templates/admin/features.tpl
Labels: UX, Enhancement

#14044 Img div class
  view/templates/content/image/single_with_height_allocation.tpl
Labels: Enhancement

#14046 Improvements for channel counter
  src/Content/Feature.php
  src/Module/Conversation/Network.php
  src/Module/Ping/Network.php
  view/lang/C/messages.po
Labels: Enhancement

#14060 Show the next try date and time on the deferred worker job list in the admin pages
  src/Module/Admin/Queue.php
  view/lang/C/messages.po
  view/templates/admin/queue.tpl
  view/theme/frio/templates/admin/queue.tpl
Labels: UX, Enhancement
