Repository friendica/friendica, pull requests merged in 2024-05, with the labels that each got.

#14137 Issue 14132: Title for videos
  src/Model/Item.php
  view/templates/video_top.tpl
Labels: Bug

#14136 Issue 14134: Allow reshare posts from Bluesky and Tumblr
  src/Module/Api/Mastodon/Statuses/Reblog.php
  src/Module/Api/Mastodon/Statuses/Unreblog.php
  src/Module/Api/Twitter/Statuses/Retweet.php
Labels: New Feature, Federation

#14135 Colorize loglevels
  view/global.css
  view/templates/admin/logs/view.tpl
Labels: UX, Enhancement, UI

#14138 Improved user agent string
  src/Content/Text/BBCode.php
  src/Model/Photo.php
  src/Model/Profile.php
  src/Module/Contact/Redir.php
  src/Module/Photo.php
  src/Network/HTTPClient/Capability/ICanSendHttpRequests.php
  src/Network/HTTPClient/Client/HttpClient.php
  src/Network/HTTPClient/Client/HttpClientOptions.php
  src/Network/HTTPClient/Client/HttpClientRequest.php
  src/Network/HTTPClient/Factory/HttpClient.php
  src/Protocol/DFRN.php
  src/Protocol/Diaspora.php
  src/Protocol/Salmon.php
  src/Util/HTTPSignature.php
  src/Util/Network.php
  src/Util/ParseUrl.php
  src/Worker/OnePoll.php
  src/Worker/PubSubPublish.php
Labels: Federation, Enhancement

#14143 Fix wrong return value in Item::gettopLevelParent()
  src/Model/Item.php
Labels: Bug

#14141 Add support for absolute file paths when removing addon
  src/Core/Addon.php
Labels: Bug

#14139 Fix a couple of stored XSS vulnerabilities
  mod/photos.php
  src/Model/APContact.php
  src/Module/PermissionTooltip.php
  src/Module/Privacy/PermissionTooltip.php
  src/Privacy/Entity/AclReceivers.php
  src/Privacy/Entity/AddressedReceivers.php
  static/routes.config.php
  view/lang/C/messages.po
  view/templates/privacy/permission_tooltip.tpl
  view/theme/frio/templates/photos_upload.tpl
Labels: Bug, Security

#14140 German translation of Channels Documentation
  doc/Channels.md
  doc/de/Channels.md
  doc/de/Home.md
Labels: Translation

#14142 Issue 11963: Set Permissions for attachments
  mod/item.php
  src/Content/Item.php
  src/Model/Attach.php
  src/Model/Item.php
  src/Model/Post/Media.php
Labels: Bug

#14147 Support for non HTML content for feed imports
  src/Content/Text/HTML.php
  src/Protocol/Feed.php
Labels: Federation, Enhancement

#14148 Use the field for the summary instead of the "abstract" element
  src/Model/Item.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Protocol/Feed.php
Labels: Enhancement

#14151 Probing for Zot improved and Pumpio removed
  src/Model/Post/Media.php
  src/Network/Probe.php
  src/Protocol/Feed.php
Labels: Federation, Enhancement

#14154 Friendica probing simplified / Zot probing improved
  src/Network/Probe.php
Labels: Enhancement

#14155 Many deprecated function calls are replaced
  mod/message.php
  mod/notes.php
  mod/photos.php
  src/BaseModule.php
  src/Contact/Avatar.php
  src/Model/APContact.php
  src/Model/Attach.php
  src/Model/Contact.php
  src/Model/Item.php
  src/Model/Post/Media.php
  src/Module/Calendar/Event/Show.php
  src/Module/Calendar/Show.php
  src/Module/HCard.php
  src/Module/Home.php
  src/Module/Media/Attachment/Browser.php
  src/Module/Media/Photo/Browser.php
  src/Module/NoScrape.php
  src/Module/Photo.php
  src/Module/Post/Edit.php
  src/Module/Profile/Schedule.php
  src/Module/Settings/Account.php
  src/Module/Settings/Profile/Photo/Crop.php
  src/Module/Settings/Profile/Photo/Index.php
  src/Navigation/Notifications/Factory/Introduction.php
  src/Util/Images.php
  src/Util/Proxy.php
  src/Worker/Notifier.php
  view/theme/vier/theme.php
Labels: Bug, Enhancement

#14157 Some more deprecated function calls are replaced
  mod/item.php
  src/App.php
  src/App/Page.php
  src/BaseModule.php
  src/Content/Conversation.php
  src/Content/Widget.php
  src/Core/Renderer.php
  src/Model/Contact.php
  src/Model/Profile.php
  src/Module/BaseAdmin.php
  src/Module/Contact/Profile.php
  src/Module/Invite.php
  src/Module/Item/Compose.php
  src/Module/Item/Display.php
  src/Module/Moderation/Blocklist/Contact.php
  src/Module/Moderation/Report/Create.php
  src/Module/Profile/Conversations.php
  src/Module/Security/Logout.php
  src/Module/Security/TwoFactor/Recovery.php
  src/Module/Security/TwoFactor/Trust.php
  src/Module/Settings/Account.php
  src/Module/User/Import.php
  src/Network/HTTPClient/Client/HttpClient.php
  src/Object/EMail/ItemCCEMail.php
  src/Object/Post.php
  src/Render/FriendicaSmartyEngine.php
  src/Util/Network.php
  update.php
  view/theme/frio/config.php
  view/theme/frio/theme.php
Labels: Enhancement

#14159 "Network::unparseURL" is replaced with "Uri::fromParts"
  src/Content/BoundariesPager.php
  src/Content/ContactSelector.php
  src/Content/Text/HTML.php
  src/Model/PushSubscriber.php
  src/Module/Api/Mastodon/Instance/Peers.php
  src/Network/HTTPClient/Client/HttpClient.php
  src/Network/HTTPClient/Response/CurlResult.php
  src/Network/Probe.php
  src/Util/Network.php
Labels: Enhancement

#14161 Fix " Call to undefined method Friendica\App::getLoggedInUserNickname"
  src/Module/Calendar/Event/Get.php
Labels: Bug

#14162 Respect the "sensitive" flag for posts
  src/Content/Conversation.php
  src/Model/Item.php
  src/Module/Settings/Connectors.php
  src/Module/Settings/Display.php
  src/Object/Post.php
  view/global.css
  view/lang/C/messages.po
  view/templates/settings/display.tpl
  view/templates/wall_thread.tpl
  view/theme/frio/templates/settings/display.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: New Feature

#14164 [frio] Colour for fading in a comment adjusted
  view/theme/frio/js/theme.js
Labels: Theme-specific, UI

#14165 Fixes "Undefined array key url"
  src/Network/Probe.php
Labels: Bug

#14167 Fix: Undefined array key "content-warning"
  mod/item.php
Labels: Bug

#14168 Issue 14153: Don't transmit activities to all participants
  src/Protocol/ActivityPub/Transmitter.php
Labels: Federation

#14169 Issue 14160: Don't add simple participants to "cc"
  src/Protocol/ActivityPub/Transmitter.php
Labels: Federation

#14173 OpenWebAuth path is now fetched during probing
  database.sql
  doc/database/db_gserver.md
  mod/photos.php
  src/App.php
  src/Model/APContact.php
  src/Model/Contact.php
  src/Model/GServer.php
  src/Model/Profile.php
  src/Module/Magic.php
  src/Module/Xrd.php
  src/Network/Probe.php
  src/Protocol/ActivityNamespace.php
  static/dbstructure.config.php
Labels: Federation, Enhancement

#14176 Improved summary handling for feeds
  src/Protocol/Feed.php
Labels: Federation, Enhancement

#14178 Issue 14175: Fix problems with upper case host names
  src/Model/APContact.php
  src/Util/HTTPSignature.php
Labels: Bug

#14179 Store the "authredirect" path of a server
  database.sql
  doc/database/db_gserver.md
  src/Model/GServer.php
  static/dbstructure.config.php
Labels: Federation, Enhancement

#14183 Issue 14102: Display "channels only" contacts in circles
  database.sql
  src/Module/Contact/Profile.php
  src/Module/Conversation/Network.php
  static/dbstructure.config.php
  static/dbview.config.php
  view/lang/C/messages.po
Labels: New Feature

#14187 Fix "TypeError: Argument 1 passed to Friendica\Util\Strings::compareLink() must be of the type string, null given"
  src/Model/Contact.php
Labels: Bug, Enhancement, Performance

#14188 Improved hostname handling with feeds
  src/Protocol/Feed.php
Labels: Federation, Enhancement

#14185 OpenWebAuth moved to a separate class / Improved authentication handling
  src/App.php
  src/Content/Nav.php
  src/Content/Widget.php
  src/Core/Session/Capability/IHandleUserSessions.php
  src/Core/Session/Model/UserSession.php
  src/Model/Profile.php
  src/Module/Contact/Follow.php
  src/Module/Directory.php
  src/Module/Photo.php
  src/Module/Register.php
  src/Security/Authentication.php
  src/Security/OpenWebAuth.php
  tests/src/Core/Session/UserSessionTest.php
  view/lang/C/messages.po
Labels: Federation, Enhancement

#14189 Blocked users need to be blocked
  database.sql
  src/Model/Contact.php
  src/Model/User.php
  static/dbstructure.config.php
  update.php
Labels: Bug, Privacy

#14192 Update Home.md
  doc/Home.md
Labels: Docs

#14193 Update Home.md (de version)
  doc/de/Home.md
Labels: Docs, Translation
