Repository friendica/friendica, pull requests merged in 2024-10, with the labels that each got.

#14462 more REUSE information
  LICENSES/CC-BY-SA-3.0.txt
  REUSE.toml
  view/lang/C/messages.po.license
  view/theme/frio/.eslintrc.json.license
  view/theme/frio/.prettierrc.license
Labels: Docs

#14463 Fix Apache instructions and PHP extension list
  doc/Install.md
Labels: Docs, Installation

#14465 Fix the following of accounts with "?" in the URL
  src/Content/Widget/VCard.php
  src/Model/Contact.php
  src/Model/Profile.php
  src/Module/Contact/Follow.php
  src/Module/Contact/Profile.php
  view/templates/widget/follow.tpl
  view/theme/frio/templates/widget/follow.tpl
Labels: Bug

#14467 Update translations
  REUSE.toml
  view/lang/ar/messages.po
  view/lang/ar/strings.php
  view/lang/bg/messages.po
  view/lang/bg/strings.php
  view/lang/ca/messages.po
  view/lang/ca/strings.php
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/eo/messages.po
  view/lang/eo/strings.php
  view/lang/es/messages.po
  view/lang/es/strings.php
  view/lang/et/messages.po
  view/lang/et/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/gd/messages.po
  view/lang/gd/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
  view/lang/is/messages.po
  view/lang/is/strings.php
  view/lang/it/messages.po
  view/lang/it/strings.php
  view/lang/ja/messages.po
  view/lang/ja/strings.php
  view/lang/nl/messages.po
  view/lang/nl/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
  view/lang/sv/messages.po
  view/lang/sv/strings.php
Labels: Translation

#14466 reorder 2FA buttons
  view/templates/settings/twofactor/index.tpl
Labels: Bug

#14474 Issue 14174 and 14421: Option to hide emojis and pictures without description
  src/App/Page.php
  src/Content/Text/BBCode.php
  src/Model/Item.php
  src/Module/Settings/Display.php
  view/lang/C/messages.po
  view/templates/settings/display.tpl
  view/theme/frio/templates/settings/display.tpl
Labels: UX, Enhancement, UI

#14477 Issue 14212: exclude channel only posts from the API timeline
  database.sql
  src/Module/Api/Mastodon/Timelines/Home.php
  static/dbstructure.config.php
  static/dbview.config.php
Labels: Enhancement, API

#14479 Improved block behaviour
  database.sql
  src/Content/Widget/VCard.php
  src/Core/Protocol.php
  src/Model/Contact.php
  src/Model/Contact/User.php
  src/Model/Post.php
  src/Module/Api/Mastodon/Accounts/Block.php
  src/Module/Api/Mastodon/Statuses/Context.php
  src/Module/Api/Mastodon/Timelines/Direct.php
  src/Module/Api/Mastodon/Timelines/Home.php
  src/Module/Api/Mastodon/Timelines/Tag.php
  src/Module/Contact/Profile.php
  src/Protocol/ActivityPub/Transmitter.php
  src/Worker/Contact/Block.php
  src/Worker/Contact/Unblock.php
  static/dbstructure.config.php
  static/dbview.config.php
  view/lang/C/messages.po
Labels: Federation, Enhancement

#14481 Issue 14121: Show precise contact counts for own user
  src/Content/Widget.php
  src/Factory/Api/Mastodon/Account.php
Labels: Enhancement, API

#14482 Issue 14126: Workaround for wrong content types
  src/Model/Item.php
Labels: Bug

#14484 QuickFix: 2FA - App specific password
  src/Module/Settings/TwoFactor/AppSpecific.php
  view/lang/C/messages.po
Labels: Bug

#14485 Add admin info to stats Endpoint
  src/Core/Update.php
  src/Database/DBStructure.php
  src/Module/Admin/Summary.php
  src/Module/Stats.php
Labels: Enhancement

#14486 Issue 14145: Fix communication with Hubzilla
  src/Util/JsonLD.php
  static/socialweb-webfinger.jsonld
Labels: Bug, Federation

#14493 Issue 14488: Extended date change range for signatures
  src/Util/HTTPSignature.php
Labels: Federation

#14494 update docs
  doc/Install.md
  doc/de/Install.md
  mods/home.html
Labels: Docs

#14499 Issue 14478: Fix OAuth registration with Buffer
  src/Security/OAuth.php
Labels: Bug

#14502 Don't show "(AP)" at platform names anymore
  src/Content/ContactSelector.php
Labels: UI

#14501 Issue 14495: Rich HTML content with embedded pictures
  src/Factory/Api/Mastodon/Status.php
  src/Object/Api/Mastodon/Status/FriendicaExtension.php
Labels: New Feature

#14503 Improved cached context file
  static/security-data-integrity-v1.jsonld
Labels: Federation, Enhancement, Performance

#14504 The code for archiving and unarchiving contacts is improved
  src/Model/Contact.php
Labels: Enhancement

#14509 Add Prometheus exporter link to docs
  doc/tools.md
Labels: Docs

#14508 Issue 13270: Fix display of private comments on the profile page
  src/Module/Profile/Conversations.php
Labels: Bug, Privacy

#14513 Issue 14478: Always use an existing application for OAuth
  src/Module/Api/Mastodon/Apps.php
Labels: Bug

#14514 remove old reverence to addons.friendi.ca
  src/Module/Admin/Addons/Index.php
  view/lang/C/messages.po
Labels: Docs

#14517 Prevent dead contacts from being revived
  src/Model/Contact.php
Labels: Bug
