Repository friendica/friendica, pull requests merged in 2025-10, with the labels that each got.

#15183 Remove translations of technical, code-specific terms and theme variation names
  src/Module/Debug/Babel.php
  view/lang/C/messages.po
  view/theme/duepuntozero/config.php
Labels: Enhancement, Translation

#15203 Enable embedding Tiktok videos / enhanced inline frame security
  src/Content/Post/Repository/PostMedia.php
  src/Util/ParseUrl.php
  tests/src/Content/Text/BBCodeTest.php
Labels: UX, Enhancement

#15199 Fix exception when processing Peertube videos
  src/Factory/Api/Mastodon/Account.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Bug, Federation

#15149 Login, forgotten password and (minor) registration adjustments
  mod/lostpass.php
  src/Content/Nav.php
  src/Module/Bookmarklet.php
  src/Module/Register.php
  src/Module/Security/Login.php
  view/lang/C/messages.po
  view/templates/field_input.tpl
  view/templates/field_openid.tpl
  view/templates/field_password.tpl
  view/templates/login.tpl
  view/templates/lostpass.tpl
  view/theme/frio/css/style.css
  view/theme/frio/scheme/light.php
  view/theme/frio/style.php
  view/theme/frio/templates/field_input.tpl
  view/theme/frio/templates/field_openid.tpl
  view/theme/frio/templates/field_password.tpl
  view/theme/frio/templates/login.tpl
  view/theme/frio/templates/nav.tpl
  view/theme/frio/templates/register.tpl
Labels: Theme-specific, UX, Enhancement
