Repository friendica/friendica, pull requests merged in 2025-01, with the labels that each got.

#14651 [CI] Fix releaser
  .woodpecker/.releaser.yml
Labels: Bug

#14653 Fix messages.po - Happy new year ;-)
  view/lang/C/messages.po
Labels: Bug

#14652 [CI] Fix releaser
  .woodpecker/.releaser.yml
Labels: Bug

#14654 Prevent contact id = 0 case in VCard
  src/Content/Widget/VCard.php
Labels: Bug

#14645 Fix links in Quick-Start-makingnewfriends
  doc/Quick-Start-makingnewfriends.md
  doc/de/Quick-Start-makingnewfriends.md
Labels: Bug, Docs

#14656 Add `bin/dev/fix-codestyle.sh`
  .woodpecker/.code_standards_check.yml
  bin/dev/fix-codestyle.sh
  src/App.php
Labels: Enhancement

#14655 Add JetStream to Console
  bin/daemon.php
  bin/jetstream.php
  src/App.php
  src/Console/Daemon.php
  src/Console/JetstreamDaemon.php
  src/Core/Console.php
  src/Protocol/ATProtocol/Jetstream.php
  src/System/Daemon.php
  view/lang/C/messages.po
Labels: Refactoring

#14658 CHANGELOG note for 2025.02
  CHANGELOG
Labels: Docs

#14660 Set the quote-uri-id when a post is linked
  src/Model/Item.php
  src/Model/Post/Media.php
Labels: Bug, Federation

#14663 Restore template engine registration for Worker execution
  src/App.php
Labels: Bug

#14668 Use the fetched mimetype if present / improved detection of quoted posts
  src/Model/Post/Media.php
  src/Protocol/ActivityPub/Receiver.php
Labels: Federation, Enhancement

#14673 Issue 14275: Avoid "Data too long" error
  src/Model/Photo.php
Labels: Bug

#14659 Move 'bin/worker.php' to 'bin/console.php worker'
  bin/auth_ejabberd.php
  bin/console.php
  bin/daemon.php
  bin/dev/vagrant_provision.sh
  bin/jetstream.php
  bin/worker.php
  doc/Install.md
  doc/Installing-Connectors.md
  doc/Migrate.md
  doc/de/Install.md
  doc/de/Installing-Connectors.md
  index.php
  mods/sample-systemd.service
  src/App.php
  src/Console/AbstractConsole.php
  src/Console/Daemon.php
  src/Console/JetstreamDaemon.php
  src/Console/Worker.php
  src/Core/Console.php
  src/Core/Container.php
  src/Core/System.php
  src/Core/Worker.php
  src/Core/Worker/Daemon.php
  tests/Unit/AppTest.php
  tests/Unit/Core/ContainerTest.php
Labels: Refactoring

#14678 Dropzone placeholder
  src/Module/Media/Photo/Upload.php
  view/js/dropzone-factory.js
  view/templates/item/compose.tpl
Labels: Bug, UX, Enhancement

#14687 Fix list enabled/disabled addons
  src/Console/Addon.php
Labels: Bug

#14683 Issue 14681: enable path "remote_follow/{nickname}"
  static/routes.config.php
Labels: New Feature, Federation

#14682 Create LoggerManager
  src/App.php
  src/Core/Logger.php
  src/Core/Logger/Factory/LegacyLoggerFactory.php
  src/Core/Logger/Factory/LoggerFactory.php
  src/Core/Logger/LoggerManager.php
  src/Core/Worker.php
  src/DI.php
  static/dependencies.config.php
  tests/Unit/Core/Logger/Factory/LegacyLoggerFactoryTest.php
  tests/Unit/Core/Logger/LoggerManagerTest.php
Labels: Refactoring

#14715 fix photo albums button appeareance for dark appereance in frio theme
  view/theme/frio/templates/media/browser.tpl
Labels: Bug, Theme-specific, UI

#14694 Backward Compatibility Promise
  doc/Developers-Intro.md
Labels: Docs

#14716 Fix App not loading Hooks
  bin/auth_ejabberd.php
  bin/console.php
  bin/daemon.php
  bin/jetstream.php
  bin/worker.php
  src/App.php
Labels: Bug

#14699 New option to only update contacts that have got a relation to local users
  src/Model/Contact.php
  src/Model/GServer.php
  src/Module/Admin/Site.php
  src/Worker/UpdateContact.php
  static/settings.config.php
  view/lang/C/messages.po
  view/templates/admin/site.tpl
  view/theme/frio/templates/admin/site.tpl
Labels: Enhancement, Performance

#14700 Issue 14692: Prevent loops with remote servers
  src/Util/HTTPSignature.php
Labels: Bug, Federation

#14720 Show Create new Group link in widget even if there's no group membership to display
  src/Content/GroupManager.php
  view/templates/widget/group_list.tpl
Labels: Bug, UX, UI

#14719 Partially revert "Improve search for user in Modration module"
  src/Module/Moderation/Users/Active.php
  src/Module/Moderation/Users/Blocked.php
  src/Module/Moderation/Users/Index.php
Labels: Bug

#14639 Fix warning "Trying to access array offset on value of type bool"
  src/Model/Contact.php
  src/Model/GServer.php
  src/Model/Post/Media.php
  src/Protocol/ActivityPub/Processor.php
  view/lang/C/messages.po
Labels: Bug

#14686 Improves the performance for contact relation discovery
  src/Model/Contact/Relation.php
  src/Worker/AddContact.php
Labels: Enhancement, Performance

#14727 Remove test code from GroupManager::widget
  src/Content/GroupManager.php
Labels: Bug

#14728 Bugfix/log table: Log level not readable in dark and black frio appeareance
  view/theme/frio/templates/admin/logs/view.tpl
Labels: Bug, Theme-specific, UI

#14733 Refactor view.tpl for admin/logs: Fixed illegal whitespace
  view/theme/frio/templates/admin/logs/view.tpl
Labels: Bug

#14730 Several accessibility improvements
  src/App/Page.php
  src/Content/Text/BBCode.php
  src/Module/BaseProfile.php
  src/Module/Calendar/Show.php
  src/Module/Contact.php
  src/Module/Conversation/Channel.php
  src/Module/Conversation/Community.php
  src/Module/Conversation/Network.php
  src/Module/Moderation/BaseUsers.php
  src/Object/Post.php
  tests/src/Content/Text/BBCodeTest.php
  view/lang/C/messages.po
  view/theme/frio/css/style.css
  view/theme/frio/php/default.php
  view/theme/frio/php/minimal.php
  view/theme/frio/php/standard.php
  view/theme/frio/templates/calendar/calendar.tpl
  view/theme/frio/templates/common_tabs.tpl
  view/theme/frio/templates/footer.tpl
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/sub/delivery_count.tpl
  view/theme/frio/templates/sub/direction.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: UX, Enhancement

#14734 Ward against empty string in Model\Item::replacePlatformIcon
  src/Model/Item.php
Labels: Bug

#14738 Return early if system.max_author_posts_community_page isn't set in Conversation\Timeline->getCommunityItems
  src/Module/Conversation/Timeline.php
Labels: Bug

#14735 Exclude invitation register rows from pending-view
  database.sql
  static/dbview.config.php
Labels: Bug

#14736 Ward against invalid URLs in Model\Post\Media::isFederatedServer
  src/Model/Post/Media.php
Labels: Bug

#14737 Account for calendar post edition in editpost()
  src/Util/Temporal.php
  view/theme/frio/js/modal.js
Labels: Bug

#14739 Remove potential new lines in reported logger instances
  src/Navigation/Notifications/Repository/Notify.php
  src/Protocol/Delivery.php
  src/Protocol/Diaspora.php
  src/Util/Emailer.php
Labels: Bug

#14740 Fix itemFiler() callback
  view/templates/jot-header.tpl
  view/theme/frio/templates/jot-header.tpl
Labels: Bug, UX

#14745 Fix wrong default value for contact_account in Mastodon\Instance
  src/Object/Api/Mastodon/Instance.php
Labels: Bug, API

#14747 Frio: break too long words in topbar notifications
  view/theme/frio/css/style.css
Labels: Bug, Theme-specific, UI

#14751 Frio: change modal header border to reflect the current color scheme
  view/theme/frio/scheme/black.css
  view/theme/frio/scheme/dark.css
Labels: Theme-specific, Enhancement, UI

#14753 [frio] Improve dropzone background color
  view/theme/frio/css/style.css
Labels: Theme-specific, Enhancement, UI

#14752 Add expected final return in Console\Storage->doMove
  src/Console/Storage.php
Labels: Bug

#14755 [frio] Use modal instead of popupbox for permissions on photo edit page
  view/theme/frio/templates/photo_edit.tpl
  view/theme/frio/templates/photos_upload.tpl
  view/theme/frio/templates/settings/profile/field/edit.tpl
Labels: Theme-specific, Enhancement, UI
