Repository friendica/friendica, pull requests merged in 2025-02, with the labels that each got.

#14758 Hard deprecate `Friendica\Core\Logger`
  doc/Developers-Intro.md
  src/Core/Logger.php
  src/Core/Logger/Handler/ErrorHandler.php
  src/DI.php
Labels: Refactoring

#14762 Create `addon/` folder in the proper order, since it's now mandatory
  .gitignore
  doc/Install.md
Labels: Bug, Installation

#14764 [frio] Small CSS fix for circle-update-wrapper shortmode headings
  view/theme/frio/css/style.css
Labels: Bug, Theme-specific, UI

#14773 Close paren in message shown at the signup form
  src/Module/Register.php
  view/lang/C/messages.po
Labels: Bug, Translation

#14769 Some more screenreader improvements
  src/Content/Nav.php
  view/lang/C/messages.po
  view/templates/item/compose.tpl
  view/theme/frio/js/mod_events.js
  view/theme/frio/php/default.php
  view/theme/frio/php/standard.php
  view/theme/frio/templates/admin/aside.tpl
  view/theme/frio/templates/admin/logs/view.tpl
  view/theme/frio/templates/calendar/calendar.tpl
  view/theme/frio/templates/common_tabs.tpl
  view/theme/frio/templates/contact/entry.tpl
  view/theme/frio/templates/contact_edit.tpl
  view/theme/frio/templates/event_stream_item.tpl
  view/theme/frio/templates/generic_links_widget.tpl
  view/theme/frio/templates/jot.tpl
  view/theme/frio/templates/media/browser.tpl
  view/theme/frio/templates/nav.tpl
  view/theme/frio/templates/page_tabs.tpl
  view/theme/frio/templates/photo_item.tpl
  view/theme/frio/templates/search_item.tpl
  view/theme/frio/templates/settings/profile/index.tpl
  view/theme/frio/templates/sub/direction.tpl
  view/theme/frio/templates/threaded_conversation.tpl
  view/theme/frio/templates/wall_thread.tpl
Labels: Enhancement

#14760 Prioritize coalescing parameters in Moderation\Users\*->processGetActions
  src/Module/Moderation/Users/Active.php
  src/Module/Moderation/Users/Blocked.php
  src/Module/Moderation/Users/Index.php
Labels: Bug

#14781 Faster count queries when updating the info about current node
  database.sql
  doc/database/db_post-user.md
  static/dbstructure.config.php
Labels: Enhancement, Performance

#14749 Fix filer dialog colors
  src/Content/Conversation.php
  src/Module/Filer/SaveTag.php
  view/lang/C/messages.po
  view/templates/filer_dialog.tpl
  view/theme/frio/templates/jot-header.tpl
Labels: Enhancement, UI

#14640 [EventDispatcher] Proof of concept
  composer.json
  composer.lock
  src/App.php
  src/App/Page.php
  src/Content/Feature.php
  src/Content/Nav.php
  src/Core/Hooks/HookEventBridge.php
  src/DI.php
  src/Event/ArrayFilterEvent.php
  src/Event/ConfigLoadedEvent.php
  src/Event/Event.php
  src/Event/EventDispatcher.php
  src/Event/HtmlFilterEvent.php
  src/Event/NamedEvent.php
  static/dependencies.config.php
  tests/Unit/Core/Hooks/HookEventBridgeTest.php
  tests/Unit/Event/ArrayFilterEventTest.php
  tests/Unit/Event/ConfigLoadedEventTest.php
  tests/Unit/Event/EventDispatcherTest.php
  tests/Unit/Event/EventTest.php
  tests/Unit/Event/HtmlFilterEventTest.php
  tests/Unit/Util/BasePathTest.php
  tests/Unit/Util/CryptoTest.php
Labels: Addons, Refactoring

#14779 Issue 14746: Improved description
  src/Module/Settings/Channels.php
  src/Module/Settings/Display.php
  view/lang/C/messages.po
Labels: Enhancement

#14784 use env variables in install wizard for values if available
  src/Module/Install.php
Labels: Enhancement

#14785 Accessibility: Widgets and other menues
  view/js/main.js
  view/lang/C/messages.po
  view/templates/admin/aside.tpl
  view/templates/circle_side.tpl
  view/templates/generic_links_widget.tpl
  view/templates/message_side.tpl
  view/templates/moderation/aside.tpl
  view/templates/moderation/report/create/aside.tpl
  view/templates/photo_albums.tpl
  view/templates/shared_content.tpl
  view/templates/widget/accounts.tpl
  view/templates/widget/community_sharer.tpl
  view/templates/widget/events.tpl
  view/templates/widget/filter.tpl
  view/templates/widget/follow.tpl
  view/templates/widget/group_list.tpl
  view/templates/widget/peoplefind.tpl
  view/templates/widget/posted_date.tpl
  view/templates/widget/saved_searches.tpl
  view/templates/widget/tagcloud.tpl
  view/templates/widget/trending_tags.tpl
  view/theme/frio/css/style.css
  view/theme/frio/php/standard.php
  view/theme/frio/templates/admin/aside.tpl
  view/theme/frio/templates/circle_side.tpl
  view/theme/frio/templates/common_tabs.tpl
  view/theme/frio/templates/message_side.tpl
  view/theme/frio/templates/moderation/aside.tpl
  view/theme/frio/templates/nav.tpl
  view/theme/frio/templates/photo_albums.tpl
  view/theme/frio/templates/profile/vcard.tpl
  view/theme/frio/templates/sub/direction.tpl
  view/theme/frio/templates/wall_thread.tpl
  view/theme/frio/templates/widget/follow.tpl
  view/theme/frio/templates/widget/peoplefind.tpl
  view/theme/frio/templates/widget/saved_searches.tpl
Labels: UX, Enhancement

#14789 Fix Crypto::randomDigits()
  src/Util/Crypto.php
  tests/Unit/Util/CryptoTest.php
Labels: Bug

#14790 Downgrade shebang from bin/bash to bin/sh
  bin/console
  bin/run_xgettext.sh
Labels: Enhancement

#14792 Followup to #14790
  bin/run_xgettext.sh
Labels: Bug

#14797 update translations
  view/lang/ar/messages.po
  view/lang/ar/strings.php
  view/lang/bg/messages.po
  view/lang/bg/strings.php
  view/lang/ca/messages.po
  view/lang/ca/strings.php
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/eo/messages.po
  view/lang/eo/strings.php
  view/lang/et/messages.po
  view/lang/et/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/gd/messages.po
  view/lang/gd/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
  view/lang/is/messages.po
  view/lang/is/strings.php
  view/lang/it/messages.po
  view/lang/it/strings.php
  view/lang/ja/messages.po
  view/lang/ja/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
  view/lang/sv/messages.po
  view/lang/sv/strings.php
Labels: Translation

#14805 Fix active tab
  src/Module/BaseSettings.php
Labels: Bug, UI

#14770 New AddonHelper
  mod/photos.php
  src/App.php
  src/App/Router.php
  src/Console/Addon.php
  src/Console/JetstreamDaemon.php
  src/Content/Conversation.php
  src/Content/Widget.php
  src/Core/Addon.php
  src/Core/Addon/AddonHelper.php
  src/Core/Addon/AddonInfo.php
  src/Core/Addon/AddonProxy.php
  src/Core/Config/Factory/Config.php
  src/Core/Config/Util/ConfigFileManager.php
  src/Core/Storage/Repository/StorageManager.php
  src/DI.php
  src/Module/Admin/Addons/Details.php
  src/Module/Admin/Addons/Index.php
  src/Module/Admin/Summary.php
  src/Module/BaseAdmin.php
  src/Module/Filer/SaveTag.php
  src/Module/Friendica.php
  src/Protocol/ZOT.php
  src/Worker/Cron.php
  static/dependencies.config.php
  tests/ApiTestCase.php
  tests/FixtureTestTrait.php
  tests/Unit/Core/Addon/AddonInfoTest.php
  tests/Util/CreateDatabaseTrait.php
  tests/src/Core/Config/Cache/ConfigFileManagerTest.php
  tests/src/Core/Config/ConfigTest.php
  tests/src/Core/Config/ConfigTransactionTest.php
  tests/src/Core/Storage/Repository/StorageManagerTest.php
  tests/src/Database/DatabaseTest.php
Labels: Refactoring

#14806 Fix refresh after commenting
  view/js/main.js
Labels: Bug

#14808 Added dedicated friendica clients FAQ.md
  doc/FAQ.md
Labels: Docs

#14810 updated translations
  view/lang/ar/messages.po
  view/lang/ar/strings.php
  view/lang/bg/messages.po
  view/lang/bg/strings.php
  view/lang/ca/messages.po
  view/lang/ca/strings.php
  view/lang/cs/messages.po
  view/lang/cs/strings.php
  view/lang/de/messages.po
  view/lang/de/strings.php
  view/lang/eo/messages.po
  view/lang/eo/strings.php
  view/lang/et/messages.po
  view/lang/et/strings.php
  view/lang/fr/messages.po
  view/lang/fr/strings.php
  view/lang/hu/messages.po
  view/lang/hu/strings.php
  view/lang/is/messages.po
  view/lang/is/strings.php
  view/lang/it/messages.po
  view/lang/it/strings.php
  view/lang/ja/messages.po
  view/lang/ja/strings.php
  view/lang/nl/messages.po
  view/lang/nl/strings.php
  view/lang/pl/messages.po
  view/lang/pl/strings.php
  view/lang/ru/messages.po
  view/lang/ru/strings.php
  view/lang/sv/messages.po
  view/lang/sv/strings.php
Labels: Translation

#14811 Set the page language
  view/php/minimal.php
  view/theme/frio/php/default.php
  view/theme/frio/php/minimal.php
  view/theme/frio/php/standard.php
  view/theme/smoothly/php/default.php
Labels: Enhancement

#14820 Fixes: Uncaught Exception TypeError: "array_merge(): Argument #1 must be of type array, int given"
  src/App.php
Labels: Bug

#14823 Fixes PR #14819: Add missing index
  database.sql
  doc/database/db_gserver.md
  static/dbstructure.config.php
Labels: Bug

#14799 Replace Hooks with EventDispatcher Part 2
  doc/Addons.md
  doc/de/Addons.md
  mod/item.php
  mod/photos.php
  src/App/Router.php
  src/Content/ContactSelector.php
  src/Content/Conversation.php
  src/Content/Item.php
  src/Content/OEmbed.php
  src/Content/PageInfo.php
  src/Content/Smilies.php
  src/Content/Text/BBCode.php
  src/Content/Text/HTML.php
  src/Content/Widget/ContactBlock.php
  src/Core/ACL.php
  src/Core/Hooks/HookEventBridge.php
  src/Core/Protocol.php
  src/Event/ArrayFilterEvent.php
  src/Event/CollectRoutesEvent.php
  src/Event/Event.php
  src/Event/HtmlFilterEvent.php
  src/Model/Item.php
  src/Module/Home.php
  src/Module/Item/Compose.php
  src/Module/Post/Edit.php
  src/Module/Post/Tag/Add.php
  src/Module/User/Delegation.php
  src/Object/Post.php
  tests/Unit/Core/Hooks/HookEventBridgeTest.php
  tests/Unit/Event/ArrayFilterEventTest.php
  tests/Unit/Event/CollectRoutesEventTest.php
  tests/src/Content/SmiliesTest.php
  tests/src/Factory/Api/Mastodon/StatusTest.php
  tests/src/Protocol/ActivityPub/TransmitterTest.php
Labels: Refactoring
