Repository friendica/friendica, pull requests merged in 2025-04, with the labels that each got.

#14880 Log uncaught exceptions as critical
  src/Core/Logger/Handler/ErrorHandler.php
Labels: Enhancement

#14883 Issue 14881: Fixed language detection for danish
  src/Core/L10n.php
Labels: Bug, UX

#14885 Bluesky: use did based profile links
  src/Network/Probe.php
  src/Protocol/ATProtocol/Actor.php
  src/Protocol/ATProtocol/Processor.php
Labels: Bug, Federation
