Repository friendica/friendica, pull requests merged in 2025-06, with the labels that each got.

#14945 Avoid warnings in the Jetstream process
  bin/console.php
  composer.json
  composer.lock
  src/Protocol/ATProtocol/Actor.php
  src/Protocol/ATProtocol/Jetstream.php
Labels: Bug, Federation, dependencies

#14962 Issue 14879: Fix activity trust check
  src/Protocol/ActivityPub/Receiver.php
  src/Util/JsonLD.php
Labels: Bug, Federation

#14972 Fix vier theme
  view/js/main.js
  view/lang/C/messages.po
  view/theme/vier/breathe.css
  view/theme/vier/dark.css
  view/theme/vier/mobile.css
  view/theme/vier/narrow.css
  view/theme/vier/plus.css
  view/theme/vier/plusminus.css
  view/theme/vier/shadow.css
  view/theme/vier/style.css
  view/theme/vier/templates/nav.tpl
Labels: Bug, Theme-specific, UI

#14974 Issue 14947: Database performance improvements
  src/Database/Database.php
  src/Worker/ExpirePosts.php
Labels: Enhancement, Performance

#14964 Frio: Make profile contacts header link to contacts instead of the eye icon (Suggestion)
  view/theme/frio/templates/widget/contacts.tpl
Labels: UX, Enhancement

#14937 Deprecate AddonLoader
  src/App.php
  src/Core/Addon/AddonHelper.php
  src/Core/Addon/AddonManagerHelper.php
  src/Core/Addon/Capability/ICanLoadAddons.php
  src/Core/Addon/Model/AddonLoader.php
  src/Core/Hooks/Util/StrategiesFileManager.php
  static/dependencies.config.php
  tests/Unit/Core/Addon/AddonManagerHelperTest.php
  tests/src/Core/Hooks/Util/StrategiesFileManagerTest.php
Labels: Refactoring

#14987 global.css: Add missing end parenthesis
  view/global.css
Labels: Bug, UI

#14983 Issue 14491 - Add alt tag indicators to images
  view/global.css
Labels: Enhancement, UI
